### ISSUE TITLE
add a repositories with a user/pass with their content in environment secrets

### ISSUE THREAD

**Issue by jurgenweber** [roboll/helmfile#1001]
the idea:
```
repositories:
  - name: asdf
    url: ref+sops://../secrets/default.yaml#/asdf/chartrepo/url
    username: ref+sops://../secrets/default.yaml#/asdf/chartrepo/user
    password: ref+sops://../secrets/default.yaml#/asdf/chartrepo/pass
```

error:
```
in ./deploy.yaml: in .helmfiles[1]: in helmfile/deploy-bases.yaml: helm exited with status 1:
  Error: could not find protocol handler for: ref+sops
```

or
```
repositories:
  - name: asdf
    url: {{ .Values.asdf.chartrepo.url }}
    username: {{ .Environment.Values.asdf.chartrepo.user }}
    password: {{ .Environment.Values.asdf.chartrepo.pass }}
```

error:
```
in ./deploy.yaml: in .helmfiles[1]: in helmfile/deploy-bases.yaml: error during deploy-repositories.yaml.gotmpl.part.0 parsing: template: stringTemplate:4:19: executing "stringTemplate" at <.Values.asdf.chartrepo.url>: map has no entry for key "asdf"
```

Any way to do this?

**Comment by mumoshu** [comment]
@jurgenweber Interesting use-case! Unfortunately, it doesn't work today, but it seems to worth a feature request. Would you like Helmfile to add it?

**Comment by jurgenweber** [comment]
Without a doubt! Super worth it. I want all my secrets encrypted, always. :)

**Comment by xabufr** [comment]
I know this issue is old, but I think it can be closed as this can be done like this:

```yaml
---
environments:
  default:
    secrets:
      - secrets.enc.yaml

repositories:
  - name: your-repo
    username: "{{ .Values.username }}"
    password: "{{ .Values.password }}"

```

It is important to define your values BEFORE you use them in your Helmfile, but it works
