### ISSUE TITLE
Setting annotations for istio-ingressgateway service using istioctl apply/generate --set

### ISSUE THREAD

**Issue by riccardomc** [roboll/helmfile#1007]
I am trying to specify an AWS certificate ARN value for the istio-ingressgateway service. I expected this would be possible using Helm syntax on CLI but the following command doesn't really do what I want:
```
istioctl manifest generate --set values.gateways.istio-ingressgateway.serviceAnnotations."service\.beta\.kubernetes\.io/aws-load-balancer-ssl-cert"="myARN:012345678901" | grep -m 1 -C 5 012345678901 

kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    service\: "map[beta\\:map[kubernetes\\:map[io/aws-load-balancer-ssl-cert:myARN:012345678901]]]"
  labels:
    app: istio-ingressgateway
    release: istio
    istio: ingressgateway
spec:
``` 

Notice that this notation works for normal Helm charts (an [example](https://github.com/jfrog/charts/issues/42#issuecomment-559445679)).

Is there a way to achieve this from command line, otherwise can I specify just this value in a `values.yaml` or similar?
