### ISSUE TITLE
bases in helmfile.yaml will make environment disappeared

### ISSUE THREAD

**Issue by RaymondKYLiu** [roboll/helmfile#1008]
Helmfile version: v0.94.0

Hi
I run into a problem when use advanced configuration[ Layering State Files](https://github.com/roboll/helmfile/blob/master/docs/writing-helmfile.md#layering-state-files)

If I include `bases` into helmfile.yaml, and then use `helm list`,  `err: no releases found that matches environment(xxx) ...` will showed.
The environments will come back If remove the `bases` in helmfile.yaml.

```yaml
# base.yaml
repositories:
  # To use official "stable" charts a.k.a https://github.com/helm/charts/tree/master/stable
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  # To use official "incubator" charts a.k.a https://github.com/helm/charts/tree/master/incubator
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com

helmDefaults:
  wait: true
  timeout: 300
  force: false
``` 

```yaml
# helmfile.yaml
bases:
  - base.yaml

environments:
  test:
  stag:
  prod:

releases:
  - name: cluster-overprovisioner
    namespace: kube-system
    chart: stable/cluster-overprovisioner
    version: 0.2.6

```

```shell
$ helmfile -e test -f helmfile.yaml list
NAME	NAMESPACE	INSTALLED	LABELS
err: no releases found that matches specified selector() and environment(test), in any helmfile
```
