### ISSUE TITLE
variable/values scoping between releases and release values.

### ISSUE THREAD

**Issue by jurgenweber** [roboll/helmfile#1012]
imagine, the following values file loaded in environments:
```
myapp:
  instances:
    - name: bob
      namespace: supercoolnamespace
      key: value
      foo:bar
```

and if I have the follow release:
```
releases:
{{- range .Values.myapp.instances }}
  - name: myapp
    namespace: {{ .namespace }}
    chart: ../../../my/chart
    <<: *default
    values:
      - myapp.yaml.gotmpl
{{- end }}
```

how can I use the key:
```
{{ .key }}
```
from the range in the myapp.yaml.gotmpl file? The only solution I have is to put the whole file in to the releases values.
