### ISSUE TITLE
values/secrets defined in the `environment` section are not applied when `helmfile -e xxx diff`

### ISSUE THREAD

**Issue by jubel-han** [roboll/helmfile#1047]
```yaml
# helmfile

releases:
- name: my-helm-chart
  chart: path/to/my/chart

environments:
  production:

    values:
    - path/to/my/prod/values.yaml
    - inlineValue:
        key: value

    secrets:
    - path/to/my/prod/secrets.yaml
```

```
envvals_loader: loaded values/prod/values.yaml:xxx
worker 1/1 started
Preparing to decrypt secret /xxx/values/prod/secrets.yaml
Found secret in cache /xxx/values/prod/secrets.yaml
worker 1/1 finished
merged environment: xxx
worker 1/1 started
worker 1/1 finished
worker 1/1 started
Comparing release=my-helm-chart, chart=path/to/my/chart
exec: helm diff upgrade --reset-values --allow-unreleased my-helm-chart path/to/my/chart
exec: helm diff upgrade --reset-values --allow-unreleased my-helm-chart path/to/my/chart:
worker 1/1 finished
```
The values and secrets are not attached to the actual `helm diff` command

**Comment by mumoshu** [comment]
Hey! Environment values are not chart values. For chart values, specify `releases[].values` like

```
releases:
- name: my-helm-chart
  chart: path/to/my/chart
  values:
  - path/to/my/prod/values.yaml
    - inlineValue:
        key: value
  secrets:
  - path/to/my/prod/secrets.yaml
```
