### ISSUE TITLE
v1: Alternative name for environment/state values

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#1048]
We call Helmfile-specific template parameters as Environemnt Values or State Values today.

Those parameters can be loaded from helmfile.yaml or another yaml and yaml template files with the syntax:

```
values:
- foo: bar
- path/to/file.yaml
```

or 

```
environments:
  prod:
    values:
    - foo: bar
    - path/to/file.yaml
```

Form the experience maintaining Helmfile for 1+ year, I'd say this name is so confusing and we'd need a better alternative.

The two biggest problems I see are:

- "Environment" in "Environment Values" makes people think it is implicitly inherited to sub-helmfiles like Environment Variables (Example: #1045
- "Values" in "Environment Values" makes people think it is implicitly inherited to charts/releases, which isn't true at all (Example: #1047

What would be a name better than those two?

## Ideas:

1. Template Parameters

```
templateParameterss:
- foo: bar
- path/to/file.yaml

environments:
  prod:
    templateParameters:
    - ...
```

2. Parameters

```
parameters:
- foo: bar
- path/to/file.yaml

environments:
  prod:
    parameters:
    - ...
```

3. Template Variables

```
templateVariables:
- foo: bar
- path/to/file.yaml

environments:
  prod:
    templateVariables:
    - ...
```

4.  State Parameters

```
stateParameters:
- foo: bar
- path/to/file.yaml

environments:
  prod:
    stateParameters:
    - ...
```

## Comments

Generally speaking, something named after `parameters` seems more appropriate than `variables` as it isn't modifiable. Anything called a variable looks modifiable to me.
