### ISSUE TITLE
diff integration breaks down when specifying version

### ISSUE THREAD

**Issue by benlangfeld** [roboll/helmfile#105]
helmfile.yaml:

```yaml
releases:
  - name: bt-internal-blog
    chart: stable/wordpress
    version: 4.9.0
```

```
root@d8f559f99faa:/app# helmfile diff
exec: helm diff bt-internal-blog stable/wordpress --version 4.9.0
2.8.0+1
root@d8f559f99faa:/app# helm diff --version
2.8.0+1
root@d8f559f99faa:/app# helm diff bt-internal-blog stable/wordpress
Error: release: "bt-internal-blog" not found
```
