### ISSUE TITLE
Hooks executing too late

### ISSUE THREAD

**Issue by alexppg** [roboll/helmfile#1055]
Hi

I'm following the section of the documentation to generate a helm chart from kustomize via the bash script helmify. It gives me an error, that the kustomize chart doesn't exist

It seems that when executing any order, first of all there's the part of downloading the dependencies. Since the hooks are executed later, it fails at this point because the directory doesn't exist.

In the other hand, when executing with the parameter `--skip-deps`, it does pass that point and uses the hooks to generate the directory. 

So, my question is, is my reasoning correct? If it is, shouldn't the hooks be called earlier?

Thanks

**Comment by mumoshu** [comment]
@alexppg Ah, good catch! I think your reasoning is indeed correct.

Perhaps we'd better use the helm-x integration to charity kustomization(https://github.com/roboll/helmfile/issues/1157#issuecomment-604743093), or modify Helmfile to run `prepare` hooks before `helm dep` is called?

**Comment by papatego123** [comment]
is there an eta for this ? Having prepare run before `helm dep` would be very useful.

**Comment by mumoshu** [comment]
@papatego123 Hey! That error seems to be caused by potential bug in your chart. Could you share it with me?

Speaking of this issue, it's fixed recently so `prepare` is run before `dep build`.

**Comment by papatego123** [comment]
@mumoshu It's just a standard chart. Regarding the Chart.yaml:
```
apiVersion: v1
appVersion: "1.0"
description: service1
name: helm-service1
version: 0.1.0
```

the first helmfile sync fails with the error
```
  Error: UPGRADE FAILED: YAML parse error on graphql/templates/helmx.all.yaml: error converting YAML to JSON: yaml: line 14: could not find expected ':'
```
but when I run the helmfile command a second time, the chart gets deployed successfully.

**Comment by mumoshu** [comment]
@papatego123 Thanks. But where does `graphql` in `graphql/templates/helmx.all.yaml` come from then?

**Comment by papatego123** [comment]
@mumoshu sorry I pasted the error message from another chart. Here is the correct one:

Error: UPGRADE FAILED: YAML parse error on service1/templates/helmx.all.yaml: error converting YAML to JSON: yaml: line 14: could not find expected ':'

**Comment by papatego123** [comment]
@mumoshu I was able to fix the problem, turns out
```
  {{- if .Values.Deployment.spec.strategy }}
  strategy:
    type: {{ .Values.Deployment.spec.strategy.type }}
  {{- end }}
```
was causing this issue (i deleted it for now). Now I'm getting the same error when using range.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
spec:
  selector:
    matchLabels:
      app: {{ .Values.Deployment.spec.selector.matchLabels.app }}
  {{- if .Values.Deployment.spec.strategy }}
  strategy:
    type: {{ .Values.Deployment.spec.strategy.type }}
  {{- end }}
  template:
    metadata:
    ...
    spec:
      containers:
        {{- range .Values.Deployment.spec.template.spec.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          command: {{ .command }}
          {{- if .volumeMounts }}
          volumeMounts:
            - name: {{ .volumeMounts.name }}
              mountPath: {{ .volumeMounts.mountPath }}
          {{- end }}
      terminationGracePeriodSeconds: {{ .Values.Deployment.spec.template.spec.terminationGracePeriodSeconds }}
      imagePullSecrets:  # stores creds for private repo
        - name: aws-registry-creds
      volumes:
        {{- range .Values.Deployment.spec.template.spec.volumes }}
        - name:  {{ .name }}
          hostPath:
            path: {{ .hostPath.path }}
            type: {{ .hostPath.type }}
        {{- end }}
```

My values file:

```
Deployment:
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: service1
    template:
      metadata:
        labels:
          app: service1
      spec:
        containers:
          - name: service1
            image: image-name
            workingDir: /home/service1
            imagePullPolicy: Always
            command: |
              ["some", "command"]
            volumeMounts:
              name: logs
              mountPath: /home/log
        terminationGracePeriodSeconds: 600  # time before sigkill
        volumes:
          - name: logs
            hostPath:
              path: /var/logs
              type: DirectoryOrCreate

**Comment by mumoshu** [comment]
@papatego123 Which line number does the error message indicate now?

Anyway, I think your `command` should be a yaml array, rather than a multi-line yaml string in your values.

BEFORE:

```
            command: |
              ["some", "command"]
```

AFTER:

```
            command: ["some", "command"]
```

Otherwise your yaml may break after rendering like this:

```
    spec:
      containers:
        - name: NAME
          image: IMAGE
          imagePullPolicy: IMAGE_PULL_POLICY
          command:
  ["some", "command"]
```
