### ISSUE TITLE
changing namespace of a deployment has no effect

### ISSUE THREAD

**Issue by ChloeConnor** [roboll/helmfile#1058]
Editing the namespace field in the helmfile does not redeploy the chart to the new namespace.

e.g changing this:
```
 - name: kubernetes-dashboard
    namespace: kube-system
    chart: stable/kubernetes-dashboard
    version: 1.10.1
    values:
      - eu-west-1/kube-dashboard/values.yaml
```

to this:
```
 - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    chart: stable/kubernetes-dashboard
    version: 1.10.1
    values:
      - eu-west-1/kube-dashboard/values.yaml
```
has no impact.

to get around it I've redeployed with a different name, but it would be good to be able to change namespace in the helmfile.
