### ISSUE TITLE
gotmpl rendering order 

### ISSUE THREAD

**Issue by kalioz** [roboll/helmfile#1065]
Hi there ! 
While using a gotmpl values file, I found out that cli argument weren't passed in priority compared to environment.ENV.values.

values.yaml: 
```
value: 'default'
second:  'default'
```

values.yaml.gotmpl:
```
value: "{{ .Values.foo }}"
``` 
command : `helmfile --state-values-set="foo=cli-arg" template` 

<details>
  <summary>helmfile with value not defined</summary>
  helmfile.yaml:

```
releases:
  - name: test
    chart: "."
    values:
      - "values.yaml.gotmpl"
      - second: "{{ .Values.foo }}"
```
will render
```
value: "cli-arg"
second: "cli-arg"
```
</details>

<details>
  <summary>helmfile with value defined</summary>
  helmfile.yaml:

```
releases:
  - name: test
    chart: "."
    values:
      - "values.yaml.gotmpl"
      - second: "{{ .Values.foo }}"
environments:
  default:
    values:
    - foo: "helmfile"
```
will render
```
value: "helmfile"
second: "cli-arg"
```
</details>

This only appears when using the gotmpl format, the order of overrides may be wrong ?

```
$ helmfile --version
helmfile version v0.98.2
```
