### ISSUE TITLE
Waiting to install release until another release is finished

### ISSUE THREAD

**Issue by maratoid** [roboll/helmfile#107]
Something like:

```
releases:
  # Published chart example
  - name: vault
    namespace: vault 
    labels:                                 
      foo: bar
    chart: roboll/vault-secret-manager
    version: ~1.24.1
  - name: grafana
    namespace: another
    chart: ../my-charts/grafana
    wait:
      vault       # wait for vault release to be "finished" before running this helm install
```

I've found myself in a situation where I was installing vault and then a bunch of things that depended on vault to be up, unsealed and populated with secrets. I ended up writing a large-ish bash script that drove `helmfile` with a bunch of while loops querying status of vault pods.

Could combine this with something like:

```
releases:
  # Published chart example
  - name: vault
    namespace: vault 
    labels:                                 
      foo: bar
    chart: roboll/vault-secret-manager
    version: ~1.24.1
    pre:
      shell: /bin/sh
      command: pre.sh          # pre orchestrate some stuff
    post: 
      shell: /bin/sh
      command: post.sh         # post orchestrate some stuff
  - name: grafana
    namespace: another
    chart: ../my-charts/grafana
    wait:
      vault       # wait for vault release to be "finished", pre and post included, before running this helm install
```

Maybe this is out of scope for a tool like helmfile though.
