### ISSUE TITLE
helmfile list reports installed after destroy

### ISSUE THREAD

**Issue by corradomatt** [roboll/helmfile#1076]
During my initial tests of helmfile I installed a chart in a new namespace. Installation worked flawlessly. I then attempted to uninstall everything with `helmfile destroy` and while the actual uninstall process went off without a hitch I noticed that running `helmfile list` is still reporting the installation.

I'm using the following...
```bash
$ helmfile --version
helmfile version v0.98.2

$ helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

My helmfile looks like this...
```yaml
releases:
  - name: testing
    namespace: testns
    chart: stable/redis
    version: ~9.5.5
```

One last thing to note is that if I change the name of the release, run `helmfile sync` and then run `helmfile list` the output shows correctly as the new release name and doesn't show the old release that wasn't purged from the list output.
