### ISSUE TITLE
Standalone hooks

### ISSUE THREAD

**Issue by dudicoco** [roboll/helmfile#1079]
Is it possible to implement hooks which will run before all of the other releases?
Something like:
```
hooks:
- events: ["prepare"]
  showlogs: true
  command: "aws eks update-kubeconfig "
    args: ["--name {{`{{.Environment.Name}}`}}", --region "{{`{{.Values.region}}`}}"
"]
releases:
- name: myapp
  chart: mychart
```
