### ISSUE TITLE
helmfile template not functional for helm 3

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#1081]
`helmfile -helm-binary /usr/local/bin/helm3 -q template --skip-deps`

```in ./helmfile.yaml: helm3 exited with status 1:
  Error: unknown flag: --name
```

```
repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
charts:
  - name: nginx
    chart: stable/nginx-ingress
```
