### ISSUE TITLE
Unable to set value for annotation variable

### ISSUE THREAD

**Issue by xjantoth** [roboll/helmfile#109]
It seem like there is a problem when I want to add variable using **set** and the value of this 
variable is supposed to be  `key: value` pair like **annotations** when it comes to nginx-ingress controller
using AWS.

    context: example.com                # kube-context (--kube-context)
    
    releases:
      # Published chart example
      - name: controller-pod-nginx                  # name of this release
        namespace: ingress-nginx                    # target namespace
        chart: stable/nginx-ingress                 # the chart being installed to create this release, referenced by `repository/chart` syntax
        set:                                        # values (--set)
          - name: rbac.create
            value: true
          - name: controller.service.annotations
            value: 'service.beta.kubernetes.io/aws-load-balancer-ssl-ports:https'

**error message**:

     helmfile -f deploy_cp_ns_ingress-nginx.yaml sync
    exec: helm repo add roboll http://roboll.io/charts --kube-context example.com
    "roboll" has been added to your repositories
    exec: helm repo update --kube-context example.com
    Hang tight while we grab the latest from your chart repositories...
    ...Skip local chart repository
    ...Successfully got an update from the "roboll" chart repository
    ...Successfully got an update from the "stable" chart repository
    Update Complete. ⎈ Happy Helming!⎈
    exec: helm upgrade --install controller-pod-nginx stable/nginx-ingress --namespace ingress-nginx --set rbac.create=true,controller.service.annotations=service.beta.kubernetes.io/aws-load-balancer-ssl-ports:https --kube-context example.com
    Error: UPGRADE FAILED: YAML parse error on nginx-ingress/templates/controller-service.yaml: error unmarshaling JSON: json: cannot unmarshal string into Go struct field .annotations of type map[string]string
    err: exit status 1

If I use a pure **helm** installation that works with no problem:

    helm install stable/nginx-ingress --set rbac.create=true --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-backend-protocol"=http --namespace=ingress-nginx

That works with no problem.
I will need to add numerous **annotations**.

**Comment by sstarcher** [comment]
The command line you are specifying at as a map, but in the set values section you are saying it as a single string.  I'm not certain if map values are support in the values section.  If it is the layout would be 

```
      - name: controller.service.annotations
        value: 
          'service.beta.kubernetes.io/aws-load-balancer-ssl-ports': https
```

If that does not work you can always use a file instead of inlining the values.

**Comment by xjantoth** [comment]
Well obviously this solution does not work. I spent entire day trying to figure out the correct format

**result:**
`exec: helm upgrade --install controller-pod-nginx stable/nginx-ingress --namespace ingress-nginx --set rbac.create=true,controller.service.annotations= --kube-context example.com `

can you probably  think about some other solution than **values.yaml** file?

**Comment by sstarcher** [comment]
I was not recommending values.yaml.  I'm recommending 

```
    values: [ whatever.yaml ]   
```

**Comment by sstarcher** [comment]
@xjantoth as for the `obviously this solution does not work`

Here is the solution
```
releases:
  # Published chart example
  - name: controller-pod-nginx                  # name of this release
    namespace: ingress-nginx                    # target namespace
    chart: stable/nginx-ingress                 # the chart being installed to create this release, referenced by `repository/chart` syntax
    set:                                        # values (--set)
      - name: rbac.create
        value: true
      - name: controller.service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-ssl-ports
        value: https
``

**Comment by xjantoth** [comment]
Your solution seemed to be promising but:

Release "controller-pod-nginx" does not exist. Installing it now.
Error: release controller-pod-nginx failed: Service in version "v1" cannot be handled as a Service: v1.Service: ObjectMeta: v1.ObjectMeta: Annotations: ReadString: expects " or n, parsing 214 ...meout\"":3... at {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"\"service.beta.kubernetes.io/aws-load-balancer-backend-protocol\"":"http","\"service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout\"":3600,"\"service.beta.kubernetes.io/aws-load-balancer-ssl-cert\"":"...977bfa5298fc","\"service.beta.kubernetes.io/aws-load-balancer-ssl-ports\"":"https"},"labels":{"app":"nginx-ingress","chart":"nginx-ingress-0.13.2","component":"controller","heritage":"Tiller","release":"controller-pod-nginx"},"name":"controller-pod-nginx-nginx-ingress-controller","namespace":"ingress-nginx"},"spec":{"clusterIP":"","ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80},{"name":"https","port":443,"protocol":"TCP","targetPort":443}],"selector":{"app":"nginx-ingress","component":"controller","release":"controller-pod-nginx"},"type":"LoadBalancer"}}

**Comment by sstarcher** [comment]
My post works as written why did you add the quotes?

**Comment by xjantoth** [comment]
well if I am trying to add just one **annotation** that works. Before pasting any comments here I am trying various options (adding quotes - as I found in some documentations, adding quotes for values etc.  )

```
releases:
  # Published chart example
  - name: controller-pod-nginx                  # name of this release
    namespace: ingress-nginx                    # target namespace
    chart: stable/nginx-ingress                 # the chart being installed to create this release, referenced by `repository/chart` syntax
    # values: ["nginx_ns_ingress-nginx_values.yaml"]
    set:                                        # values (--set)
      - name: rbac.create
        value: "true"
      - name: controller.service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-ssl-ports
        value: https
      - name: controller.service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-connection-idle-timeout
        value: 3600
      - name: controller.service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-backend-protocol
        value: http

```

Output:

```
Update Complete. ⎈ Happy Helming!⎈
exec: helm upgrade --install controller-pod-nginx stable/nginx-ingress --namespace ingress-nginx --set rbac.create=true,controller.service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-ssl-ports=https,controller.service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-connection-idle-timeout=3600,controller.service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-backend-protocol=http --kube-context example.com
Release "controller-pod-nginx" does not exist. Installing it now.
Error: release controller-pod-nginx failed: Service in version "v1" cannot be handled as a Service: v1.Service: ObjectMeta: v1.ObjectMeta: Annotations: ReadString: expects " or n, parsing 206 ...timeout":3... at {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-backend-protocol":"http","service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout":3600,"service.beta.kubernetes.io/aws-load-balancer-ssl-ports":"https"},"labels":{"app":"nginx-ingress","chart":"nginx-ingress-0.13.2","component":"controller","heritage":"Tiller","release":"controller-pod-nginx"},"name":"controller-pod-nginx-nginx-ingress-controller","namespace":"ingress-nginx"},"spec":{"clusterIP":"","ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80},{"name":"https","port":443,"protocol":"TCP","targetPort":443}],"selector":{"app":"nginx-ingress","component":"controller","release":"controller-pod-nginx"},"type":"LoadBalancer"}}
```

**Comment by sstarcher** [comment]
@xjantoth I took a look at the output you have try quoting 3600.  The current output you have has all of the correct annotations, but it complaining about the lack of quotes around 3600.

**Comment by sstarcher** [comment]
@xjantoth again none of this is related to helmfile this is all in how helm itself is handling these arguments.

As I said quoting 3600 fixes the issue.  The following works.

```
releases:
  # Published chart example
  - name: controller-pod-nginx                  # name of this release
    namespace: ingress-nginx                    # target namespace
    chart: stable/nginx-ingress                 # the chart being installed to create this release, referenced by `repository/chart` syntax
    # values: ["nginx_ns_ingress-nginx_values.yaml"]
    set:                                        # values (--set)
      - name: rbac.create
        value: "true"
      - name: controller.service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-ssl-ports
        value: https
      - name: controller.service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-connection-idle-timeout
        value: "3600"
      - name: controller.service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-backend-protocol
        value: http
```
