### ISSUE TITLE
.Environment.Name is not set in environment values template

### ISSUE THREAD

**Issue by messiahUA** [roboll/helmfile#1090]
I'm trying to do dynamic environment values:
```
environments:
  services:
    values:
      - values.yaml.gotmpl
```
values.yaml.gotmpl contains simple exec of a file with ".Environment.Name" as an argument, but it is not set (empty).

Is it expected behavior? Considering environment name is passed as a cli parameter and should be available from the start I don't see a reason for it to not be set at this point.
