### ISSUE TITLE
pass data from release file template to values file template

### ISSUE THREAD

**Issue by jurgenweber** [roboll/helmfile#1096]
Is there a way to pass data from releases to the values templates in a release?

The idea is, I have an array in my `.Values` that I would like to range and then use the data for that instance of the array:

The array:
```
api:
  instances:
    - name: bob
       option: one
```

```
releases:
{{- range .Values.api.instances }}
  - name: api
    namespace: {{ .name }}
    chart: my/api
    values:
      - api.yaml.gotmpl
{{ end }}
```

so I would like `api.yaml.gotmpl` to have access to `.`.

**Comment by jurgenweber** [comment]
In the end I moved as much config I could into the helm charts themselves and then moved any unique config into the releases file.

```
  - name: api
    namespace: {{ .name }}
    chart: my/aii
    <<: *default
    values:
      - api:
          helm-chart:
             thing: {{ .option }}
```

etc
