### ISSUE TITLE
Add resource lookup function like in helm3

### ISSUE THREAD

**Issue by paulczar** [roboll/helmfile#1097]
Helm 3 now has a [lookup template function](https://github.com/helm/helm/pull/6752) that lets you check for resources.  This would allow us to run hooks based on pre-existing resources... for example helm3 does not currently create namespaces ... we could put a condition around a release that looks something like:

```
{{ if not (lookup "v1" "Namespace" .Release.namespace "my-app") }}
hooks:
  - events: ["prepare", "cleanup"]
    showlogs: true
    command: "kubectl"
    args: ["create", "ns", "my-app"]
{{- end }}
```

**Comment by mumoshu** [comment]
@paulczar Thanks! I'm not familiar with the `lookup` function but is it basically `kubectl get -n NAMESPACE KIND NAME`?

Unfortunately, this doesn't seem to comply with how Helmfile works. If we add `lookup`, all the lookups would be executed BEFORE all the releases are parsed. Is that really an expected behavior?

**Comment by mumoshu** [comment]
Probably a better way would be to enhance hooks so that you can easily write things like this.

How about adding `if` to make a hook conditional, and optionally add `run` as an alternative to the pair of `command` and `args`, so that `run` and `if` seems visually consistent?

```
hooks:
- events: ["prepare", "cleanup"]
  sohwlogs: true
  if: ["kubectl", "get", "ns", "{{.Release.namespace}}"]
  run: ["kubectl", "create", "ns", "{{.Release.namespace}}"]
```
