### ISSUE TITLE
Environment based value direct substitution in charts not working 

### ISSUE THREAD

**Issue by alisters** [roboll/helmfile#1099]
I'd like to use the environment functionality, with a values file, to template our charts per environment. I don't need to template values in the helmfile, only the referenced charts. I'd like to leave the helmfile largely untouched if possible.

The issue is that when i reference a value inside a chart from an environment inside my helmfile - see deployment.yaml below, there is no value provided to them. i.e the output is  (note lines 7 and 8 below ) - UNLESS i reference the value inside the release stanza for a given chart helmfile (i.e assign it to an intermediate value inside the release)

```yaml
value-from-env-values.yaml: {{ .Values.envInlineValue }}
value-from-env-values-file.yaml: {{ .Values.envFileValue }}
```

```bash
Building dependency release=test, chart=test-chart
Templating release=test, chart=test-chart
# Source: test-chart/templates/deployment.yaml
value-from-chart-values.yaml: 1
value-from-release: build
value-from-release-file: release-bar
value-from-env-values.yaml:
value-from-env-values-file.yaml:
value-from-env-values-via-release-value.yaml: Some build
value-from-env-values-file-via-release-value.yaml: build-bar
value-from-env-templated-release-values-file.yaml:
```

(The naming of the fields and their values reflect where the field values are derived from)

- I'm running >  `helmfile -e build template` 

My test helmfile and chart is 

helmfile.yaml

```yaml
environments:
  build:
    values:
    - build-env.yaml
    - envInlineValue: "Some build"
    missingFileHandler: Error

---

releases:
  - name: test           
    chart: test-chart   
    values:
    - releaseInlineValueTemplatedEnvObjectName: {{ .Environment.Name }}
    - release-env.yaml
    - releaseInlineValueTemplatedEnvObject: {{.Environment.Values.envInlineValue }}
    missingFileHandler: Error
```

test-chart/templates/deployment.yaml

```yaml
value-from-chart-values.yaml: {{ .Values.replicaCount }}
value-from-release: {{ .Values.releaseInlineValueTemplatedEnvObjectName }}
value-from-release-file: {{ .Values.releaseFileValue }}
value-from-env-values.yaml: {{ .Values.envInlineValue }}
value-from-env-values-file.yaml: {{ .Values.envFileValue }}
value-from-env-values-via-release-value.yaml: {{ .Values.releaseInlineValueTemplatedEnvObject }}
value-from-env-values-file-via-release-value.yaml: {{ .Values.releaseInlineValueTemplatedEnvObjectFromFile }}
value-from-env-templated-release-values-file.yaml: {{ .Values.releaseTemplatedEnvFileValue }}

all-values: 
  {{ toYaml . }}

```

values.yaml

```yaml
# Default values for test-chart.                       
# This is a YAML-formatted file.                       
# Declare variables to be passed into your templates.  
                                                       
replicaCount: 1                                        
                                                       
image:                                                 
  repository: nginx                                    
  pullPolicy: IfNotPresent                             
```

build-env.yaml

```yaml
envFileValue: "build-bar"
```

release-env.yaml

```yaml
releaseFileValue: "release-bar"
```

I've tried this test with:

- Environment block first and last
- With and without '---' seperator
- default environment and named environments
- With the --log-level command (and debug)

When i inspect the rendered chart toYaml field, in values i see only 

```yaml
Values:
  image:
    pullPolicy: IfNotPresent
    repository: nginx
  releaseFileValue: release-bar
  releaseInlineValueTemplatedEnvObject: Some build
  releaseInlineValueTemplatedEnvObjectFromFile: build-bar
  releaseInlineValueTemplatedEnvObjectName: build
  replicaCount: 1
```

i.e the values defined in the environment have not been passed (envFileValue: "build-bar")

When i run with the debug command I can see that it looks like it's generating values - and storing them in /tmp/.... (this is the output without the --- divider - it differs from the output with the --- divider, which has no reference "to replaced <no value>s to workaround" ). I've looked at these files - none of these contain envFileValue despite the logging showing that it did "load" these values 

i.e merged environment: &{build map[envFileValue:build-bar envInlineValue:Some build] map[]}

```
processing file "helmfile.yaml" in directory "."
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{build map[] map[]}, overrode=<nil>
first-pass uses: &{build map[] map[]}
first-pass rendering output of "helmfile.yaml.part.0":
 0:
 1: releases:
 2:   - name: test
 3:     chart: test-chart
 4:     values:
 5:       - releaseInlineValueTemplatedEnvObjectName: build
 6:       - release-env.yaml
 7:       - releaseInlineValueTemplatedEnvObject:  <no value>
 8:       - releaseInlineValueTemplatedEnvObjectFromFile:  <no value>
 9:     missingFileHandler: Error
10:
11: environments:
12:   build:
13:     values:
14:     - build-env.yaml
15:     - envInlineValue: "Some build"
16:     missingFileHandler: Error

replaced <no value>s to workaround https://github.com/golang/go/issues/24963 to address https://github.com/roboll/helmfile/issues/553:
  strings.Join({
        ... // 5 identical lines
        "      - releaseInlineValueTemplatedEnvObjectName: build",
        "      - release-env.yaml",
-       "      - releaseInlineValueTemplatedEnvObject:  <no value>",
-       "      - releaseInlineValueTemplatedEnvObjectFromFile:  <no value>",
+       "      - releaseInlineValueTemplatedEnvObject:  ",
+       "      - releaseInlineValueTemplatedEnvObjectFromFile:  ",
        "    missingFileHandler: Error",
        "",
        ... // 6 identical lines
  }, "\n")

envvals_loader: loaded build-env.yaml:map[envFileValue:build-bar]
first-pass produced: &{build map[envFileValue:build-bar envInlineValue:Some build] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {build map[envFileValue:build-bar envInlineValue:Some build] map[]}
vals:
map[envFileValue:build-bar envInlineValue:Some build]
defaultVals:[]
second-pass rendering result of "helmfile.yaml.part.0":
 0:
 1: releases:
 2:   - name: test
 3:     chart: test-chart
 4:     values:
 5:       - releaseInlineValueTemplatedEnvObjectName: build
 6:       - release-env.yaml
 7:       - releaseInlineValueTemplatedEnvObject:  Some build
 8:       - releaseInlineValueTemplatedEnvObjectFromFile:  build-bar
 9:     missingFileHandler: Error
10:
11: environments:
12:   build:
13:     values:
14:     - build-env.yaml
15:     - envInlineValue: "Some build"
16:     missingFileHandler: Error

envvals_loader: loaded build-env.yaml:map[envFileValue:build-bar]
merged environment: &{build map[envFileValue:build-bar envInlineValue:Some build] map[]}
Building dependency release=test, chart=test-chart
exec: helm dependency build test-chart
exec: helm dependency build test-chart:
processing 1 groups of releases in this order:
GROUP RELEASES
1     test

processing releases in group 1/1: test
worker 1/1 started
worker 1/1 finished
successfully generated the value file at release-env.yaml. produced:
releaseFileValue: "release-bar"
Templating release=test, chart=test-chart
exec: helm template test test-chart --values /tmp/values488756425 --values /tmp/values726486932 --values /tmp/values876768739 --values /tmp/values216311782
exec: helm template test test-chart --values /tmp/values488756425 --values /tmp/values726486932 --values /tmp/values876768739 --values /tmp/values216311782: ---
# Source: test-chart/templates/deployment.yaml
value-from-chart-values.yaml: 1
value-from-release: build
value-from-release-file: release-bar
value-from-env-values.yaml:
value-from-env-values-file.yaml:
value-from-env-values-via-release-value.yaml: Some build
value-from-env-values-file-via-release-value.yaml: build-bar
value-from-env-templated-release-values-file.yaml:

#all-values:
 # `{`{ toYaml . `}`}

---
# Source: test-chart/templates/deployment.yaml
value-from-chart-values.yaml: 1
value-from-release: build
value-from-release-file: release-bar
value-from-env-values.yaml:
value-from-env-values-file.yaml:
value-from-env-values-via-release-value.yaml: Some build
value-from-env-values-file-via-release-value.yaml: build-bar
value-from-env-templated-release-values-file.yaml:

#all-values:
 # `{`{ toYaml . `}`}

```

I'm using:

helmfile version v0.99.0

helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}

What am i missing ? Is this by design ? Apologies if i'm missing something obvious !!

[helmfile-test.zip](https://github.com/roboll/helmfile/files/4196287/helmfile-test.zip)

**Comment by cdunford** [comment]
I am seeing the same behavior on 0.101.0

**Comment by irlevesque** [comment]
I'm not sure if this is by design, but it bit me too. I was hoping to utilize `bases` to implement an environment layer that could be a reusable way to reference helmfile-specific values to reduce boilerplate for requiring the helmfile authors at our org.

Here's what I was trying to do:

```shell
→ tree .
├── helmfile.yaml
└── values
    ├── development.yaml
    ├── production.yaml
    └── staging.yaml
```

```shell
→ tree ../defaults/
├── layers
│   └── environments.yaml
└── values
    ├── development.yaml
    ├── production.yaml
    └── staging.yaml
```

```shell
→ cat ../defaults/layers/environments.yaml
environments:
  staging:
    values:
    - ../defaults/values/staging.yaml
    - values/staging.yaml
...

```shell
→ cat ../defaults/values/staging.yaml
global:
  environment: staging
...
```

```
bases:
- ../defaults/layers/environments.yaml

releases:
- name: app
  chart: repo/app
  version: "~0.1.0"
```

The hope was that we could simplify the dev experience by providing an "automatic" way to reference global variables and to have helmfile env-specific values files integrated into a release's values using a simple `helmfile -e staging...` syntax. Unfortunately, I see that the values assigned in the `environments` are only accessible to the helmfile itself and not the helm chart.

My hope is that environment values can be more useful. At the very least, they need better documentation.

**Comment by mumoshu** [comment]
@alisters Hey! Sorry for the slow response.

> i.e the values defined in the environment have not been passed (envFileValue: "build-bar")

Yeah this is by design.

The environment values are completely different concept than chart values. That's why the name doesn't contain "chart".

I admit this is confusing but it was unavoidable to support the case that you wanna have "intermediate" environment values that you don't want to pass-though to charts without any processing.

**Comment by mumoshu** [comment]
> At the very least, they need better documentation.

@irlevesque I've been constantly hearing people asking this - but honestly I'm not sure where/how to improve. 

Environment values concept is already documented in https://github.com/roboll/helmfile#environment-values and it doesn't say it is propagated to chart values.

Also - for your specific example, you should use `---` after `bases`. Otherwise you're falling into the chicken-and-egg prob between environment values and your desired state. That is, helmfile.yaml needs environment values loaded in order to render all the template expressions. But you need to render the helmfile.yaml to load environment values.

```
bases:
- ../defaults/layers/environments.yaml

---

releases:
- name: app
  chart: repo/app
  version: "~0.1.0"
```

**Comment by mumoshu** [comment]
Also, propagating environment values to chart values is as easy as:

```
bases:
- ../defaults/layers/environments.yaml

---

releases:
- name: app
  chart: repo/app
  version: "~0.1.0"
  values:
  - {{ .Values | ndeint 4 }}
```
