### ISSUE TITLE
cannot install stolon using helmfile

### ISSUE THREAD

**Issue by zerthimon** [roboll/helmfile#1103]
Using helm 3.1.0, trying to install stolon
helmfile:
```
repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: stolon
    namespace: stolon
    chart: stable/stolon
    version: v1.5.6
```
installing:
```
# helmfile -i apply
Adding repo stable https://kubernetes-charts.storage.googleapis.com
"stable" has been added to your repositories

Updating repo
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 

Comparing release=stolon, chart=stable/stolon

No affected releases
```
