### ISSUE TITLE
helmfile apply fails with `expects " or n, but found t`

### ISSUE THREAD

**Issue by slaterx** [roboll/helmfile#1106]
For the following service template:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{- if .Values.svc.annotations }}{{- range $name, $value := .Values.svc.annotations }}{{- if not (empty $value) }}
    {{ $name }}: {{ $value }}
{{- end }}{{- end }}{{- end }}
  labels:
{{- if .Values.labels }}{{- range $name, $value := .Values.labels }}{{- if not (empty $value) }}
    {{ $name }}: {{ $value }}
{{- end }}{{- end }}{{- else }}
    name: {{ .Values.name }}
{{- end }}
spec:
  type: {{ .Values.svc.type }}
  ports:
{{- range .Values.svc.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: {{ .protocol }}
    targetPort: {{ .targetPort }}
{{- end }}
  selector:
{{- if .Values.labels }}{{- range $name, $value := .Values.labels }}{{- if not (empty $value) }}
    {{ $name }}: {{ $value }}
{{- end }}{{- end }}{{- else }}
    name: {{ .Values.name }}
{{- end }}
{{- end }}
```

With the following helmfile:

```yaml
repositories:
  - name: "foo"
    url: "https://bar"
helmDefaults:
  timeout: 1800
environments:
  staging:
    values:
      - {{ env "STAGING_YAML" | default "values/staging.yaml" }}
releases:
  - name: {{ .Environment.Name }}
    namespace: {{ .Namespace }}
    chart: foo/mychart
    version: !!string 1.2.3
    atomic: true
    wait: true
    labels:
      app: {{ .Environment.Name }}
    values:
      - name: {{ .Environment.Name }}
(...)
        svc:
          enabled: true
          type: LoadBalancer
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "secret-arn"
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
          ports:
            - name: http
              port: 80
              protocol: TCP
              targetPort: 3000
            - name: https
              port: 443
              protocol: TCP
              targetPort: 3000
```

When executing helmfile apply, we obtain the following go error:

```bash  
coalesce.go:199: warning: destination for env is a table. Ignoring non-table value rendered_from_helmfile
coalesce.go:199: warning: destination for livenessProbe is a table. Ignoring non-table value <nil>
Error: unable to build kubernetes objects from release manifest: unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|enabled":true,"servi|..., bigger context ...|o/aws-load-balancer-connection-draining-enabled":true,"service.beta.kubernetes.io/aws-load-balancer-|...
```

Tested on macOS and Linux. See that all annotations are defined using double quotes, but they are referenced in go error as without quotes. Diff shows the resource as new 100% of time. In my example, services are the only resources at the moment with annotations.
