### ISSUE TITLE
TLS support?

### ISSUE THREAD

**Issue by reidab** [roboll/helmfile#111]
I've got tiller configured to require a client cert on incoming connections, either provided via the `--tls-ca-cert`, `--tls-cert`, and `--tls-key` options to `helm` or by placing the relevant certs in `$HELM_HOME` and just providing `--tls` to `helm`.

Is there a way to enable TLS transport for the `helm` commands that `helmfile` execs?

**Comment by reidab** [comment]
It looks like this is possible by passing `--args --tls` to `helmfile sync`, but it still might make sense to be globally configurable.

**Comment by rmartinez3** [comment]
Theres an issue currently opened at helm diff repo regarding this issue for the diff plugin.
https://github.com/databus23/helm-diff/issues/35

**Comment by maver1ck** [comment]
@mumoshu 
There is also work to be done in helmfile. 
For example delete command doesn't support args (so I can't pass --tls)

**Comment by mumoshu** [comment]
So this is possible today by using `--args`. To make it even more declarative, I'm going to add the following config syntax:

```yaml
helmDefaults:
  tls:
    # when enabled, helmfile adds `--tls` flags to helm commands that supports tls(upgrade, test, diff)
    enabled: true
    # options
    key: path/to/key
    cert: path/to/cert
    ca: path/to/ca/cert
```

Any comments? Thanks!
