### ISSUE TITLE
Add support for ArgoCD resource hooks and sync waves

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#1110]
I've often heard that people use `helmfile template` to export the whole collection of K8s manifests managed by Helmfile to a "config repo" for GitOps, so that actual deployments can be delegated toArgoCD and Flux.

The advantages of this approach are:

- Higher security: Your CI doesn't need production env access for diffing and applying anymore
- Better visibility: Instead of `helmfile diff` results being posted in your Slack channel or pull request comments, they are now visible and reviewable in the pull request's "Files changed" tab would give you better reviewing experience by providing nicer coloring, layouts, inline review comments, etc.

Altohugh Helmfile + GitOps do have advantages over the "Helmfile on CI" approach, there are issues, too.

For me, the biggest issue in traditional GitOps had been that there was no way to control installation/upgrade order of helm charts. Helmfile have been long supporting this via DAG(`needs: ...`) and sub-helmfiles(`helmfiles: [...]`).

However, I've recently got to know about ArgoCD's [Resource Hooks](https://argoproj.github.io/argo-cd/user-guide/resource_hooks/) and [Sync Waves](https://argoproj.github.io/argo-cd/user-guide/sync-waves/#how-does-it-work), and realized that, theoretically, it enables Helmfile to export manifests with ordering in mind.

I'd like to experiment this by introducing a new flag `--argocd-phases-and-hooks` to `helmfile template`.

The flag will instruct Helmfile to add `argocd.argoproj.io/hook: PreSync` annotations to whatever manifest that has `"helm.sh/hook": pre-install,pre-upgrade`, and also `argocd.argoproj.io/sync-wave: "N"` where `N` is the globally assigned sequence number of the set of releases that are installed/upgraded concurrently.

To illustrate how `N` is assigned, let's assume you have the following helmfiles:

helmfile.yaml:

```yaml
helmfiles:
- infra.yaml
- apps.yaml
```

apps.yaml:

```yaml
releases:
- name: foo-api
  chart: mycharts/api
  # ...
- name: bar-api
  chart: mycharts/api
  # ...
- name: web
  chart: mycharts/web
  needs:["foo-api", "bar-api"]
```

infra.yaml

```yaml
- name: logging
  chart: mycharts/fluentbit
  # ...
- name: prometheus
  chart: mycharts/prometheus
  # ...
- name: cilium
  chart: cilium/cilium
  # ...
- name: istio
  chart: istio/istio
  # ...
  needs: ["cilium"]
```

Today, `helmfile sync` and `helmfile apply` deploys this in the following order. Note that each group of releases are deployed concurrently as they don't depend on each other.

1: logging, prometheus, cilium
2. istio
3. foo-api, bar-api
4. web

`helmfiel template --argocd-phases-and-hooks` will give `argocd.argoproj.io/sync-wave: "1"` annotations to any manifest that belongs to `logging`, `prometheus` and `cilium`, `argocd.argoproj.io/sync-wave: "2"` for `istio`, and so on.

You can git-push these manifests to a config repo, so that ArgoCD will sync those manifests in the order.
