### ISSUE TITLE
Best practice for deploying additional ConfigMap

### ISSUE THREAD

**Issue by svistoi** [roboll/helmfile#1129]
Hi,

Certain charts like stable/mongodb allow database initialization scripts from ConfigMap.  Other charts allow you to reference Secrets for admin passwords.  In both cases I need to create k8s object and then deploy the chart.  What's the best way to do that if using helmfile?

From reading the docs, one way would be with 
```
hooks:
  - events: ["prepare"]
    showlogs: true
    command: "sh"
    args: ["kubectl apply -f myconfig.yaml"]
```

Is that an anti-pattern for usage?  Is there a better way?

Thanks.

**Comment by abatilo** [comment]
Prepare is intended to be a non-mutating change. Either you can use `presync` and do a `helmfile sync` instead of `helmfile apply`, or what I've done to solve this problem is to use the [incubator/raw](https://github.com/helm/charts/tree/master/incubator/raw) chart, and then created another `helmfile`, and reference it as a layered helmfile.

```
helmfiles:
  - other-helmfile.yaml
```

The other helmfiles are evaluated before the main one that you're executing, so you can get order execution guarantees.

**Comment by andrewnazarov** [comment]
We are using separate charts and incubator/raw for such cases. There might be some issues with hooks such as `diff` won't see changes in your configMap.yaml, for instance, as it was stated before.

**Comment by svistoi** [comment]
Thank you for the suggestions, that does seem like a better way and should cleanup on helm destroy.
And I wouldn't need destroy hook https://github.com/roboll/helmfile/issues/802

I'll close this issue.

**Comment by seocam** [comment]
Any alternatives for incubator/raw since it's deprecated?

**Comment by YevheniiPokhvalii** [comment]
> incubator/raw

Here is the alternative, but I haven't tried it myself: https://github.com/itscontained/charts/tree/master/itscontained/raw

**Comment by YevheniiPokhvalii** [comment]
It may help someone. I did it this way:

```
---
releases:

- name: "argo"
  namespace: "argocd"
  labels:
    chart: "argocd"
  chart: "argo/argo-cd"
  hooks:
  - events: ["prepare"]
    showlogs: true
    command: "kubectl"
    args: ["apply", "-f", "../resources/argocd-scc.yaml"]
  - events: ["postuninstall"]
    showlogs: true
    command: "kubectl"
    args: ["delete", "-f", "../resources/argocd-scc.yaml"]
```
