### ISSUE TITLE
Feature Request: Support for Upcoming Helm3 —create-namespace 

### ISSUE THREAD

**Issue by osterman** [roboll/helmfile#1140]
## what

Next release of Helm will hopefully have support for automatic namespace creation. 

Would like this natively supported by Helmfile. 

## why

This is a pain point when migrating from helm2 to heln3. Using the flag restores the behavior of helm2.

## references 
https://github.com/helm/helm/pull/7648

**Comment by mumoshu** [comment]
Sounds good!

Can we just always add that flag to `helm upgrade` called by helmfile?

**Comment by RothAndrew** [comment]
Toggle. I find BaconGobbler's arguments about letting users opt in/out to this functionality totally valid. Clusters with strong RBAC will have users that want to use Helmfile that don't have permissions to create namespaces.

**Comment by mumoshu** [comment]
Thanks. Fair enough! Let's add a toggle that would look like `disableNamespaceCreation`, which is set to `true` when and only when you want to opt-out.

**Comment by mumoshu** [comment]
Note that Helmfile will never take care of cleaning up namespaces created with `disableNamespaceCreation: false` and wrong namespace names.

For that, you'll want to add a dedicated release named something like `namespaces` with `incubator/raw` chart that includes namespaces that are required by subsequent releases.

You can use helmfile's DAG after that, like:

```yaml
releases:
- name: namespaces
  chart: incubator/raw
  namespace: kube-system
  values:
  - resources:
     kind: Namespace
     metadata:
        name: foo
- name: foo
  namespace: foo
  chart: myapp
  needs: ["kube-system/namespaces"]
```


Releated: https://github.com/helm/helm/pull/7648#issuecomment-590520569
