### ISSUE TITLE
release templating cannot refer to other release variables

### ISSUE THREAD

**Issue by mtb-xt** [roboll/helmfile#1143]
I'm using release templating for a common directory structure with auto loading values per environment, and really want to use in `installed` field as well. But for the life of me, I can't figure out how. Either there's a bug or I'm doing something wrong (most probably)

I have this in templates.yaml:
```
  loader: &loader
    missingFileHandler: Debug
    values:
    - values.yaml
    - values.yaml.gotmpl
    - ./{{ if contains "prod" .Environment.Name }}prod.yaml{{ else }}nonexistent.yaml{{end}}
    - ./{{ if contains "prod" .Environment.Name }}prod.yaml.gotmpl{{ else }}nonexistent.yaml{{end}}
    - ./{{ .Environment.Name }}.yaml
    - ./{{ .Environment.Name }}.yaml.gotmpl
```
and I'm trying to do something like this:
```
---
bases:
- ../../common/environments.yaml
- ../../common/defaults.yaml
---
{{ readFile "../../common/templates.yaml" }}
releases:
- name: "prometheus-operator"
  namespace: "prometheus-operator"
  chart: "stable/prometheus-operator"
  installed: {{ .Values.releases.`{{ .Release.name }}` | getOrNil "enabled" | default "false" }}
  <<: *loader
```
ideally, I want `version` and `installed` to go live in the `loader` template, but I can't - no combination of {s and `s work. and yes, I've tried installedTemplate as well. 
I have to hardcode it for now like this
```
  version:   {{ .Values.releases.prometheus_operator | getOrNil "version" | default "~8" }}
  installed: {{ .Values.releases.prometheus_operator | getOrNil "enabled" | default "false" }}
```
@mumoshu any chance you could have a look?

**Comment by mumoshu** [comment]
Could you try this?

```
installedTemplate: {{` .Values.releases | index .Release.Name | getOrNil "enabled" | default "false" }}
```

**Comment by mtb-xt** [comment]
> Could you try this?
> 
> ```
> installedTemplate: {{` .Values.releases | index .Release.Name | getOrNil "enabled" | default "false" }}
> ```
Thanks for having a look, unfortunately it doesn't work:
installedTemplate: {{`{{ .Values.releases | index .Release.Name | getOrNil "enabled" | default "false" }}`}} gives 

```
44 | + cd components && helmfile -e stage diff
45 | in ./helmfile.yaml: in .helmfiles[0]: in releases/external-dns/helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: line 38: found character that cannot start any token
```
installedTemplate: {{ .Values.releases | index .Release.Name | getOrNil "enabled" | default "false" }} gives 
```

in ./helmfile.yaml: in .helmfiles[0]: in releases/external-dns/helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
--
46 | line 38: cannot unmarshal !!map into string

```

**Comment by mumoshu** [comment]
Oops, sorry! I missed {{ for the nested expression. Could you also try:

```
installedTemplate: {{` {{ .Values.releases | index .Release.Name | getOrNil "enabled" | default "false" }} }}
```

**Comment by mumoshu** [comment]
Note that `{{ .Values.releases | index .Release.Name | getOrNil "enabled" | default "false" }}` is nested within

```
{{`
```
and
```
`}}
```

**Comment by mtb-xt** [comment]
@mumoshu still getting the same error, sorry :( I did try nested handlebars:

```
in ./helmfile.yaml: in .helmfiles[0]: in releases/external-dns/helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: line 38: found character that cannot start any token
```

external-dns/helmfile.yaml has this:
```
---
bases:
- ../../common/environments.yaml
- ../../common/defaults.yaml
---
{{ readFile "../../common/templates.yaml" }}

repositories:
....
```

and I've set `installedTemplate` in templates.yaml:
```
  loader: &loader
    missingFileHandler: Debug
    values:
    - values.yaml
    - values.yaml.gotmpl
    - ./{{ if contains "prod" .Environment.Name }}prod.yaml{{ else }}nonexistent.yaml{{end}}
    - ./{{ if contains "prod" .Environment.Name }}prod.yaml.gotmpl{{ else }}nonexistent.yaml{{end}}
    - ./{{ .Environment.Name }}.yaml
    - ./{{ .Environment.Name }}.yaml.gotmpl
    installedTemplate: {{`{{ .Values.releases | index .Release.Name | getOrNil "enabled" | default "false" }}`}}

```

**Comment by mtb-xt** [comment]
EDIT: full file contents in gist - https://gist.github.com/mtb-xt/30bafae45745829ffb2aacee9e812f5b

**Comment by mtb-xt** [comment]
I've updated the gist to remove excessive code - trying to make this work with only one release for now

**Comment by mumoshu** [comment]
@mtb-xt Hey! Thanks for the example. So there's a few problems:

- You cant use helmfile template expressions within any file that is read by `readFile`. Only release templates are possible there. You cant use values like `./{{ .Environment.Name }}.yaml` there. Only `installedTemplate` seems possible.
- In this context, installedTemplate must look like:
  ```
    installedTemplate: |
      {{ .Values.releases | index .Release.Name | getOrNil "enabled" | default "false" }}
  ```

**Comment by mtb-xt** [comment]
@mumoshu I'm probably confused, but .Environment.Name thing IS working now, it breaks only when I try to add installedTemplate....

**Comment by mtb-xt** [comment]
MWAHAHA - another error - 

```
in ./helmfile.yaml: in .helmfiles[0]: in releases/monitoring/helmfile.yaml: failed executing release templates in "helmfile.yaml": failed executing templates in release "helmfile.yaml"."prometheus-operator": failed executing template expressions in release "prometheus-operator".version = "{{ .Values.releases | index .Release.Name | getOrNil "enabled" | default "false" }}

": template: stringTemplate:1:22: executing "stringTemplate" at <index .Release.Name>: error calling index: cannot index slice/array with type map[string]interface {}
```

**Comment by mumoshu** [comment]
Well, I think I got it working with `environments.yaml` looking:

```
environments:
  default:
    values:
    - releases:
	external_dns:
          enabled: true


```

How's your environments.yaml?

**Comment by mumoshu** [comment]
> .Environment.Name thing IS working now,

Oh, really!

Perhaps I forgot that I did added support for release templates in `releases[].values`? Alright if that works.

**Comment by mtb-xt** [comment]
Mine looks like this:

environments.yaml
```
environments:
  stage:
    values:
      - ../../common/environments/stage.yaml
  dev:
    values:
      - ../../common/environments/dev.yaml
  tools:
    values:
      - ../../common/environments/tools.yaml
  prod-us:
    values:
      - ../../common/environments/prod.yaml
      - ../../common/environments/prod-us.yaml
  prod-eu:
    values:
      - ../../common/environments/prod.yaml
      - ../../common/environments/prod-eu.yaml
  prod-hk:
    values:
      - ../../common/environments/prod.yaml
      - ../../common/environments/prod-hk.yaml
```
and the corresponding `stage.yaml`:
```
releases:
  external_dns:
    enabled: true
  external_secrets:
    enabled: true
    version: "~3.1"
    replica_count: 1
  prometheus_operator:
    enabled: true
variables:
  aws_account_id: 225711623517
```
