### ISSUE TITLE
helmfile apply with helm3 -  "helm upgrade" requires 2 arguments

### ISSUE THREAD

**Issue by abdennour** [roboll/helmfile#1145]
This is my helmfile

```yaml
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

helmDefaults:
  tillerless: true
  args:
    - "--log-level debug"
  # defaults for verify, wait, force, timeout and recreatePods under releases[]
  verify: false
  wait: true
  timeout: 600
 # recreatePods: false
  force: true

releases:
- name: metrics-server
  chart: stable/metrics-server
  namespace: kube-system
  version: '2.8.2'
  values:
  - "./metrics-server-values.yaml"
```
Also, I have installed the diff plugin. I got the following command in another issue under this repo :

```sh
helm plugin install https://github.com/databus23/helm-diff --version v3.0.0-rc.7
```

Then, I run `helmfile apply` inside the container based on image `quay.io/roboll/helmfile:helm3-v0.102.0` . I got this issue:

```
FAILED RELEASES:
NAME
metrics-server
in ./helmfile.yaml: failed processing release metrics-server: helm exited with status 1:
  Error: "helm upgrade" requires 2 arguments
  
  Usage:  helm upgrade [RELEASE] [CHART] [flags]

```

More ? 
Yes, I didn't give up, and I searched on previous issues. Then, I realized that I have to export the environment variable `HELMFILE_HELM3=1`. I did. But still the same issue with the same error 😤
