### ISSUE TITLE
Allow use of glob in needs block

### ISSUE THREAD

**Issue by dudicoco** [roboll/helmfile#1148]
There are use cases where you want to define dependencies in the ```needs``` block for multiple releases with a similar name.

Let's say that I have the following releases:
```
myapp1
myapp2
myapp3
myapp4
myapp5
otherpp
```

I would like to have the following in the ```otherapp``` release:
```
releases:
- name: otherapp
  chart: otherapp
  version: 1.0.0
  installed: true
  needs:
  - myapp*
  values: []
```

Thanks!
