### ISSUE TITLE
Values merge with nil and map doesn't work

### ISSUE THREAD

**Issue by mattymo** [roboll/helmfile#1150]
Problem: Map should always win over nil in a values merge scenario.

Scenario to reproduce

values1.yaml:
```
components:
  etcd-operator:
```

values2.yaml:
```
components:
  etcd-operator:
    version:  0.10.3
```

helmfile.yaml
```
repositories:
- name: "stable"
  url: "https://kubernetes-charts.storage.googleapis.com"

environments:
  default:
    values:
      - values1.yaml
      - values2.yaml

releases:
- name: "etcd-operator"
  chart: stable/etcd-operator
{{- if .Values.components | getOrNil "etcd-operator" | getOrNil "version" }}
  version: {{ .Values.components  | getOrNil "etcd-operator"  | getOrNil "version"  }}
{{- end }}
```

The result is that the second values file doesn't properly merge if the first one contains any nil values. In the resulting values set, .Values.components["etcd-operator"] is nil.

Helmfile version:
helmfile version v0.102.0
