### ISSUE TITLE
Interploation of `releases` values from values/environment

### ISSUE THREAD

**Issue by soupdiver** [roboll/helmfile#1155]
I'm looking for a way to interpolate values for my `releases` inside `helmfile` from environment or values.

Background: I'm working on a prod/staging setup. I want to use the same `helmfile` for an application but deploy different versions on prod/staging. E.g. `1.2.3` and `~1.2.3`.
Ideally I could write this:

`helmfile.yaml`
```yaml
releases:
  - name: foo
    namespace: default
    chart: my/foo
    version: {{ .Values.Version }}
    values:
      - values/values.defaults.yaml.gotmpl
      - values/values.{{ .Environment.Name }}.yaml.gotmpl
```

`values/values.production.yaml.gotmpl`
```yaml
Version: 1.2.3
```

`values/values.staging.yaml.gotmpl`
```yaml
Version: ~1.2.3
```

This always results in error ` ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:6:28: executing "stringTemplate" at <.Values.Version map has no entry for key "Version"`

What kinda works:
`helmfile.yaml`
```yaml
releases:
  - name: foo
    namespace: default
    chart: my/foo
{{ eq .Environment.Name "production" }}
    version: 1.2.3
{{ else }}
    version: ~1.2.3
{{ end }}
    values:
      - values/values.defaults.yaml.gotmpl
      - values/values.{{ .Environment.Name }}.yaml.gotmpl
```

but this gets messy very quickly with more than 2 envs.

Any idea how to do this or am I trying it the wrong way?

**Comment by mikeduffy11fs** [comment]
Hey folks - is there a solution for this? I'm in exactly the same situation where I would like to describe a set of environments with different versions. Ideally, in each environment I'd maintain a versions file with a simple <component>: <version> type layout with I can then refer to in the Helmfile.yaml

**Comment by mumoshu** [comment]
@soupdiver @mikeduffy11fs Hey! Sorry but I'm still not sure what you are trying to achieve here.

Does the version number really need to be defined within helm values, rather than helmfile values?

In other words, does this work for you?

```
values:
- someApp:
    version: "1.2.3"

environments:
  prod:
    values:
    - someApp:
        version: 1.2.2
  dev:
    values:
    - someApp:
        version: 1.2.4

releases:
  - name: foo
    namespace: default
    chart: my/foo
    # This version number results in 1.2.4. for `helmfile -e dev`  and 1.2.2 for `helmfile -e prod`, and 1.2.3 without `-e`
    version: {{ .Values.someApp.version }}
````
