### ISSUE TITLE
Loading of template values fails when a kube context cannot be found

### ISSUE THREAD

**Issue by madAndroid** [roboll/helmfile#1156]
We just went through a very painful debugging exercise where template values were not being found from the `.Environment.Values` map .. and it turned out that it was because the K8s context we were referencing in both `context` and `helmDefaults.kubeContext` were not available on the CI server. 

Two issues here, and possible suggested solutions:

- At no point did Helmfile give any indication that the context in the config wasn't available.
  - Would it be possible to fail with a better error message if this happens?
- Should the values in the template not be resolved _first_, and not be dependant on being able to reach the K8s api?
  - In this instance just a change to ordering might also help determining where a failure happened.

A failure saying template values are missing, when the issue was an incorrect Kube config, lead us down a very long winding rabbit hole, and hopefully logging this will help someone else down the road :)

**Comment by mumoshu** [comment]
@madAndroid Hi! I read this twice but I still don't understand - Helmfile doesn't depend on context nor helmDefaults.kubeContext to render environment values.

Are you, by any chance, calling out to `kubectl` by using the `exec` template function to obtain a few dynamic values from the live cluster to be fed into environment values?

**Comment by madAndroid** [comment]
Apologies for the delayed response ..  yes, that's what we would have expected as well, but it appears to have been the behaviour we experienced .. I'm going to see if I can reproduce this as minimally as possible, and reply back here

**Comment by mumoshu** [comment]
@madAndroid Thanks! Do you use environment secrets, releases[].secrets, helm-secrets, helm-tiller/releases[].tillerless in your setup?

**Comment by madAndroid** [comment]
Yes we do, the helm-secrets plugin, and encrypt the values using SOPs and KMS in AWS

**Comment by mumoshu** [comment]
@madAndroid Which one do you user, `enviroments[].NAME.secrets`, or `releases[].secrets`?

**Comment by madAndroid** [comment]
the first: `enviroments[].NAME.secrets` ... here is the `Helmfile` (actual values changed to protect the innocent ;) ) :

```
repositories:
  - name: our-helm-repo
    url: s3://our-helm-repo/charts

environments:
  dev:
    secrets:
      - ../../environments/dev/secrets.lab.yaml

releases:
  - name: chart
    namespace: namespace
    chart: our-helm-repo/chart
    version: 0.1.0
    values:
      - ../../environments/dev/eu-west-1.yaml.gotmpl

```
