### ISSUE TITLE
Diff issues when running `helmfile apply`

### ISSUE THREAD

**Issue by ivandardi** [roboll/helmfile#1182]
I'm running helmfile apply, and I'm getting this error:

```
in ./helmfile.yaml: 2 errors:
err 0: helm.exe exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 1: helm.exe exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
```

My helmfile version: v0.108.0
My helm version: `version.BuildInfo{Version:"v3.1.2",GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce",GitTreeState:"clean",GoVersion:"go1.13.8"}`
My `helmfile.yaml`:
```
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com/
- name: appscode
  url: https://charts.appscode.com/stable/

environments:
  dev:
    values:
    - environment/dev/values.yaml
  hml:
    values:
    - environment/hml/values.yaml
  prd:
    values:
    - environment/prd/values.yaml
  svc:
    values:
    - environment/svc/values.yaml

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  chart: stable/nginx-ingress
  values:
  - values/ingress-nginx.values.yaml
- name: kubed
  namespace: kubed
  chart: appscode/kubed
  version: v0.12.0-rc.2
  values:
  - ./values/kubed.values.yaml
```

`helmfile apply` doesn't work, but `helmfile sync` does because it doesn't run the diff command. But I'd like to only use `helmfile apply` to avoid unnecessary release upgrades. Anyone has a light on this?
