### ISSUE TITLE
Changes in Values aren't detected

### ISSUE THREAD

**Issue by Vad1mo** [roboll/helmfile#1183]
I create an `IngressRoute` with incubator/raw then I did some changes in the resources and added a new Object `kind: Middleware`

If I run `helmfile diff/sync` I don't see my changes applied in the cluster.  Now I am puzzeld on how  to make sure the changes are applied.

```yaml
- name: ingresses-grafana
    chart: incubator/raw
    namespace: monitoring
    labels:
      component: "prometheus-operator-ingresses"
      namespace: "monitoring"
    wait: true
    force: true
    needs:
      - monitoring/prometheus-operator
    values:
      - resources:
          - apiVersion: traefik.containo.us/v1alpha1
            kind: Middleware
            metadata:
              name: redirect-to-https
            spec:
              redirectScheme:
                scheme: https
                permanent: true

          - apiVersion: traefik.containo.us/v1alpha1
            kind: IngressRoute
            metadata:
              name: prometheus-operator-grafana
              helm.sh/hook: "post-install"
            spec:
              entryPoints:
                - websecure
              routes:
                - match: Host(`{{ .Values.grafana_domain }}`)
                  kind: Rule
                  middlewares:
                    - name: redirect-to-https
                  services:
                    - name: prometheus-operator-grafana
                      port: 80
              tls:
                secretName: monitoring-grafana-prod-tls
                domains:
                  - main: {{ .Values.grafana_domain }}
```
