### ISSUE TITLE
`false` value removed from Values map in version v0.106.3

### ISSUE THREAD

**Issue by johncblandii** [roboll/helmfile#1184]
## Error

> err: error during helmfile.yaml.part.1 parsing: template: stringTemplate:41:27: executing "stringTemplate" at <.Values.service_monitor_enabled>: map has no entry for key "service_monitor_enabled"
in ./helmfile.yaml: error during helmfile.yaml.part.1 parsing: template: stringTemplate:41:27: executing "stringTemplate" at <.Values.service_monitor_enabled>: map has no entry for key "service_monitor_enabled"

## Details

When the `defaults.yaml` has a `false` value (`service_monitor_enabled: false`), this fails:

```yaml
        enabled: {{ .Values.service_monitor_enabled }}
```

The map is: 

```yaml
map[chart_version:7.2.0 cluster_name:some-eks-cluster installed:true
        provider:aws region:us-east-2 service_account_name:autoscaler]
```

I can change the value to `"false"` (`service_monitor_enabled: "false"`), it works:

```yaml
map[chart_version:7.2.0 cluster_name:some-eks-cluster installed:true
        provider:aws region:us-east-2 service_account_name:autoscaler service_monitor_enabled:false]
```

This also works too regardless of surrounding the bool in quotes:

```yaml
        enabled: {{ .Values | get "service_monitor_enabled" false }}
```

I tested the exact same code (no quotes, just `service_monitor_enabled: false`) works perfectly fine in version 0.100.0 with `enabled: {{ .Values.service_monitor_enabled }}`.

### Project Details

**helmfile.yaml**

```yaml
bases:
- ../helm-defaults.yaml
- ../environments.yaml
---
repositories:
# Stable repo of official helm charts
- name: "stable"
  url: "https://kubernetes-charts.storage.googleapis.com"

releases:
#   - https://github.com/kubernetes/charts/blob/master/stable/cluster-autoscaler
- name: "cluster-autoscaler"
  namespace: "kube-system"
  labels:
    chart: "cluster-autoscaler"
    repo: "stable"
    component: "autoscaler"
    namespace: "kube-system"
    vendor: "kubernetes"
  chart: "stable/cluster-autoscaler"
  version: {{ .Values.chart_version | quote }}
  wait: true
  timeout: 180
  installed: {{ .Values.installed }}
  values:
    - serviceMonitor:
        enabled: {{ .Values.service_monitor_enabled }}

```

**../helm-defaults.yaml**

```yaml
helmDefaults:
  tillerless: true
```

**environments.yaml**

```yaml
environments:
  mystage:
    values:
    - defaults.yaml
```

**defaults.yaml**

```yaml
chart_version: 7.2.0

provider: "aws"

region: "us-east-2"

service_account_name: "autoscaler"

service_monitor_enabled: false
```
