### ISSUE TITLE
destroy ordering not reversed when mixing helmfiles and inline releases

### ISSUE THREAD

**Issue by omnibs** [roboll/helmfile#1192]
Hi! Thanks for writing helmfile!

I've a `helmfile` that mixes inline `releases` and `helmfiles`, like so:

```yaml
helmfiles:
  - path: ./init.yaml

releases:
  - name: my-app
    ...
```

At `apply` time `init.yaml` releases are created first, and then `my-app` gets created.

At `destroy` time, the same order takes place.

I've seen https://github.com/roboll/helmfile/issues/797 which made me wonder if `destroy` should follow reverse order in this case too. Is this a bug?

**Comment by mumoshu** [comment]
@omnibs Hey! Thanks. I'm trying to reproduce this.

In the mean time, would you mind helping me to isolate the possible cause of this - Which version of Helmfile are you using? Does it reproduce with Helmfile v0.105.0 AND v0.108.0?

**Comment by omnibs** [comment]
Sure! I used `0.102.0` when I posted. I managed to repro it with both versions you mentioned.

**Comment by omnibs** [comment]
A simple example to reproduce this:

#### helmfile.yaml
```yaml
repositories:
  - name: azure-samples
    url: https://azure-samples.github.io/helm-charts/

helmfiles:
  - path: ./init.yaml

releases:
  - name: second
    namespace: test
    chart: azure-samples/aks-helloworld
    version: 0.1.1
    values:
      - serviceName: second-service
```

#### init.yaml
```yaml
repositories:
  - name: azure-samples
    url: https://azure-samples.github.io/helm-charts/

releases:
  - name: first
    namespace: test
    chart: azure-samples/aks-helloworld
    version: 0.1.1
    values:
      - serviceName: first-service
```

Doing `helmfile apply` does (abbreviated):

```
Upgrading release=first, chart=azure-samples/aks-helloworld
Release "first" does not exist. Installing it now.

[...]

Upgrading release=second, chart=azure-samples/aks-helloworld
Release "second" does not exist. Installing it now.
```

Doing `helmfile destroy` does (abbreviated):

```
Deleting first
release "first" uninstalled

[...]

Deleting second
release "second" uninstalled
```

The `apply` order is fine, but I expected the `destroy` order to be reversed.
