### ISSUE TITLE
Add support for referencing base helmfiles from a URL

### ISSUE THREAD

**Issue by zoonage** [roboll/helmfile#1193]
# Use Case
If you have multiple repositories with their own helmfiles being deployed it would be helpful to syncronise certain aspects, for example the `environments` section. This would make management of the per-repository helmfiles much simpler.

# Example

## Repository helmfile.yaml

```yaml
helmfiles:
  - "./010/helmfile.yaml"
  - "./020/helmfile.yaml"
bases:
  - git+ssh://git@github.com/zoonage/helm-lib@bases/environment.yaml
```

## Library bases/environment.yaml

```yaml
environments:
  local:
    values:
      - local.yaml
  testing:
    values:
      - testing.yaml
  staging:    
    values:
      - staging.yaml
  production:
    values:
      - production.yaml
```
