### ISSUE TITLE
How to define a map inline in environments section

### ISSUE THREAD

**Issue by cjroebuck** [roboll/helmfile#1194]
Use case is to set different resources per environment, something like in helmfile.yaml:

```yaml
environments:
  staging:
    resources:
      requests:
         cpu: 1
         memory: 1Gi
...
```

and reference in releases:

```yaml
releases:
  - name: myrelease
    values:
      resources: {{ .Environments.resources }}
```

Ends up being spat out as a go text/template map converted to a string, something like:

```yaml
resources:
  map[requests:map[cpu:1 memory:1Gi]]
```

with errors `coalesce.go:196: warning: cannot overwrite table with non table for resources (map[])` and 
`invalid type for io.k8s.api.core.v1.ResourceRequirements: got "string", expected "map"`

I am assuming this is to do with the Environments section being double rendered, first interpreted as a go text/template and then as yaml. I'm a noobie with go text/template so am wondering how I can avoid it being interpreted by the first pass and just have it go through as 'raw' text so that it is interpreted correctly as yaml.
