### ISSUE TITLE
Pass all helmfile release labels as helm values map

### ISSUE THREAD

**Issue by voron** [roboll/helmfile#1197]
What's the best option to implement this ?
I've tried following
```yaml
templates:
  _common: &_common
...
    labels:
      chart: base-chart
      app: common
    valuesTemplate:
      - helmfileLabels:
          "{{`{{ toYaml .Release.Labels }}`}}"
```

But it renders `helmfileLabels` as string with value `'app: common chart: base-chart '` instead of map. I use additional labels in templates which use `_common` as a base template and I use more additional labels per release. How to render all these helmfile labels as helm values map w/o specifying every label name&value with  ```app: "{{`{{ toYaml .Release.Labels.app }}`}}"```
to get helm values map like
```yaml
helmfileLabels:
  chart: base-chart
  app: common
  custom: value
```
