### ISSUE TITLE
`helmDefaults.args` strips leading `--`

### ISSUE THREAD

**Issue by davidnortonjr-sps** [roboll/helmfile#1199]
When I use:

```
helmDefaults:
  args:
    - "--set k=v"
```

And run `helmfile --log-level debug sync`, I see:

```
...
exec: helm upgrade --install --reset-values releasename chart-drir --namespace namespace --values /var/folders/lr/4yxtnq0s0pbd89bn3hk18f_0g0lvq_/T/values733988000 set k=v:
...
```

I had to add another set of dashes to get them to show up, or separate them into two lines:

```
helmDefaults:
  args:
    - "----set k=v"

# OR

helmDefaults:
  args:
    - "--set"
    - k=v"
```

I'm not sure if this is an implementation bug, or a documentation bug (I was using the example from the docs)

Thank you! helmfile is a great tool.
