### ISSUE TITLE
Values are not populated in second pass renderer if preliminary state parsing had failed

### ISSUE THREAD

**Issue by dany74q** [roboll/helmfile#1201]
Hey hey !

I've tackled a small issue (maybe ? would love your feedback) when executing helmfile on our uber-templated helmfile hierarchy that we've built in the past week.

To illustrate it, here's a small reproducer:

```yaml
# helmfile.yaml
environments:
  default:
    values:
      - ./values.yaml.gotmpl
---

{{ readFile "common.yaml.gotmpl" }}

releases:
  - name: {{ .Values.releaseName }}
    <<: *default


# common.yaml.gotmpl
templates:
  default: &default
    chart: charts/{{ .Values.chartName }}


# values.yaml.gotmpl 
releaseName: pasten
chartName: pasten-chart
```

I spot the following behavior:
- Using .Values.releaseName fails with: `in helmfile.yaml: error during helmfile.yaml.part.1 parsing: template: stringTemplate:5:20: executing "stringTemplate" at <.Values.releaseName>: map has no entry for key "releaseName"`
- Chaging it to `.Environment.Values.releaseName` fixes it, and it renders correctly

After debugging this, what I've found is:

- We mock `readFile` in the preliminary state to return an empty string
- This makes the prestate rendering fail, because the yaml anchor is undefined
- The failure is tolerated and we continue towards the second pass rendering
- When the prestate fails, the values map stays empty, while the environment values are correctly populated due to the previous part (layer)

This can be easily overcome by using (the deprecated / not recommended) `.Environment.Values`.

If that's in fact an issue (albeit probably an esoteric one), I think that a potential solution could be to populate the values regardless of whether or not the prestate had succeeded.

Would love to hear your thoughts.

Thanks !
