### ISSUE TITLE
ref not parsed properly in string context

### ISSUE THREAD

**Issue by Nuru** [roboll/helmfile#1203]
I want to interpolate an AWS SSM parameter into a data field. It doesn't work because the parser does not properly detect the end of the `ref` field. 

Example helmfile.yaml:
```yaml
repositories:
# Kubernetes incubator repo of helm charts
- name: "kubernetes-incubator"
  url: "https://kubernetes-charts-incubator.storage.googleapis.com"

releases:
- name: 'oidc-configuration'
  chart: "kubernetes-incubator/raw"
  namespace: "kube-system"
  version: "0.2.3"
  values:
  - resources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: oidc-configuration
      data:
        single-signon-client-configuration.yaml: |
          oidc:
            clientSecret: ref+awsssm://sso/oidc-client-secret?region=us-east-1
            clientId: sso-client-id
```

Example failure:
```
$ helmfile --version
helmfile version v0.109.0
$ helmfile diff --skip-deps 
in ./helmfile.yaml: failed processing release oidc-configuration: expand awsssm://sso/oidc-client-secret?region=us-east-2
  clientId: sso-client-id
: parse awsssm://sso/oidc-client-secret?region=us-east-2
  clientId: sso-client-id
: net/url: invalid control character in URL
```

It looks to me like in the context of the `|` operator the parser finds the `ref+` token and takes the rest of the string as the URL, rather than only taking the string up until the first whitespace. 

I have not found a workaround, either. I also have not found documentation on the `ref+awssm` that would help me figure out when and how that is evaluated and how I might restructure things to get it to work.

**Comment by mumoshu** [comment]
@Nuru Hey! Thanks for reporting. As you might have realized, `ref` embedded as a part of a string isn't supported.

I'd be fine to implement it if we could come up with a nice syntax that doesn't conflict with other we-known template languages.

For example. it shouldn't use `{{ }}` as the interpolation syntax to avoid conflict with go template expressions used within e.g. the Prometheus chart config.

**Comment by Nuru** [comment]
@mumoshu Well, the thing is, the go template stuff gets interpolated properly because it is just doing text substitution; even commented out lines get go template substitution. So I suggest you create a function like `readFile` that lets us use `ref+` inside `{{ }}`.

It would also be nice if you had some documentation (I know it sometimes seems like a thankless chore) about how this `ref+` stuff works and where in the process of things it gets interpreted. Because honestly I do not understand why `ref+` is being picked up at all in this case and why my example does not work but
```yaml
      data:
        single-signon-client-configuration.yaml: 
          oidc:
            clientSecret: ref+awsssm://sso/oidc-client-secret?region=us-east-1
            clientId: sso-client-id
```
gets parsed fine.

**Comment by mumoshu** [comment]
@Nuru The point of the `ref+` syntax was that it "allows"(not necessarily mean everyone needs this) you to "defer" the expansion of secret values until the last moment.

Let's say you had a helmfile values.yaml containing:

```
      data:
        single-signon-client-configuration.yaml: 
          oidc:
            clientSecret: ref+awsssm://sso/oidc-client-secret?region=us-east-1
            clientId: sso-client-id
```

Runnign `helmfile template` can produce:

```
kind: Secret
stringData:
  single-signon-client-configuration.yaml: 
    oidc:
      clientSecret: ref+awsssm://sso/oidc-client-secret?region=us-east-1
      clientId: sso-client-id
```

As you can see, it's safe to git-commit this, as it doesn't contain actual credentials.

Then a CD system like ArgoCD is able to use `cat manifests.yaml | vals eval -f - | kubectl apply -f` to deploy the rendered K8s manifests, so that only the CD system needs access to the secrets store you use.

> readFile that lets us use ref+ inside `{{ }}`.

Indeed this can be an option - It's just that I hope we could come up with any other way to preserve the above benefit, which is why I've chosen the syntax in the first place.
