### ISSUE TITLE
Values in maps not available for namespace

### ISSUE THREAD

**Issue by Nuru** [roboll/helmfile#1204]
This looks like a bug to me.

Given this `hemlfile.yaml`:
```yaml
environments:
  default:
    values:
    - defaults.yaml

repositories:
# Kubernetes incubator repo of helm charts
- name: "kubernetes-incubator"
  url: "https://kubernetes-charts-incubator.storage.googleapis.com"

releases:
- name: 'test'
  chart: "kubernetes-incubator/raw"
  namespace: "{{ .Values.map.key }}"
  version: "0.2.3"
  values:
  - resources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: test
      data:
        test.yaml: |
          test:
            namespace: "{{ .Values.map.key }}"
```

and this `defaults.yaml`:
```yaml
map:
  key: map.value

mapkey: flat.value
```

`helmfile` chokes:
```
$ helmfile -version
helmfile version v0.109.0
$ helmfile diff
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:14:24: executing "stringTemplate" at <.Values.map.key>: map has no entry for key "map"
```

But changing line 14
```yaml
  namespace: "{{ .Values.map.key }}"
```
to
```yaml
  namespace: "{{ .Values.mapkey }}"
```
works fine, despite the reference to `{{ .Values.map.key }}` in the `values` section. So this is not a case of the value never being available, or of not being able to use `.Values` to set the namespace, this is something particular to using maps.

**Comment by mumoshu** [comment]
This can possible be a recent regression since mergo changes. I'll try to reproduce and fix this soon. Thanks!

**Comment by mumoshu** [comment]
So this seems like more difficult and complex issue than I originally thought.

There's two problems.

First, this is due to that the first-render fails with access to nil map, which basically means that this is a fundamental issue due to double-rendering.

For this the only workaround would be to put `---` after environments, like

```
environments:
  default:
    values:
    - defaults.yaml

---

repositories:
# Kubernetes incubator repo of helm charts
- name: "kubernetes-incubator"
  url: "https://kubernetes-charts-incubator.storage.googleapis.com"

```

It's also affected by #1201 so we also need #1202 to make it work.

**Comment by Nuru** [comment]
I don't have `helmfile` with #1202, but using v0.109.0, adding the `---` after the environments section does not change the result.

**Comment by mumoshu** [comment]
@Nuru Yes that's the expected behaviour. I believe you need both to fix your issue.

**Comment by mumoshu** [comment]
#1202 has been merged and would be available since v0.109.1.
Would you mind giving it a try?

**Comment by Nuru** [comment]
Looks like with the addition of `---` as you suggested, this is now working in `helmfile` [v0.111.0](https://github.com/roboll/helmfile/releases/tag/v0.111.0)

**Comment by darkn3rd** [comment]
I am running into a problem with a similar output in **helmfile version v0.125.1**
```
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:16:17: executing "stringTemplate" at <.Values.charts>: map has no entry for key "charts"
```

**Comment by mumoshu** [comment]
@darkn3rd Thanks for reporting! I haven't tried `platform-operations-on-kubernetes` myself yet. So, would you mind telling me exact steps to get your error myself? (Like `cd` to somewhere, then edit some file, run some command, see the error, etc)

**Comment by darkn3rd** [comment]
@mumoshu I am using my own custom one that is copy/paste.   The error doesn't give me much to go by, so I am clueless as to where the error.

This is my helmfile:
```yaml
environments:
  default:
    values:
      - ./charts.yaml
      - ./values.yaml
      {{- if env "ENV_DIR" }}
      - {{ requiredEnv "ENV_DIR" }}/charts.yaml.gotmpl
      - {{ requiredEnv "ENV_DIR" }}/values.yaml.gotmpl
      {{- end }}

repositories:
{{- range .Values.charts }}
{{- if and .enabled (hasKey . "repository") }}
  - name: {{ .repository.name }}
    url: {{ .repository.url }}
{{- end }}
{{- end }}

releases:
{{- range .Values.charts }}
{{- if .enabled }}
  - name: {{ .name }}
    namespace: {{ .namespace }}
    chart: {{ .chart }}
    version: "{{ . | getOrNil "version" }}"
    values:
    {{- range .values }}
      - {{ . }}
    {{- end }}
    secrets:
    {{- range . | getOrNil "secrets" }}
      - {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
```

I wish there was a command where I could get the intermediary rendering, such as see what repositories or releases looks like when finally rendered before it goes to the next state.

**Comment by mumoshu** [comment]
Thanks. Could you try adding `---` before `repositories` so that `values` are loaded before evaluating go template?

```
environments:
  default:
    values:
      - ./charts.yaml
      - ./values.yaml
      {{- if env "ENV_DIR" }}
      - {{ requiredEnv "ENV_DIR" }}/charts.yaml.gotmpl
      - {{ requiredEnv "ENV_DIR" }}/values.yaml.gotmpl
      {{- end }}

---

repositories:
{{- range .Values.charts }}
{{- if and .enabled (hasKey . "repository") }}
  - name: {{ .repository.name }}
    url: {{ .repository.url }}
{{- end }}
{{- end }}
```

**Comment by darkn3rd** [comment]
I tried that before and it didn't work.  In the example code from either [getting started](https://github.com/paulczar/helmfile-starter-kit) or [POOK](https://github.com/paulczar/platform-operations-on-kubernetes/blob/master/helmfile.yaml), they explicitly use the version, if I don't have a version specified, I got weird errors.

**Comment by mumoshu** [comment]
> I tried that before and it didn't work

What error did you see when you used `---`?

**Comment by mumoshu** [comment]
> In the example code from either getting started or POOK, they explicitly use the version, if I don't have a version specified, I got weird errors.

Can we say that it's just that POOK and the getting-started example is designed to require you to define `version` then? Do you think there's any problem on helmfile side for that?

**Comment by darkn3rd** [comment]
I actually am able to isolate a reproducible case.
I updated my `charts.yaml` case to this:
```yaml
charts:
  azuregateway:
    enabled: true
    repository:
      name: minio
      url: https://helm.min.io/
    name: minio
    namespace: minio
    version: 6.1.2
    chart: minio/minio
    values:
      - ./envs/aks/tf.minio_config.yaml

  dgraph:
    name: dgraph
    enabled: true
    namespace: default
    chart: {{ env "HOME" }}/workarea/charts/charts/dgraph
```
When I run it, `helmfile lint`, I get:
```
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:19:17: executing "stringTemplate" at <.Values.charts>: map has no entry for key "charts"
```

When I add the `---`, I get something quite different.

```
$ helmfile lint
in ./helmfile.yaml: failed to read helmfile.yaml: failed to load environment values file "charts.yaml": yaml: line 17: did not find expected key

Offending YAML:
charts:
  azuregateway:
    enabled: true
    repository:
      name: minio
      url: https://helm.min.io/
    name: minio
    namespace: minio
    version: 6.1.2
    chart: minio/minio
    values:
      - ./envs/aks/tf.minio_config.yaml

  dgraph:
    name: dgraph
    enabled: true
    namespace: default
    chart: {{ env "HOME" }}/workarea/charts/charts/dgraph
```
