### ISSUE TITLE
Merge remote helmfile with local values

### ISSUE THREAD

**Issue by XenoAura** [roboll/helmfile#1205]
It would be nice if the following syntax was implemented. Remote helmfile and local values are not being merged.

```
helmfiles:
  - path: git::ssh://git@dsf.yaml
    values:
      - values.yaml
```

_Originally posted by @kamsz in https://github.com/roboll/helmfile/issues/469#issuecomment-505532232_

**Comment by andrewnazarov** [comment]
I don't think I'm following you correctly but we've been using this syntax for some time. It works for us.

**Comment by XenoAura** [comment]
I discovered strange behavior.
This works for repositories in github, but not working for **gitlab** repos.

**Comment by andrewnazarov** [comment]
We are using Gitlab:)

Probably our case is a bit different as we are utilizing `environments:`. But since global environments are not inherited by sub-helmfiles we've ended up with the following workaround:

```
environments:
  staging:
    values:
      - environments/staging.yaml

helmfiles:
  - path: git::https://gitlab+mytoken:{{ requiredEnv "REPO_TOKEN" }}@gitlab.mydomain.com/my-project/my-repo.git@deployment/helmfile.yaml?ref=master
    values:
      - environments/staging.yaml
```

and we run this like `helmfile -e staging diff`

**Comment by baurmatt** [comment]
Running into the same problem. Using the syntax shown in the README.md doesn't use the provided values file:

```yaml
...
helmfiles:
- path: path/to/subhelmfile.yaml
  values:
    # Values files merged into the nested state's values
    - additional.values.yaml
...
```

Also your workaround @andrewnazarov doesn't work for us:

```yaml
environments:
  default:
    values:
      - values.yaml

helmfiles:
  - path: git::https://gitlab.com/path/to/project@helmfile.yaml?ref=master
    values:
      - values.yaml
```

**Comment by andrewnazarov** [comment]
@baurmatt what is your helmfile version?

**Comment by baurmatt** [comment]
@andrewnazarov v0.114.0

**Comment by baurmatt** [comment]
I *think* the problem is: You can't override values which are defined in other values YAML includes.

For example this **doesn't work**:

helmfile-to-be-included.yaml
```yaml
...
releases:
  - name: foo
    ...
    values:
      - values.yaml # Uses replica: 1
...
```

helmfile.yaml:
```yaml
helmfiles:
  - path: path/to/helmfile-to-be-included.yaml
    values:
      - values-override.yaml # Uses replica: 2
```

But this seems to **work**:

helmfile-to-be-included.yaml
```yaml
...
releases:
  - name: foo
    ...
    values:
      - replica: 1
...
```

helmfile.yaml:
```yaml
helmfiles:
  - path: path/to/helmfile-to-be-included.yaml
    values:
      - values-override.yaml # Uses replica: 2
```

**Comment by andrewnazarov** [comment]
Yes, our case is your second example. We don't have these nested references. In our remote helmfile we have inline values only.

**Comment by baurmatt** [comment]
Thanks for checking! :) Sadly this approach doesn't work for us, as we depend on two different files of values being used in the sub helmfile:

```
...
releases:
  - name: prometheus-operator
    chart: stable/prometheus-operator
    version: 8.12.3
    values:
      - values-managed-services.yaml
      - values-base.yaml
...
```

This is because the `values-base.yaml` gets used by another project.
