### ISSUE TITLE
locally defined environments values aren't merged when bases is present

### ISSUE THREAD

**Issue by svistoi** [roboll/helmfile#1207]
Hi,

I'm not sure if this is a bug or my mis-use.  I have specified some repositories and empty environments in ./base/base.yaml

```yaml
---
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com/

helmDefaults:
  wait: true

environments:
  default:
  stage:
  prod:
```

Then the following helmfile in ./test/helmfile.yaml
```yaml
---
bases:
  - ../base/base.yaml

environments:
  default:
    values:
      - namespace: mon
      - kubeContext: dev

releases:
  - name: prometheus
    namespace: {{ .Values.namespace }}
    chart: stable/prometheus
    version: 10.6.0
    kubeContext: {{ .Values.kubeContext }}
```

Specifying environment values here fails to render saying that map has no entry namespace.  Full debug log.  If I remove `bases:` from helmfile then it works to find .Values.namespace. 

```
processing file "helmfile.yaml" in directory "."
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
first-pass rendering output of "helmfile.yaml.part.0":
 0: ---
 1: bases:
 2:   - ../base/base.yaml
 3: 
 4: environments:
 5:   default:
 6:     values:
 7:       - namespace: mon
 8:       - kubeContext: dev
 9: 
10: releases:
11:   - name: prometheus
12:     namespace: <no value>
13:     chart: stable/prometheus
14:     version: 10.6.0
15:     kubeContext: <no value>
16: 

replaced <no value>s to workaround https://github.com/golang/go/issues/24963 to address https://github.com/roboll/helmfile/issues/553:
  strings.Join({
  	... // 10 identical lines
  	"releases:",
  	"  - name: prometheus",
- 	"    namespace: <no value>",
+ 	"    namespace: ",
  	"    chart: stable/prometheus",
  	"    version: 10.6.0",
- 	"    kubeContext: <no value>",
+ 	"    kubeContext: ",
  	"",
  }, "\n")

error in first-pass rendering: result of "helmfile.yaml.part.0":
 0: ---
 1: bases:
 2:   - ../base/base.yaml
 3: 
 4: environments:
 5:   default:
 6:     values:
 7:       - namespace: mon
 8:       - kubeContext: dev
 9: 
10: releases:
11:   - name: prometheus
12:     namespace: <no value>
13:     chart: stable/prometheus
14:     version: 10.6.0
15:     kubeContext: <no value>
16: 

first-pass produced: &{default map[] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {default map[] map[]}
second-pass rendering failed, input of "helmfile.yaml.part.0":
 0: ---
 1: bases:
 2:   - ../base/base.yaml
 3: 
 4: environments:
 5:   default:
 6:     values:
 7:       - namespace: mon
 8:       - kubeContext: dev
 9: 
10: releases:
11:   - name: prometheus
12:     namespace: {{ .Values.namespace }}
13:     chart: stable/prometheus
14:     version: 10.6.0
15:     kubeContext: {{ .Values.kubeContext }}
16: 

err: error during helmfile.yaml.part.0 parsing: template: stringTemplate:13:25: executing "stringTemplate" at <.Values.namespace>: map has no entry for key "namespace"
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:13:25: executing "stringTemplate" at <.Values.namespace>: map has no entry for key "namespace"
```

My helmfile version is v0.104.0

Thanks.

**Comment by mumoshu** [comment]
@svistoi Hey! Would you mind trying this? You seem like encountring the chicken-and-egg problem of helmfile.yaml, that is, to render the helmfile.yaml you need to load bases and environments, but to load bases and environments you need to render the helmfile.yaml.

```

---
bases:
  - ../base/base.yaml

---

environments:
  default:
    values:
      - namespace: mon
      - kubeContext: dev

---

releases:
  - name: prometheus
    namespace: {{ .Values.namespace }}
    chart: stable/prometheus
    version: 10.6.0
    kubeContext: {{ .Values.kubeContext }}
```

**Comment by svistoi** [comment]
Thanks, I guess that's not a supported use.  I'll try to think about re-organizing the files.

The reason I had it this way is because I thought I'd define a base set of environments applicable to all helmfiles, along with some common values applicable to all helmfiles.  Say base.yaml:
```
environments:
  default:
    values:
      - kubeContext: dev
  stage:
    values:
      - kubeContext: stage
```

And then add additional variables (or not), say `test/helmfile.yaml`
```
bases:
  - ../base/base.yaml

environments:
  default:
    values:
      - namespace: mon
      # kubeContext implied from base
```

Because test/helmfile.yaml includes base, I assumed there wasn't a circular dependency.
