### ISSUE TITLE
Layering State Files is not working as documented.

### ISSUE THREAD

**Issue by Vad1mo** [roboll/helmfile#1209]
I am trying to structure my helmfile according to https://github.com/roboll/helmfile/blob/master/docs/writing-helmfile.md#layering-state-files. However it doesn't work as documented

> base.yaml
```yaml
environments:
  stage:
  prod:
helmDefaults:
  wait: true
  verify: true
```

>helmfile.yaml
```yaml
bases:
- base.yaml

repositories:
 ...
 #740 

releases:
  - name: letsencrypt-cert-issuer
    namespace: cert-manager
    chart: incubator/raw
    labels: 
      - email: {{ .Values.acme_email }}
    values:
       - {{ .Environment.Name }}-values.yaml
```

>stage-values.yaml
```yaml
acme_email: "org+certs+stage@example.com"
```

> `helmfile --log-level debug -e stage diff`

Error:
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:48:22: executing "stringTemplate" at <.Values.acme_email>: map has no entry for key "acme_email"

**Comment by mumoshu** [comment]
Seems like you're missing `stage-values.yaml` under `environments.stage.values[]`?

**Comment by Vad1mo** [comment]
it was on purpose to leave out `nvironments.stage.values[]`.
I wanted to create a baseline with my  environment names and global defaults. Then I wanted to import that base in all Helmfiles. I  wanted to use it  by importing the right file values.yaml with the env prefix. 

It also doesn't work with `---` after bases:

**Comment by mumoshu** [comment]
No it doesn't work. So you're trying to reference chart values as if it's environment values?

```
releases:
  - name: letsencrypt-cert-issuer
    namespace: cert-manager
    chart: incubator/raw
    labels: 
      - email: {{ .Values.acme_email }}
    values:
       - {{ .Environment.Name }}-values.yaml
```

Chart values are environment values are completely different things. You can't use `{{ .Values.acme_email }}` to reference any value defined under `releases[].values.
