### ISSUE TITLE
Keeping Vault secrets encrypted in helmfile diff & apply

### ISSUE THREAD

**Issue by Tlzps** [roboll/helmfile#1210]
We are using the hashicorp vault integration ( #906 ) with success, however the passwords are show in clear text in the helmfile diff & helmfile apply outputs. 

`mypassword: 'ref+vault://secret/data/foo?proto=http#/mykey'`

`+   my_password: ismyclearpassword`

Are there any way to instead show what has been set in the helmfile's values or show a dummy value ?

Thanks.

**Comment by zam-zam** [comment]
Hey

"helmfile diff" shows differences for kubernetes entities and uses "helm-diff" plugin. By default this plugin hides all values in "data" section of kubernetes kind "Secret"
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: cm-config
type: Opaque
data:
  mypassword: {{ .Values.mypassword | b64enc | quote }}
```
and then reference it in you environment value like this
```yaml
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: cm-config
      key: mypassword
```
Therefore you wiil see something like this in your diff output (your secret values are beeing replaced by '+++++++')
```diff
 + # Source: app/templates/cm-config.yaml
 + apiVersion: v1
 + kind: Secret
 + metadata:
 +   name: cm-config
 + data:
 +   password: '++++++++ # (24 bytes)'
 + type: Opaque
```
