### ISSUE TITLE
Default values support (helmDefaults.args issue)

### ISSUE THREAD

**Issue by antonu17** [roboll/helmfile#1214]
## Challenge

Kudos! We need to deploy multiple releases of `stable/mysql` helm chart to staging and live k8s clusters. The `mysqlRootPassword` value must be the same on each release within the same cluster, but `mysqlUser`, `mysqlPassword`, and `mysqlDatabase` have to be different for each release.

## Tried solution

clusters/staging.yaml:

```yaml
mysqlRootPassword: stagingpass
```

clusters/live.yaml:

```yaml
mysqlRootPassword: livepass
```

helmfile.staging.yaml:

```yaml
helmDefaults:
  args:
    - --values
    - clusters/staging.yaml

releases:
  - name: db-customers
    chart: stable/mysql
    values:
      - mysqlUser: customers
      - mysqlPassword: customers
      - mysqlDatabase: customers

  - name: db-orders
      chart: stable/mysql
      values:
        - mysqlUser: orders
        - mysqlPassword: orders
        - mysqlDatabase: orders
```

helmfile.live.yaml:

```yaml
helmDefaults:
  args:
    - --values
    - clusters/live.yaml

releases:
  - name: db-customers
    chart: stable/mysql
    values:
      - mysqlUser: customers
      - mysqlPassword: customers
      - mysqlDatabase: customers

  - name: db-orders
      chart: stable/mysql
      values:
        - mysqlUser: orders
        - mysqlPassword: orders
        - mysqlDatabase: orders
```

The `stable/mysql` is given just as an example, not recommended to use such an approach for production. :wink:

## Problem

When running `helmfile -f helmfile.staging.yaml --log-level debug apply` it runs 3 commands:

1. `helm diff upgrade --reset-values --allow-unreleased db-customers stable/mysql --values /tmp/values033010272 --values /tmp/values754787903 --values /tmp/values723253906 --detailed-exitcode`
2. `helm upgrade --install --reset-values --allow-unreleased db-customers stable/mysql --values /tmp/values033010272 --values /tmp/values754787903 --values /tmp/values723253906 --detailed-exitcode --values clusters/staging.yaml`
3. `helm list ^db-customers$ --deployed --failed --pending --values clusters/staging.yaml`

The first command `helm diff upgrade` ignores `helmDefaults.args` which makes it always show changes. The second command works fine because it adds `helmDefaults.args`, but it shouldn't actually be called at all, because there were no changes for real. The third command fails because helm list doesn't like `--values` parameter.

## Workaround

Instead of using `helmDefaults.args` we added `- clusters/staging.yaml` to every release's values. But this is not how we want to proceed.

## Feature request

It would be awesome if `helmDefaults` supported `values` that are merged with every release's values.
