### ISSUE TITLE
question: get values from chart

### ISSUE THREAD

**Issue by nejtr0n** [roboll/helmfile#1229]
Hey, how can I get app container version from helm chart.yaml in helmfile?

**Comment by mumoshu** [comment]
What's chart.yaml?

Are you trying to fetch the container image tag of the running container in a running pod in your live cluster?

Or are you trying to scape the default value for `image.tag` defined in the default values.yaml contained in your chart?

**Comment by mumoshu** [comment]
Also - why you need to do that? Sharing your original goal would help me understand your issue and provide the possibly-best way to deal with it.

**Comment by nejtr0n** [comment]
I need to get imge tag from Chart.yaml of cockroachdb.
After deployment of helm cockroachdb:
```
  - name: {{ .Environment.Name }}-cockroachdb
    namespace: {{ .Environment.Name }}-cockroachdb
    needs:
      - {{ .Environment.Name }}-cockroachdb-resources
    chart: stable/cockroachdb
    version: {{ .Values.igwm.charts.versions.cockroachdb }}
    labels:
      app: cockroachdb
      tier: igwm
    values:
      - statefulset:
          replicas: {{ .Values | getOrNil "igwm.cockroachdb.replicas" | default "3" }}
          resources:
            {{ .Values.igwm.cockroachdb.resources | toYaml | nindent 12 }}
        conf:
          {{ .Values.igwm.cockroachdb.conf | toYaml | nindent 10 }}
        storage:
          persistentVolume:
            enabled: yes
            size: {{ .Values.igwm.cockroachdb.size }}
            storageClass: {{ .Values.global.storageClass }}
```
After that i want to create dabase and user. So im trying to do it in job.
But it have to be done in the same version of crdb container for consistency.
