### ISSUE TITLE
When `installed` is `false` chart should not be fetch

### ISSUE THREAD

**Issue by guillomep** [roboll/helmfile#1232]
Hello,

I'm facing a problem when I'm set the `installed` boolean to false because, helmfile still fetch the chart on the repository.

I have several environments in which I define the component versions. For some environments some components are not required and so I don't set any version and I would like to not install them, so I write a helmfile like that:

```yaml
release:
- name: releaseA
  chart: A
  installed: {{ not (empty .Values.chartAVersion }}
  version: {{ .Values.chartAVersion | default "noVersion" }}
```

But helmfile still wants to download chartA:noversion, which doesn't exists so it fails.
My question is why helmfile download the chart ? I think it's unecessary if `installed` is false since it will do nothing with it am I right ?

FYI I loop over all my helmfiles for each environments that's why I need something like that.
If you have another solution please give me an hint.
