### ISSUE TITLE
No matches for kind "X" in version "Y"

### ISSUE THREAD

**Issue by Vad1mo** [roboll/helmfile#1241]
I still have difficulties finding an elegant solution.  In #1195 there is the recommendation to avoid hooks and put CRD into Helm. However the example below contains this practice but it results in the same type of error 

`Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ClusterIssuer" in version "cert-manager.io/v1alpha2"`

To me the error is clear and how to bypass it (1. install cert-manager  - 2. Install ClusterIssuer)  However I still would like to have this on one flow so I could install everything at the same time.

```yaml
repositories:
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  - name: jetstack
    url:  https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v0.14.2
    atomic: true
    cleanupOnFail: true
    values:
      - installCRDs: true

  - name: letsencrypt-cert-issuer
    namespace: cert-manager
    chart: incubator/raw
    atomic: true
    force: true
    cleanupOnFail: true
    needs:
      - cert-manager/cert-manager
    values:
      - resources:
          - apiVersion: cert-manager.io/v1alpha2
            kind: ClusterIssuer
            metadata:
              name: letsencrypt-staging
            spec:
              acme:
                server: https://acme-staging-v02.api.letsencrypt.org/directory
                email: "pomerium@getnada.com"
                privateKeySecretRef:
                  name: letsencrypt-staging
```
