### ISSUE TITLE
failed to download from Artifactory

### ISSUE THREAD

**Issue by michaelpporter** [roboll/helmfile#1243]
I am getting `Error: failed to download` when using our internal Artifactory repo. I am able to publish charts and use `helm install` without issues. If I use the local path it works fine. Am I missing something?

```yaml
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
# To use official "incubator" charts a.k.a https://github.com/helm/charts/tree/master/incubator
- name: incubator
  url: https://storage.googleapis.com/kubernetes-charts-incubator
- name: mycompany-stable
  url: https://artifactory.ourdomain.com/artifactory/mycompany-stable
  username: {{ requiredEnv "MYCOMPANY_STABLE_USERNAME" }}
  password: {{ requiredEnv "MYCOMPANY_STABLE_PASSWORD" }}

releases:

- name: darktrace
  chart: mycompany-stable/darktrace-osagent
  wait: true
  namespace: default
```

```bash
Updating repo
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "mycompany-stable" chart repository
Update Complete. ⎈ Happy Helming!⎈

Comparing release=darktrace, chart= mycompany-stable/darktrace-osagent
in ./helmfile.yaml: helm exited with status 1:
  Error: Failed to render chart: exit status 1: Error: failed to download "mycompany-stable/darktrace-osagent" (hint: running `helm repo update` may help)
```

Artifactory Helm has the file
mycompany-stable/darktrace-osagent-3.0.0.tgz

```yaml
- name: darktrace
  chart: ../../../helm-charts/darktrace-osagent
  wait: true
  namespace: default
```

```bash
helmfile diff
...
Building dependency release=darktrace, chart=../../../helm-charts/darktrace-osagent
Comparing release=darktrace, chart=../../../helm-charts/darktrace-osagent
```
