### ISSUE TITLE
kubeContext override is broken 

### ISSUE THREAD

**Issue by voron** [roboll/helmfile#1244]
Hello,

I use `kubeContext` override per release, and it's broken starting from v.0.106.0. Simple helmfile.yaml is following:
```yaml
helmDefaults:
  kubeContext: default
releases:
  - name: cert-manager
    namespace: cert-manager
    version: v0.14.0
    chart: jetstack/cert-manager
    kubeContext: {{ env "KUBE_CONTEXT" | default ( printf "gke-%s" .Environment.Name ) }}

```
I see doubled `--kube-context` in debug log
```
helmfile -e dev -l name=cert-manager --log-level=debug diff
...
Comparing release=cert-manager, chart=jetstack/cert-manager
exec: helm diff upgrade --reset-values --allow-unreleased cert-manager jetstack/cert-manager --version v0.14.0 --tiller-namespace kube-system --kube-context gke-dev --namespace cert-manager --values /var/folders/0b/7qzzv73j7cg5sh97xds05c8r0000gn/T/values826630363 --kube-context default
```
Thus, `kubeContext` from release is ignored. 
`kubeContext` in `helmDefaults` is dummy in my case and I use it as a safe plug to prevent  access to current k8s context while debugging (incorrect) releases which do not  specify `kubeContext` explicitly.

**Comment by mumoshu** [comment]
@voron Thanks for reporting. I'll see what's going wrong soon.

**Comment by mlushpenko** [comment]
Maybe the issue is bigger, setting kubecontext works for me only inside release, not via helmfiles. 

I have cascading structure with helmfiles like this:


```
# example-customer-helmfile
helmfiles:
- path: common/helmfile.yaml
- path: ../monitoring/prometheus/customers/helmfile.yaml
  selectors: [ customer=example ]
```

```
# common helmfile
helmfiles:
- path: ../common-charts/helmfile.yaml
```

In prometheus customers `helmfile.yaml` I defined several identical releases with different labels and kubectonext.  Then, when executing `example-customer-helmfile`, I see proper kubecontext picked up:

```
Comparing release=prom, chart=stable/prometheus-operator
exec: helm diff upgrade --reset-values --allow-unreleased prom stable/prometheus-operator --kube-context example-customer --namespace monitoring --values ...
``` 

For the common charts, I was hoping to define helmDefaults per customer, but it doesn't work like this:
```
helmDefaults:
  kubeContext: customer

helmfiles:
- path: common/helmfile.yaml
- path: ../monitoring/prometheus/customers/helmfile.yaml
  selectors: [ customer=customer ]
```

Neither does it work like this:
```
helmfiles:
- path: common/helmfile.yaml
  values:
  - kubeContext: customer
- path: ../monitoring/prometheus/customers/helmfile.yaml
  selectors: [ customer=customer ]
```

And not like this:
```
values:
- kubeContext: customer

helmfiles:
- path: common/helmfile.yaml
- path: ../monitoring/prometheus/customers/helmfile.yaml
  selectors: [ customer=customer ]
```

The only way common helmfile will pickup kubecontext is if i add it to the release definition like with customer prometheus helmfiles, so this seems to be the only way to enforce kubecontext:
```
releases:
- name: blackbox-exporter
  namespace: monitoring
  chart: stable/prometheus-blackbox-exporter
  kubeContext: customer
```

Environment:
```
helm version                         
Client: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}
helmfile --version
helmfile version v0.115.0 (and tried with previous release as well)
```

**Comment by mumoshu** [comment]
@mlushpenko Hey! Thanks for reporting.

Sorry, but I didn't get it.

Neither `helmDefaults` nor `values` are designed to be automatically propagated to sub-helmfiles.

Did you see anything other than that?

**Comment by mlushpenko** [comment]
Oh, my bad then @mumoshu , I didn't realise that. Do you have suggestion in that case how to structure modular setup with helmfiles accross clusters?

For every chart that has to be deployed on all clusters, I could create a file similar to this:

```
releases:
- name: prom
  namespace: monitoring
  chart: stable/prometheus-operator
  labels:
    customer: customer-1
  kubeContext: customer-1
  values: [ customer-1 ]

- name: prom
  namespace: monitoring
  chart: stable/prometheus-operator
  labels:
    customer: customer-2
  kubeContext: customer-2
  values: [ customer-2 ]
```

And then have a folder with helmfile per customer like I showed above. Such setup currently allows me to run one command to apply monitoring changes across all clusters:

```
helmfile -f helmfiles/ -l name=prom sync --skip-deps
```

But creating such files with labels and kubectonext per customer for every chart seems like too much work/copying. Would be better to import whatever sub-helmfiles I need and then apply kubecontext to all of them or maybe you have some other idea.
