### ISSUE TITLE
Make condition field part of release templates?

### ISSUE THREAD

**Issue by chqr** [roboll/helmfile#1247]
Loving the new support for conditional releases (#781). Are there any plans to make that field part of release templates?

    releases:
    - name: app1
      condition: app1.enabled
      <<: *myTemplate

    - name: app2
      condition: app2.enabled # Would love to be able to populate this in a template
      <<: *myTemplate

**Comment by mumoshu** [comment]
@chqr I hear you, but I believe that's not a good idea. The more release template you have in a release, it gets more complicated and harder to review.

A slightly better alternative to that would be using environment values to make it dynamic:

```
values:
- envvals.yaml

---

values:
- app1:
     enabled: {{ .Values.whatever || whatever }}

---

releases:
- name: app1
  condition: app1.enabled
  <<: *myTemplate
```
