### ISSUE TITLE
Question: exec and stdout/stderr

### ISSUE THREAD

**Issue by cdunford** [roboll/helmfile#1258]
I am trying to use the `exec` function within a release to compute a value via a script. It's a somewhat complex bash script I have, so I would like to add some diagnostic logging in case it goes sideways. What I thought would happen is that whatever is written to `stdout` would be used as the computed "value", so I figured I could write to `stderr` for my diagnostic information, but it seems that `stderr` is also being consumed and appended into the "value".

Is this expected? Is there somewhere else (other than a file) that I could write diagnostic logging information to?

**Comment by mumoshu** [comment]
Yes. That's expected. We explicitly use stderr to capture error message that should be shown when the command exited with a non-zero code.

**Comment by cdunford** [comment]
Thanks for the response.

I certainly think it makes sense to capture stderr to show any error messages. I'm not sure it makes sense to capture stderr as part of the output used for the value (in the case the script still returns zero).

**Comment by cdunford** [comment]
Any feedback on that? Is that some that could be changed so only stdout is used as the value and stderr could be used for logging? Is there some other possible solution?

**Comment by mumoshu** [comment]
Oh, well, Helmfile should use only stdout as a value. It's coded here:

https://github.com/roboll/helmfile/blob/master/pkg/helmexec/runner.go#L74

So what you might be seeing can be a bug?

Would you mind giving me an example for reproduction so that I can investigate further?

**Comment by cdunford** [comment]
Here is a minimal example:

`helmfile.yaml`:
```
repositories:
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com

releases:
- name: test
  namespace: test
  createNamespace: true
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: test
      data:
        value: {{ exec "./test.sh" (list "test") }}
```

`test.sh`:
```
#!/bin/bash

echo "stderr $1" 1>&2
```

Output from `helmfile diff`:
```
Comparing release=test, chart=incubator/raw
********************

        Release was not present in Helm.  Diff will show entire contents as new.

********************
test, test, ConfigMap (v1) has been added:
- 
+ # Source: raw/templates/resources.yaml
+ apiVersion: v1
+ data:
+   value: stderr test
+ kind: ConfigMap
+ metadata:
+   labels:
+     app: raw
+     chart: raw-0.2.3
+     heritage: Helm
+     release: test
+   name: test
```

Version:
```
❯ helmfile -v  
helmfile version v0.116.0

❯ helm version  
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.14.2"}

❯ helm plugin list
NAME    VERSION DESCRIPTION                                                                  
diff    3.1.1   Preview helm upgrade changes as a diff                                       
secrets 2.0.2   This plugin provides secrets values encryption for Helm charts secure storing
```
