### ISSUE TITLE
could not deduce `environment:` block, configuring only .Environment.Name. : unmarshal errors: cannot unmarshal !!str `map` into bool

### ISSUE THREAD

**Issue by infa-anisrini** [roboll/helmfile#1259]
helmfile version :
```helmfile version v0.115.0```

helmfile:
```
---
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com
- name: infa-chart
  url: https://infacloud.github.io/ct-charts/
- name: bitnami
  url: https://charts.bitnami.com/bitnami 
- name: jetstack
  url: https://charts.jetstack.io

helmDefaults:
  tillerNamespace: kube-system  #dedicated default key for tiller-namespace
  tillerless: false                  #dedicated default key for tillerless
  
# Ordered list of releases.
helmfiles:
  - "releases/coredns.yaml"
  #- "releases/external-dns.yaml"
```

In releases folder i have this :
```
bases:
  - ../commons/environments.yaml
---
releases:
  - name: "coredns"
    namespace: "kube-system"
    labels:
      chart: "coredns"
      repo: "stable"
    chart: "stable/coredns"
    version: {{ .Environment.Values.helm.coredns.version }}
    wait: true
    installed: {{ .Environment.Values.helm | default true }}
    values:
      - coredns-values.yaml.gotmpl
```
Content of coredns-values.yaml.gotmpl:

```
"image":
  "tag": {{ .Environment.Values.helm.coredns.tag }}
  "pullPolicy": IfNotPresent
"replicaCount": 3
"service":
  "clusterIP": 172.20.0.10 
"rbac":
  "create": true
```
content of environments.yaml:

```
environments:
  default:
    values:
      - ../auto-generated.yaml
```
auto-generated.yaml content :

```
helm:
  coredns:
    installed: true
    version: 1.10.1
    tag: 1.6.6
```

**Comment by infa-anisrini** [comment]
In releases folder:

```---
bases:
  - ../commons/environments.yaml
---
releases:
  - name: "coredns"
    namespace: "kube-system"
    labels:
      chart: "coredns"
      repo: "stable"
    chart: "stable/coredns"
    version: {{ .Environment.Values.helm.coredns.version }}
    wait: true
    installed: {{ .Environment.Values.helm | default true }}
    values:
      - coredns-values.yaml.gotmpl```

Content of coredns-values.yaml.gotmpl:

```"image":
  "tag": {{ .Environment.Values.helm.coredns.tag }}
  "pullPolicy": IfNotPresent
"replicaCount": 3
"service":
  "clusterIP": 172.20.0.10 
"rbac":
  "create": true```

Content of environments.yaml

```environments:
  default:
    values:
      - ../auto-generated.yaml```

content of auto-generated.yaml:
```helm:
  #externaldns:
  #  installed: true
  #  version: 2.24.0
  #  tag: 0.7.1-debian-10-r32
  #  domainfilter: clt-shrd-eks-qa.usw2.cloudtrust.rocks

  coredns:
    installed: true
    version: 1.10.1
    tag: 1.6.6```

**Comment by infa-anisrini** [comment]
Content of coredns-values.yaml.gotmpl:

```"image":
  "tag": {{ .Environment.Values.helm.coredns.tag }}
  "pullPolicy": IfNotPresent
"replicaCount": 3
"service":
  "clusterIP": 172.20.0.10 
"rbac":
  "create": true```

**Comment by infa-anisrini** [comment]
environments.yaml:
```
environments:
  default:
    values:
      - ../auto-generated.yaml
```
auto-generated.yaml content :
```
helm:
  #externaldns:
  #  installed: true
  #  version: 2.24.0
  #  tag: 0.7.1-debian-10-r32
  #  domainfilter: clt-shrd-eks-qa.usw2.cloudtrust.rocks

  coredns:
    installed: true
    version: 1.10.1
    tag: 1.6.6
```
