### ISSUE TITLE
[Question] How to reference Chart's Values

### ISSUE THREAD

**Issue by l-rossetti** [roboll/helmfile#1260]
I have the following `values/myapp.dev.values.yaml` :
```
image:
    pullPolicy: Always
    repository: <here I would like to use registryFqdn coming from environment>/path/myapp
    tag: 2.7.1-test
```

`And helmfile.yaml`:
```
releases:
    - name: myapp
      namespace: myapp
      installed: true
      atomic: true
      labels:
          app: myapp
      chart: myrepo/myapp
      version: 1.1.0
      missingFileHandler: Error
      values:
          - values/myapp.default.values.yaml
          - values/myapp.{{ .Environment.Name }}.values.yaml
      hooks:
          - events: [ "presync" ]  
            showlogs: true
            command: "skopeo"
            args: [ 
                    "copy", 
                    "--src-creds" , "{{`{{ requiredEnv \"SRC_USER\" }}`}}:{{`{{ requiredEnv \"SRC_PASSWORD\" }}`}}", 
                    "--dest-creds" , "{{`{{ requiredEnv \"DEST_REGISTRY_USER\" }}`}}:{{`{{ requiredEnv \"DEST_REGISTRY_PASSWORD\" }}`}}", 
                    "docker://docker-repo.example.net/path/myapp:{{`{{ .Values.image.tag }}`}}",
                    "docker://{{`{{ .Environment.Values.registryFqdn}}`}}/path/myapp:{{`{{ .Values.image.tag }}`}}"
                ]   
```
**I face two issues.
First**
In the hook I would like to make use of the `image.tag` value coming from `myapp.dev.values.yaml`, i tried:
- by referencing `{{`{{ .Release.Values.image.tag }}`}}`, but I get `in ./helmfile.yaml: failed processing release nokia-superset: hook[skopeo]: template: stringTemplate:1:78: executing "stringTemplate" at <.Values.image.tag>: map has no entry for key "Values"`
- by referencing `{{`{{ .Values.image.tag }}`}}`, but I get:
`./helmfile.yaml: failed processing release nokia-superset: hook[skopeo]: template: stringTemplate:1:79: executing "stringTemplate" at <.Release.Values.image.tag>: can't evaluate field image in type []interface {}`

**Second**
How can I make the `repository` value in `values/myapp.dev.values.yaml ` parametric with respect to values defined in `dev` environment ?

**Comment by mumoshu** [comment]
Sorry, but you can't refer to chart values from helmfile template. Helmfile's {{.Values}}` is for helmfile state values, which is a completely different concept than chart values.

**Comment by l-rossetti** [comment]
and what about `.Release.Values`?
Or what's the suggested approach for sharing a value between multiple files?

**Comment by mumoshu** [comment]
What's `.Release.Values`?

Anyway, you'd just add the same `values.yaml` under `values` of every release. Or just generate chart values from helmfile state values:

```
values:
- foo:
    bar: 1

releases:
- name: yourapp
   values:
   - {{ .Values | toYaml | nindent 4 }}
```

or 

```
values:
- foo:
    bar: 1

releases:
- name: yourapp
   values:
   foobar: "{{ .Values.foo.bar }}"
```

**Comment by l-rossetti** [comment]
Thank you for answering. 
About `.Release.Values` I found it in this issue: https://github.com/roboll/helmfile/issues/978 and I blindly tried it.

About your proposal I'm not sure it can be applied to my context. Let me explain.

I have a docker image version 2.7.1-test and I would like this version to be re-used  in multiple places avoiding misalignment :
- as value for the chart
- in the hook snippet of the first post, cause I need this image to be copied by Skopeo command.

Something like:
```
releases:
    - name: myapp
      chart: myrepo/myapp
      version: 1.1.0
      values:
          - values/myapp.default.values.yaml
          - image:
              tag: 2.7.1-test                                                  <------------------------ here
      hooks:
          - events: [ "presync" ]  
            showlogs: true
            command: "skopeo"
            args: [ 
                    "copy", 
                    "docker://src.com/path/myapp:{{`{{ .Values.image.tag }}`}}",   <--- here
                    "docker://dest.com/path/myapp:{{`{{ .Values.image.tag }}`}}"  <--- here
                ] 

```

**Comment by mumoshu** [comment]
@l-rossetti Thanks. What you're trying to do is actually impossible. You'd need to lift it to use state values. I'd suggest something like the below:

```
values:
- myapp:
    image:
      tag: 2.7.1-test

releases:
    - name: myapp
      chart: myrepo/myapp
      version: 1.1.0
      values:
          - values/myapp.default.values.yaml
          - image:
              tag: {{ .Values.myapp.image.tag }}                         <----------------- here
      hooks:
          - events: [ "presync" ]  
            showlogs: true
            command: "skopeo"
            args: [ 
                    "copy", 
                    "docker://src.com/path/myapp:{{`{{ .Values.myapp.image.tag }}`}}",   <--- here
                    "docker://dest.com/path/myapp:{{`{{ .Values.myapp.image.tag }}`}}"  <--- here
                ] 

```

**Comment by l-rossetti** [comment]
@mumoshu I've tried your idea, but  I got 2 issues:

1. the utilization of .Values in hook causes:
`in ./helmfile.yaml: failed processing release myapp: hook[scripts/copy-docker-image.sh]: template: stringTemplate:1:10: executing "stringTemplate" at <.Values.myapp.image.tag>: map has no entry for key "Values" `

2. the utilization in release values cause:
`in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: invalid map key: map[interface {}]interface {}{".Values.myapp.image.tag":interface {}(nil)}`

tried with helmfile 0.116.0 and 0.109.0

**Comment by mumoshu** [comment]
@l-rossetti Gotcha! What if you tried this? Please note that there's `---` which ensures that the `values` are loaded and parsed before rendering the latter part of your helmfile.yaml

```
values:
- myapp:
    image:
      tag: 2.7.1-test

---

releases:
    - name: myapp
      chart: myrepo/myapp
      version: 1.1.0
      values:
          - values/myapp.default.values.yaml
          - image:
              tag: {{ .Values.myapp.image.tag }}                         <----------------- here
      hooks:
          - events: [ "presync" ]  
            showlogs: true
            command: "skopeo"
            args: [ 
                    "copy", 
                    "docker://src.com/path/myapp:{{`{{ .Values.myapp.image.tag }}`}}",   <--- here
                    "docker://dest.com/path/myapp:{{`{{ .Values.myapp.image.tag }}`}}"  <--- here
                ] 
```
