### ISSUE TITLE
[Feature] common labels for releases

### ISSUE THREAD

**Issue by mlushpenko** [roboll/helmfile#1266]
Hi @mumoshu, I've figured a proper structure to apply changes across all clusters and would like to suggest one feature.

I defined helmcharts as follows:

```
templates:
  autoscaler: &autoscaler
    name: cluster-autoscaler
    namespace: kube-system
    chart: stable/cluster-autoscaler
    version: "7.2.0"
    needs:
    - kube-system/kube2iam
    values: # paths are relative to the helmfile that defines releases
    - ../helm-values/common/{{ .Release.Name }}.yaml
    - ../helm-values/{{ .Release.Labels.customer }}/{{ .Release.Name }}.yaml
``` 

And then in helmafile.yaml:

```
{{ readFile "templates/common.yaml" }}

helmDefaults:
  kubeContext: example

releases:
- <<: *blackbox
- <<: *autoscaler
  labels:
    customer: example
- <<: *kube2iam
  labels:
    customer: example
```

labels are used in templating to search for proper file name for values. When number or releases per customer grows, I would have to add this block many times:

```
labels:
    customer: example
```

Would you be open to defining common labels for releases, I guess something like this, so they would be automatically added to all releases? There is a similar [feature](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md#labels-transformer) in kustomize

```
helmDefaults:
  commonLabels:
    label1: value
    label2: value
```

**Comment by mumoshu** [comment]
@mlushpenko Sounds greeat! As it isn't strictly a helm arg, I believe it worth a top-level key so that the usage looks like:

```
commonLabels:
  label1: value
  label2: value

releases:
- ...
```

WDYT?

**Comment by mlushpenko** [comment]
Yes, @mumoshu, awesome, it's indeed not a helm argument, so this looks great.

**Comment by voron** [comment]
@mlushpenko did you tried to create nested template with customer-specific common values ? 
```yaml
templates:
  _autoscaler: &_autoscaler
    name: cluster-autoscaler
    namespace: kube-system
    chart: stable/cluster-autoscaler
    version: "7.2.0"
    needs:
    - kube-system/kube2iam
    values: # paths are relative to the helmfile that defines releases
    - ../helm-values/common/{{ .Release.Name }}.yaml
    - ../helm-values/{{ .Release.Labels.customer }}/{{ .Release.Name }}.yaml

  autoscaler: &autoscaler
    values: # paths are relative to the helmfile that defines releases
    - ../helm-values/common/{{ .Release.Name }}.yaml
    - ../helm-values/commonLabel1value/{{ .Release.Name }}.yaml
    - ../helm-values/commonLabel2value/{{ .Release.Name }}.yaml
```
It requires single templates file however ...

**Comment by mlushpenko** [comment]
@voron I am not sure I understand your example. I guess you meant to create something like this:

```
templates:
  _autoscaler: &_autoscaler
    name: cluster-autoscaler
    namespace: kube-system
    chart: stable/cluster-autoscaler
    version: "7.2.0"
    needs:
    - kube-system/kube2iam

  autoscalerA: &customerA_autoscaler
    <<: *_autoscaler
    values:
    - ../helm-values/common/{{ .Release.Name }}.yaml
    - ../helm-values/customerA/{{ .Release.Name }}.yaml

  autoscalerB: &customerB_autoscaler
    <<: *_autoscaler
    values:
    - ../helm-values/common/{{ .Release.Name }}.yaml
    - ../helm-values/customerB/{{ .Release.Name }}.yaml
```

But even if I interpreted your idea correctly, that's not what I would like because this setup would import templates for all customers if I use `readFile` function and wouldn't be very DRY in general.
