### ISSUE TITLE
Question on new strategicMergePatches / jsonPatches

### ISSUE THREAD

**Issue by cdunford** [roboll/helmfile#1277]
Hopefully a quick one.

Can either of these new patching mechanisms be used to create brand new objects? I notice in both examples, the incubator chart is used to create an object and then the patch is used to modify that new object.

I'm thinking of cases where a chart doesn't provide an object (eg configmap or secret) that is needed for it to function. Today I have a few cases of this and have been creating separate releases that reference little dummy charts that can just create a configmap or secret. It would be great to use the functionality to eliminate the extra chart and release and be able to create the necessary config object with one of these mechanisms.

Another semi-related question - are these patches tracked as part of helm? Such that if they are modified, they show in a diff, etc?

**Comment by mumoshu** [comment]
> Can either of these new patching mechanisms be used to create brand new objects?

Not yet, but I think that worth a dedicated feature request!

In the meantime, I think you can use this one(not tested yet, but powered by the same feature that is giving us patching):

```yaml
release:
- name: myapp
  dependencies:
  - chart: incubator/raw
    values:
    - raw:
        resources:
        - #write raw k8s manifests here
```

> Another semi-related question - are these patches tracked as part of helm? Such that if they are modified, they show in a diff, etc?

Yes, it should be included in the diff, as internally helmfile does create a temporary local chart that has everything, including the k8s resources rendered from the original chart templates in addition to patched resources.

**Comment by michaelgeorgeattard** [comment]
@mumoshu `state.Dependency` does not seem to have a `values` field

https://github.com/roboll/helmfile/blob/master/pkg/state/helmx.go#L11

**Comment by mumoshu** [comment]
@michaelgeorgeattard How would you like to use `values` if it's added to `state.Dependency`?

**Comment by mumoshu** [comment]
Ah sry, I've spotted some mistakes on my prev example.

It should be

```
release:
- name: myapp
  dependencies:
  - chart: incubator/raw
  values:
  - raw:
      resources:
      - #write raw k8s manifests here
```
