### ISSUE TITLE
Handling secrets with kustomize

### ISSUE THREAD

**Issue by michaelgeorgeattard** [roboll/helmfile#1278]
I am trying to use the new kustomize first-class support, together with helm secrets:

```yaml
- name: kustomize
  namespace: kube-system
  chart: .
  secrets:
  - credentials.yaml
  jsonPatches:
  - target:
      kind: Secret
    patch:
    - op: replace
      path: Username
    value: {{ .Values.Username }} # From credentials.yaml after decryption
```

`jsonPatches` or `strategicMergePatches` do not seem to be supported with `kustomize`.

What is the recommended way to handle some resources/values being encrypted by `helm secrets`?
