### ISSUE TITLE
Importing existing k8s resources into a release

### ISSUE THREAD

**Issue by dudicoco** [roboll/helmfile#1281]
I would like to import existing resources into my release. 
This new `helm` feature allows you to adopt existing resources by annotating them: https://github.com/helm/helm/pull/7649

I was thinking of implementing this using the new `Kustomize` feature https://github.com/roboll/helmfile/pull/1172 but I couldn't get it to work.
Is it possible to use this feature just for patching existing k8s resources? If not, is there a different way to achieve this?

Thanks

**Comment by mumoshu** [comment]
@dudicoco Hey! Sorry but I don't get it. For example, how would you expect your helmfile.yaml to look like when importing existing k8s resources? That may help me understanding what you are trying to.

Anyway, I was thinking that you would just manually modify your existing resources with `kubectl annotate` and then run `helmfile apply` as usual, so that helmfile/helm will adopt resources like explained in helm/helm#7649. Im not sure how Helmfile can helm that.

**Comment by dudicoco** [comment]
Hey @mumoshu, thanks for the reply! The `helmfile.yaml` will look like this:
```
releases:
- name: foo
  chart: my-repo/foo
  version: 1.0.0
  namespace: default
  installed: true
  jsonPatches:
  - target:
      version: v1
      kind: Deployment
      name: foo
      namespace: default
    patch:
    - op: replace
      path: /metadata/annotations
      value:
      - meta.helm.sh/release-name=foo
      - meta.helm.sh/release-namespace=default
    - op: replace
      path: /metadata/labels
      value:
      - app.kubernetes.io/managed-by=Helm
```

Obviously I could patch the resources manually, but I would like the process to be automated with infrastructure as code.
When creating a new cluster with AWS EKS (and I assume with other providers as well) there are many resources that are created by default, such as `aws-node` and `coredns` which I would like to manage using helm. A manual step during the provisioning process is less ideal.

**Comment by mumoshu** [comment]
@dudicoco Thanks!

I believe you need another mechanism that jsonPatches for that. `jsonPatches` in helmfile works by patching "desired" resources to be applied. On the other hand, what you need to let helm adopt existing resources to patch existing/live resources.

I do understand your use-case. If I were you, I would probably enhance eksctl OR terraform-provider-eksctl OR helmfile to enable you to patch live resources. But implementing that in Helmfile seems to bloat Helmfile's scope? 🤔 WDYT?

**Comment by dudicoco** [comment]
@mumoshu I wonder if this feature would provide the solution:
https://github.com/roboll/helmfile/pull/746

Not sure how it works exactly.

**Comment by mumoshu** [comment]
Please let met me dive into my memory... anyway,  I might have possibly missed porting that feature in #1172 so it may not work now

**Comment by mumoshu** [comment]
#746 was intended to work by importing existing resources before the first `helm upgrade --install` run, and the imported resources are specified via a list of `NAMESPACE/KIND/NAME` entries.

Would that work for you if it worked as advertised?

**Comment by mumoshu** [comment]
I thought it was used like this:

```
releases:
- name: aws-auth
   chart: ...
   adopt:
   - kube-system/configmap/aws-auth
```

**Comment by dudicoco** [comment]
@mumoshu i'm getting the following error: `Error: unknown flag: --adopt`

Perhaps using the helm-x binary is needed for this feature to work?

Regarding patching via terraform, this is not possible at the moment:
https://github.com/terraform-providers/terraform-provider-kubernetes/issues/723

**Comment by mumoshu** [comment]
Yes, I believe you're correct. But on the other hand I thought `helm x --adopt` supported Helm 2. Probably I need to rework on that.

Otherwise letting Helmfile to leverage helm 3's ability to adopt resources would be nice as well.

**Comment by dudicoco** [comment]
Thanks @mumoshu. 
Do you think this feature might be added any time soon?

In the meantime, I have found a workaround using `hooks`:
```
  hooks:
  - events:
    - presync
    showlogs: true
    command: kubectl
    args:
    - --context={{ $kubecontext }}
    - --namespace={{ $namespace }}
    - annotate
    - serviceaccount
    - my-svc
    - meta.helm.sh/release-name={{ .name }}
    - meta.helm.sh/release-namespace={{ $namespace }}
  - events:
    - presync
    showlogs: true
    command: kubectl
    args:
    - --context={{ $kubecontext }}
    - --namespace={{ $namespace }}
    - label
    - serviceaccount
    - my-svc
    - app.kubernetes.io/managed-by=Helm
```

This is working as expected, however I have a problem - as part of our CI we are running `helmfile apply --args "--dry-run"`.
This command will actually trigger the hook during the CI test, a solution for that would be to add an `if` block to not include the hook during a dry run, but then helm would fail on conflict with existing resources: `Error: rendered manifests contain a resource that already exists.`.
Do you have an advise on how to handle this chicken and egg problem?
