### ISSUE TITLE
YAML long line wrap 

### ISSUE THREAD

**Issue by voron** [roboll/helmfile#1282]
May be related to https://github.com/go-yaml/yaml/issues/387 

Seems, Helmfile wraps line silently around 115 character, here is test `helmfile.yaml`:
```yaml
templates:
  default: &default
    chart: stable/nginx-ingress
    valuesTemplate:
      - output: {{ printf "my very long-long-long-long-long-long-long-long line is here %s" `{{ .Release.Name }}` }}
releases:
  - <<: *default
    name: test
```
Output:
```
helmfile list
in ./helmfile.yaml: failed executing release templates in "helmfile.yaml": failed executing templates in release "helmfile.yaml"."test": failed executing template expressions in release "test".values[0] = "[111 117 116 112 117 116 58 32 109 121 32 118 101 114 121 32 108 111 110 103 45 108 111 110 103 45 108 111 110 103 45 108 111 110 103 45 108 111 110 103 45 108 111 110 103 45 108 111 110 103 45 108 111 110 103 32 108 105 110 101 32 105 115 32 104 101 114 101 32 123 123 32 46 82 101 108 101 97 115 101 46 78 97 109 101 10 32 32 125 125 10]": template: stringTemplate:1: unclosed action
```
Note multiple char with code `10` inside `values[0]`.

Expected output:
```
helmfile list
NAME    NAMESPACE       ENABLED LABELS
test                    true 
```

Is there any way to customize/increase wrap length?
