### ISSUE TITLE
Variable with path to temporary chart dir

### ISSUE THREAD

**Issue by ofen** [roboll/helmfile#1285]
Good day!

Is there any variable (e.g.  {{ .tmpPath }}) associated with the directory in which Helmfile downloaded the chart?

This required to extract custom override (e.g. values-eks.yaml) from root of Helm chart

**Comment by mumoshu** [comment]
Hey! Unfortunately no. A possible workaround would be to use external tooling to fetch/update that values-eks.yaml stored within the same git repository as your helmfile.yaml so that you can reference it locally.

**Comment by ofen** [comment]
@mumoshu, thank you for your response.

Found another workaround via hooks:
```yaml
releases:
  - name: monitoring
    <<: *default
    namespace: monitoring
    version: 0.1.0
    hooks:
      - events: ["prepare"]
        command: helm
        args: ["fetch", "chartmuseum-lab/{{`{{ .Release.Name }}`}}", "--untar", "--untardir", "."]
      - events: ["cleanup"]
        command: rm
        args: ["-fr", "{{`{{ .Release.Name }}`}}"]
    values:
    {{- if eq .Environment.Values.cluster_type "eks" }}
      - ./{{`{{ .Release.Name }}`}}/values-eks.yaml
    {{- end }}
```
