### ISSUE TITLE
gotmpl files do not render values properly

### ISSUE THREAD

**Issue by unacceptable** [roboll/helmfile#1297]
### Helmfile Version

Several versions checked:
```
helmfile version v0.85.2
helmfile version v0.90.1
helmfile version v0.118.5
```

### Helm Version

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

#### helmfile.yml

```yml
repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: {{ requiredEnv "NAME" }}-jenkins
    namespace: {{ requiredEnv "NAME" }}
    labels:
      app: {{ requiredEnv "NAME" }}-jenkins-master
    chart: stable/jenkins
    version: ~1.27.0
    hooks:
    - events: ["prepare"]
      command: "kubectl"
      args: ["apply","-f", "{{ requiredEnv "NAME" }}/casc-config-map.yaml", "-n", {{ requiredEnv "NAME" }}]
    - events: ["prepare"]
      command: "kubectl"
      args: ["apply","-f","jenkins-rabc.yaml","-n", {{ requiredEnv "NAME" }}]
    values:
    - values.yaml.gotmpl
    wait: true
    timeout: 280
    recreatePods: true
    force: true
```

#### values.yaml.gotmpl

https://github.com/helm/charts/blob/75a1020b6cce44cba3df11999b277e5c2c43db84/stable/jenkins/values.yaml

### Crash Output
```
/ # NAME=ci helmfile -f /helm/jenkins/helmfile.yaml template
Adding repo stable https://kubernetes-charts.storage.googleapis.com
"stable" has been added to your repositories

Updating repo
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.

helmfile.yaml: basePath=.
helmfile.yaml: basePath=.
Fetching stable/jenkins
in /helm/jenkins/helmfile.yaml: failed to render values files "values.yaml.gotmpl": failed to render [values.yaml.gotmpl], because of template: stringTemplate:336:36: executing "stringTemplate" at <.Values.master.servicePort>: map has no entry for key "master"
/ #
```

### Expected Behavior

I expected the helm chart to be templated.

### Actual Behavior

An unexpected crash as a result of... a missing key in the values? 🤷‍♂️   (I am super confused by this error because in the values.yaml.gotmpl this value is clearly present.)

### Steps to Reproduce

1. use `helmfile.yaml` and `values.yaml.gotmpl` provided (removing hooks sections)
2. do a `helmfile -f helmfile.yml template`

### Remediation

I was able to remediate this by changed the helmfile like so:

``` diff
diff --git a/jenkins/helmfile.yaml b/jenkins/helmfile.yaml
index 9f09eae..1f9de6e 100644
--- a/jenkins/helmfile.yaml
+++ b/jenkins/helmfile.yaml
@@ -17,7 +17,7 @@ releases:
       command: "kubectl"
       args: ["apply","-f","jenkins-rabc.yaml","-n", {{ requiredEnv "NAME" }}]
     values:
-    - values.yaml.gotmpl
+    - values.yaml
     wait: true
     timeout: 280
     recreatePods: true
```

and renaming values.yaml.gotmpl to values.yaml

### References

https://github.com/roboll/helmfile#templates
- I have found this doc to be inaccurate because regardless of file extension the values file is rendered if there is appropriate go templating in place.
