### ISSUE TITLE
Helm release with `strategicMergePatches` no longer respecting release namespace

### ISSUE THREAD

**Issue by ggillies** [roboll/helmfile#1299]
I have been starting to use helmfiles new `strategicMergePatches` functionality with helm v0.118.5 and I noticed that once i had a `strategicMergePatches` stanza the `namespace` entry on the release gets ignored, or at least, the resources in the helm chart no longer get installed into the namespace I specify in the release, but rather into the default namespace.

**Comment by ggillies** [comment]
using `helmfile template` we can see the output explicitly have `namespace` set to default even though the release says it should go into the `vault` namespace

```
# output from helmfile template
# Source: vault/templates/helmx.all.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
  name: vault
  namespace: default
```

```
# helmfile release
  - name: vault
    chart: hashicorp/vault
    namespace: vault
    version: 0.6.0
    values:
      - values.yaml.gotmpl
    strategicMergePatches:
      - apiVersion: apps/v1
        kind: StatefulSet
        metadata:
          name: vault
        spec:
          template:
            spec:
              containers:
                - name: vault
                  readinessProbe:
                    periodSeconds: 5
                    timeoutSeconds: 3
```
