### ISSUE TITLE
Clarify two pass renderer errors

### ISSUE THREAD

**Issue by astorath** [roboll/helmfile#1302]
Hi!

1.  Consider the following helmfile:
```yaml
environments:
  test:
    values:
    - int: ''
    - int: 1

releases:
  - name: dummy-{{ .Environment.Values.int }}
    namespace: default
    chart: stable/nginx-ingress
```

2. `helmfile -e test diff` output:
```
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:9:31: executing "stringTemplate" at <.Environment.Values.int>: map has no entry for key "int"
```

3. root cause `helmfile -e test --debug diff`:
```
...
could not deduce `environment:` block, configuring only .Environment.Name. error: failed to read helmfile.yaml.part.0: failed to merge map[int:1]: cannot append two different types (int, string)
...
```
4. expected behavior:
- break rendering on `could not deduce` error (I think there should be another check elsewhere on second pass)
- output error in console (not just debug mode)

**Comment by mumoshu** [comment]
@astorath Hey! Thx for reporting.

> Another option is to revert for previous behavior: just override the type

Are you saying that previous version(s) of Helmfile did override it?

**Comment by mumoshu** [comment]
I think this should be fixed but not sure how I can.

The difficulty here is that there's two phases of rendering, first and second, as you may already know.

This is an error in the first phase. An error in the first phase may or may not result in an error in the second phase. An error in the second phase may or may not be caused by/related to the first phase error.

So, when you get an error in the second phase, how would you determine if it's caused by the first phase error?

> break rendering on could not deduce error (I think there should be another check elsewhere on second pass)

This can be a potential option. But doing this without considering the above concern can be wrong, as a deduce error doesn't always result in an error in the second phase.

> output error in console (not just debug mode)

This can also be an option. Again, an error in the first phase may or may not result in the second phase error. So, this can be also confusing.

But would it be ok if we output the first phase error in a way it looks like a "warning", not "error"?

**Comment by astorath** [comment]
The thing is, if you consider the following helmfile:
```yaml
environments:
  test:
    values:
    - int: ''
    - int: 1

releases:
  - name: dummy
    namespace: default
    chart: stable/nginx-ingress
```

The output would be:
```
in ./helmfile.yaml: failed to read helmfile.yaml: failed to merge map[int:1]: cannot append two different types (int, string)
```

So, I think, that a "warning" on first phase would be just ok.
