### ISSUE TITLE
Layering error "not found in type state.HelmState"

### ISSUE THREAD

**Issue by dstieglitz** [roboll/helmfile#1305]
Hello-- I am trying to do "advanced" layering, and have the following setup:

```
#helmfile.yaml
bases:
  - myenv.yaml
---
bases:
  - defaults.yaml
---
repositories: 
...
```

```
#myenv.yaml
environments:
  minikube:
     - minikube/values.yaml
  dev:
  stg:
  prod:
```

```
#minikube/values.yaml
global:
  client: myclient
```

```
#defaults.yaml
global:
  ldap:
    host: "openldap.{{ .Values.global.client }}" 
#redacted for security
```

When I run the helmfile, the debug log shows the full defaults file rendered correctly! But then this error immediately follows:

```
err: failed to read defaults.yaml: reading document at index 1: yaml: unmarshal errors:
  line 1: field global not found in type state.HelmState
  (the rest of the fields show similar errors)
```

**Comment by mumoshu** [comment]
Hey! First, aren'y you missing `values` in `myenv.yaml`? 

What you shared is:

```
#myenv.yaml
environments:
  minikube:
     - minikube/values.yaml
  dev:
  stg:
  prod:
```

But I guess it should be:

```
#myenv.yaml
environments:
  minikube:
    values:
     - minikube/values.yaml
  dev:
  stg:
  prod:
```

Second, any file specified under `bases` must conform to `helmfile.yaml` syntax.

So this part of your config is definitely problematic:

```
---
bases:
  - defaults.yaml
```

cuz your defaults.yaml is:

```
global:
  ldap:
    host: "openldap.{{ .Values.global.client }}" 
#redacted for security
```

Probably you intended to use defaults.yaml as an environment values file like `minikube/values.yaml`?
