### ISSUE TITLE
parsing: template: stringTemplate:8: bad character U+002D '-'

### ISSUE THREAD

**Issue by infa-anisrini** [roboll/helmfile#1306]
$ helmfile --version
```helmfile version v0.118.7```

I wanted to add a new addon cluster autoscaler and when running helmfile running into issues:

Here is my release file:

```
---
bases:
  - ../commons/environments.yaml
---
releases:
  - name: "clusterautoscaleraddon"
    namespace: "kube-system"
    labels:
      chart: "cluster-autoscaler"
      repo: "stable"
    chart: "stable/cluster-autoscaler"
    version: '{{ .Environment.Values.helm.cluster-autoscaler.version }}'
    wait: true
    installed: '{{ .Environment.Values.helm.cluster-autoscaler.installed }}'
    values:
      - clusterautoscaler-values.yaml.gotmpl
```

The complete error is below:

```
in ./helmfile.yaml: in .helmfiles[5]: in releases/clusterautoscaler.yaml: error during clusterautoscaler.yaml.part.1 parsing: template: stringTemplate:8: bad character U+002D '-'
```

Not sure how this is different from my other addon coredns, it looks exactly the same ,but not getting any error there
