### ISSUE TITLE
Dealing with Openshift weird handling of kubeconfig

### ISSUE THREAD

**Issue by michaelgeorgeattard** [roboll/helmfile#1310]
In Openshift, logging in with `oc login` overwrites context name to include namespace and current name: `namespace/cluster/user`.

Unfortunately this makes it hard to set `kubeContext` in `helmDefaults` as context name is related to active namespace during log in and actual user name.

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://cluster.name.com:6443
  name: cluster-name-com:6443
contexts:
- context:
    cluster: cluster-name-com:6443
    namespace: test
    user: michael.attard/cluster-name-com:6443
  name: test/cluster-name-com:6443/michael.attard
current-context: test/cluster-name-com:6443/michael.attard
kind: Config
preferences: {}
users:
- name: michael.attard/cluster-name-com:6443
  user:
    token: tOk3n123@$1
```

Is there any suggested way to dynamically generate a context name from a cluster name?

Does `helmfile` bundle some helper functions that would be this possible?
