### ISSUE TITLE
Is it possible to use .Release.Name inside .Values?

### ISSUE THREAD

**Issue by odinsy** [roboll/helmfile#1313]
Hi!
I have a common values file for my releases (only one for environment, because it's about ~70 releases for one env).
But i don't understand how to use .Release.Name as key for my values
Look:
```
balancer:
  resources:
    requests:
      memory: 384Mi
    limits:
      memory: 384Mi

backend:
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 512Mi
```
now i want to use `resources` variable for all my releases separately
something like this, but it doesn't work
```
environments:
  dev:

templates:
  default: &default
    {{ $releaseName := "{{`{{ .Release.Name }}`}}" }}
    chart: "{{`{{ .Release.Name }}`}}"
    values:
      - values//{{ .Environment.Name }}/values.yaml
      - resources: {{ .Environment.Values | get ($releaseName).resources }}

releases:
- name: balancer
  <<: *default
- name: backend
  <<: *default
```
can u help me, is it possible?

**Comment by adl2db** [comment]
I'm interested in this too, if its possible. Essentially looking to do something like this (with no success), motivated from this example https://github.com/roboll/helmfile/issues/1143#issuecomment-599824264:


```yaml

templates:
  values: &values
      set:
         - name: replicas
           values: {{ index .Values.replicas .Release.Name }}
```

with helmfile looking like this

```yaml
environments:
    dev: 
      values:
         - replicas.yaml
releases:
- name: release-name-1
  <<: *values
```

replicas.yaml looks like this

```yaml
replicas:
  release-name-1: 1
```

`helmfile 0.119.0`

**Comment by mumoshu** [comment]
Hey! Please note that any go template expressions is evaluated BEFORE it's parsed as YAML. That's why it doesn't work.

A possible way would be to use `valuesTemplate` added in https://github.com/roboll/helmfile/pull/823 and https://github.com/roboll/helmfile/pull/833

**Comment by odinsy** [comment]
> Hey! Please note that any go template expressions is evaluated BEFORE it's parsed as YAML. That's why it doesn't work.
> 
> A possible way would be to use `valuesTemplate` added in #823 and #833

Hm, thank you!
Could you help me with one more question - do you know how can i make separate release files for every environment?

**Comment by odinsy** [comment]
This one works but i want to have separate releases file for every environment.
There is more than 70 services for install
```
bases:
- environments.yaml

---
{{- $apps := readFile "_custom_values/common/releases.yaml" | fromYaml }}

templates:
  default: &default
    chart: "{{`{{ .Release.Name }}`}}"
    values:
      - _custom_values/{{ .Environment.Name }}/values.yaml
{{- range $_, $settings := $apps }}
      - resources: {{ $settings | get "resources" | toYaml | nindent 10 }}
{{- end }}

releases:
{{- range $app, $_ := $apps  }}
- name: {{ $app }}
  <<: *default
{{- end }}
```

**Comment by odinsy** [comment]
arghh, this one doesn't work too
```
environments:
  dev:
    values:
      - _custom_values/dev/releases.yaml

templates:
  default: &default
    {{ $releaseName := "{{`{{ .Release.Name }}`}}" }}
    chart: "{{`{{ .Release.Name }}`}}"
    valuesTemplate:
      - _custom_values/{{ .Environment.Name }}/values.yaml
      - _custom_values/{{ .Environment.Name }}/resources.yaml

releases:
{{- range $release := .Values.releases  }}
- name: {{ $release }}
  <<: *default
  values:
    - resources: {{ .Values.resources | get $release }}
{{- end }}
```

**Comment by odinsy** [comment]
one more not working example
```
environments:
  dev:
    values:
      - _custom_values/dev/releases.yaml

templates:
  default: &default
    chart: "{{`{{ .Release.Name }}`}}"
    valuesTemplate:
      - _custom_values/{{`{{ .Environment.Name }}`}}/values.yaml
      - _custom_values/{{`{{ .Environment.Name }}`}}/resources.yaml
      - resources.yaml.gotmpl
    setTemplate:
    - name: '{{`{{ .Release.Name }}`}}'

releases:
{{- range $release := .Values.releases  }}
- name: {{ $release }}
  <<: *default
{{- end }}
```
resources.yaml.gotmpl
```
resources: {{ .Values.resources | get .Name |  toYaml | nindent 10 }}
```
