### ISSUE TITLE
Helmfile + Kustomize - cannot unmarshal !!seq into state.HelmState

### ISSUE THREAD

**Issue by deveshmehta** [roboll/helmfile#1323]
By following the instructions given in Readme, I am trying to use the Kustomize with Helmfile but I am getting below error when I try to run the sync command.

```
helmfile --environment dev --file=helmfile.yaml sync
in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line 4: cannot unmarshal !!seq into state.HelmState
```

```
$cat helmfile.yaml
- name: common-virtual-services
  chart: ./common-virtual-services
  hooks:
  - events: ["prepare", "cleanup"]
    command: "./helmify"
    args: ["{{`{{if eq .Event.Name \"prepare\"}}build{{else}}clean{{end}}`}}", "{{`{{.Release.Chart}}`}}", "{{`{{.Environment.Name}}`}}"]
```

**Environment:**
helmfile version v0.119.0
kustomize - Version:3.6.1
OS - Darwin DEM-C02X5AKLJG5J 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

Please let me know if you need more details.
