### ISSUE TITLE
variantdev/vals aws profile for SSM ignored with helmfile

### ISSUE THREAD

**Issue by Tanbouz** [roboll/helmfile#1325]
**Test 1:** This works with vals-0.6.0
```
echo "foo: ref+awsssm://mypath/somekey?profile=myprofile&region=eu-west-1" | bin/vals eval -f -
```
Result:
```
SSM: successfully retrieved key=/mypath/somekey
foo: "banana"
```

**Test 2:** Using helmfile version v0.119.1
```
releases:
  - name: something
    namespace: kube-system
    chart: ./something
    values:
      - foo: ref+awsssm://mypath/somekey?profile=myprofile&region=eu-west-1
```
Result:
```
get parameter: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Test 3:** If I provide helmfile with `AWS_PROFILE=profile-with-permissions` as env with permission to that parameter it works. 
(but I need to use ?profile for different parameters, also kubeconfig is using a different role with aws-iam-authenticator)

**Test 4:** If I provide helmfile with `AWS_PROFILE=some-other-profile` as env without permission to that parameter, says:
```
get parameter: ParameterNotFound: 
```

It seems when using helmfile the `?profile` part is being ignored.
