### ISSUE TITLE
Request support for ChartCenter from JFrog

### ISSUE THREAD

**Issue by michaelpporter** [roboll/helmfile#1326]
The new [chart repo (Chart Center) from JFrog](https://chartcenter.io/) is not supported due to chart path setting.

Example aws-alb-ingress-controler:

Because Chart Center prepends 'center/' to cloned repo paths Helmfile reads it as a folder path.

https://chartcenter.io/incubator/aws-alb-ingress-controller?version=0.1.14

Example helmfile.yaml

```yaml
repositories:
- name: center
  url: https://repo.chartcenter.io

releases:

- name: aws-alb-ingress-controller
  chart: center/incubator/aws-alb-ingress-controller
  version: 0.1.14
  namespace: default
```

Error output

```bash
STDERR:
  Error: could not find center/incubator/aws-alb-ingress-controller: stat center/incubator/aws-alb-ingress-controller: no such file or directory
```
