### ISSUE TITLE
Support Complex Types With Environment Files

### ISSUE THREAD

**Issue by toneill818** [roboll/helmfile#1327]
Currently the following does not work:
env.yaml
```yaml
complexType:
  -  object1Item1: object1Value1
     object1Iitem2: object1Value2
  -  object2Item1: object2Value1
     object2Item2: object2Value2
```

helmfile.yaml
```yaml
values:
   - complexType: {{ .Environment.Values.complexType }}
```

It sets the value to `[map[object1Item1:object1Value1 object1Item2:object1Value2], [object2Item1: object2Value1, object2Item2: object2Value2]]`

It would be nice to be able to specify complex types within the environment files.
