### ISSUE TITLE
One common values.yaml with params for multiple Releases

### ISSUE THREAD

**Issue by odinsy** [roboll/helmfile#1336]
I have one file for one environment with only release names 
```
releases:
  - frontend
  - balancer
```
and have separate file with specific for releases values
```
frontend:
  version: 0.1.0
  resources:
    requests:
      memory: 384Mi
    limits:
      memory: 384Mi
balancer:
  version: 0.0.1
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 512Mi
```
now i want to iterate over every release and set values but still getting errors
```
environments:
  dev:
    values:
      - dev/releases.yaml

templates:
  default: &default
    chart: "{{`{{ .Release.Name }}`}}"
    values:
      - {{`{{ .Environment.Name }}`}}/values.yaml
      - {{`{{ .Environment.Name }}`}}/resources.yaml

releases:
{{- range $release := .Values.releases  }}
- name: {{ $release }}
  <<: *default
  values:
    - resources: {{ .Values | get $release.resources }}
{{- end }}
```
```
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:18:20: executing "stringTemplate" at <.Values>: can't evaluate field Values in type interface {}
```
is it possible?

UPD:
Sure, i can merge releases and values into one file, but what about separate files for releases and values? 
```
releases:
  balancer:
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 512Mi
```
```
environments:
  dev:
    values:
      - dev/releases.yaml

templates:
  default: &default
    chart: "{{`{{ .Release.Name }}`}}"
    valuesTemplate:
      - _custom_values/{{`{{ .Environment.Name }}`}}/values.yaml
      - _custom_values/{{`{{ .Environment.Name }}`}}/resources.yaml

releases:
{{- range $release, $settings := .Values.releases  }}
- name: {{ $release }}
  <<: *default
  values:
    - resources: {{ $settings | get "resources" | toYaml | nindent 10 }}
{{- end }}
```

**Comment by odinsy** [comment]
Sure, i can merge releases and values into one file, but it's not  so interesting :)
release.yaml
```
releases:
  balancer:
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 512Mi
```
helmfile.yaml
```
environments:
  dev:
    values:
      - dev/releases.yaml

templates:
  default: &default
    chart: "{{`{{ .Release.Name }}`}}"
    valuesTemplate:
      - _custom_values/{{`{{ .Environment.Name }}`}}/values.yaml
      - _custom_values/{{`{{ .Environment.Name }}`}}/resources.yaml
{{- range $_, $settings := .Values.releases }}
      - resources: {{ $settings | get "resources" | toYaml | nindent 10 }}
{{- end }}

releases:
{{- range $release, $_ := .Values.releases  }}
- name: {{ $release }}
  <<: *default
{{- end }}
```

**Comment by odinsy** [comment]
Well, i did it
```
environments:
  dev:
    values:
      - dev/releases.yaml

templates:
  default: &default
    chart: "{{`{{ .Release.Name }}`}}"
    valuesTemplate:
      - _custom_values/{{`{{ .Environment.Name }}`}}/values.yaml
      - _custom_values/{{`{{ .Environment.Name }}`}}/resources.yaml

releases:
{{- range $release := .Values.releases  }}
- name: {{ $release }}
  <<: *default
{{- end }}
```
