### ISSUE TITLE
Set version for autogenerated chart

### ISSUE THREAD

**Issue by olfway** [roboll/helmfile#1337]
I'm using kustomize integration to install kustomized manifests files as chart:

```
❯ ls coredns
dns.yaml
kustomization.yaml
```

```
releases:
  - name: coredns
    namespace: kube-system
    chart: ./coredns
    version: v1.6.6
```

but the version of chart and app is 1.0.0:
```
NAME   	NAMESPACE  	REVISION	UPDATED                              	STATUS  	CHART        	APP VERSION
coredns	kube-system	2       	2020-07-08 08:43:02.446469 +0300 EEST	deployed	coredns-1.0.0	1.0.0
```

is it possible to set chart and app version?

**Comment by mumoshu** [comment]
Hey! When I've added the feature, I thought that it isn't correct to show it as v1.6.6, as it's not exactly v1.6.6 but the altered version of it

**Comment by olfway** [comment]
These manifests install coredns v1.6.6 so I think it's ok

Actually I tried to deploy another chart and it has correct version:
```
  - name: metrics-server
    namespace: kube-system
    chart: ./metrics-server
    version: v0.3.6
```

```
 ❯ helm list
NAME          	NAMESPACE  	REVISION	UPDATED                              	STATUS  	CHART                	APP VERSION
coredns       	kube-system	2       	2020-07-08 08:43:02.446469 +0300 EEST	deployed	coredns-1.0.0        	1.0.0
metrics-server	kube-system	1       	2020-07-08 10:42:49.963566 +0300 EEST	deployed	metrics-server-v0.3.6	v0.3.6
```

So it seems version is set on deploy

I deployed coredns without "version" first time and then added version to helmfile
unfortunately, helmfile apply doesn't update version

**Comment by mumoshu** [comment]
> These manifests install coredns v1.6.6

Are you saying that not only the chart's version but appVersion is also v1.6.6?

Reusing the appVersion from the original chart after patching does seem correct. Not sure on the chart version though.

**Comment by olfway** [comment]
Both versions now set to version from helmfile.yml

But there is no "original chart", these folders are plain manifests plus kustomize, for example for metrics-server:

helmfile.yaml:
```
releases:
  - name: metrics-server
    namespace: kube-system
    chart: ./metrics-server
    version: v0.3.6
```

```
❯ cat metrics-server/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- components.yaml

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: metrics-server
  path: patches/deployment.yaml
```

```
❯ head metrics-server/components.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:aggregated-metrics-reader
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
...
```

```
❯ helm list
NAME          	NAMESPACE  	REVISION	UPDATED                              	STATUS  	CHART                	APP VERSION
metrics-server	kube-system	1       	2020-07-08 10:42:49.963566 +0300 EEST	deployed	metrics-server-v0.3.6	v0.3.6
```
