### ISSUE TITLE
Proposal: upgrade/install subsets of releases, like: helmfile charts --releases chart-a,chart-b

### ISSUE THREAD

**Issue by fishi0x01** [roboll/helmfile#134]
**Usecase**
---
In some cases I would like to install/upgrade only a subset of my charts from the `helmfile.yaml`. This should not be seen as a standard usecase, but more as a help in certain operational edge cases.

**Proposal**
---
A `--releases` option, which accepts a comma separated array of release ids, that you want to install/upgrade. 

**helmfile.yaml:**
```
---
releases:
  - name: proxy
    namespace: default
    chart: charts/proxy
  - name: app
    namespace: default
    chart: charts/app
  - name: redis
    namespace: default
    chart: charts/redis
```

`helmfile charts --releases proxy,app` would then run upgrade/install on the `proxy` and `app` chart, but would not update the `redis` chart.
