### ISSUE TITLE
Variables in kustomization.yaml

### ISSUE THREAD

**Issue by olfway** [roboll/helmfile#1340]
Is it possible to use go template variables in kustomization.yaml file?

For example I want to have something like this:
```
$ cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubernetes-sigs/metrics-server/releases/download/{{ .Values.appVersion }}/components.yaml

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: metrics-server
  path: patches/deployment.yaml
```

**Comment by mumoshu** [comment]
@olfway Hey! Interesting idea. It's impossible today, but worth investigating.

What `.Values.appVersion` should refer to, btw? The values of the release, or helmfile state(environment) values?

**Comment by mumoshu** [comment]
I.e. what if helmfile allowed this?

```
releases:
- name: yourapp
  kustomization: some/dir/kustomization.yaml.gotmpl
  values:
  - appVersion: ver
```

**Comment by olfway** [comment]
I thought .Values. should refer to the values of the release, like in your example

**Comment by darkn3rd** [comment]
I absolutely need this feature.  My use case is this use a namespace for the installation but also set the `subjects[0].namespace` in `ClusterRoleBinding.rbac.authorization.k8s.io`.  So the question is, how do I inject env var of `ROOK_NFS_OPERATOR_NAMESPACE` into the kustomize with helmfile?

```yaml
releases:
  {{- if eq (env "NFS_STRATEGY") "rook" }}
  - name: rook-nfs-operator
    namespace: rook-nfs-system
    chart: ./rook-nfs-operator
    hooks:
      - events:
          - prepare
          - cleanup
        command: ./helmify.sh
        args:
          - "{{`{{if eq .Event.Name \"prepare\"}}build{{else}}clean{{end}}`}}"
          - "{{`{{.Release.Chart}}`}}"
          - default
  {{- end }}
```

In my `rook-nfs-operator-kustomize/base/operator.yaml`, I will have this:
```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-nfs-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-nfs-operator
subjects:
- kind: ServiceAccount
  name: rook-nfs-operator
  namespace: $(ROOK_NFS_OPERATOR_NAMESPACE)
```
