### ISSUE TITLE
Implement 'include' function

### ISSUE THREAD

**Issue by sirianni** [roboll/helmfile#1345]
It would be nice to have an `include` function [like helm](https://helm.sh/docs/howto/charts_tips_and_tricks/).  The use case is to be able to render a template to a string and then further transform it in a pipeline.

Without this it is impossible to have a common YAML snippet defined in a template and then indent it contextually based on where it is used.  For example:

```yaml
{{ define "my-template" }}
some-yaml:
  foo:
{{ end }}

bar:
  {{- include "my-template" | nindent 2 }}

baz:
  qux:
    {{- include "my-template" | nindent 4 }}
```

**Comment by mumoshu** [comment]
@sirianni Hey!

I thought the Helmfile way for that has been `{{ readFile "path/to/gotmpl/file" }}` and `{{ tpl (readFile "path/to/gotmpl/file") .Values }}`.

Just curious, but do you think we'd still need `include`?

**Comment by sirianni** [comment]
You're right, the `tpl` function can just be used directly.  I'm not sure why `helm` defines both `tpl` and `include` then.... :thinking: 
```yaml
{{ define "my-template" }}
some-yaml:
  foo:
{{ end }}

bar:
  {{- tpl "my-template" . | nindent 2 }}

baz:
  qux:
    {{- tpl "my-template" . | nindent 4 }}
```
