### ISSUE TITLE
How to ignore string templates ?

### ISSUE THREAD

**Issue by scorsi** [roboll/helmfile#1349]
Hello :wave:

I would like to ignore string templates. Like in this example, I would like to pass both `tls.crt: {{ .Values.cert }}` and `tls.key: {{ .Values.key }}` as is into the `incubator/raw` chart and let it interpret the template.

```yaml
repositories:
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
releases:
  - name: linkerd-trust-anchor
    namespace: linkerd
    chart: incubator/raw
    version: 0.2.3
    values:
      - templates:
          - apiVersion: v1
            kind: Secret
            type: kubernetes.io/tls
            metadata:
              name: linkerd-trust-anchor
            data:
              tls.crt: {{ .Values.cert }}
              tls.key: {{ .Values.key }}
    set:
      - name: cert
        file: ca.crt
      - name: key
        file: ca.key
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "step"
        args: ["certificate", "create", "identity.linkerd.cluster.local", "ca.crt", "ca.key", "--profile", "root-ca", "--no-password", "--insecure"]
```

Thanks,

**Comment by andrewnazarov** [comment]
What about just 
```
{{`{{ .Values.cert }}`}} 
```
trick?

**Comment by scorsi** [comment]
Thanks I didn't try the ``` but I still got the error: `in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: invalid map key: map[interface {}]interface {}{".Values.cert":interface {}(nil)}`. :(

**Comment by mumoshu** [comment]
@scorsi That seems like due to that you have an invalid key in your values file? @andrewnazarov's suggestion is correct and there should be another kind of error that causing it.

**Comment by scorsi** [comment]
This is my whole `helmfile`. No missing parts.

While looking at https://github.com/helm/charts/tree/master/incubator/raw, it appears I missed something, I shall put the templates values in yaml multi-line string. Like this:

```yaml
releases:
  - name: linkerd-trust-anchor
    namespace: linkerd
    chart: incubator/raw
    version: 0.2.3
    values:
      - templates:
          - |
            apiVersion: v1
            kind: Secret
            type: kubernetes.io/tls
            metadata:
              name: linkerd-trust-anchor
            data:
              tls.crt: {{`{{ .Values.cert }}`}}
              tls.key: {{`{{ .Values.key }}`}}
    set:
      - name: cert
        file: ca.crt
      - name: key
        file: ca.key
```

With or without the trick, I still have errors:
```
# With, so : {{`{{ .Values.cert }}`}}

Error: 'error converting YAML to JSON: yaml: line 9: could not find expected '':'''
metadata:
  labels:
    app: raw
    chart: raw-0.2.3
    heritage: Helm
    release: linkerd-trust-anchor

# Without, so : {{ .Values.cert }}

in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:18:33: executing "stringTemplate" at <.Values.cert>: map has no entry for key "cert"
```

**Comment by smlx** [comment]
your `cert` and `keys` values are likely to be multiline, so you'll need something like this:
```
            data:
              tls.crt: |
                {{`{{- .Values.cert | nindent 16 }}`}}
              tls.key: |
                {{`{{- .Values.key | nindent 16 }}`}}
```

**Comment by scorsi** [comment]
Oh my god, I feel stupid. It's perfectly working now. Thank you very much !

Here's the complete code if someone needs it:
```yaml
repositories:
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
releases:
  - name: linkerd-trust-anchor
    namespace: linkerd
    chart: incubator/raw
    version: 0.2.3
    values:
      - templates:
          - |
            apiVersion: v1
            kind: Secret
            type: kubernetes.io/tls
            metadata:
              name: linkerd-trust-anchor
            data:
              tls.crt: |
                {{`{{- .Values.cert | nindent 16 }}`}}
              tls.key: |
                {{`{{- .Values.key | nindent 16 }}`}}
    set:
      - name: cert
        file: ca.crt
      - name: key
        file: ca.key
    hooks:
      - events: ["prepare"]
        command: "step"
        args: ["certificate", "create", "identity.linkerd.cluster.local", "ca.crt", "ca.key", "--profile", "root-ca", "--no-password", "--insecure", "-f"]
```
