### ISSUE TITLE
`helmfile apply` ignores --disable-openapi-validation flag

### ISSUE THREAD

**Issue by dpeckett** [roboll/helmfile#1378]
The apply operation ignores the `--disable-openapi-validation` flag if passed as an arg on the command line, or as custom args in the helmfile. However the apply operation does respect the `disableOpenAPIValidation` helmDefaults property.

The sync operation behaves in the inverted manner, respecting the argument but not the helmDefaults property.

Both operations, at a minimum should respect the `disableOpenAPIValidation` helmDefaults property.

Reported version: v0.125.0

**Comment by mumoshu** [comment]
@dpeckett Hey!

> The apply operation ignores the --disable-openapi-validation flag if passed as an arg on the command line

Sorry I don't understand this. `helmfile apply` doesn't have an command-line flag named `--disable-openapi-validation`.

> or as custom args in the helmfile

Are we stalking about `--args`? It's deprecated because it's so hard to maintain/undestand as we have no way which flags should be passed to which helm command, as a single helmfile command usually results in multiple helm commands.

> The sync operation behaves in the inverted manner, respecting the argument but not the helmDefaults property.

I don't get this, too. `helmfile sync` doesn't have a flag named `--disable-openapi-validation` and it doesn't call `helm diff` so there's no way `disableOpenAPIValidation` affects it.

**Comment by mumoshu** [comment]
Can I suggest you to try running `helmfile --debug apply` or `helmfile --debug diff` with:

```
releases:
- name: myrelease
  chart: somebrokenchart
  disableOpenAPIValidation: true
```

or 

```
helmDefaults:
  disableOpenAPIValidation: true

releases:
- name: myrelease
  chart: somebrokenchart
```

Both are working fine for me.

**Comment by klebediev** [comment]
The same issue for me `v0.125.1`
```yaml
releases:
{{- range list 0 1 }}
- name: prom-server-{{ . }}
  namespace: monitoring
  labels:
    app: prometheus
    component: prom-server-{{ . }}
  installed: {{ $install }}
  chart: stable/prometheus-operator
  version: 8.10.0
  disableOpenAPIValidation: true
  values:
....
```

```bash
helmfile ..... -l component=prom-server-0 --log-level debug apply
.......
# --disable-openapi-validation appended to diff
Comparing release=prom-server-0, chart=stable/prometheus-operator
exec: helm3 diff upgrade --reset-values --allow-unreleased prom-server-0 stable/prometheus-operator --version 8.10.0 --disable-openapi-validation --namespace monitoring --values /var/folders/70/cl7fhhd51zj6_5kxr2dl3fwr0000gn/T/values111325688 --values /var/folders/70/cl7fhhd51zj6_5kxr2dl3fwr0000gn/T/values335703799 --detailed-exitcode

......
# then --disable-openapi-validation NOT appended to `helm upgrade` command 
Upgrading release=prom-server-0, chart=stable/prometheus-operator
exec: helm3 upgrade --install --reset-values prom-server-0 stable/prometheus-operator --version 8.10.0 --create-namespace --namespace monitoring --values /var/folders/70/cl7fhhd51zj6_5kxr2dl3fwr0000gn/T/values458357738 --values /var/folders/70/cl7fhhd51zj6_5kxr2dl3fwr0000gn/T/values361722433 --history-max 10
```

I feel like it's a bug.
