### ISSUE TITLE
Using release values in conjunction with environment values in release templates

### ISSUE THREAD

**Issue by bwbonanno** [roboll/helmfile#1379]
I have been toying around with release templates and wanted to know if it was possible to define a template like such:
```yaml
templates:
  some_template: &some_template
    values:
      - someValuesFile.yaml
      - key_one: {{ .Environment.Values | getOrNil "{{.Release.Name}}.key_one" | default "value" }}
    installed: {{ index .Environment.Values "installed" "{{.Release.Name}}" | default false }}
```

Desired output for the release would be something like:
```yaml
releases:
  release_one:
    values:
      - someValuesFile.yaml
      - key_one: {{ .Environment.Values | getOrNil "release_one.key_one" | default "value" }}
    installed: {{ index .Environment.Values "installed" "release_one" | default false }}
```

That way the values file could look something like:
```yaml
release_one:
  key_one: value

installed:
  release_one: true
```

Thanks!
