### ISSUE TITLE
[Question] `needs` ignores namespaced releases

### ISSUE THREAD

**Issue by amnk** [roboll/helmfile#1380]
I recently found that helmfile supports DAGs, and now I'm trying to get use of it. But the behavior that I see seems odd, e.g. I don't understand it.

I have a base template, which defines all my services, like this:
```
templates:
  base: &base
    namespace: {{ $env }}
    chart: .ci/charts/helm-microservice
    needs:
      - {{ $env }}/configconnector

  service: &service
    <<: *base
```
And I use it then like this:
```
releases:
  - name: api
    labels:
      app: api
      mask: all
    <<: *service-secret

 - name: configconnector
    labels:
      app: configconnector
      mask: all
    namespace: {{ $env }}
    chart: .ci/charts/config-connector-helper
    installed: true
```

And my issue is that `configconnector` never gets created - it seems that `needs` is ignored. If I change `needs` to be simple `configconnector` (without the `{{ $env }}`), helmfile complains that it can't find that.
