### ISSUE TITLE
Go-getter URLs from #1374 are not working

### ISSUE THREAD

**Issue by Nuru** [roboll/helmfile#1401]
I am trying to use `go-getter` URLs as described in #1374 in Helmfile v0.125.2 but they are not working for me:

```yaml
releases:
  - name: "forecastle"
    chart: git::https://github.com/stakater/Forecastle.git@deployments/kubernetes/chart/forecastle?ref=v1.0.54
    forceGoGetter: true
```

Helmfile does not seem to intercept this URL, it just passes it along to helm, which of course cannot handle it.

I tried `http` instead of `https`, with and without `.git`, and replacing `@` with `//` as described in [the go-getter docs](https://github.com/hashicorp/go-getter#subdirectories).

<details>
<summary>
Error output
</summary>

```text
$ helmfile -b /usr/bin/helm3 template
Fetching git::http://github.com/stakater/Forecastle.git@deployments/kubernetes/chart/forecastle?ref=v1.0.54
Removing remove .helmfile/cache/http_github_com_stakater_Forecastle_git.ref=v1.0.54/deployments/kubernetes/chart/forecastle: directory not empty: %!v(MISSING)
in ./helmfile.yaml: [command "/usr/bin/helm3" exited with non-zero status:

PATH:
  /usr/bin/helm3

ARGS:
  0: /usr/bin/helm3 (14 bytes)
  1: fetch (5 bytes)
  2: git::http://github.com/stakater/Forecastle.git@deployments/kubernetes/chart/forecastle?ref=v1.0.54 (98 bytes)
  3: --version (9 bytes)
  4: v1.0.54 (7 bytes)
  5: --untar (7 bytes)
  6: --untardir (10 bytes)
  7: /tmp/934991620/portal/v1.0.54/git::http:/github.com/stakater/Forecastle.git@deployments/kubernetes/chart/forecastle?ref=v1.0.54 (127 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: git::http://github.com/stakater/Forecastle.git@deployments/kubernetes/chart/forecastle?ref=v1.0.54

COMBINED OUTPUT:
  Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: git::http://github.com/stakater/Forecastle.git@deployments/kubernetes/chart/forecastle?ref=v1.0.54]
```
</details>

**Comment by mumoshu** [comment]
@Nuru Thanks as always for your support 🙏 This was definitely a bug, which is being fixed via #1405 soon.

// BTW, I'm planning to enhance our integration test suite so that regressions like this won't happen in the future.

**Comment by lukasmrtvy** [comment]
@mumoshu Can You take a look at something like this, please?
```
releases:
- name: gitlab
  namespace: gitlab
  chart: git::https://gitlab.com/gitlab-org/charts/gitlab?ref=master&sparse=0
  forceGoGetter: true
```

```
in ./helmfile.yaml: [Parsing url from directory of release "gitlab" failed due to error "invalid src format: it must be `[<getter>::]<scheme>://<host>/<path/to/dir>@<path/to/file>?key1=val1&key2=val2: got https://gitlab.com/gitlab-org/charts/gitlab?ref=master&sparse=0".
```
Thanks ! <3

**Comment by mumoshu** [comment]
@lukasmrtvy Could you try `chart: git::ssh://git@gitlab.com/gitlab-org/charts/gitlab.git@charts/gitlab?ref=master&sparse=0` instead? I believe go-getter doesn't support https-access for gitlab

**Comment by lukasmrtvy** [comment]
SSH:
`chart: git::ssh://git@gitlab.com/gitlab-org/charts/gitlab.git@charts/gitlab?ref=master&sparse=0`

```
in ./helmfile.yaml: [fetching "git::ssh://git@gitlab.com/gitlab-org/charts/gitlab.git@charts/gitlab?ref=master&sparse=0": get: error downloading 'ssh://git@gitlab.com/gitlab-org/charts/gitlab.git?ref=master&sparse=0': /usr/bin/git exited with 128: Cloning into '.helmfile/cache/ssh_gitlab_com_gitlab-org_charts_gitlab_git.ref=master_sparse=0'...
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
]
```

Imported to Github:
`chart: git::https://github.com/lukasmrtvy/gitlab-chart.git@charts/gitlab?ref=master`

```
COMBINED OUTPUT:
  Error: failed to download "git::https://github.com/lukasmrtvy/gitlab-chart.git@charts/gitlab?ref=master" (hint: running `helm repo update` may help)
```


With sparse=0 arg:
` chart: git::https://github.com/lukasmrtvy/gitlab-chart.git@charts/gitlab?ref=master%sparse=0`
```
COMBINED OUTPUT:
  Error: failed to download "git::https://github.com/lukasmrtvy/gitlab-chart.git@charts/gitlab?ref=master%sparse=0" (hint: running `helm repo update` may help
```

**Comment by mumoshu** [comment]
@lukasmrtvy Which version of Helmfile are you using? The fix for this issue #1405 isn't released yet as a helmfile release. So you'd need to build your own binary to test it.

**Comment by mumoshu** [comment]
Anyway, I've just released v0.125.4 😃 Would u mind testing it out, if you weren't using your own binary?

**Comment by lukasmrtvy** [comment]
My mistake, sorry :( 

Both formats  `chart: git::https://gitlab.com/gitlab-org/charts/gitlab@charts/gitlab?ref=master%sparse=0` and `chart: git::https://gitlab.com/gitlab-org/charts/gitlab@charts/gitlab?ref=master` are **OK** with  v0.125.4 

btw I am getting: 
```
COMBINED OUTPUT:
  Error: template: gitlab/charts/webservice/templates/tests/tests.yaml:5:20: executing "gitlab/charts/webservice/templates/tests/tests.yaml" at <{{template "fullname" .}}>: template "fullname" not defined
  Use --debug flag to render out invalid YAML
```
, but I guess its chart specific...

**Comment by lukasmrtvy** [comment]
@mumoshu 

Btw ( Related: https://github.com/roboll/helmfile/pull/1374 ), this is working now:
```
releases:
- name: cert-manager-crds
  namespace: cert-manager
  chart: git::http://github.com/jetstack/cert-manager.git@deploy/crds?ref=v0.15.2
```

I have tried also:
```
releases:
- name: cert-manager-crds
  namespace: cert-manager
  chart: https://github.com/jetstack/cert-manager/releases/download/v0.15.2/cert-manager.crds.yaml
```
, but it does not work:
```
Templating release=cert-manager-crds, chart=https://github.com/jetstack/cert-manager/releases/download/v0.15.2/cert-manager.crds.yaml
in ./hel.yaml: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: template (8 bytes)
  2: cert-manager-crds (17 bytes)
  3: https://github.com/jetstack/cert-manager/releases/download/v0.15.2/cert-manager.crds.yaml (89 bytes)
  4: --namespace (11 bytes)
  5: cert-manager (12 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: file '/home/mrtvyl/.cache/helm/repository/cert-manager.crds.yaml' seems to be a YAML file, but expected a gzipped archive

COMBINED OUTPUT:
  Error: file '/home/mrtvyl/.cache/helm/repository/cert-manager.crds.yaml' seems to be a YAML file, but expected a gzipped archive
```

**Comment by mumoshu** [comment]
@lukasmrtvy Thanks for your detailed reports! Glad to hear it (almost) worked for you.

```
releases:
- name: gitlab
  namespace: gitlab
  chart: git::https://gitlab.com/gitlab-org/charts/gitlab@
  forceGoGetter: true
  values:
    - certmanager-issuer:
        email: you@example.com
```

Re this one, I'm wondering if the `gitlab` chart is incomplete that we need to run `helm dep build` after git-cloning it? Could you check if the gitlab chart has `Chart.lock`?

Recently, Helmfile has been updated in #1400, to NOT run `helm dep build` on the fetched chart to avoid blocking on a "broken" chart that has an outdated Chart.lock. Apparently, we need to run `helm dep build` on a fetched chart without Chart.lock, while it shouldn't be run on a chart with an outdated Chart.lock?
