### ISSUE TITLE
Repositories are not properly added in v0.125.1+

### ISSUE THREAD

**Issue by elordahl** [roboll/helmfile#1404]
I've verified it's OK in v0.125.0.  Output and file for v0.125.1 follow.  What's strange is that if i rename the repository to `stable`, it is added.  output:

```sh
bash-5.0$ helmfile -v
helmfile version v0.125.1
bash-5.0$ helmfile repos
bash-5.0$
```

`repositories.yaml`:
```yaml
repositories:
- name: traefik
  url: https://containous.github.io/traefik-helm-chart
- name: bitnami
  url: https://charts.bitnami.com/bitnami
```
</p>
</details>

**Comment by mumoshu** [comment]
@elordahl Hey! I've tried to reproduce it, but had no luck so far.

For me, it works. With v0.125.3 with the below `helmfile.yaml`:

```
repositories:
- name: traefik
  url: https://containous.github.io/traefik-helm-chart
- name: bitnami
  url: https://charts.bitnami.com/bitnami
```

and just ran

```
$ helmfile repos
```

After that, I see two repos exist in `helm repo list` output.

Would you mind giving me your helmfile.yaml, rather than `repositories.yaml` so that I can fully duplicate your environment?

**Comment by elordahl** [comment]
@mumoshu i dont have a single `helmfile.yaml`, but two files in the `helmfile.d/` directory.  do you want to see each of those files, or something else?

**Comment by mumoshu** [comment]
@elodani Thanks for response! Yeah, sharing the two files for reproduction would be super helpful.

**Comment by qqshfox** [comment]
Same issue here. Set `helmBinary` in 1 of 2 helmfiles (helm2 for one, helm3 for another), and having same repo in both two helmfiles. Only one repo got added.

**Comment by elordahl** [comment]
Here are the files.  Please note that i have also unsuccessfully tried with the addition of `---` in various locations based on another thread.

helmfile.d/0.yaml:
```yaml
bases:
  - ../repositories.yaml
  - ../environments.yaml

{{ readFile "../templates.yaml" }}

values:
  - ../environments/global.yaml

releases:
- name: init
  namespace: default
  chart: ../chart/init
  <<: *default

- name: loki-stack
  namespace: mesh
  chart: ../chart/loki-stack
  <<: *default

- name: traefik
  namespace: mesh
  chart: ../chart/traefik
  <<: *default
```

helmfile.d/1.yaml:
```yaml
bases:
  - ../repositories.yaml
  - ../environments.yaml

{{ readFile "../templates.yaml" }}

values:
  - ../environments/security.yaml

releases:
- name: influxdb
  namespace: app
  disableValidation: true
  chart: ../chart/influxdb
  <<: *default
```

**Comment by Nuru** [comment]
Running into the same or similar problem in v0.125.0 through 0.125.5:

Repo defined in `repositories` but not used in `releases`, but referenced by a chart dependency, is not added by `helmfile repos` or `helmfile deps`.

**Comment by Nuru** [comment]
<details><summary>helmfile.yaml</summary>

```yaml
repositories:
  # Cloud Posse incubator repo of helm charts
  - name: "cloudposse-incubator"
    url: "https://charts.cloudposse.com/incubator/"
  # Incubator repo of official helm charts (used by monochart)
  - name: "kubernetes-incubator"
    url: "https://kubernetes-charts-incubator.storage.googleapis.com/"

releases:
  - name: 'example'
    chart: "cloudposse-incubator/monochart"
    version: "0.22.0"
    values:
      - fullnameOverride: "infrastructure-docs"
```
</details>

Expected:
```
$ helmfile version
helmfile version v0.124.0
$ helmfile deps
Adding repo cloudposse-incubator https://charts.cloudposse.com/incubator/
"cloudposse-incubator" has been added to your repositories

Adding repo kubernetes-incubator https://kubernetes-charts-incubator.storage.googleapis.com/
"kubernetes-incubator" has been added to your repositories

Updating repo
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "cloudposse-incubator" chart repository
...Successfully got an update from the "kubernetes-incubator" chart repository
Update Complete. ⎈ Happy Helming!⎈ 

Updating dependency /tmp/130468758
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "kubernetes-incubator" chart repository
...Successfully got an update from the "cloudposse-incubator" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading monochart from repo https://charts.cloudposse.com/incubator/
Deleting outdated charts

```
Got:
```text
$ helmfile version
helmfile version v0.125.5
$ helmfile deps
Adding repo cloudposse-incubator https://charts.cloudposse.com/incubator/
"cloudposse-incubator" has been added to your repositories

Updating dependency /tmp/381431663
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "cloudposse-incubator" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading monochart from repo https://charts.cloudposse.com/incubator/
Deleting outdated charts
```
