### ISSUE TITLE
Why aren't nested variables accessible?

### ISSUE THREAD

**Issue by jamesla** [roboll/helmfile#1418]
Given the following helmfile and values file:

```
#values.yaml
test: 
  nested: test

test2: test
```
```
#helmfile
releases:
- name: atlantis
  ...
  values:
  - atlantisUrl: {{ .Values.test.nested }}  (Doesn't work)
  - atlantisUrl: {{ .Values.test2 }}  (Does work)
environments:
  test:
    values:
      - values.yaml
```

Gives the following error:
```
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:19:63: executing "stringTemplate" at <.Values.test.nested>: map has no entry for key "test"
```

However using non nested values such as `{{ .Values.test2 }}` works fine.

How can I make nested values work?

**Comment by tonsV2** [comment]
I running into the same issue which I've described [here](https://stackoverflow.com/questions/63811855/using-nested-values-defined-in-environment).

I can make it work by using the `index` function but it's slightly more complicated and I feel like it ought to work without.

**Comment by mumoshu** [comment]
@jamesla @tonsV2 Hey! Sorry for the silence. I think the gist of your issues is that "double-rendering" gotcha.

Helmfile runs renders the template twice, once before for loading environment values, and another before loading entire helmfile. To load the environment values, Helmfile needs to render the template, because the original content of it:

```
#helmfile
releases:
- name: atlantis
  ...
  values:
  - atlantisUrl: {{ .Values.test.nested }}  (Doesn't work)
  - atlantisUrl: {{ .Values.test2 }}  (Does work)
environments:
  test:
    values:
      - values.yaml
```

Isn't a proper YAML. 

Obviously before loading environment values, template expressions like `{{ .Values.test.nested }}` and `{{ .Values.test2 }}` has no results. So... Helmfile does some nasty "fix" to skip parts of your template that have no results. It's a best-effort fix. It sometimes works, sometimes not. In your case, it doesn't work. I think you can see "why" it's failing in details by giving `--log-level=debug` to helmfile.

**Comment by mumoshu** [comment]
To fix it, I'd suggest explicitly telling Helmfile which part of your helmfile.yaml needs to be evaluated/loaded first, by separating "parts" of your helmfile with `---`:

```
environments:
  test:
    values:
      - values.yaml

---

releases:
- name: atlantis
  ...
  values:
  - atlantisUrl: {{ .Values.test.nested }}  (Doesn't work)
  - atlantisUrl: {{ .Values.test2 }}  (Does work)
```

**Comment by tonsV2** [comment]
@mumoshu - Thanks for the explanation.

I can fix this by simply listing my `environments` before my `releases`. No need for a separator.

I think it's a bit of a shame that the order matters but I'm well aware that we don't live in a perfect world.

**Comment by mumoshu** [comment]
> I can fix this by simply listing my environments before my releases. No need for a separator.

@tonsV2 You found it! Yes - that workaround also works in many cases 😃 Theoretically it isn't perfect though. So I'd recommend you to use `---` as the go-to option in the future.

> I think it's a bit of a shame that the order matters but I'm well aware that we don't live in a perfect world.

Yes. I'm not satisfied with the current state. It's just that I'm not yet sure what's the best/correct way to deal with this.

**Comment by tonsV2** [comment]
> > I can fix this by simply listing my environments before my releases. No need for a separator.
> 
> @tonsV2 You found it! Yes - that workaround also works in many cases  Theoretically it isn't perfect though. So I'd recommend you to use `---` as the go-to option in the future.
> 

The `---` separator doesn't work for me. Helmfile only runs if I list the `environments` first.

> > I think it's a bit of a shame that the order matters but I'm well aware that we don't live in a perfect world.
> 
> Yes. I'm not satisfied with the current state. It's just that I'm not yet sure what's the best/correct way to deal with this.

As a programmer I can relate to this but I feel the current implementation of environments is a bit limited. Being able to specify things such as kube context per environment and values per release would be really nice. Please don't take this comment the wrong way I greatly appreciate your work and support here :-)

**Comment by mozai** [comment]
I ran into this problem today, and a co-worker suggested a solution I did not expect.  Leaving it here for the next person to find.

```
environments:
  default: {values: ['junk.env.yaml']}
releases:
- name: 'autoscaler'
  chart: '{{.Values.autoscaler.chartname}}'
  version: 'latest'
```
`chart: '{{.Values.autoscaler}}'`  would evaluate to a string-serialized version of the mapping.
`chart: '{{.Values.autoscaler.chartname}}'` would error with "map has no entry for key "autoscaler" "
`chart: "{{.Values.autoscaler.chartname}}"` same result with double-quotes.
`chart: {{.Values.autoscaler.chartname}}` would give me the string I expected from the .Environment.Values map.
