### ISSUE TITLE
(bug): Its not possible to use helm built-in objects in jsonPatches and strategicMergePatches

### ISSUE THREAD

**Issue by lukasmrtvy** [roboll/helmfile#1432]
Its not possible to use helm built-in objects in jsonPatches and strategicMergePatches

```
  jsonPatches:
  - target:
      version: apps/v1
      kind: DaemonSet
      name: {{`{{ .Release.Name }}`}}
      namespace: {{`{{ .Release.Namespace }}`}}
    patch:
    - op: add
      path: /metadata/annotations/foo
      value: bar
```

```
reading document at index 1: yaml: invalid map key: map[interface {}]interface {}{".Release.Name":interface {}(nil)}
```

helmfile version v0.125.7
