### ISSUE TITLE
Question: how to use arrays in environment variables?

### ISSUE THREAD

**Issue by 4c74356b41** [roboll/helmfile#1435]
```
environments:
  default:
    values:
    - tolerations:
      - key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
        effect: NoSchedule
      - key: pool
        operator: Equal
        value: workers
        effect: NoSchedule

releases:
- name: jaeger
  chart: jaegertracing/jaeger-operator
  labels:
    app: jaeger
  values:
  - tolerations: {{ .Environment.Values.tolerations }}
```

doesn't work, it appears it treats it like a string, not like an array
