### ISSUE TITLE
Helmfile v0.125.5 fails to build dependencies

### ISSUE THREAD

**Issue by jheidbrink** [roboll/helmfile#1438]
Versions used: Helmfile 0.125.5 (0.125.4 works alright), Helm 3.2.4

When defining multiple releases for a chart with a dependency, Helmfile fails when updating the dependencies:

```
$ helmfilev0.125.5 diff

Building dependency release=release1, chart=chart-templates/example-with-dependency
Building dependency release=release2, chart=chart-templates/example-with-dependency
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "harbor" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈

Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "harbor" chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading nginx-ingress from repo https://kubernetes-charts.storage.googleapis.com
Deleting outdated charts

in ./helmfile.yaml: [command "/home/[...]/development/bin/helm" exited with non-zero status:

PATH:
  /home/[...]/development/bin/helm

ARGS:
  0: helm (4 bytes)
  1: dependency (10 bytes)
  2: build (5 bytes)
  3: chart-templates/example-with-dependency (39 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: unable to move current charts to tmp dir: link error: cannot rename chart-templates/example-with-dependency/charts to chart-templates/example-with-dependency/tmpcharts: rename chart-templates/example-with-dependency/charts chart-templates/example-with-dependency/tmpcharts: file exists

COMBINED OUTPUT:
  Hang tight while we grab the latest from your chart repositories...
  ...Successfully got an update from the "incubator" chart repository
  ...Successfully got an update from the "harbor" chart repository
  ...Successfully got an update from the "stable" chart repository
  Update Complete. ⎈Happy Helming!⎈
  Error: unable to move current charts to tmp dir: link error: cannot rename chart-templates/example-with-dependency/charts to chart-templates/example-with-dependency/tmpcharts: rename chart-templates/example-with-dependency/charts chart-templates/example-with-dependency/tmpcharts: file exists]
```

The command was run in a fresh clone of the repository.
This is the content of the files involved:

helmfile.yaml:
```
releases:
  - name: release1
    namespace: services
    chart: chart-templates/example-with-dependency
  - name: release2
    namespace: services
    chart: chart-templates/example-with-dependency
```

chart-templates/example-with-dependency/Chart.yaml:
```
apiVersion: v1
description: example-with-dependency
name: example-with-dependency
version: 0.1.0
```

chart-templates/example-with-dependency/requirements.yaml:
```
dependencies:
  - name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.28.2
```

chart-templates/example-with-dependency/requirements.lock:
```
dependencies:
- name: nginx-ingress
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.28.2
digest: sha256:ed05ca41ee36de8615e6cf86456d086ea5914473c002ea9a7885ce0b1a73d829
generated: "2020-08-26T18:17:16.678972358+02:00"
```
