### ISSUE TITLE
Enhancement: Output release name with hook logs

### ISSUE THREAD

**Issue by cdunford** [roboll/helmfile#1446]
I have several releases that have the same presync hooks; I run with the default concurrency which means several of these releases (and hence hooks) can be executing concurrently. Right now it is quite difficult to figure out which release a hook log line belongs to. It would be a great addition if the release name was included in the logging; something like:

```
hook[my-release-name|presync] logs | some meaningful log
```

**Comment by dudicoco** [comment]
@cdunford per the docs, you could print the release name in your script:
```
  hooks:
  - events: ["prepare", "cleanup"]
    showlogs: true
    command: "echo"
    args: 
    - "{{`{{.Release.Name}}`}}"
```
