### ISSUE TITLE
Defining environments in a an separate layer doesn't work

### ISSUE THREAD

**Issue by K1Hyve** [roboll/helmfile#1454]
I'm trying to use environments and layers at the same time while using a variable in my helmfile.yaml:
```yaml
bases:
- environments.yaml

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

releases:
- name: nginx-ingress
  chart: stable/nginx-ingress
  version: 1.40.2
  installed: {{ .Values.install }}
```

environments.yaml:
```yaml
environments:
  default:
    values:
    - values.yaml
```

values.yaml:
```yaml
install: "true"
```
When running `helmfile template` with version v0.127.0 I get this error:
```
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:17:23: executing "stringTemplate" at <.Values.install>: map has no entry for key "install"
```

But when I merge both files into one I don't get any errors:
```yaml
environments:
  default:
    values:
    - values.yaml

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

releases:
- name: nginx-ingress
  chart: stable/nginx-ingress
  version: 1.40.2
  installed: {{ .Values.install }}
```

Am I doing something wrong here?

**Comment by mumoshu** [comment]
@K1Hyve Thanks for using Helmfile! I'm a bit uncertain, but does it make any difference if you separated `bases` and the later part with `---`, like:


```
bases:
- environments.yaml

---

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

releases:
- name: nginx-ingress
  chart: stable/nginx-ingress
  version: 1.40.2
  installed: {{ .Values.install }}
```

?
