### ISSUE TITLE
Value templates and Secrets don't seem to work when under environment stanza

### ISSUE THREAD

**Issue by mmellin** [roboll/helmfile#1455]
Hello, thanks for creating such a great tool! I am learning how to use Helmfile environments to organize my values files. Currently I have two environments, `default` and `gpoc`.  My goal is to utilize commands such as `helmfile -e <env> [apply|destroy|sync]` so that that installation values can be customized per environment.

The problem I am facing is that when I use a `*.gotmpl` values file under an environment, the template values do not get rendered if those values come from a SOPs secret file under `secrets: `.

To simplify my `Helmfile.yaml` is setup like this:
```
environments:
  default:
    values:
      - default.yaml.gotmpl
    secrets:
      - secrets.yaml

releases:
  - name: myapp
    chart: myapp
```

The values files may have different keys/values depending on the name but contain the same templated items like:
```
accessKey: {{ .Values.ACCESS_KEY }}
```

When I run this I received the following error:
```
$ helmfile destroy
in ./helmfile.yaml: failed to read helmfile.yaml: failed to load environment values file "values.yaml.gotmpl": failed to render [values.yaml.gotmpl], because of template: stringTemplate:11:21: executing "stringTemplate" at <.Values.ACCESS_KEY>: map has no entry for key "ACCESS_KEY"
```

If I remove the `values: ` stanza from the `environments: ` and place it within the `releases: `  as below, it works fine. 
```
environments:
  default:
    secrets:
      - secrets.yaml

releases:
  - name: myapp
    chart: myapp
    values:
      - default.yaml.gotmpl
```

Is this expected behavior?

helmfile version v0.125.7
