### ISSUE TITLE
Evaluating {{ .Namespace }} in a gotmpl file no longer works since v0.126.0

### ISSUE THREAD

**Issue by mattymo** [roboll/helmfile#1464]
I have a line in one of my values files for a release like this:
```
  service:
    local:
      annotations:
        metallb.universe.tf/allow-shared-ip: {{ .Namespace }}
```
It gives this error:
```
ailed to render values files "myapp.yaml.gotmpl": failed to render [myapp.yaml.gotmpl], because of template: stringTemplate:18:48: executing "stringTemplate" at <.Namespace>: can't evaluate field Namespace in type state.releaseTemplateData
```

I checked out v0.125.0 and v0.125.9 and they don't have this issue. It must be something that changed in v0.126.0. It is also present in v0.128.0.

Maybe https://github.com/roboll/helmfile/pull/1415 is the source of the regression?
