### ISSUE TITLE
Is it Possible to Run the Same chart against multiple namespaces

### ISSUE THREAD

**Issue by jseiser** [roboll/helmfile#1479]
Basically, I need a way to create our TLS cert for nginx, in all of our namespaces in one go.

I feel like I could somehow use the kubernetes raw chart, but Im not sure how to go about looping through this, depending on the environment.

Essentially, I have the encrypted secret file, containing the certs, and a list of namespaces I would need it installed.

Any ideas?

**Comment by mumoshu** [comment]
How about ranging over the namespaces of your choice with go template?

```
values:
- namespaces:
  - foo
  - bar

---

releases:
{{ $i, $ns := range .Values.namespaces -}}
- name: yourapp
  namespace: {{ $ns }}
  chart: yourchart
{{ end -}}
```

**Comment by jseiser** [comment]
Ill have to try this, but it looks perfect.  Thank you.

I wasnt sure where I could really do the templating at in the helmfile.yaml

**Comment by jseiser** [comment]
@mumoshu no luck getting this going.

```
environments:
  qa-core:
    values:
    - certs:
        enabled: true
    - namespaces:
      - qa2
      - qa3
```

```
{{ if .Values.certs }}
{{ range $i, $ns := .Values.namespaces -}}
- name: certs
  namespace: {{ $ns }}
  chart: "kubernetes-incubator/raw"
  condition: certs.enabled
  missingFileHandler: Warn
  values:
    - template:
      - |
        apiVersion: v1
        kind: Secret
        metadata:
          name: "{{ $ns }}-nginx-epix-tls"
          namespace: {{ $ns }}
        type: kubernetes.io/tls
        data:
          tls.crt: {{ .Values.tls_cert | b64enc | quote }}
          tls.key: {{ .Values.tls_key | b64enc | quote }}
  secrets:
    - helm_vars/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}/secrets.yaml
{{ end -}}
{{ end }}
```

My secret file exists, and contains both tls_key and tls_cert

```
❯ ls -l helm_vars/qa-core/certs
total 48
-rw-r--r--  1 jseiser  staff  21647 Sep 16 08:58 secrets.yaml
```

Abridged version

```
tls_key: ENC[AES256_GCM,data:vakTa+yp4deZSyj7xfafK0q6nz1Lk45SBz2dqEbmt9XVQnY5jFrqZXoEBbVnPpnS1bdUyIQqQ58hRrHI
tls_cert: ENC[AES256_GCM,data:7zVOIRrPlaaXvcRpYprKovYDeJ17R0N3zRwWlpkd4r7MkhzvfdRSqYiACJMH1vIiqrE4uMTYi+W+1xC7
sops:
    kms:
```

Error I get

```
❯ helmfile -e qa-core diff
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:64:29: executing "stringTemplate" at <.Values.tls_cert>: can't evaluate field Values in type interface {}
```

I believe thats its telling me .Values.tls_cert doesnt exist, which I imagine means its not actually evaluating the location of secrets.yml.

**Comment by jseiser** [comment]
I got this, running without errors, but nothing actually installs.

```
environments:
  qa-core:
    values:
    - certs:
        enabled: true
    - namespaces:
      - qa2
      - qa3
    secrets:
      - helm_vars/qa-core/certs/secrets.yaml

releases:
{{ if .Values.certs.enabled }}
{{ range $i, $ns := .Values.namespaces -}}
- name: certs
  namespace: {{ $ns }}
  chart: "kubernetes-incubator/raw"
  condition: certs.enabled
  missingFileHandler: Warn
  values:
    - template:
      - |
        apiVersion: v1
        kind: Secret
        metadata:
          name: "{{ $ns }}-nginx-tls"
          namespace: {{ $ns }}
        type: kubernetes.io/tls
        data:
          tls.crt: {{ $.Values.tls_cert | b64enc | quote }}
          tls.key: {{ $.Values.tls_key | b64enc | quote }}
{{ end -}}
{{ end }}
```

Diff
```
helmfile -e qa-core diff

Decrypting secret /Users/jseiser/repos/github/helm_vars/qa-core/certs/secrets.yaml
Decrypting /Users/jseiser/repos/github/helm_vars/qa-core/certs/secrets.yaml

Comparing release=ingress-nginx, chart=ingress-nginx/ingress-nginx
Comparing release=certs, chart=kubernetes-incubator/raw
Comparing release=autoscaler, chart=autoscaler/cluster-autoscaler-chart
Comparing release=certs, chart=kubernetes-incubator/raw
Comparing release=datadog, chart=datadog/datadog
Comparing release=externaldns, chart=bitnami/external-dns

********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************

********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************
```

Apply
```
❯ helmfile -e qa-core apply
Decrypting secret /Users/jseiser/repos/github/helm_vars/qa-core/certs/secrets.yaml
Decrypting /Users/jseiser/repos/github/helm_vars/qa-core/certs/secrets.yaml

Comparing release=certs, chart=kubernetes-incubator/raw
Comparing release=certs, chart=kubernetes-incubator/raw

❯ helm list --all-namespaces
NAME         	NAMESPACE  	REVISION	UPDATED                             	STATUS  	CHART                         	APP VERSION
autoscaler   	kube-system	1       	2020-09-15 10:50:29.163224 -0400 EDT	deployed	cluster-autoscaler-chart-1.0.3	1.18.1
datadog      	kube-system	1       	2020-09-15 12:01:50.49899 -0400 EDT 	deployed	datadog-2.4.17                	7
externaldns  	kube-system	2       	2020-09-15 10:53:59.239427 -0400 EDT	deployed	external-dns-3.4.0            	0.7.3
ingress-nginx	kube-system	2       	2020-09-15 15:53:12.300823 -0400 EDT	deployed	ingress-nginx-2.16.0          	0.35.0
```
