### ISSUE TITLE
Escaping special characters breaks --set array syntax.

### ISSUE THREAD

**Issue by teejaded** [roboll/helmfile#148]
The change merged in #136 breaks setting arrays.  As per the [helm documentation](https://github.com/kubernetes/helm/blob/master/docs/using_helm.md#the-format-and-limitations-of---set):

`--set name={a, b, c}` translates to:

```yaml
name:
  - a
  - b
  - c
```

Also, as far as I can we don't absolutely need this feature because you can just add "`\\`" in front of special characters. Like this:

```yaml
    set:
    - name: scalar
      value: "item1\\,item2"
```

Example:

```yaml
--- #chart template
apiVersion: v1
kind: ConfigMap
metadata:
  name: arrtest
data:
  arrtest: |
    {{- range .Values.array }}
    {{ . }}
    {{- end}}

--- #helmfile
releases:
  - name: test
    chart: ./arrtest
    set:
    - name: array
      value: "{item1,item2}"
```

Output:

```
/usr/local/bin/helmfile_darwin_amd64_0_15_0 sync --args "--dry-run --debug"
exec: helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
exec: helm dependency update /tmp/test_chart/arrtest
No requirements found in /tmp/test_chart/arrtest/charts.
exec: helm upgrade --install --reset-values test /tmp/test_chart/arrtest --set array=\{item1\,item2\} --dry-run --debug
[debug] Created tunnel using local port: '53227'

[debug] SERVER: "127.0.0.1:53227"

Error: UPGRADE FAILED: render error in "arrtest/templates/arrtest.yaml": template: arrtest/templates/arrtest.yaml:8:21: executing "arrtest/templates/arrtest.yaml" at <.Values.array>: range can't iterate over {item1,item2}
err: exit status 1
```

**Comment by mumoshu** [comment]
@teejaded Thanks for the feedback!

You are correct. And thanks to everyone's feedback including
this PR, my understanding is now that we should avoid relying on `--set` at
all.

Helmfile recently introduced inline values in `values:` key(#139). The usage is
basically same as the former `--set`, but it doesn't suffer from this escaping issue. Would you
mind trying it?

Also, probably we should deprecate the `set:` key asap not to confuse
people?

**Comment by teejaded** [comment]
I can confirm that inline values work for my personal use cases.  Sorry for the delay, it took me a while to debug the templating I used to DRY things up.

I'm not sure how someone might replace a single index in an array without `--set`.  I'm fairly sure it's the only way since arrays replace instead of merge in yaml files.

**Comment by mumoshu** [comment]
@teejaded Good point! Thanks for pointing it out. Then, how about leaving `set:` as-is? To be extra clear, we don't need to revert #136, right?

Also, it would be nicer to have a clear documentation that says `set:` is mainly for replacing a single index in an array.

**Comment by mumoshu** [comment]
Also: Do we still need `setString:`(#119 ) to replace a single index in an array while forcing a string value? cc/ @osterman

**Comment by mumoshu** [comment]
Okay so how about:

```yaml
set:
  someArray[0]:
    - 1
    - 2
    - 3
  someArrayLikeString[0]: 1,2,3
```

to be translated to:

```console
--set someArray[0]='{1,2,3},someArrayLikeString[0]=1\,2\,3'
```

This way, users would never be forced to deal with escaping.

**Comment by mumoshu** [comment]
In #207, I decided to stick with the current `set:` configuration syntax in the meantime, to keep feature parity with helm with least effort.

So, this issue is going to be resolved by adding support for setting an array as:

```yaml
set:
- name: someArray[0]
  array:
  - 1
  - 2
  - 3
```
