### ISSUE TITLE
Default Values Not Applied with helmfile template 

### ISSUE THREAD

**Issue by darkn3rd** [roboll/helmfile#1481]
It seems that the source helm chart default `values.yaml` are not included when using `helmfile template`, so it errors with an exit status 1.  When using `helm template` with identical values, or using `helmfile template` and in repositories item, explicitly including the default `values.yaml`, the chart renders correctly.

## Steps

```bash
ENV_DIR=./envs/aks helmfile template
```

**charts.yaml.gotmpl**
```yaml
charts:
  azuredgraph:
    enabled: true
    name: dgraph
    namespace: default
    chart: {{ env "HOME" }}/workarea/charts/charts/dgraph
    version: 0.0.11
    set:
      - backups.destination: minio://minio.minio.svc:9000/dgraph-backups
      - image.tag: v20.03.4
      - backups.incremental.enabled = true
      - backups.full.enabled = true
    values:
      - ./charts/dgraph/helmfile/base.yaml.gotmpl
      - ./envs/aks/tf.dgraph_config.yaml

  azuregateway:
    enabled: true
    repository:
      name: minio
      url: https://helm.min.io/
    name: minio
    namespace: minio
    version: 6.1.2
    chart: minio/minio
    values:
      - ./envs/aks/tf.minio_config.yaml
```

**helmfile.yaml**
```yaml
helmDefaults:
  timeout: 600
  recreatePods: false
  tillerless: true
  force: true

environments:
  default:
    values:
      - ./charts.yaml.gotmpl
      - ./values.yaml
      {{- if env "ENV_DIR" }}
      - {{ requiredEnv "ENV_DIR" }}/charts.yaml.gotmpl
      - {{ requiredEnv "ENV_DIR" }}/values.yaml.gotmpl
      {{- end }}

repositories:
{{- range .Values.charts }}
{{- if and .enabled (hasKey . "repository") }}
  - name: {{ .repository.name }}
    url: {{ .repository.url }}
{{- end }}
{{- end }}

releases:
{{- range .Values.charts }}
{{- if .enabled }}
  - name: {{ .name }}
    namespace: {{ .namespace }}
    chart: {{ .chart }}
    version: "{{ . | getOrNil "version" }}"
    values:
    {{- range .values }}
      - {{ . }}
    {{- end }}
    secrets:
    {{- range . | getOrNil "secrets" }}
      - {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
```

## Expected Results

I expected this to work correctly, as it works fine with `helm` using the same exact values verbatim.   It looks like the default values are not applied somehow.

This works fine with the rendered values (copy/pasted from `helmfile --debug template`) with:
```bash
helm install test --values dgraph.yaml ~/workarea/charts/charts/dgraph/ --debug --dry-run
```

When including the default values in the chart, it also functions fine without an error:

```yaml
  azuredgraph:
    ...
    values:
      - ./charts/dgraph/helmfile/base.yaml.gotmpl
      - ./envs/aks/tf.dgraph_config.yaml
     ### ADDING THIS LINE ###
      - {{ env "HOME" }}/workarea/charts/charts/dgraph/values.yaml
```

## Actual Results

It seems the default values are omitted.  Which produces an error with the chart.

```
Adding repo minio https://helm.min.io/
"minio" has been added to your repositories

Building dependency release=dgraph, chart=/home/joaquin/workarea/charts/charts/dgraph
Templating release=dgraph, chart=/home/joaquin/workarea/charts/charts/dgraph
in ./helmfile.yaml: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: template (8 bytes)
  2: dgraph (6 bytes)
  3: /home/joaquin/workarea/charts/charts/dgraph (43 bytes)
  4: --version (9 bytes)
  5: 0.0.11 (6 bytes)
  6: --namespace (11 bytes)
  7: default (7 bytes)
  8: --values (8 bytes)
  9: /tmp/values698937119 (20 bytes)
  10: --values (8 bytes)
  11: /tmp/values890104306 (20 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: template: dgraph/templates/backups/secrets.yaml:4:64: executing "dgraph/templates/backups/secrets.yaml" at <.Values.backups.admin.auth_token>: nil pointer evaluating interface {}.auth_token
  Use --debug flag to render out invalid YAML

COMBINED OUTPUT:
  Error: template: dgraph/templates/backups/secrets.yaml:4:64: executing "dgraph/templates/backups/secrets.yaml" at <.Values.backups.admin.auth_token>: nil pointer evaluating interface {}.auth_token
  Use --debug flag to render out invalid YAML
```

**Comment by mumoshu** [comment]
@darkn3rd Thanks for reporting! Can we say that this is an upstream bug, that `helm template /abs/path/to/local/chart` doesn't pick the default values.yaml from the filesystem?

If not, it's likely due to that your values somehow overrides the default, cuz all helmfile does is just run `helm template`, as you might have seen in the logs.

Does it contain something like the below?

```
backups:
  admin:
```

You can run helmfile with --debug or run `helmfile build --embed-values` or `helmfile write-values` to see the actual values for debugging.

Also, the general best practice is to gradually change your values.yaml/helmfile.yaml by periodically checking if it runs as expected.
Big-bang testing is always not a good idea.

**Comment by darkn3rd** [comment]
Interesting.  This will override the `backups.admin`, which obviously, well is not good.  
```yaml
backups:
  admin: null
```

I was doing this:
```yaml
backups:
  admin:
    {{- if env "DGRAPH_ALPHA_ACL_ENABLED" }}
    user: {{ env "DGRAPH_BACKUPS_USER" | default "groot" }}
    password: {{ env "DGRAPH_BACKUPS_PASSWORD" | default "groot" }}
    {{- end }}
    {{- if env "DGRAPH_ALPHA_TLS_ENABLED" }}
    tls_client: {{ env "DGRAPH_ALPHA_TLS_CLIENT_NAME" | default "backupuser" }}
    {{- end }}
    {{- if env "DGRAPH_ALPHA_AUTH_TOKEN_ENABLED" }}
    auth_token: {{ env "DGRAPH_ALPHA_AUTH_TOKEN" | default "6jtXKSTL9vz5KPg" }}
    {{- end }}
```
