### ISSUE TITLE
helmfile does not seem to follow DAG as defined by `needs`

### ISSUE THREAD

**Issue by ztmr** [roboll/helmfile#1482]
I am trying to build a DAG with `needs`, like:

```yaml
releases:
  # [...a simple incubator/raw-powered bootstrap release to create some basic objects...]
  - name: cert-manager
    namespace: apps
    chart: jetstack/cert-manager
    version: ~1.0.1
    values:
      - apps/cert-manager/values.yaml.gotmpl
  - name: cert-manager-issuers
    chart: incubator/raw
    namespace: apps
    version: ~0.2.3
    needs:
      - apps/cert-manager
    values:
      - apps/cert-manager-issuers/values.yaml.gotmpl
  # [...many other "proper" releases here...]
```

But I can see all the charts being deployed at the same time and the `cert-manager-issuers` is failing at the end because the `cert-manager` has not managed to create its CRDs yet.

I have seen in another thread that `concurrency` can be passed so I was trying to set it to 1 to see what is happening but this flag does not seem to be supported anymore. I have set `atomic`, `wait` and `verify` globally but these does not seem to affect the observed behaviour in any way.

What is going wrong here? Is it a bug? I have just upgraded to the latest (v0.129.3) but no luck.
