### ISSUE TITLE
seems tpl function not working in hooks args

### ISSUE THREAD

**Issue by kupnu4x** [roboll/helmfile#1484]
helmfile.yaml
```
repositories:
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com

values:
  - domain: example.com

releases:
  - name: test
    chart: incubator/raw
    values:
      - resources:
          -
            apiVersion: extensions/v1beta1
            kind: Ingress
            metadata:
              name: test
            spec:
              rules:
                - host: {{ .Values.domain }}
                  http:
                    paths:
                      - backend:
                          serviceName: test
                          servicePort: 80
                        path: /
    hooks:
      - events: [prepare]
        showlogs: true
        command: bash
        args:
          - -c
          - echo kubectl patch ingress/test --type=json -p="{{`{{ tpl (readFile "test-patch.yaml.gotmpl") . }}`}}"

```

test-patch.yaml.gotmpl
```
- op: add
  path: /spec/tls
  value:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ .Values.domain }}-tls
```
expected behavior: rendering test-patch.yaml.gotmpl with actual values
current behavior:
```
$ helmfile template
helmfile.yaml: basePath=.
in ./helmfile.yaml: [hook[bash]: template: stringTemplate:1:51: executing "stringTemplate" at <tpl (readFile "test-patch.yaml.gotmpl") .>: error calling tpl: template: stringTemplate:5:20: executing "stringTemplate" at <.Values.domain>: map has no entry for key "Values"]
```

helmfile version v0.129.3
