### ISSUE TITLE
Templating a list of maps with the gotmpl 

### ISSUE THREAD

**Issue by yohanb** [roboll/helmfile#1496]
Hi!
I'm trying to template a list of maps with the gotmpl file and getting this error:

_Error: failed to parse /var/folders/75/bv9kxw6j64xgjm2mgy9zhxh0wngd6b/T/values797219317: error converting YAML to JSON: yaml: line 11: did not find expected ',' or ']'_

**helmfile.yaml**
```
    values:
        secrets:
          - objectName: obj1
            objectType: cert
            objectVersion: ""
          - objectName: obj2
            objectType: secret
            objectVersion: ""
          - objectName: obj3
            objectType: secret
            objectVersion: ""
```
**values.yaml.gotmpl**
`    secrets: {{ .Values.secrets }}`

Using only the Helm templating works fine so I'm guessing the problem is somewhere in helmfile's templating system.
Thanks
