### ISSUE TITLE
Feature request: go-getter chart values

### ISSUE THREAD

**Issue by philomory** [roboll/helmfile#1499]
Since #1296, it's possible to reference values files in remote git repositories. However, in my testing so far, it only seems to work with Environment values, not with indivual chart/release values. In other words, I'd like this to work:

```yaml
releases:
  - name: example
    chart: foo/bar
    values:
      - git::ssh:/git@github.com/example/foo//helm/values.yaml?ref=branch
      - git::ssh:/git@github.com/example/foo//helm/values.{{ .Environment.Name }}.yaml?ref=branch
```
When I try this, though, it just looks for a local file with with that name (e.g. `./git::ssh...`).

Do I have the syntax wrong somehow, or is this not currently supported?
