### ISSUE TITLE
"map has no entry for key" when using values in "environments"

### ISSUE THREAD

**Issue by hans-hsieh-asus** [roboll/helmfile#1501]
I'm trying to use values defined in `environments` in the release. But it shows the error `map has no entry for key`
My `helmfile.yaml`:
```yaml
repositories:
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
releases:
- name: haproxy-ingress
  namespace: haproxy-ingress
  chart: incubator/haproxy-ingress
  version: 0.0.27
  values:
  - controller:
      tcp:
        1936: "my_namespace/my-service:{{ .Values.my.port }}"
environments:
  default:
    values:
    - my:
        port: 8080
```
And I run
```bash
$ helmfile version
helmfile version v0.130.0
$ helmfile template
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:12:49: executing "stringTemplate" at <.Values.my.port>: map has no entry for key "my"
```

**Comment by mumoshu** [comment]
@hans-hsieh-asus Hey! Please try the below to avoid the chicken-and-egg problem(YAML needs to be parsed before evaluating `.Values.my.port` but to parse YAML you need to render it...

```
environments:
  default:
    values:
    - my:
        port: 8080
---
repositories:
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
releases:
- name: haproxy-ingress
  namespace: haproxy-ingress
  chart: incubator/haproxy-ingress
  version: 0.0.27
  values:
  - controller:
      tcp:
        1936: "my_namespace/my-service:{{ .Values.my.port }}"
```

**Comment by hans-hsieh-asus** [comment]
@mumoshu Thanks, it works!
But I'm curious that isn't the text below still a valid yaml?
```yaml
repositories:
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
releases:
- name: haproxy-ingress
  namespace: haproxy-ingress
  chart: incubator/haproxy-ingress
  version: 0.0.27
  values:
  - controller:
      tcp:
        1936: "my_namespace/my-service:{{ .Values.my.port }}"
environments:
  default:
    values:
    - my:
        port: 8080
```
