### ISSUE TITLE
The helmfile merges incomplete yaml and sets default values to null

### ISSUE THREAD

**Issue by j-zimnowoda** [roboll/helmfile#1502]
I have a value file `nginx-ingress.yaml` with the following structure:
```
charts:
    nginx-ingress:

```
Yes, the file above is incomplete.

I merge the `nginx-ingress.yaml` with the other files that does not specify `charts.nginx-ingress` property:
```
environments:
  aws-dev:
    values:
    # many other files
    - ../env/env/charts/oauth2-proxy.yaml
    - ../env/env/charts/nginx-ingress.yaml
    - ../env/env/charts/drone.yaml
    # many other files
```

The helmfile merges the nginx-ingress.yaml file with the other values and produces:
```
.Values.charts.nginx-ingress
```
that contains `null` value.

My question is if this is expected behaviour and why?
I personally would expect that helmfile fails while loading an incomplete yaml files.

My helmfile version is: `v0.128.1`

Thanks for any comments on that topic.
