### ISSUE TITLE
Feature Request: State/Global Secrets

### ISSUE THREAD

**Issue by philomory** [roboll/helmfile#1505]
Currently, it's possible to have state values defined both on a per-environment basis, as well as a set of "global"/"state" values defined under the top-level `values` key. Because of this feature, when some value is shared across all environments, you don't need repeat it for each environment, turning this:

```yaml
environments:
  test:
    values:
      - common.yaml
      - test.yaml
  stage:
    values:
      - common.yaml
      - stage.yaml
  prod:
    values:
      - common.yaml
      - prod.yaml
```
...into this:
```yaml
values:
  - common.yaml

environments:
  test:
    - test.yaml
  stage:
    - stage.yaml
  prod:
    - prod.yaml
```
...or even this:
```yaml
values:
  - common.yaml
  - {{.Environment.Name }}.yaml
```

With secrets, no such option is available to you; the `secrets` key is only available under an environment, not at the top level, so you can specify global default secrets, you're stuck with repeating the same filename over and over again.

One straightforward example of where this would be useful is if you have a private chart repository that needs credentials to access, credentials which are stored in a secrets file.

**Comment by eperdeme** [comment]
Don't know this is the answer to your problem but would this method work ? But we do something similar to the below to have 'global' secrets.

The issue I think you might run in to, is how your secrets are encrypted and if that key is available to decrypt the default file in all 'envs' your CI runs.

```
environments:
  default:

  templated-environment: &templated-environment
    missingFileHandler: Info
    values:
      - ../envs/default/config.yaml
      - ../envs/{{ .Environment.Name }}/config.yaml
    secrets:
     - ../envs/default/secrets.yaml
      - ../envs/{{ .Environment.Name }}/secrets.yaml

  uat:
    <<: *templated-environment

  sit:
    <<: *templated-environment

  prod:
    <<: *templated-environment
```
