### ISSUE TITLE
How to disallow users to choose `default` environment

### ISSUE THREAD

**Issue by fzyzcjy** [roboll/helmfile#1507]
Hi thanks for this excellent lib! I wonder how to prevent using default environment, but instead force the user to specify environment in `dev` and `prod`. In other words, `helmfile sync` is DISallowed, and `helmfile --environment dev sync` is OK.

Thanks!

**Comment by fzyzcjy** [comment]
OK I give it a hack:

```
environments:
  default:
    values:
      - PLEASE_DO_NOT_USE_THE_DEFAULT_ENVIRONMENT__BUT_USE_THINGS_LIKE_DEV_OR_PROD__THIS_FAKE_FILE_IS_HERE_TO_REMIND_YOU
  dev:
  prod:
```

Now when you accidentially use default env, you will see

```
in ./helmfile.yaml: failed to read helmfile.yaml: environment values file matching "PLEASE_DO_NOT_USE_THE_DEFAULT_ENVIRONMENT__BUT_USE_THINGS_LIKE_DEV_OR_PROD__THIS_FAKE_FILE_IS_HERE_TO_REMIND_YOU" does not exist in "."
```
