### ISSUE TITLE
Intermittent failures

### ISSUE THREAD

**Issue by Stono** [roboll/helmfile#1521]
We've recently upgraded from to `0.130.1` from `0.111.0` and are seeing intermittent failures particularly on helmfiles with multiple repositories.

This is the error:
```
 Building dependency release=istio-collector, chart=charts/istio-collector
 Hang tight while we grab the latest from your chart repositories...
 ...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
 	Get "http://127.0.0.1:8879/charts/index.yaml": dial tcp 127.0.0.1:8879: connect: connection refused
 ...Successfully got an update from the "aws" chart repository
 ...Successfully got an update from the "stable" chart repository
 Update Complete.
 Saving 1 charts
 Deleting outdated charts
```

The `helmfile.yaml`:
```
---
releases:
- name: istio-collector
  namespace: istio-system
  chart: ./charts/istio-collector
  values:
  - environments/values.yaml
  - environments/{{ env "HELMFILE_ENV" }}/shared/values.yaml
  - environments/{{ env "HELMFILE_ENV" }}/istio-collector/values.yaml

- name: istio-prometheus
  namespace: istio-system
  chart: ./charts/istio-prometheus
  values:
  - environments/values.yaml
  - environments/{{ env "HELMFILE_ENV" }}/shared/values.yaml
  - environments/{{ env "HELMFILE_ENV" }}/istio-prometheus/values.yaml

- name: app-prometheus
  namespace: app-metrics
  chart: ./charts/app-prometheus
  values:
  - environments/values.yaml
  - environments/{{ env "HELMFILE_ENV" }}/shared/values.yaml
  - environments/{{ env "HELMFILE_ENV" }}/app-prometheus/values.yaml

- name: prometheus-alertmanager
  namespace: istio-system
  chart: ./charts/prometheus-alertmanager
  values:
  - environments/{{ env "HELMFILE_ENV" }}/shared/values.yaml
  - environments/{{ env "HELMFILE_ENV" }}/alertmanager/values.yaml
  secrets:
  - environments/{{ env "HELMFILE_ENV" }}/alertmanager/secrets.yaml

- name: prometheus-pushgateway
  namespace: istio-system
  chart: ./charts/prometheus-pushgateway
  values:
  - environments/{{ env "HELMFILE_ENV" }}/shared/values.yaml
  set:
  - name: kubectl.tag
    value: '{{ requiredEnv "GO_DEPENDENCY_LABEL_KUBECTL" }}'

- name: kube-state-metrics
  namespace: istio-system
  chart: ./charts/exporters/kube-state-metrics

- name: helm-platform-node-exporter
  namespace: core-system
  chart: ./charts/exporters/node-exporter

- name: stackdriver
  namespace: core-system
  chart: ./charts/exporters/stackdriver
  values:
  - environments/{{ env "HELMFILE_ENV" }}/shared/values.yaml

- name: helm-prometheus-redis-exporter
  namespace: core-system
  chart: ./charts/exporters/redis-exporter
  values:
  - environments/{{ env "HELMFILE_ENV" }}/redis-exporter/values.yaml
  set:
  - name: image.tag
    value: '{{ requiredEnv "GO_DEPENDENCY_LABEL_REDIS_EXPORTER" }}'
```
