### ISSUE TITLE
NOTES.txt are not included when using jsonPatches

### ISSUE THREAD

**Issue by kyounger** [roboll/helmfile#1522]
When including a jsonPatch for a release, the NOTES in chart are not installed. Here's a simple helmfile to reproduce the issue:

```
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
releases:
- name: wp
  namespace: wp
  chart: stable/wordpress
  version: 9.0.3
  jsonPatches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: wp-wordpress
    patch:
    - op: add
      path: /spec/template/spec/initContainers
      value:
        - name: init-sleep
          image: busybox:latest
          command: ['sh', '-c', 'echo fast asleep; sleep 3']
```

Tested on both:
helmfile version v0.129.4
helmfile version v0.130.1
