### ISSUE TITLE
same release name across different namespaces doesn't work

### ISSUE THREAD

**Issue by azhang** [roboll/helmfile#1524]
In my helmfile.yaml, I have 

```yaml
releases:
- name: analytics
  namespace: staging
  chart: ./analytics

- name: analytics
  namespace: prod
  chart: ./analytics
  values:
    - values.prod.yaml
```

running `helmfile apply` returns

```
Building dependency release=analytics, chart=analytics
Building dependency release=analytics, chart=analytics

...


in ./helmfile.yaml: [command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: dependency (10 bytes)
  2: build (5 bytes)
  3: analytics (9 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: unable to move current charts to tmp dir: link error: cannot rename analytics/charts to analytics/tmpcharts: rename analytics/charts analytics/tmpcharts: file exists
```

Same error occurs if I select by namespace.

    helmfile -f helmfile.yaml -l namespace=prod apply

**Comment by azhang** [comment]
Turns out it's a different issue. 

```
- name: analytics
  namespace: staging
  chart: ./analytics

- name: asdfasdfasd
  namespace: prod
  chart: ./analytics
  values:
    - values.prod.yaml
```
fails as well, so I think it's because i'm trying to deploy the same chart in multiple namespaces?
