### ISSUE TITLE
Default namespace

### ISSUE THREAD

**Issue by zhilyaev** [roboll/helmfile#1531]
# Feature proposal 

## Current
```
releases:
  - <<: *release
    name: api
    namespace: {{ requiredEnv "HELM_NS" }}
    labels:
      name: api
      type: backend
- <<: *release
    name: frontend
    namespace: {{ requiredEnv "HELM_NS" }}
    labels:
      name: frontend
      type: frontend
```

## Proposal

```
helmDefaults:
  namespace: {{ requiredEnv "HELM_NS" }}

releases:
  - <<: *release
    name: api
    labels:
      name: api
      type: backend
```
