### ISSUE TITLE
How to feed dynamically generated values.yaml to specific release via envvar?

### ISSUE THREAD

**Issue by gobengo** [roboll/helmfile#157]
I have a script that prepares the values for my app, and I'd like to use the computed value in my helmfile.

```
releases:
- name: apps
  namespace: default
  chart: ./charts/apps
  values:
  - {{ requiredEnv "APPS_CHART_VALUES" | default "" }}
```

and then
```
APPS_CHART_VALUES="$(./values)" helmfile sync
```

But I get an error  
```
2018/05/31 13:12:56 err: failed to read ./helm/helmfile.yaml: yaml: line 91: did not find expected key
```

In a helm template I can sometimes use the 'toYaml' function, but it is not around in helmfile templates..
