### ISSUE TITLE
Set arguments under release aren't being picked up

### ISSUE THREAD

**Issue by mlagran1** [roboll/helmfile#1572]
Hey -- I'm having issues deploying with the `set` block under my release. When I deploy my chart, the `set` arguments I'm adding aren't showing up. Unfortunately, the chart only deploys *if* I pass the filebeat command as a set argument. It doesn't read the value correctly if it's set in values file.

helmfile.yaml:
```
releases:
  - name: example
    namespace: default
    chart: example
    values:
      - values.yaml.gotmpl
    set:
      - name: "filebeat.filebeatConfig"
        value: null
```
Output on failure:
```
ARGS:
  0: helm (4 bytes)
  1: upgrade (7 bytes)
  2: --install (9 bytes)
  3: --reset-values (14 bytes)
  4: example (9 bytes)
  5: example (10 bytes)
  6: --create-namespace (18 bytes)
  7: --namespace (11 bytes)
  8: default (9 bytes)
  9: --values (8 bytes)
  10: /var/folders/w9/asdfasdfasdfasdfasdfasdf (64 bytes)
  11: --history-max (13 bytes)
  12: 10 (2 bytes)
```
I should see the `--set filebeat.filebeatConfig` in those ARGS. Am I doing something wrong here?

helmfile version: v0.132.1
helm version: v3.4.0
