### ISSUE TITLE
Cross Namespace Network Policy?

### ISSUE THREAD

**Issue by jseiser** [roboll/helmfile#1577]
Just hit a roadblock, and not sure how to handle this.

Helmfile does our installs.  Something are in kube-system ( nginx ingress ), other things are in namespaces per env/app

so 

qa1/app1
qa1/app2

etc.

With helmfile creating namespaces, and those namespaces being unlabelled, I cant figure out a way, in code, to label these namespaces so they can be used in Network Policies.  I dont want to do anything by hand, because thier are currently 53 namespaces, and we add QA environments to this cluster, all the time.

**Comment by jseiser** [comment]
so i thought about using hooks, but that would require making sure everyone kube-context is correct when they run it.

**Comment by jseiser** [comment]
Example

```
helmDefaults:
  kubeContext: arn:aws:eks:us-east-1:1234:cluster/eks-qa


  hooks:
  - events: ["postsync"]
    showlogs: true
    command: "kubectl"
    args: ["--context", "{{`{{ .Release.KubeContext }}`}}", "label", "namespace",  "{{`{{ .Release.Namespace }}`}}", "app.kubernetes.io/environment={{ .Environment.Name }}"]
```

This works if my current kube-context is "arn:aws:eks:us-east-1:1234:cluster/eks-qa", fails if its not.  We actually run this from Jenkins, so that adds another layer, because we run mostly of these like this.

```
    KUBECONFIG=$(readlink -f ./${CLUSTER}.config) helmfile -f helmfile-${HELM_FILE_ENV}.yaml -e ${ENV_NAME} --selector name=${App} apply
```

Since we have multiple clusters, we generate the context on the fly.
