### ISSUE TITLE
Go Template Variable Defninitions in separate File

### ISSUE THREAD

**Issue by pjotre86** [roboll/helmfile#1579]
Hey!
I have a lot of variable definitions on top of my helmfile. I'm wondering if it's somehow possible to pull them out to a separate file and therefore include them in my helmfile. That would result in a less cluttered and easier to read helmfile.  
To be clear, the external file would really just contain variable definitions like:
`{{ $myVariable := "myValue" }}`
I tried to do it with `readFile` and `base`, but failed.  
Is it even possible?

**Comment by jduepmeier** [comment]
I  use this snippet for loading data from outside of template files:
```
{{- $data := ( readFile "data.yaml" | fromYaml ) }}
```

This makes everything in the yaml file accessable via `$data.<key>`

You can even wrap the call with `tpl` to use templating in the file:
```
{{- $data := tpl ( readFile "data.yaml" | fromYaml ) . }}
```

Example:
```yaml
# data.yaml
---
test: value
next: value2
```

```yaml
---
# helmfile.yaml

{{- $data := tpl ( readFile "data.yaml" | fromYaml ) . }}

releases:
- name: test
  chart: test
  values:
  - value: {{ $data.test }}-{{ $data.next }}
```
