### ISSUE TITLE
`createNamespace: false` still passes --create-namespace

### ISSUE THREAD

**Issue by dmmsonos** [roboll/helmfile#1585]
Helmfile `0.134.0` and `0.134.1`
Helm `3.2.1` and `3.4.1`

helmfiles/base.yaml
```yaml
helmDefaults:
  wait: false
  timeout: 600
  createNamespace: false
```

helmfiles/name/helmfile.yaml (values replaced with generic values)
```
bases:
- ../base.yaml
---
helmfiles:
- path:  ../name2/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

releases:
- name: name
  namespace: namespace-name
  chart: repo/chart-name
  version: x.y.z
  values:
  - {{ toYaml .Values | nindent 4 }}
  - name.values.yaml
```

command:
```
$ HELMFILE_HELM=1 /path/to/helmfile --allow-no-matching-release --helm-binary path/to/helm --kube-context cluster.name.com sync --set kubeContext=cluster.name.com
```

This results in the following for the first included helmfile (values replaced with generic values):
```
PATH:
  /path/to/helm

ARGS:
  0: path/to/helm (74 bytes)
  1: --kube-context (14 bytes)
  2: cluster.name.com (44 bytes)
  3: upgrade (7 bytes)
  4: --install (9 bytes)
  5: --reset-values (14 bytes)
  6: namespace-name-a (36 bytes)
  7: ../../../charts/raw (19 bytes)
  8: --version (9 bytes)
  9: 0.2.3 (5 bytes)
  10: --create-namespace (18 bytes)
  11: --kube-context (14 bytes)
  12: cluster.name.com (44 bytes)
  13: --namespace (11 bytes)
  14: namespace-name (12 bytes)
  15: --values (8 bytes)
  16: /var/folders/kk/__wzgn_x5tdblztwtjxnqsnsy0m64d/T/values272651012 (64 bytes)
  17: --set (5 bytes)
  18: kubeContext=cluster.name.com (56 bytes)
  19: --history-max (13 bytes)
  20: 10 (2 bytes)
```

Notice that `--create-namespace` is being passed despite disabling that with the base file. Explicitly setting `createNamespace: false` on the release itself also results in the same incorrect behavior. 

Reverting to our previously used Helmfile version (0.108.0) and removing `helmDefaults.createNamespace` from base reverts to not passing `--create-namespace`, probably due to it being released prior to Helm v3.2.x
