### ISSUE TITLE
Dependencies between releases?

### ISSUE THREAD

**Issue by jkroepke** [roboll/helmfile#1595]
Hi,

it is possible to define dependencies between releases?

For example, I have the cert-manager Chart and an 2nd chart to provide a ClusterIssuer (CRD of cert-manager). The 2nd chart should wait until the cert-manager Chart is installed. Otherwise the 2nd chart would fail.

**Comment by reixd** [comment]
Hi @jkroepke, I solved this type of dependency like this:

```
releases:

- name: "cert-manager"
  namespace: "cert-manager"
  chart: "jetstack/cert-manager"
  version: {{ .Values.chart_version | quote }}
  #[...]

- name: 'cert-manager-issuers'
  needs: ['cert-manager/cert-manager']
  chart: "kubernetes-incubator/raw"
  namespace: "cert-manager"
  version: {{ .Values.cert_manager_issuers_chart_version | quote }}
  #[...]
```

Take a look at the `needs` keyword. See [DAG-aware installation/deletion ordering](https://github.com/roboll/helmfile/blob/master/README.md#dag-aware-installationdeletion-ordering)
