### ISSUE TITLE
transform fails due to no kustomization.yml

### ISSUE THREAD

**Issue by jbadeau** [roboll/helmfile#1608]
Hello,

I am using

Helmfile: 0.135.0
Kustomize: 3.8.7
Helm: 3.3.0

I have tried your kustomize transformer inline example and added the following to my release:

```yaml
    transformers:
    - apiVersion: builtin
      kind: AnnotationsTransformer
      metadata:
        name: notImportantHere
      annotations:
        area: 51
        greeting: take me to your leader
      fieldSpecs:
        - path: metadata/annotations
          create: true
```

I get the error:

```
running helm template --debug=false --include-crds --output-dir C:\Users\jbadeau\AppData\Local\Temp\chartify889231816\mongodb\helmx.1.rendered -f C:\Users\jbadeau\AppData\Local\Temp\chartify889231816\mongodb\values.yaml -f C:\Users\jbadeau\AppData\Local\Temp\values139161805 --namespace todo-dev sixsense C:\Users\tk
9ax\AppData\Local\Temp\chartify889231816\mongodb
patching files: [C:\Users\jbadeau\AppData\Local\Temp\chartify889231816\mongodb\helmx.1.rendered\mongodb/templates/secrets.yaml C:\Users\jbadeau\AppData\Local\Temp\chartify889231816\mongodb\helmx.1.rendered\mongodb/templates/pvc.yaml C:\Users\jbadeau\AppData\Local\Temp\chartify889231816\mongodb\helmx.1.rendered\mong
odb/templates/svc.yaml C:\Users\jbadeau\AppData\Local\Temp\chartify889231816\mongodb\helmx.1.rendered\mongodb/templates/deployment.yaml]
generated and using kustomization.yaml:
kind: ""
apiversion: ""
resources:
- C:\Users\jbadeau\AppData\Local\Temp\chartify889231816\mongodb\helmx.1.rendered\mongodb/templates/secrets.yaml
- C:\Users\jbadeau\AppData\Local\Temp\chartify889231816\mongodb\helmx.1.rendered\mongodb/templates/pvc.yaml
- C:\Users\jbadeau\AppData\Local\Temp\chartify889231816\mongodb\helmx.1.rendered\mongodb/templates/svc.yaml
- C:\Users\jbadeau\AppData\Local\Temp\chartify889231816\mongodb\helmx.1.rendered\mongodb/templates/deployment.yaml
transformers:
- transformers\transformer.0.yaml

Generating C:\Users\jbadeau\AppData\Local\Temp\chartify889231816\mongodb\all.patched.yaml
running kustomize build C:\Users\jbadeau\AppData\Local\Temp\chartify889231816\mongodb --output C:\Users\jbadeau\AppData\Local\Temp\chartify889231816\mongodb\all.patched.yaml
Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory 'C:\Users\jbadeau\AppData\Local\Temp\kustomize-535000131\repo'

in ./helmfile.yaml: [exit status 1

COMMAND:
  kustomize build C:\Users\jbadeau\AppData\Local\Temp\chartify889231816\mongodb --output C:\Users\jbadeau\AppData\Local\Temp\chartify889231816\mongodb\all.patched.yaml

OUTPUT:
  Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory 'C:\Users\jbadeau\AppData\Local\Temp\kustomize-535000131\repo']
```
The dir C:\Users\jbadeau\AppData\Local\Temp\kustomize-535000131\repo does not exist?

Any ideas?
