### ISSUE TITLE
Support CD to development

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#161]
Say we have a chart that we have deployed to a production cluster.

```
charts:
  - name: stuff
    namespace: stuff
    chart: ../charts/stuff
    version: 1.0.0
    values:
    - ../values/stuff.yaml
```

We have this version and it's deployed and everything is great.  We have an automated process that when someone commits to master we generate semver values automatically for the next release.

The second commit after the tag would be `1.0.1-1` and the next commit would be `1.0.1-2`.  We would like to use helmfile to automatically allow support for something along the lines of `helmfile sync --devel`.

When that is specified we would install any matching pre-release version.  

Would this be something that we could consider for helmfile or would anyone have a better workflow idea to support CD using helmfile?
