### ISSUE TITLE
Using strategicMergePatches or jsonPatches with helm chart containing a CRD fails

### ISSUE THREAD

**Issue by jwilkicki** [roboll/helmfile#1611]
Hi!

I'm currently working with a helm chart to install the kiali dashboard for istio.  The kiali-server chart is available from https://kiali.org/helm-charts   It doesn't expose a way to change its service type from ClusterIP to LoadBalancer so I wanted to use kustomize to manipulate the service definition before applying it.

I've tried with these two approaches:

```yaml
- name: kiali-server
    namespace: istio-system
    disableValidation: true
    verify: false
    version: ~1.26.0
    chart: kiali/kiali-server
    needs:
      - istio-system/istio-base
      - istio-system/istio-discovery
    labels:
      mesh: istio
    values:
      - values-kiali.yaml
    set:
      - name: nameOverride
        value: kiali
      - name: fullnameOverride
        value: kiali
    jsonPatches:
    - target:
        version: v1
        kind: Service
        name: kiali
        namespace: istio-system
      patch:
        - op: replace
          path: /spec/type
          value: "LoadBalancer"
```
```yaml
- name: kiali-server
    namespace: istio-system
    disableValidation: true
    verify: false
    version: ~1.26.0
    chart: kiali/kiali-server
    needs:
      - istio-system/istio-base
      - istio-system/istio-discovery
    labels:
      mesh: istio
    values:
      - values-kiali.yaml
    set:
      - name: nameOverride
        value: kiali
      - name: fullnameOverride
        value: kiali
    strategicMergePatches:
       - apiVersion: v1
         kind: Service
         metadata:
           name: kiali
           namespace: istio-system
         spec:
           type: LoadBalancer
```
(I apologize if the yaml doesn't look indented correctly; may have gotten mangled as I copy-pasted. It's right in the actual helmfile.yaml)

As far as I can tell, the chart's output gets turned into a single yaml file that is wrapped up in a simple helm chart that is applied to the cluster.  I've checked the Service definition and the type is being set the way I want it.  However, with either approach I get the error:

```
COMBINED OUTPUT:
  Release "kiali-server" does not exist. Installing it now.
  Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
```
I think what is happening is that the CRD that defines the MonitoringDashboard type is bundled in with the rest of the resources into the single YAML file and isn't getting applied in time to satisfy other resources in the chart.  I think Helm 3 gets around this by having crds in a separate directory and applying them fully before it even attempts to apply the resources defined in the templates/ directory.  That is short-circuited with the temporary chart created by Helmfile.

If I remove the patches, the kiali-server release applies successfully. I think this is because helm gets a chance to run unmodified.

If I were doing this with just straight Helm, I think I would just use the --post-renderer switch to call kustomize and have the patches applied at a point that probably is compatible with the CRD's.  I thought maybe I could do that with hooks in Helmfile, but I'm not sure how.  

Would it make more sense for the kustomize functionality in Helmfile to use --post-renderer instead?  Or could helmfile somehow detect that there are crd's in the chart and just copy them to the temporary chart so they aren't templatized?

Thanks for any help or insight on the issue.
