### ISSUE TITLE
Unable to set env variable in the template

### ISSUE THREAD

**Issue by atcvetkov** [roboll/helmfile#1613]
I want to use the following template:

```
templates:
  default: &default
    namespace: test
    chart: stable/test-api
    values:
    - applications/values.yaml
    - applications/test-api/values.yaml
    - applications/test-api/development/{{ requiredEnv "CLUSTER_NAME" }}/values.yaml
    - deployment:
        image:
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
```

here is the release file, where I call this template:
```
{{ readFile "releases/templates.yaml.gotmpl" }}
releases:
  - name: test
    <<: *default
```
 
but helmfile is unable to process it:
```
in ./helmfile.yaml: failed to read releases/test-api.yaml.gotmpl: reading document at index 1: yaml: invalid map key: map[interface {}]interface {}{"requiredEnv \"IMAGE_TAG\" | quote":interface {}(nil)}
```

at the same time, everything works ok if I remove __{{ requiredEnv "IMAGE_TAG" | quote }}__ and just replace it with the specific value.

You can see that the template is able to work with the environment variables when I use them in the path to values files:
 __- applications/test-api/development/{{ requiredEnv "CLUSTER_NAME" }}/values.yaml__
but it fails when we try to use env variables to set/overwrite some values (like deployment.image.tag in my example)

helmfile version v0.135.0
