### ISSUE TITLE
hooks args with template expression from external file do not render

### ISSUE THREAD

**Issue by ExiaSR** [roboll/helmfile#1621]
- helmfile version v0.135.0
- helm version 3.4.1

`shared.yaml`

```yml
---
templates:
templates:
  defaultChartVersion: &defaultChartVersion
    # The default portals helm chart version:
    # You can find the latest at https://github.ibm.com/skills-network/helm-charts/blob/master/portals/Chart.yaml
    version: 5.0.0-rc.1
  defaultHooks: &defaultHooks
    hooks:
      - events: [presync]
        showlogs: true
        command: things.sh
        args: ["{{`{{.Release.Name}}`}}"]
```

`helmfile.yaml`
```yml
{{ readFile "./shared.yaml" }}

releases:
- name: stuff
  namespace: some-namespace
  chart: stuff
  <<: *defaultHooks
```

Running `helmfile sync` does not render the `{{`{{.Release.Name}}`}}` template expression

However, if we move the content of `shared.yaml` into `helmfile.yaml`, template expression in hooks args work as expected.
