### ISSUE TITLE
problem overriding boolean values in helmDefaults when layering / using bases

### ISSUE THREAD

**Issue by jhcolville** [roboll/helmfile#1624]
Hi,

I wonder if I'm hitting a similar issue to #1168 (which now is fixed) but when trying to override helmDefaults rather than environment definitions.

Here is my test case:

```
# helmfile.yaml
---
bases:
- environments.yaml
- helmdefaults.yaml

---

helmDefaults:
  verify: false
  timeout: 100

environments:
  default:
    values:
    - foo: false
# environments.yaml
---
environments:
  default:
    values:
    - foo: true
# helmdefaults.yaml
---
helmDefaults:
  verify: true
  timeout: 200
```

Rendering this I would expect `.Values.foo` to be `false`, `helmDefaults.timeout` to be `100`, and crucially, `helmDefaults.verify` to be `false`.

Instead the environment merge of boolean `foo` seems to work, the helmDefaults merge of non-boolean `timeout` seems to work, but the merge of helmDefaults boolean for `verify` incorrectly remains the base values `true` rather than the expected override `false` from helmfile.yaml:

```
helmfile  build
---
#  Source: helmfile.yaml

filepath: helmfile.yaml
helmBinary: helm
environments:
  default:
    values:
    - foo: false
bases:
- environments.yaml
- helmdefaults.yaml
helmDefaults:
  tillerless: false
  verify: true
  devel: false
  wait: false
  timeout: 100
  recreatePods: false
  force: false
  atomic: false
  skipDeps: false
  tls: false
templates: {}
missingFileHandler: ""
renderedvalues:
  foo: false
err: no releases found that matches specified selector() and environment(default), in any helmfile
```

Does this look like a bug? My use case is as stated to be able to define a base for helmDefaults and then override those defaults in state files that source that base, in this case I'm trying to override the `verify` property but I can't seem to do so.

Thanks for your tireless work on this outstanding contribution to the helm community!

Johan
