### ISSUE TITLE
Question: how to deploy additional YAML with external chart?

### ISSUE THREAD

**Issue by dalbani** [roboll/helmfile#1627]
I deploy Zalando's Postgres operator with Helmfile using the official chart available at https://github.com/zalando/postgres-operator/tree/master/charts/postgres-operator.
This chart requires an additional resource to be pushed in Kubernetes to provide configuration for the operator.
Depending on how the operator is used, it is either a `ConfigMap` or a `OperatorConfiguration` custom resource.

I may have missed something obvious in the capabilities of Helmfile, but my question is: how can I make Helmfile generate this additional resource?
I know that I can _modify_ a resource with `strategicMergePatches`, `jsonPatches` or `transformers`.
But is it possible to _add_ an additional resource (which is not present in the original chart)?

Thanks!

**Comment by dalbani** [comment]
Oh, I forget to mention: I did find a workaround by creating some kind of "wrapper chart".
With the additional resource I need under `templates/`.
And with a dependency on the upstream Postgres operator chart:
```yaml
dependencies:
  - name: postgres-operator
    repository: https://chart-repo/zalando-postgres-operator
    version: 1.5.0
```
But it's quite clumsy and verbose. That's why I'm looking for a more elegant solution.

**Comment by slamdev** [comment]
I have exactly the same use case and would like to know as well what is the "best practice" for such kind of situations?

**Comment by dalbani** [comment]
By coincidence, I've just discovered the other day a chart named `raw` where you can install Kubernetes resources:
https://github.com/helm/charts/tree/master/incubator/raw

**Comment by slamdev** [comment]
after browsing through the issues I found this two that discuss the same problem:
- https://github.com/roboll/helmfile/issues/1157
- https://github.com/roboll/helmfile/issues/1129

it seems like the the **raw** chart is indeed the best and the only way to handle such cases. it would be nice to have it mentioned in the docs somewhere.

Using a chart for such case seems like a workaround to me. Would be nice to have some native approach. For example that is a [skaffold](https://github.com/GoogleContainerTools/skaffold) way:

```yaml
apiVersion: skaffold/v2beta11
kind: Config
deploy:
  helm:
    releases:
      - name: cert-manager
        chartPath: cert-manager
        valuesFiles:
          - values.yaml
        version: v1.1.0
  kubectl:
    manifests:
      - acme-issuer.yaml
```
