### ISSUE TITLE
If using a kustomize patch, helmfile ignores all templating done with with `set:`

### ISSUE THREAD

**Issue by rdelpret** [roboll/helmfile#1628]
When a `strategicMergePatches:` block is added to this helmfile.yaml everything in the `set:` section is ignored. `extraArgs.base-role-arn` and the new image repo is missing.

```
repositories:
  - name: stable
    url: https://charts.helm.sh/stable

releases:
  - name: kube2iam
    chart: stable/kube2iam
    version: {{ requiredEnv "CHART_VERSION" }}
    values:
      - values.yaml
    set:
      - name: aws.region
        value: {{ requiredEnv "REGION" }}
      - name: extraArgs.base-role-arn
        value: "arn:aws:iam::{{ requiredEnv "AWS_ACCOUNT" }}:role/"
      - name: image.repository
        value: "test.com/kube2iam"
    wait: true
    timeout: 1000
    recreatePods: false
    force: false
    installed: true
    atomic: true
    strategicMergePatches:
    - apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: kube2iam
      spec:
        updateStrategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 3
```

**Comment by rdelpret** [comment]
with no patch, helmfile template outputs:
```
      containers:
        - name: kube2iam
          image: "617762925086.dkr.ecr.us-east-1.amazonaws.com/mosaic/mosaic/shared-services/kube2iam:0.10.9"
          imagePullPolicy: "IfNotPresent"
          args:
            - --host-interface=eni+
            - --node=$(NODE_NAME)
            - --host-ip=$(HOST_IP)
            - --iptables=true
            - --base-role-arn=arn:aws:iam::test:role/
            - --log-format=json
            - --log-level=info
            - --namespace-restrictions
            - --resolve-duplicate-cache-ips
            - --use-regional-sts-endpoint
            - --app-port=8181
            - --metrics-port=8181
            ````
            
 with a patch it outputs: 
 ```
      containers:
      - args:
        - --host-interface=eni+
        - --node=$(NODE_NAME)
        - --host-ip=$(HOST_IP)
        - --iptables=true
        - --log-format=json
        - --log-level=info
        - --namespace-restrictions
        - --resolve-duplicate-cache-ips
        - --use-regional-sts-endpoint
        - --app-port=8181
        - --metrics-port=8181
```
