### ISSUE TITLE
helm lint and list ignore enabled condition

### ISSUE THREAD

**Issue by agoloAbbas** [roboll/helmfile#1651]
`helmfile list` shows enabled while chart is disabled, same issue for `helm lint`, `helm lint` would try to lint releases with values for environments that is not enabled for.

```
helmfile version
helmfile version v0.137.0
```

```
helmfile -f helmfile.yaml -e staging list
NAME                        	NAMESPACE   	ENABLED	LABELS
kube-prometheus-stack       	xxxx  	true   	chart:kube-prometheus-stack
```

```
bases:
- ../envs/environments.yaml
releases:
- name: kube-prometheus-stack
  labels:
    chart: kube-prometheus-stack
  chart: ../charts/kube-prometheus-stack
  condition: prometheus.enabled
```
envs
```
prometheus:
  enabled: false
```
