### ISSUE TITLE
No way to ignore missing file for "values:" in helmfile

### ISSUE THREAD

**Issue by dene14** [roboll/helmfile#1653]
Hello @mumoshu !

I'm trying to set `missingFileHandler: Warn` for `values:` section of my helmfile:

```
bases:
- ../_lib/defaults.yaml.gotmpl
---
{{ readFile "../_lib/templates.yaml.gotmpl" }}
values:
- hosts: []
#  - name: "example"
#    ingressClass: "nginx"
#    port: "80"
#    targetPort: "80"
#    upstreamAddress: "192.168.0.1"
#    upstreamVhost: "www.example.com"
#    hostname: "www.example.com"
- ../../config/dbcc-external-services/{{ .Environment.Name }}/values.yaml.gotmpl        # Import env-specific list of hosts
releases:
- name: dbcc-external-services
  <<: *dbcc
  chart: incubator/raw
  namespace: miscellaneous-extra
  version: 0.2.3
```

I cannot use `Environments:` here, because it's complimentary helmfile included in a few entry-level helmfiles with different sets of environments... I've checked #548, but no solution provided for my case, or I'm doing something wrong?
Any advice is much appreciated!

**Comment by muffl0n** [comment]
I'm also stuck with this. Setting it with 
```
environmentDefaults:
  missingFileHandler: Warn
```
throws this error
```
in ./monitoring.loki.yaml: failed to read environments/common.yaml: reading document at index 1: yaml: unmarshal errors:
  line 7: field environmentDefaults not found in type state.HelmState
```

Setting it under `environments` is ignored completely
```
environments:
  common:
    missingFileHandler: Warn
```

Though using it under `releases` works:
```
releases:
  - name: loki
    namespace: loki
    chart: grafana/loki
    missingFileHandler: Warn
    values:
      - defaults/loki.yaml
      - environments/{{ .Environment.Name }}/loki.yaml
```
->
```
Adding repo grafana https://grafana.github.io/helm-charts
"grafana" has been added to your repositories

Building dependency release=loki-infrastructure, chart=charts/gcp-infrastructure
skipping missing values file matching "environments/common/loki.yaml"
Comparing release=loki, chart=grafana/loki
```

I'm using the latest release: 
```
helmfile version v0.137.0
```
