### ISSUE TITLE
repos do not work when I pass --environment 

### ISSUE THREAD

**Issue by szymonpk** [roboll/helmfile#1657]
I have a release with some environment variables

```
releases:
  - name: {{ .Values.fullnameOverride }}
    chart: some-chart
    version: v0.1.0
    values:
      - fullnameOverride: {{ .Values.fullnameOverride }}
```

And I have environments where I do not define default one:

```
environments:
  helmfile:
    values:
      - fullnameOverride: test-app-foo
```

When I try to run `helmfile repos`, I get

```
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:8:20: executing "stringTemplate" at <.Values.fullnameOverride>: map has no entry for key "fullnameOverride"
```

Ok, I add `--environment` to the mix and run `helmfile --environment helmfile repos`, and I get no output. Nothing happens, repos are not updated.

Is it a bug? Should it work like that? I do not want to add `default` environment, I have a lot of variables, it would be counterproductive. 

I am running `v0.136`.

**Comment by yurrriq** [comment]
Perhaps like #1665 you're missing `repositories`. Could you share a minimal failing example?

**Comment by szymonpk** [comment]
I pulled repositories from external (git) helmfile, everything worked fine when I used default environment (didn't pass --environment at all), I scrapped the wole idea due to multiple issues with external (nested) helmfiles.

Here is poc, two files:

helmfile.yaml

```
helmfiles:
- path: sub-helmfile.yaml
missingFileHandler: Error

releases:
  - name: vault
    namespace: vault
    chart: roboll/vault-secret-manager

environments:
  default: {}
  foo: {}
```

sub-helmfile.yaml

```
repositories:
  - name: stable
    url: https://charts.helm.sh/stable
```

and the results

```
$ helmfile --environment foo repos
$
```

```
$ helmfile repos 
Adding repo stable https://charts.helm.sh/stable
"stable" has been added to your repositories
```
