### ISSUE TITLE
chart go-getter git fetch fails if cache is empty

### ISSUE THREAD

**Issue by kirrmann** [roboll/helmfile#1660]
Hi,

latest version 0.137.0 fails to fetch a chart git repo (go-getter style). Error states that it's because the folder/cache already exists or cannot unlink directory. Running helmfile a second or third time fixes this error. Error is reproducible if I delete helmfile.d directory

helmfile:

```
releases:
  - name: test1
    namespace: test
    chart: git::https://github.com/mintel/dex-k8s-authenticator.git@charts/dex-k8s-authenticator?ref=v1.1.0
    values:
      - values1.yaml
```

First run:

```
in ./helmfile.yaml: [release "dex-kibana": fetching "git::https://github.com/mintel/dex-k8s-authenticator.git@charts/dex?ref=v1.1.0": get: error downloading 'https://github.com/mintel/dex-k8s-authenticator.git?ref=v1.1.0': /usr/local/bin/git exited with 128: fatal: could not create work tree dir '.helmfile/cache/https_github_com_mintel_dex-k8s-authenticator_git.ref=v1.1.0': File exists
```

Second run (not always but often):

```
in ./helmfile.yaml: [release "dex-kibana": fetching "git::https://github.com/mintel/dex-k8s-authenticator.git@charts/dex?ref=v1.1.0": get: error downloading 'https://github.com/mintel/dex-k8s-authenticator.git?ref=v1.1.0': /usr/local/bin/git exited with 128: fatal: unlinkat .helmfile/cache/https_github_com_mintel_dex-k8s-authenticator_git.ref=v1.1.0/.git: directory not empty]
```

If I define in releases another chart go-getter for the same git repo I hit both errors at the same run.

Subsequent runs work without issue.
