### ISSUE TITLE
Fail to fetch OCI chart if repositiory definition is in another helmfile

### ISSUE THREAD

**Issue by sereinity** [roboll/helmfile#1670]
Helmfile version: `v0.138.3`

Example structure (not a real case, just so everyone can reproduce).

Tree:
```
.
├── foo.yaml
└── helmfile.yaml
```

In `helmfile.yaml`:
```yaml
repositories:
  - name: myrepo
    url: myrepo.domain
    oci: true

helmfiles:
  - path: ./foo.yaml
```

`foo.yaml`:
```yaml
# repositories:
#   - name: myrepo
#     url: myrepo.domain
#     oci: true

releases:
  - name: myrelease
    chart: myrepo/mychart
    version: 0.1.0
```

If I run `helmfile template`, it fails

```
Templating release=keycloak, chart=myrepo/mychart
in ./helmfile.yaml: in .helmfiles[0]: in ./foo.yaml: command "/home/sereinity/.local/bin/helm" exited with non-zero status:

PATH:
  /home/sereinity/.local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: template (8 bytes)
  2: myrelease (8 bytes)
  3: myrepo/mychart (x bytes)
  4: --version (9 bytes)
  5: 0.1.0 (5 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: failed to download "myrepo/mychart" at version "0.1.0" (hint: running `helm repo update` may help)

COMBINED OUTPUT:
  Error: failed to download "myrepo/mychart" at version "0.1.0" (hint: running `helm repo update` may help)
````

If I uncomment the `repositories` definition in `foo.yaml` everything goes fine.

```
Logging in to registry
Login succeeded

Pulling myrepo.mydomain/mychart:0.1.0
0.1.0: Pulling from myrepo.mydomain/mychart
ref:     myrepo.mydomain/mychart:0.1.0
digest:  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
size:    34.1 KiB
name:    myrelease
version: 0.1.0
Status: Chart is up to date for myrepo.mydomain/mychart:0.1.0

Exporting myrepo.mydomain/mychart:0.1.0
ref:     myrepo.mydomain/mychart:0.1.0
digest:  xxxxxxxxxxxxxxxxxxxxxxx
size:    34.1 KiB
name:    myrelease
version: 0.1.0
Exported chart to /tmp/646511412/………

Templating release=myrelease, chart=/tmp/646511412/………
…
```
