### ISSUE TITLE
Error while working with Adhoc dependency and chart apiVersion: v2

### ISSUE THREAD

**Issue by and-1** [roboll/helmfile#1680]
I had tried to use adhoc dependency (incubator/raw) with coredns helm chart and i got error:
```
PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: dependency (10 bytes)
  2: build (5 bytes)
  3: /tmp/chartify968884949/kube-system-coredns-678f56459d (53 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: the lock file (Chart.lock) is out of sync with the dependencies file (Chart.yaml). Please update the dependencies

COMBINED OUTPUT:
  Error: the lock file (Chart.lock) is out of sync with the dependencies file (Chart.yaml). Please update the dependencies]
```
Chart.yaml in temp folder:
```
apiVersion: v2
name: coredns
version: 1.14.1
appVersion: 1.8.0
home: https://coredns.io
icon: https://coredns.io/images/CoreDNS_Colour_Horizontal.png
description: CoreDNS is a DNS server that chains plugins and provides Kubernetes DNS Services
keywords:
  - coredns
  - dns
  - kubedns
sources:
  - https://github.com/coredns/coredns
maintainers:
  - name: mrueg
  - name: haad
engine: gotpl
type: application
annotations:
  artifacthub.io/changes: |
    - Initial helm chart changelog
```
Chart.lock:
```
dependencies:
- name: helm-inserter
  repository: file:///root/manifests/charts/helm-inserter
  version: 0.2.5
digest: sha256:06508081fccb6b7a332389a8a52704bd48be3f2f96514c33d632ecf6bd7d636b
generated: "2021-02-12T12:34:41.15134553+03:00"
```

**Comment by mumoshu** [comment]
@and-1 Would you mind giving me an example helmfile.yaml and the version number of your helmfile binary for reproduction?

**Comment by and-1** [comment]
I've got v0.138.4 with following helmfile.yaml:
```
templates:
  values: &values
    missingFileHandler: Debug
    dependencies:
    - chart: 'charts/helm-inserter'
    #- chart: "incubator/raw"
    values:
    - values/common.values
    - values/{{`{{ (split "/" .Release.Chart)._1 }}`}}/common.values
    - values/{{`{{ (split "/" .Release.Chart)._1 }}`}}/{{`{{ .Release.Name }}`}}.values
    - values/{{`{{ (split "/" .Release.Chart)._1 }}`}}/{{`{{ .Release.Name }}`}}-{{`{{ .Environment.Name }}`}}.values

releases:
- name: coredns
  namespace: kube-system
  chart: charts/coredns
  <<: *values
```
I done a little bit patch to support local chart as adhoc dependency, but with chart from repo (incubator/raw) i got the same result. If i change chart apiVersion to v1 - everything ok.
