### ISSUE TITLE
Feature Request: Adding additional resources for helm charts with pure YAML

### ISSUE THREAD

**Issue by shibumi** [roboll/helmfile#1682]
Hi,

I am running into the following problem nearly all the time. I have a very fancy helm chart, but it is missing a few additional Kubernetes Resources to suit my cluster setup (for example additional prometheus alerting rules.. or an ingress resource if the helm chart doesn't provide this).

In the past I solved this with having a dedicated charts directory and having "addon" charts for real Helm charts. I think this way is really really incovenient. So I switched to Terraform. In Terraform I can do something like this:

```hcl
resource "helm_release" "nfs-provisioner" {
  name       = "nfs-provisioner"
  repository = "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/"
  chart      = "nfs-subdir-external-provisioner"
  version    = "3.0.0"
  namespace  = "nfs-provisioner"
  set {
    name  = "nfs.server"
    value = "10.88.10.5"
  }
  set {
    name  = "nfs.path"
    value = "/data"
  }
}

resource "kubernetes_namespace" "nfs-provisioner" {
  metadata {
    name = "nfs-provisioner"
  }
}

...<another resource.....>
```

My question would be. How can I achieve the same with Helmfile without creating addon charts for it?
What I basically want is something like this:

```yaml
 - name: bootstrap-cockroachdb
    chart: avency-library/bootstrap-cockroachdb
    version: 1.0.0
    namespace: "{{ .Values.namespace }}"
    values:
      - environments/base/bootstrap-cockroachdb.gotmpl
    additionalResources:
      - addon/my-fancy-resource.yaml
 ```

In the end I should be able to create/delete additional resources this way (even namespaces with labels, something that isn't supported right now).

I guess I can use hooks somehow and trigger a `kubectl apply` or `kubectl delete` when I run/upgrade/delete the helm chart.

But is there any more convenient way?

I never checked out kustomize and I have to admit I don't understand the kustomize example in the helmfile documentation. This is something that could be better explained.

**Comment by shibumi** [comment]
Solved this via `chartify`.

Example:
```yaml
  - name: rook-ceph
    chart: rook-release/rook-ceph
    version: 1.5.7
    namespace: rook-ceph
    needs:
      - kube-system/namespace
    # We need to wait for the rook-ceph operator
    wait: true
  - name: addons-rook-ceph
    chart: addons/rook-ceph
    namespace: rook-ceph
    # We need the rook CRDS for deploying the ceph-cluster configuration
    needs:
      - rook-ceph/rook-ceph
      - kube-system/namespace
 ```

The `addons-rook-ceph` is just a directory with plain YAML files in it. This works great :)
