### ISSUE TITLE
Helmfile generated Helm Delete commands with `installed: false` should pass in timeout settings

### ISSUE THREAD

**Issue by RyPeck** [roboll/helmfile#1683]
When setting `installed: false` for a given release - Helmfile should run a `helm delete` command that includes the `--timeout` parameter using the value set in `helmDefaults` or the release specific value.

```
helmDefaults:
  timeout: 3600

releases:
  - name: release-name
    installed: false
    wait: true
  ...
``` 

Error log - 

```
in k8s-cluster/localized_helmfile.yaml: failed processing release release-name: command "/usr/local/bin/helm" exited with non-zero status:
PATH:
  /usr/local/bin/helm
ARGS:
  0: helm (4 bytes)
  1: delete (6 bytes)
  2: release-name (22 bytes)
  3: --namespace (11 bytes)
  4: ns-name (12 bytes)
ERROR:
  exit status 1
EXIT STATUS
  1
STDERR:
  Error: timed out waiting for the condition
```

I can work together a simple helmfile and chart that demonstrates this - but hopefully easy enough fix. Though there might be a good reason for Helmfile *not* to do this that I haven't been able to find.
