### ISSUE TITLE
JsonPatches seems to ignore values provided

### ISSUE THREAD

**Issue by 4c74356b41** [roboll/helmfile#1684]
Working example:

```
- name: istio
  namespace: istio-system
  chart: istio/istio
  version: {{ .Environment.Values.istio.version }}
  labels:
    app: istio
  values:
  - 03-istio.values.yaml
 ```

to get a non working example add the following to the example above:
```
  jsonPatches:
  - target:
      version: v1
      group: apps
      kind: Service
      name: istio-ingressgateway
      namespace: istio-system
    patch:
    - op: add
      path: /spec/ports
      value:
      - name: xxx
```

the issue comes from the fact that it tries to pull all the dependencies for istio and kiali doesn't satisfy the dependencies constrains. Works fine without JsonPatch :(
