### ISSUE TITLE
Helmfile destroy command produces 403 forbidden error for oci repo

### ISSUE THREAD

**Issue by Savasw** [roboll/helmfile#1685]
**helmfile version:** v0.138.4
**Helm Version**: v3.3.4

**Overview**:
When using oci feature, helmfile destroy command tries to pull helm charts from oci repo without logging into the repo and produces following error:

```
+ helmfile -i -e non-prod --state-values-file ../helmfile_non-prod_value.yaml destroy
Pulling myociregistry.com/day-zero-resource:0.4.0
0.4.0: Pulling from myociregistry.com/day-zero-resource

in helmfile.d/53-authenticator.yaml: [release "authenticator-secret": command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: chart (5 bytes)
  2: pull (4 bytes)
  3: myociregistry.com/day-zero-resource:0.4.0 (70 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden

COMBINED OUTPUT:
  0.4.0: Pulling from myociregistry.com/day-zero-resource
  Error: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden]
  ```
  
  **Sample Helmfile:**
  ```
repositories:
  - name: platform
    url: myociregistry.com
    oci: true
    username: {{ requiredEnv "CHART_REGISTRY_USERNAME" }}
    password: {{ requiredEnv "CHART_REGISTRY_TOKEN" }}
 
releases:
  - name: authenticator-secret
    chart: platform/day-zero-resource
    version: "0.4.0"
  ```
