### ISSUE TITLE
Feature Request: Specify kubecontext via environment

### ISSUE THREAD

**Issue by shibumi** [roboll/helmfile#1689]
Hello,

I would like to propose the following feature, it should be possible to manage the kubecontext via environments.
What I am thinking of is something like this:

```yaml
environments:
    - default:
          kubeContext: kubernetes-admin@stage
    - production:
          kubeContext: kubernetes-admin@prod
    - test:
          kubeContext: minikube
```

With the above configuration it would be possible to never accidentally push something to the wrong environment and therefore overwriting the whole cluster configuration. Instead `helmfile -e production sync` would *always* sync with the production cluster.
