### ISSUE TITLE
Multiple releases with the same name

### ISSUE THREAD

**Issue by xabufr** [roboll/helmfile#1694]
HI,

I think I found a bug, here is the context:
I have a multicluster use case. For each kube cluster I want to deploy some releases, sometimes with the same configuration, sometimes with some differences.
I came from a bash script that does that, and I want to migrate to Helmfile.

Current Helm releases have the same name on each cluster.

To facilitate the deploying of releases in these clusters, I have a Helmfile that looks like this:

```yaml
{{- define "release" }}

{{ $extraValues := dict }}
{{ if hasKey $.Context.data "extraValues" }}
{{ $extraValues = deepCopy $.Context.data.extraValues }}
{{ end }}

{{ range $pop, $popData := .Context.data.pops }}
{{ if kindIs "string" $popData }}
{{ $popData = dict "ip" $popData }}
{{- end }}

{{- $popValues := dict }}
{{- if hasKey $popData "extraValues" }}
{{ $popValues = deepCopy $popData.extraValues }}
{{- end }}

{{ $size := pluck "size" $popData $.Context.data | first }}
{{ $channel := pluck "channel" $popData $.Context.data | first }}
  - name: {{ $.Context.name }}
    chart: ../channels/{{ $channel }}
    kubeContext: {{ $pop }}
    namespace: {{ $.Context.name }}
    createNamespace: true
    skipDeps: true
    labels:
      pop: {{ $pop }}
      client: {{ $.Context.name }}
    values:
      - {{ sprigGet (sprigGet $.Values.pops $pop) "values" | toJson }}
      - "../sizes/{{ $size }}.yaml"
      - proxy-out:
          defaultOrigin: {{ $.Context.data.defaultOrigin | toJson }}
        proxy-in:
          service:
            externalIPs:
              - "{{ $popData.ip }}"
      - {{ $extraValues | toJson}}
      - {{ $popValues | toJson }}
    secrets:
      - "certificates/{{ $.Context.name }}.enc.yaml"
    atomic: true
{{- end }}
{{- end }}

releases:
{{ range $name, $data := .Values.clients }}
{{ $context := (dict "name" $name "data" $data) }}
{{ $root := dict "Values" (deepCopy $.Values) | merge (dict "Context" $context) }}
{{ template "release" $root }}
{{ end }}

```

The problem I encounter is that when I try to launch a helmfile diff it seems to mix some releases specific values accross clusters. If I try to launch each specific cluster separatly using selector everything looks good. If I change the release name to make it unique accross my cluster the problem also disapear, but as I have already releases deployed this way this isn't really a good solution...

A workaround I found is to split each cluster in it's own step using the `helmfiles:` directive, but I loose concurrent deployements accross cluster...

Can you helm me ?

**Comment by xabufr** [comment]
To illustrate a little more the situation, here is the rendered values by a `helmfile build`:
```yaml
- chart: ../channels/stable #  <- please note the chart is not the same as in labels. It is incorrect here, the one in labels is correct
  atomic: true
  createNamespace: true
  name: test
  namespace: test
  labels:
    chart: cache-v1 # <- The correct chart
    client: test
    name: test
    namespace: test
    pop: pop-b
```
