### ISSUE TITLE
Add integration with helm-unittest

### ISSUE THREAD

**Issue by renehernandez** [roboll/helmfile#1713]
At work, we use [helm-unittest plugin](https://github.com/quintush/helm-unittest) as part of our CI/CD pipelines.

It would be great if we could integrate the plugin natively into `helmfile`, e.g

```yaml
releases:
  - name: release1
    namespace: default
    chart: .test-chart
    values:
      - ./values1.yaml
      - ./values2.yaml
    unit_tests:
       - ./tests
```

And this would automatically generate the final values file (like `helmfile write-values` does) and automatically invoke the `helm unittest` command.
