### ISSUE TITLE
I cannot authenticate to artifactory helm repository

### ISSUE THREAD

**Issue by adrianiacob22** [roboll/helmfile#1716]
I tried to add a JFROG Artifactory repository into helmfile, but it fails to authenticate..
I need to mention that I am using API token for artifactory auth.

I tried using variables to pickup values from environment, but I have also tried specifying the values for username and password inline.

Here is an example of how I tried:
```
repositories:
- name: dev
  url: https://na.artifactory.swg-devops.com/artifactory/hyc-cmscloud-helm-virtual
  username: my_artifactory_username
  password: my_artifactory_access_token
```
It fails with bellow unauthorized error:

```
output: 'Error: looks like "https://na.artifactory.swg-devops.com/artifactory/hyc-cmscloud-helm-virtual" is not a valid chart repository or cannot be reached: failed to fetch https://na.artifactory.swg-devops.com/artifactory/hyc-cmscloud-helm-virtual/index.yaml : 401 Unauthorized'
```
