### ISSUE TITLE
git+https repositories basic auth don't work

### ISSUE THREAD

**Issue by DnR-iData** [roboll/helmfile#1738]
Hi,

I'm trying this feature : https://github.com/roboll/helmfile/pull/154 on gitlab `git+https` repo.
And don't seems to work, here's my code :

```yaml
repositories:
  - name: xxxxxxx
    url: git+https://gitlab.com/ggggggg/sssssssss@charts?ref=master
    username: aaaaaaa
    password: bbbbbbb
```

When I run helmfile, vscode or command line ask me to enter username & password :

```bash
Adding repo xxxxxxx git+https://gitlab.com/ggggggg/sssssssss@charts?ref=master
Username for 'https://gitlab.com': aaaaaaa
Password for 'https://aaaaaaaa@gitlab.com': 
```

![image](https://user-images.githubusercontent.com/2852024/112602339-d2609580-8e13-11eb-8e5e-b614da646348.png)
![image](https://user-images.githubusercontent.com/2852024/112602356-d987a380-8e13-11eb-94d8-eaf3e546e15d.png)

If I put username & password directly in URL no problem, all works fine :

```bash
Adding repo xxxxxxx git+https://aaaaaaa:bbbbbbb@gitlab.com/ggggggg/sssssssss@charts?ref=master
"xxxxxxx" has been added to your repositories
Templating release=wwwwwwwww, chart=xxxxxxx/wwwwwwwww
```

Any suggestion / idea why username & password don't work as expected ?

Thank u.

D
