### ISSUE TITLE
Kustomize

### ISSUE THREAD

**Issue by strainovic** [roboll/helmfile#1739]
Hi,

I'm trying to apply kustomize to modify the registry of container images based on examples from https://github.com/roboll/helmfile/blob/master/docs/advanced-features.md page.

What I did:

- include values.yaml file in the release
- added images section in values.yaml and set to the proper value
- try with `helmfile template`

and nothing happened. There is no `kustomization.yaml` created. In docs I found this:

> Helmfile firstly generates a temporary kustomization.yaml that looks like:

````
bases:
- $(ABS_PATH_TO_HELMFILE_YAML}/mykustomization
````

I manage to do it with `transformers`  using builtin ImageTagTransformer but in that case, I have to create yaml manually.

What am I doing wrong?

If I want to use kustomize without transformers, do I have to use helmfile hooks and [helmify-kustomize](https://gist.github.com/mumoshu/f9d0bd98e0eb77f636f79fc2fb130690)? I found it in the Readme.md file but there is nothing about `helmify-kustomize` in the advanced-features.md file.

Thanks a lot!

**Comment by strainovic** [comment]
I tried to figure out the flow and this is what I've found:

- helmx and chartify are included in kustomize feature

Chartify is responsible for the creation of tmp kustomization.yaml file with following line of code:

```
baseFile := []byte("bases:\n- " + relPath + "\n")
```

https://github.com/variantdev/chartify/blob/88634f72ad99b62bbdc530ad3d02731dbcebdc6c/kustomize.go#L97

But, the problem is that `KustomizeBuild` will not be called if `isKustomization` is not true.

`isKustomization` will be true only if Helm Chart already contains `kustomization.yaml` file.

```
isKustomization, err := r.Exists(filepath.Join(dirOrChart, "kustomization.yaml"))
```

https://github.com/variantdev/chartify/blob/88634f72ad99b62bbdc530ad3d02731dbcebdc6c/chartify.go#L118

My assumption is that we have no control over third-party Helm Charts, thus, `kustomization.yaml` probably does not exist.

> Helmfile firstly generates a temporary kustomization.yaml that looks like:

A suppose this is not really true as Helmfile just skips to apply `kustomize` if local/remote Helm Chart does not have `kustomization.yaml` file.

Is this correct or I do not understand the flow?

Thanks

**Comment by mumoshu** [comment]
@strainovic Hey! I believe you read it almost correctly. To be clear, `chartify` do run `kustomize build` for another case- when you have any of jsonPatches, strategicMergePatches, or transformers defined, `Patch` is called which involves kustomize:

https://github.com/variantdev/chartify/blob/88634f72ad99b62bbdc530ad3d02731dbcebdc6c/chartify.go#L410-L419

> Helmfile firstly generates a temporary kustomization.yaml that looks like:

This is true for `Patch`.

https://github.com/variantdev/chartify/blob/88634f72ad99b62bbdc530ad3d02731dbcebdc6c/patch.go#L40-L43

The important point here is that kustomize is used in two ways. For generating a temporary chart from an existing kustomize project, and/or for adding patches to helm chart using kustomize.

Reading the original issue, I'm still not sure which is your goal-

- Are you trying to patch the chart by using kustomize? (But you already seem to have achieved this using `transformers`- yes, transformers triggers `Patch`)
- Are you trying to generate a temporary chart from an existing kustomize project? (Apparently no- So you don't need to struggle with the `isKustomization` part, as it's needed only when you want to generate a temporary chart from kustomize build)

> I manage to do it with transformers using builtin ImageTagTransformer but in that case, I have to create yaml manually.

I think this is important part. How did the yaml you created look like? Does it mean that you wanted to use helmfile template to declarare transformers but somehow you couldn't?

**Comment by strainovic** [comment]
@mumoshu Thank you for your reply.

My goal is to apply kustomize before rendered manifest is sent to the K8s API. I'm using my own and some third-party Helm Charts that I want to customize (inject on-fly service account, replace image server registry etc.).

The only way I managed to achieve it is with transformers key in release array of helmfile.yaml (I didn't try `jsonPatches` nor `strategicMergePatches`).

How can I use `Path` if it will not create temp charts?

Here is the content of my transformer.yaml

```yaml
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: image-tag-transformer
imageTag:
  name: "docker.io/alpine"
  newName: "private-registry.com/alpine"
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: not-important-to-example
patch: |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: not-important
  spec:
    template:
      spec:
        serviceAccountName: serviceaccount
target:
  kind: Deployment
```

Thanks!

**Comment by mumoshu** [comment]
@strainovic Hey! Thanks for response.

> My goal is to apply kustomize before rendered manifest is sent to the K8s API

Yes, That's how `strategicMergePatches`, `jsonPatches`, and `transformers` work.

> I'm using my own and some third-party Helm Charts that I want to customize (inject on-fly service account, replace image server registry etc.).

Seems to be a valid use case!

I believe the below transformer:

```
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: not-important-to-example
patch: |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: not-important
  spec:
    template:
      spec:
        serviceAccountName: serviceaccount
target:
  kind: Deployment
```

can be rewritten in strategicMergePatches like:

```
releases:
- name: myapp
  strategicMergePatches:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: not-important
      namespace: the-namespace
    spec:
      template:
        spec:
          serviceAccountName: serviceaccount
```

Regarding `ImageTagTransformer`, can you just use your original chart's ability to customize the container image repo/tag in that case? Assuming it supports the standard `image.repository` and `image.tag` values, I'd write something like:

```
releases:
- name: myapp
  values:
  - image:
      repository: private-registry.com/alpine
      tag: whatever
  strategicMergePatches:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: not-important
      namespace: the-namespace
    spec:
      template:
        spec:
          serviceAccountName: serviceaccount
```
