### ISSUE TITLE
Reading .Values in helmfile doesn't work when bases specified

### ISSUE THREAD

**Issue by Sh1ftry** [roboll/helmfile#1740]
I have such `helmfile.yaml`
```yaml
releases:
  - name: release
    namespace: namespace
    chart: repo/chart
    version: {{ .Values.chartVersion }}
    values:
      - "./{{ .Environment.Name }}/values.yaml"
environments:
  dev:
    values:
      - chartVersion: 0.3.0
bases:
  - ../helmfile.yaml
```
running `helmfile --environment dev diff` gives
```
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:5:23: executing "stringTemplate" at <.Values.chartVersion>: map has no entry for key "chartVersion"
```
If I use `{{ readFile "../helmfile.yaml" }}` instead of
```yaml
bases:
  - ../helmfile.yaml
```
it works fine. The `../helmfile.yaml` looks like this
```yaml
repositories:
  - name: repo
    url: s3://some-s3-bucket/stable

helmDefaults:
  wait: true
  timeout: 300
  recreatePods: true
```

**Comment by itscaro** [comment]
The reason is that : helmfile.yaml is rendered before base layering is processed. Base layers are merged with helmfile to produce final values.

- render helmfile
- render base files
- merge helmfile into base files

The documentation is not clear about this. I do not know if this is a bug or it's by design.

Final words, render helmfile with bases is not possible yet.

**Comment by mumoshu** [comment]
Yeah so this is kind of a chicken-and-egg problem. Helmfile needs to render helmfile.yaml template to load environment values but it needs values to render the template... For such cases, you could defer the template rendering to happen only after the values are loaded. Using `---`, yours could probably be:

```
environments:
  dev:
    values:
      - chartVersion: 0.3.0

---

releases:
  - name: release
    namespace: namespace
    chart: repo/chart
    version: {{ .Values.chartVersion }}
    values:
      - "./{{ .Environment.Name }}/values.yaml"
bases:
  - ../helmfile.yaml
```
