### ISSUE TITLE
hooks not honouring '--quiet' and cause output to stderr even when showLogs=false

### ISSUE THREAD

**Issue by Morriz** [roboll/helmfile#1742]
Hi, when I use a hook in a `template` command it always seems to list the name of the helmfile to stderr like so:

```
helmfile-init.yaml: basePath=.
```

I believe that to be an error as I provide `--quiet` and in the hook set `shoLog: false`.

The fact that this output goes to stderr confuses me also.

The command I use:
```
helmfile --quiet -f helmfile.tpl/helmfile-init.yaml template --skip-deps
```

The hook section of the release:
```yaml
      - events: [prepare]
        showlogs: false
        command: ../bin/somescript.sh
        args: ["{{ .Release.Name }}"]
```
