### ISSUE TITLE
Using `forceNamespace` feature breaks `helmfile repos` command

### ISSUE THREAD

**Issue by pstackle** [roboll/helmfile#1752]
It seems like using the `forceNamespace` field is causing the `helmfile repos` command to break. In the below examples, where I call `helmfile repos`, when the `forceNamespace` field is used, the chart is attempted to be fetched and then fails because the repo is unknown. If I do not use the `forceNamespace` field, then no chart is attempted to be fetched and the configured repo is added. 

Given the description of the `repos` command:
> sync repositories from state file (helm repo add && helm repo update)

I would not have expected it to have tried to fetch the chart.

---
Example using `forceNamespace` where it fails:
```
❯ cat helmfile-not-working.yaml
repositories:
  - name: center
    url: https://repo.chartcenter.io

releases:
  - name: prometheus-blackbox-exporter
    chart: center/prometheus-community/prometheus-blackbox-exporter
    namespace: monitoring
    forceNamespace: monitoring
    version: 4.10.2
```

```
❯ docker run -it --rm -v "$(pwd)":/workspace -w /workspace quay.io/roboll/helmfile:helm3-v0.138.7 helmfile -f helmfile-not-working.yaml --debug repos
processing file "helmfile-not-working.yaml" in directory "."
first-pass rendering starting for "helmfile-not-working.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
first-pass rendering output of "helmfile-not-working.yaml.part.0":
 0: repositories:
 1:   - name: center
 2:     url: https://repo.chartcenter.io
 3:
 4: releases:
 5:   - name: prometheus-blackbox-exporter
 6:     chart: center/prometheus-community/prometheus-blackbox-exporter
 7:     namespace: monitoring
 8:     forceNamespace: monitoring
 9:     version: 4.10.2
10:

first-pass produced: &{default map[] map[]}
first-pass rendering result of "helmfile-not-working.yaml.part.0": {default map[] map[]}
vals:
map[]
defaultVals:[]
second-pass rendering result of "helmfile-not-working.yaml.part.0":
 0: repositories:
 1:   - name: center
 2:     url: https://repo.chartcenter.io
 3:
 4: releases:
 5:   - name: prometheus-blackbox-exporter
 6:     chart: center/prometheus-community/prometheus-blackbox-exporter
 7:     namespace: monitoring
 8:     forceNamespace: monitoring
 9:     version: 4.10.2
10:

merged environment: &{default map[] map[]}
helm:XVlBz> v3.5.0+g32c2223
running helm fetch center/prometheus-community/prometheus-blackbox-exporter --untar -d /tmp/chartify305946437/monitoring-prometheus-blackbox-exporter-57d6f6fcdd --version 4.10.2
Error: repo center not found

err: [exit status 1

COMMAND:
  helm fetch center/prometheus-community/prometheus-blackbox-exporter --untar -d /tmp/chartify305946437/monitoring-prometheus-blackbox-exporter-57d6f6fcdd --version 4.10.2

OUTPUT:
  Error: repo center not found]
in ./helmfile-not-working.yaml: [exit status 1

COMMAND:
  helm fetch center/prometheus-community/prometheus-blackbox-exporter --untar -d /tmp/chartify305946437/monitoring-prometheus-blackbox-exporter-57d6f6fcdd --version 4.10.2

OUTPUT:
  Error: repo center not found]
```

---

Example without `forceNamespace` where it works:
```
❯ cat helmfile-without-force.yaml
repositories:
  - name: center
    url: https://repo.chartcenter.io

releases:
  - name: prometheus-blackbox-exporter
    chart: center/prometheus-community/prometheus-blackbox-exporter
    namespace: monitoring
    version: 4.10.2
```

```
❯ docker run -it --rm -v "$(pwd)":/workspace -w /workspace quay.io/roboll/helmfile:helm3-v0.138.7 helmfile -f helmfile-without-force.yaml --debug repos
processing file "helmfile-without-force.yaml" in directory "."
first-pass rendering starting for "helmfile-without-force.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
first-pass rendering output of "helmfile-without-force.yaml.part.0":
 0: repositories:
 1:   - name: center
 2:     url: https://repo.chartcenter.io
 3:
 4: releases:
 5:   - name: prometheus-blackbox-exporter
 6:     chart: center/prometheus-community/prometheus-blackbox-exporter
 7:     namespace: monitoring
 8:     version: 4.10.2
 9:

first-pass produced: &{default map[] map[]}
first-pass rendering result of "helmfile-without-force.yaml.part.0": {default map[] map[]}
vals:
map[]
defaultVals:[]
second-pass rendering result of "helmfile-without-force.yaml.part.0":
 0: repositories:
 1:   - name: center
 2:     url: https://repo.chartcenter.io
 3:
 4: releases:
 5:   - name: prometheus-blackbox-exporter
 6:     chart: center/prometheus-community/prometheus-blackbox-exporter
 7:     namespace: monitoring
 8:     version: 4.10.2
 9:

merged environment: &{default map[] map[]}
helm:XVlBz> v3.5.0+g32c2223
Adding repo center https://repo.chartcenter.io
exec: helm repo add center https://repo.chartcenter.io --force-update --debug
helm:gbaiC> "center" has been added to your repositories
"center" has been added to your repositories
```
