### ISSUE TITLE
Helmfile hooks should have `allowFailure` option

### ISSUE THREAD

**Issue by unacceptable** [roboll/helmfile#1753]
Problem statement
-------------------
I ran into this weird edge case with my Minecraft in K8s deployment when deploying with helmfile and a custom chart that I wrote.  I need a `presync` hook to scale down my deployment to 0 because of how the PVC is configured (can't attach RWO PVC to multiple pods) to update, but when I delete the chart and create a new installation (to start a new Minecraft world) I have to comment out the hook (since the deployment doesn't exist).

I definitely realize that I should do an RWX PVC and I will do that with a tool like Longhorn, OpenEBS, Rook, etc. sometime in the future.

I doubt that I explained that very well, please lemme know how I can clarify that if it's unclear.

Helmfile
--------
``` yaml
# DOMAIN=blah.example.com helmfile -f helmfile.yaml diff

repositories:
- name: aztek
  url: https://charts.aztek.io

releases:
- name: {{ requiredEnv "DOMAIN" | replace "." "-" }}
  namespace: minecraft
  chart: aztek/minecraft
  version: v0.1.0
  # scale deployment to 0 for rwo pvc
  hooks:
  - events: ["presync"]
    showlogs: true
    command: "kubectl"
    args: ['scale', 'deployment', '-n', 'minecraft', '{{ requiredEnv "DOMAIN" | replace "." "-" }}-minecraft', '--replicas=0']
  values:
  - service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: {{ requiredEnv "DOMAIN"  }}
    minecraft:
      env:
        MINECRAFT_EULA: true
        MINECRAFT_OPS: <REDACTED>
    resources:
      limits:
        cpu: 2000m
        memory: 4096Mi
      requests:
        cpu: 1000m
        memory: 2048Mi
  wait: true
  timeout: 300
```

**Comment by mumoshu** [comment]
@unacceptable Hey! Thanks for reporting. A bit hesitant to say but a workaround would be to use something like the below:

```
  hooks:
  - events: ["presync"]
    showlogs: true
    command: "bash"
    args: ['-c', 'alias k="kubectl -n Minecraft"; name={{ requiredEnv "DOMAIN" | replace "." "-" }}-minecraft; k get deploy $name 2>&1 /dev/null && k scale deploy $name --replicas=0']
```

`allowFailure` seems like a good addition to Helmfile so please let me keep this as the issue to track addition of it.

I'd also appreciate your response if the above workaround doesn't work for you for some reason 😃
