### ISSUE TITLE
Local dependencies not working in release definition

### ISSUE THREAD

**Issue by marianogg9** [roboll/helmfile#1762]
Hi all.
I am facing an issue with local `dependencies` declaration part of a `release`, as follows:

```yaml
releases:
- name: foo_rel
   namespace: foo_ns
   chart: foo_example
   dependencies:
   - name: dep_chart
      repository: file://../path/to/dep_chart_dir
      version: 1.0.1
```

The above will throw this error when trying to render/diff templates:

```text
in helmfile.d/helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line 12: field name not found in type state.Dependency
  line 13: field repository not found in type state.Dependency
exit status 1
```

But if declared in `Charts.yaml` within `foo_example` directory, it works just fine and loads/renders `dep_chart` along with `foo_example` as expected.

```yaml
dependencies:
- name: dep_chart
   repository: file://../path/to/dep_chart_dir
   version: 1.0.1
```

Thank you.

**Comment by mumoshu** [comment]
@marianogg9 Hey! Please see https://github.com/variantdev/chartify/commit/c9b4508f8a490d167eac6c96032d049eda0728a9 and #1765.

I was pretty confused initially but I managed to make it work.

First of all, Helmfile's `dependencies` syntax is a bit different from Helm Chart.yaml's. In helmfile's, the only available fields are:

- alias (optional)
- chart (required)
- version (optional)

Until now `chart` only supported the `REMOTE_REPO/CHART` where `REMOTE_REPO` must be defined in `repositories` section of your helmfiel.yaml like:

```
repositories:
- name: REMOTE_REPO
  url: https://example.com/charts
```

Neither repositories[].url nor releases[].dependencies[].chart had support for local file URLs(with a `file://` scheme)

#1765 enhanced the latter, `repositories[].dependencies[].chart` to just accept the path to local chart.

So,

```
releases:
- name: foo
  chart: ./path/to/foo
  dependencies:
  - chart: ./path/to/bar
```

results in Helmfile internally generating Chart.yaml containing:

```
dependencies:
- alias: bar
  name: bar
  chart: file:///abs/path/to/bar
```

@marianogg9 WDYT? Does this resolve your issue?

**Comment by marianogg9** [comment]
Thank you @mumoshu, that looks good!

**Comment by mumoshu** [comment]
@marianogg9 Thanks for confirming! #1765 has been merged with a brand new documentation about adding ad-hoc dendendencies https://github.com/roboll/helmfile/blob/master/docs/advanced-features.md#adding-dependencies-without-forking-the-chart

**Comment by eigood** [comment]
This is still an issue, as the dependencies need a proper version  constraint, but with a local kustomization  chart, that doesn't work.

**Comment by arielweinberger** [comment]
Confirming this does not work

```
releases:
- name: aws-load-balancer-controller
  chart: eks/aws-load-balancer-controller
  version: 1.4.3
  namespace: kube-system
  dependencies:
  - chart: ./crds
  values:
  - values.yaml.gotmpl
```

Getting the following error:
```
in ./helmfile.yaml: in .helmfiles[0]: in releases/aws-load-balancer-controller/helmfile.yaml: [exit status 1

COMMAND:
  helm dependency up /var/folders/9_/hb_cskt16clgqf0380d96shw0000gn/T/chartify978043108/kube-system/aws-load-balancer-controller/aws-load-balancer-controller

OUTPUT:
  Error: dependency "crds" has an invalid version/constraint format: improper constraint: 
```
