### ISSUE TITLE
Helmfile lint fails/panics

### ISSUE THREAD

**Issue by steffakasid** [roboll/helmfile#1773]
Hi,

I'm trying out helmfile lint (never did before) but it panics with the following error.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1e6d59e]

goroutine 1 [running]:
github.com/roboll/helmfile/pkg/state.(*Storage).normalizePath(0xc0006a0280, 0xc0001f8000, 0x54f, 0xc0001f8000, 0x54f)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/state/storage.go:89 +0x3e
github.com/roboll/helmfile/pkg/state.(*HelmState).generateVanillaValuesFiles(0xc0000f1900, 0xc0002cc000, 0xc0006a0330, 0xc000090000, 0x0, 0xc0006a0380, 0x104fb65)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/state/state.go:2551 +0x1b9
github.com/roboll/helmfile/pkg/state.(*HelmState).generateValuesFiles(0xc0000f1900, 0x26e70c8, 0xc000450840, 0xc0002cc000, 0x0, 0xc0005fc400, 0x0, 0x2, 0x1e6e227, 0xc000401cc0)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/state/state.go:2636 +0x4d
github.com/roboll/helmfile/pkg/state.(*HelmState).namespaceAndValuesFlags(0xc0000f1900, 0x26e70c8, 0xc000450840, 0xc0002cc000, 0x0, 0x300, 0xc0002cc000, 0x101679b, 0xc000090000, 0x0, ...)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/state/state.go:2659 +0xb1
github.com/roboll/helmfile/pkg/state.(*HelmState).flagsForLint(0xc0000f1900, 0x26e70c8, 0xc000450840, 0xc0002cc000, 0x0, 0xc000250620, 0x73, 0x74c4f40, 0x0, 0x100f2db, ...)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/state/state.go:2391 +0x74
github.com/roboll/helmfile/pkg/state.(*HelmState).LintReleases(0xc0000f1900, 0x26e70c8, 0xc000450840, 0xc000250e90, 0x1, 0x1, 0xc000250630, 0x1, 0x1, 0x0, ...)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/state/state.go:1460 +0x29d
github.com/roboll/helmfile/pkg/app.(*Run).Lint(0xc0001a04e0, 0x26d4c58, 0xc000250f60, 0xc351629445c8d501, 0xc30000c0006a0bd0, 0x3)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/run.go:204 +0x278
github.com/roboll/helmfile/pkg/app.(*App).Lint.func1.1()
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/app.go:281 +0x45
github.com/roboll/helmfile/pkg/app.(*Run).withPreparedCharts(0xc0001a04e0, 0x2235e38, 0x4, 0x1, 0xc0006a0e00, 0x0, 0x0)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/run.go:83 +0x39c
github.com/roboll/helmfile/pkg/app.(*App).Lint.func1(0xc0001a04e0, 0xc0001a04e0, 0x0, 0x0, 0x0)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/app.go:276 +0x135
github.com/roboll/helmfile/pkg/app.(*App).ForEachState.func1(0xc0000f1900, 0xc0006a10d8, 0xc0006a0fa0, 0xc0006a1230, 0xc0006a10a0)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/app.go:815 +0xd1
github.com/roboll/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport.func1.1(0xc0000f1900, 0xc0006a0fa0, 0xc0006a1040, 0xc0006a1240)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/app.go:924 +0x2f
github.com/roboll/helmfile/pkg/app.processFilteredReleases(0xc0000f1900, 0x26e70c8, 0xc000450840, 0xc0006a15a0, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/app.go:973 +0x67e
github.com/roboll/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport.func1(0xc0000f1900, 0xc0000f1900, 0x0, 0x0, 0xc0000f1180)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/app.go:923 +0x8f
github.com/roboll/helmfile/pkg/app.(*App).visitStates.func1(0x7ffeefbff02c, 0xc, 0xc000686940, 0x38, 0x0, 0x0)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/app.go:763 +0x82d
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles.func1(0x0, 0x0)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/app.go:596 +0xa2
github.com/roboll/helmfile/pkg/app.(*App).within(0xc0003d3680, 0x2234b8e, 0x1, 0xc00061dc18, 0xc00061dbd8, 0x2)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/app.go:538 +0x629
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles(0xc0003d3680, 0x7ffeefbff02c, 0xc, 0x2f58df8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/app.go:590 +0x2ee
github.com/roboll/helmfile/pkg/app.(*App).visitStates(0xc0003d3680, 0x7ffeefbff02c, 0xc, 0x2f58df8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/app.go:675 +0x125
github.com/roboll/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport(0xc0003d3680, 0x7ffeefbff02c, 0xc, 0xc00061df30, 0xc00061df98, 0x1, 0x1, 0x1, 0xc00003ec40)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/app.go:930 +0x4fd
github.com/roboll/helmfile/pkg/app.(*App).ForEachState(0xc0003d3680, 0xc00061dfa0, 0xc00061df98, 0x1, 0x1, 0x221cb40, 0xc000250f60)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/app.go:811 +0xb2
github.com/roboll/helmfile/pkg/app.(*App).Lint(0xc0003d3680, 0x26d4c58, 0xc000250f60, 0xc000250f60, 0xc0005d9730)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/pkg/app/app.go:274 +0xa9
main.main.func7(0xc0003d3680, 0xc0001189a0, 0x0, 0xc000250f10, 0x0)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/main.go:327 +0x6d
main.action.func1(0xc0001189a0, 0xc000401e00, 0xc000401ef0)
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/main.go:793 +0xdc
github.com/urfave/cli.HandleAction(0x1fcdd20, 0xc0002506c0, 0xc0001189a0, 0xc0001189a0, 0x0)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0x105
github.com/urfave/cli.Command.Run(0x2235e38, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x226812a, 0x27, 0x0, ...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x579
github.com/urfave/cli.(*App).Run(0xc0004a6a80, 0xc0000ca000, 0x9, 0x9, 0x0, 0x0)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x808
main.main()
        /private/tmp/helmfile-20210309-71266-5p6zw9/helmfile-0.138.7/main.go:564 +0x4105
```

Any idea why this happens?

My helmfile version is v0.138.7

Regards
Steffen

**Comment by mumoshu** [comment]
@steffakasid Hey! Thanks for reporting. This seems to be coming from https://github.com/roboll/helmfile/blame/master/pkg/state/storage.go#L89, where Helmfile is trying to parse the file path to chart/values/etc as a URL.

Would you mind sharing your helmfile.yaml for reproduction?

**Comment by steffakasid** [comment]
Hi,

yes I can share it but the chart I use is an internal one which I can't share. Basically it enhances/bundles Prometheus, Alertmanager, Grafana and some additions (Parent Chart with a lot dependencies). Here is the file:

```
---
repositories:
  - name: maas
    url: https://bahnhub.tech.rz.db.de/artifactory/observability-helm-release-virtual/

environments:
  non-prod:
    values:
      - ./values-non-prod.yml
      - installKubeMetrics: false
  prod:
    values:
      - ./values.yml
      - installKubeMetrics: true

helmDefaults:
  createNamespace: false
  cleanupOnFail: true

releases:
  - name: {{ requiredEnv "CHART_NAME" }}
    chart: ./maas-openshift
    version: 1.16.0
    namespace: {{ requiredEnv "MONITORING_NAMESPACE"}}
    values:
      - {{ .Values }}
      - global:
          clusterUrlSuffix: {{ requiredEnv "APPLICATION_URL_SUFFIX_PROD" }}
        alertmanager:
          fullnameOverride: {{ requiredEnv "ALERTMANAGER_CONTAINER_NAME" }}
        prometheus:
          fullnameOverride: {{ requiredEnv "PROMETHEUS_CONTAINER_NAME" }}
        grafana:
          fullnameOverride: {{ requiredEnv "GRAFANA_CONTAINER_NAME"}}
          sidecar:
            dashboards:
              label: {{ requiredEnv "GRAFANA_CONTAINER_NAME" }}
          env:
            no_proxy: {{ requiredEnv "PROMETHEUS_CONTAINER_NAME" }}
        kube-state-metrics:
          fullnameOverride: {{ requiredEnv "KUBE_STATE_METRICS_CONTAINER_NAME" }}
        gitlab-ci-pipelines-exporter:
          config:
            gitlab:
              token: {{ requiredEnv "GITLAB_TOKEN" }}
{{ range .Values.scrapeAdditionalNamespaces }}
  - name: {{ requiredEnv "CHART_NAME" }}
    chart: ./maas-openshift
    version: 1.16.0
    namespace: {{ . }}
    values:
      - ./values-other-ns.yml
      - kube-state-metrics:
          enabled: {{ $.Values.installKubeMetrics }}
          fullnameOverride: {{ requiredEnv "KUBE_STATE_METRICS_CONTAINER_NAME" }}
      - allow-maas-scraping:
          allowScrapingFromNamespace: {{ requiredEnv "MONITORING_NAMESPACE"}}
          allowScrapingFromServiceAccount: prometheus{{ requiredEnv "COMMIT_REF_SLUG" }}
          networkPolicy:
            namePrefix: allow-traffic-from{{ requiredEnv "COMMIT_REF_SLUG" }}
          rbac:
            namePrefix: namespace-reader-from{{ requiredEnv "COMMIT_REF_SLUG" }}
{{ end }}

```

So this error relates to files from the chart (templates, values etc.)? I'll try to investigate on my side as well. What I did: I don't reference the chart directly as I want to add some custom dashboards for Grafana. Therefore I run `helm pull --repo ${HELM_CHART_REPO} --version ${HELM_CHART_VERSION} --untar --untardir . maas-openshift` before executing Helmfile (done within GitLab CI). Maybe this helps.

Regards
Steffen
