### ISSUE TITLE
destroy not reversing the order of releases

### ISSUE THREAD

**Issue by bseenu** [roboll/helmfile#1775]
helmfile.yaml

```
repositories:
  - name: cert-manager
    url: https://charts.jetstack.io
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
  - name: kiali
    url: https://kiali.org/helm-charts
  - name: autoscaler
    url: https://kubernetes.github.io/autoscaler
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: elastic
    url: https://helm.elastic.co

helmDefaults:
  cleanupOnFail: true
  # wait for k8s resources via --wait. (default false), 300 seconds
  wait: true


releases:
  - name: cert-manager
    namespace: test
    chart: cert-manager/cert-manager
    version: v1.2.0
  - name: metrics-server
    namespace: test
    needs:
      - test/cert-manager
    chart: bitnami/metrics-server
    version: 5.8.0
  - name: prometheus
    needs:
      - test/cert-manager
    chart: prometheus/prometheus
    namespace: test
    version: 13.3.1
  - name: autoscaler
    namespace: test
    needs:
      - test/prometheus
    chart: autoscaler/cluster-autoscaler
    version: 9.4.0
  - name: prometheus-adapter
    namespace: test
    needs:
      - test/autoscaler
    chart: prometheus/prometheus-adapter
    version: 2.12.0
  - name: grafana
    namespace: test
    needs:
      - test/prometheus-adapter
    chart: grafana/grafana
    version: 6.6.3
  - name: external-dns
    namespace: test
    needs:
      - test/grafana
    chart: bitnami/external-dns
    version: 4.7.0
  - name: logstash
    namespace: test
    needs:
      - test/external-dns
    chart: elastic/logstash
    version: 7.11.1
```

Install order

```
processing 7 groups of releases in this order:
GROUP RELEASES
1     test/cert-manager
2     test/metrics-server, test/prometheus
3     test/autoscaler
4     test/prometheus-adapter
5     test/grafana
6     test/external-dns
7     test/logstash

```

uninstall order

```
processing 7 groups of releases in this order:
GROUP RELEASES
1     test/cert-manager
2     test/external-dns
3     test/grafana
4     test/prometheus-adapter
5     test/autoscaler
6     test/prometheus, test/metrics-server
7     test/logstash
```

```
bash-3.2$ helmfile --version
helmfile version v0.138.7
```

**Comment by mumoshu** [comment]
@bseenu Hey! Thanks for reporting. Unfortunately I had no luck reproducing this. What was the exact `helmfile destroy` command you tried?

**Comment by ldemailly** [comment]
I can confirm on a fresh 1.18 cluster

$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
$ helmfile version
helmfile version v0.138.7


same output


```
processing 7 groups of releases in this order:
GROUP RELEASES
1     test/cert-manager
2     test/external-dns
3     test/grafana
4     test/prometheus-adapter
5     test/autoscaler
6     test/prometheus, test/metrics-server
7     test/logstash

processing releases in group 1/7: test/cert-manager
Deleting cert-manager
```
which is unexpected

**Comment by ldemailly** [comment]
I reproduced in a simpler (and faster to test) way:

helmfile
```
repositories:
  - name: envoy
    url: https://slamdev.github.io/helm-charts


releases:
  - name: envoy1
    namespace: test
    chart: envoy/envoy
  - name: envoy2
    namespace: test
    chart: envoy/envoy
    needs:
      - test/envoy1
  - name: envoy3
    namespace: test
    chart: envoy/envoy
    needs:
      - test/envoy2
  - name: envoy4
    namespace: test
    chart: envoy/envoy
    needs:
      - test/envoy3
  - name: envoy5
    namespace: test
    chart: envoy/envoy
    needs:
      - test/envoy4
  - name: envoy6
    namespace: test
    chart: envoy/envoy
    needs:
      - test/envoy5
  - name: envoy7
    namespace: test
    chart: envoy/envoy
    needs:
      - test/envoy6
```

```
$ helmfile --debug apply --skip-diff-on-install
processing 7 groups of releases in this order:
GROUP RELEASES
1     test/envoy1
2     test/envoy2
3     test/envoy3
4     test/envoy4
5     test/envoy5
6     test/envoy6
7     test/envoy7
```
^ as expected
```
$ helmfile --debug destroy
processing 7 groups of releases in this order:
GROUP RELEASES
1     test/envoy1
2     test/envoy6
3     test/envoy5
4     test/envoy4
5     test/envoy3
6     test/envoy2
7     test/envoy7
[...]
DELETED RELEASES:
NAME
envoy1
envoy6
envoy5
envoy4
envoy3
envoy2
envoy7
```
(Big!) BUG :-) 


Note: it works with a dependency chain of 6 somehow and starts breaking at 7
