### ISSUE TITLE
Failed to render chart with strategicMergePatches/jsonPatches and CRDs

### ISSUE THREAD

**Issue by azkore** [roboll/helmfile#1778]
When using `helmfile apply` with

```
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
releases:
  - name: test
    namespace: test
    chart: prometheus-community/kube-prometheus-stack
    version: ~14.4.0
    strategicMergePatches:
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: test-grafana
          namespace: test
        data:
          bar: BAR
```

I get an error:

STDERR:
  Error: Failed to render chart: exit status 1: Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "alertmanagerconfigs.monitoring.coreos.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "test"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "test"
  Error: plugin "diff" exited with error

The same helmfile applies with any issue when there are no `strategicMergePatches` present
The same is reproducible for `jsonPatches`

helmfile version v0.138.7, just built from master
