### ISSUE TITLE
support multi version deployment to enable canary release

### ISSUE THREAD

**Issue by kameshchauhan** [roboll/helmfile#1780]
Currently helmfile support definition of multiple versions of the same chart by way of duplicating the release block of the chart as below:
```
releases: 
    - name: hello-world
      version: 1.3.5
    - name: hello-world
      version: 1.3.6
    - name: hello-world
      version: 1.3.7
```

The above approach works fine but  consider a helmfile having deployment of 100s of microservices...adds a lot of unwanted duplicated lines just to allow for `multiple version value` 

Instead, the Helmfile solution should be enhanced to support the same requirement as below, which is more cleaner solution e.g.
```
releases: 
    - name: hello-world
      version: 
         - 1.3.5
         - 1.3.6
         - 1.3.7
 ```

**Comment by mumoshu** [comment]
@kameshchauhan Hey! This is actually an interesting idea. I once wondered if we could eliminate a lot of go template `range` loops OR the manual repetition like you've shown in helmfile.yaml with the kind of "matrix" of release values that is consumed by helmfile to duplicate releases.

That said, I'd rather use the term `matrix` for something like this:

```
releases: 
- name: hello-world
  matrix: 
    version:
    - 1.3.5
    - 1.3.6
    - 1.3.7
```

Then the next question is- how would you like to name your release after the `version` derived from the matrix?

Would you like to explicitly tell helmfile how it should incorporate the derived value into the release name, like below?

```
releases:
# I thought helm release name nor K8s resource name allowed the use of `.` so we'd probably need to replace it...
- name: hello-world-{{` .Release.matrix.version | replace ".", "-"`}}
```

**Comment by kameshchauhan** [comment]
@mumoshu 
1. Don't know what value does the use of word "matrix" would add? Matrix looks just redundent...and `version` can/should be renamed to `versions` ...but that is not the very important thing
2. I think the name of the release in the helmfile can stay as is e.g. "hello-world" but the related deployment yaml should have name value replacement with version number as you mentioned above
3. BTW...K8S allows the use of `.` in the deployment as well as pod name...i am already using this naming convention ..one of the pod in my app is e.g. `xyz-service-1.8.0-85c7c6dd6c-pwx9s`

**Comment by mumoshu** [comment]
@kameshchauhan Hey! Thanks for the reply.

Regarding the point 1, I'd choose `matrix` because I can easily imagine people would start asking for similar usecases to this, like you want to duplicate releases based on image tags, envvars, arbitrary helm values, etc.

The point 2 sounds good from a users perspective but not possible from Helmfile's perspective. Helmfile does not always parse every K8s resources manifest YAML or Helm chart contents, but your request requires that.

About the last point- good to know! Thanks for sharing.

**Comment by kameshchauhan** [comment]
@mumoshu  oh yeah..this reminds me the extended use-case which in fact was something like this
```
releases: 
- name: hello-world
  matrix: 
    versions:
    - 1.3.5
         - env : dev
         - portfolioRelease : v0.1.3 
    - 1.3.6
         - key1 : value1
         - key2 : value2
    - 1.3.7
         - key1 : value1
         - key2 : value2
  ```

**Comment by andrewnazarov** [comment]
Sorry for the interruption. Probably I'm missing something I didn't get how this is supported?
```
releases: 
    - name: hello-world
      version: 1.3.5
    - name: hello-world
      version: 1.3.6
    - name: hello-world
      version: 1.3.7
```

Shouldn't names be unique within a namespace? If it's something new and `helmfile` now can handle multiple releases with the same name where I could read about the behaviour?
