### ISSUE TITLE
Using reserved words in labels only select the first release

### ISSUE THREAD

**Issue by vsimon** [roboll/helmfile#1781]
Consider a simple example with 3 labels in 2 releases:

```
repositories:
- name: datawire
  url: https://www.getambassador.io
- name: incubator
  url: https://charts.helm.sh/incubator
releases:
- name: ambassador
  namespace: ambassador
  labels:
    chart: ambassador
    namespace: ambassador
    foo: bar
  chart: datawire/ambassador
  version: 6.6.2
- name: raw
  namespace: ambassador
  labels:
    chart: ambassador
    namespace: ambassador
    foo: bar
  chart: incubator/raw
  version: 0.2.5
```

Running `helmfile -l namespace=ambassador diff`
both releases are selected in the diff

Running `helmfile -l foo=bar diff`
both releases are selected in the diff

However, running `helmfile -l chart=ambassador diff`
only the first release is selected in the diff. This is on v0.138.6.

From SweetOps Slack #helmfile:
mumoshu  2 minutes ago
Ah, that makes sense! Probably we'd better enhance the docs to note about reserved labels and make it a validation error when you've tried to override a reserved label
