### ISSUE TITLE
KubeContext does not fallback to the default value

### ISSUE THREAD

**Issue by katsew** [roboll/helmfile#1782]
Hi,

I try to generate manifests by running like:

```
helmfile --kube-context testing --namespace dev template \
  --output-dir ./output \
  --output-dir-template '{{ .OutputDir }}/{{ .Release.KubeContext }}/{{ .Release.Namespace }}/{{ .Release.Name }}'
```

However, the path `{{ .Release.KubeContext }}` is missing like `./output//dev/foo`, 
while I expected that the path becomes like `./output/testing/dev/foo`.
It seems that when kubeContext is missing in a release, it does not fallback to the default kubeContext provided by `--kube-context`.

For instance, 

```
releases:
- name: "foo"
  chart: ../../charts/foo
  kubeContext: testing
- name: "bar"
  chart: ../../charts/bar
```

in this helmfile, when I run the command above, the path for each release becomes like these.

- foo: `./output/testing/dev/foo`
- bar: `./output//dev/bar`
