### ISSUE TITLE
helmfile errors on valid yaml for vault configuration property:`externalConfig.policies.rules`

### ISSUE THREAD

**Issue by notjames** [roboll/helmfile#1798]
From vault chart documentation to show official documentation about the format of the policy:
https://github.com/banzaicloud/bank-vaults/blob/master/charts/vault/values.yaml

(note that the link above is an example to the way the property is formatted. We use the vault operator, so what I'm actually attempting to do is decrypt a configuration manifest which uses the exact same property.)

example yaml:
```
 0: releases:
 1:   - name: vault-operator
 2:     namespace: vault
 3:     createNamespace: true
 4:     labels:
 5:       app: vault-operator
 6:     chart: banzaicloud-stable/vault-operator
...
...
 56:         externalConfig:
 57:             policies:
 58:             -   name: allow_secrets
 59:                 rules: 'path "secret/*" { capabilities = ["create", "read", "update", "delete", "list"] }'. <<== fails
 60:             auth:
 61:            -   type: kubernetes
...
...
```

Causes the error (during template; not tested with any other functionality)
```
err: failed to read helmfile.yaml: reading document at index 1: yaml: line 68: did not find expected ',' or ']'
in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: line 68: did not find expected ',' or ']'
```

Noteworthy: in this setup, the file containing this is a `secrets.yaml` file getting decrypted by SOPS (helm secrets). To test, I removed that property from the file and was able to successfully `template` the project. When I returned that property back to the file, `helmfile` barfed again.

The manifest is valid yaml (yamllint passes it) but `helmfile` fails on it.

**Comment by mumoshu** [comment]
@notjames Hey! Sorry but this looks too vague to be investigated. At glance this is just a error in your values so there should be no helmfile fault. Can you give me a simple helmfile.yaml that ideally has only one release (bank-vaults?) that can reproduce the issue?

**Comment by notjames** [comment]
@mumoshu I've updated the comment. Hopefully it makes better sense.

**Comment by mumoshu** [comment]
Sorry but no. That basically says your values is incorrect. But I cant verify that as you have no example for reproduction..

**Comment by notjames** [comment]
```
vaultconfig: |-                                                                                                                                                                                                                                                                                                                                          
    kind: Vault                                                                                                                                                                                                                                                                                                                                          
      name: vault                                                                                                                                                                                                                                                                                                                                        
      namespace: vault                                                                                                                                                                                                                                                                                                                                   
    spec:
      size: 3
      image: vault:1.6.0
      bankVaultsImage: banzaicloud/bank-vaults:latest
      vaultPodSpec:
          priorityClassName: system-node-critical
      serviceAccount: vault
      serviceType: ClusterIP
      volumeClaimTemplates:
      -   metadata:
              name: vault-raft
          spec:
              storageClassName: persistent
              accessModes:
              - ReadWriteOnce
              volumeMode: Filesystem
              resources:
                  requests:
                      storage: 1Gi
      volumeMounts:
      -   name: vault-raft
          mountPath: /vault/file
      veleroEnabled: true
      caNamespaces:
      - '*'
      unsealConfig:
          options:
              preFlightChecks: true
          kubernetes:
              secretnamespace: vault
      config:
          storage:
              raft:
                  path: /vault/file
          listener:
              tcp:
                  address: 0.0.0.0:8200
                  tls_cert_file: /vault/tls/server.crt
                  tls_key_file: /vault/tls/server.key
          api_addr: https://vault.vault.svc.cluster.local:8200
          cluster_addr: https://vault:8201
          ui: true
      statsdDisabled: true
      resources:
          vault:
              limits:
                  cpu: 2
                  memory: 1Gi
              requests:
                  cpu: 1
                  memory: 512Mi
      externalConfig:
          policies:
          -   name: allow_secrets
              rules: 'path "secret/*" { capabilities = ["create", "read", "update", "delete", "list"] }'
          auth:
         -   type: kubernetes
              roles:
              -   name: default
                  bound_service_account_names:
         secrets:
          -   path: secret
              type: kv
              description: General secrets.
              options:
                  version: 2
      vaultEnvsConfig:
      -   name: VAULT_LOG_LEVEL
          value: debug
      labels:
          app: vault
```

There's an example...

**Comment by mumoshu** [comment]
What's `vaultconfig`?  Why isn't `externalConfig` under [the`vault` key](https://github.com/banzaicloud/bank-vaults/blob/master/charts/vault/values.yaml#L100) as the default values file, but `spec` in your example?

**Comment by mumoshu** [comment]
Sorry, but this shouldn't really be discussed in GitHub issue. Let's use Slack and ask for the community for this kind of general guidance on how to use helm and helmfile.

**Comment by mumoshu** [comment]
Well anyway, the yaml snippet you pointed does look like a valid yaml. You can verify that with e.g.

```
releases:
- name: myapp
  chart: incubator/raw
  values:
  - externalConfig:
        policies:
        -   name: allow_secrets
            rules: 'path "secret/*" { capabilities = ["create", "read", "update", "delete", "list"] }'
```

and seeing it doesn't fail while parsing yaml. So you're very likely messed up with environment values or go template.

That's why I'm asking for a whole example for reproduction.

**Comment by mumoshu** [comment]
helmfile.yaml

```
values:
- values.yaml

---

releases:
 - name: vault-operator
   namespace: vault
   createNamespace: true
   labels:
     app: vault-operator
   chart: banzaicloud-stable/vault-operator
   values:
   - {{ .Values.vaultconfig | nindent 4 }}

```

values.yaml

```
vaultconfig: |-                                                                                                                                                                                                                                                                                                                                          
    kind: Vault                                                                                                                                                                                                                                                                                                                                          
    name: vault                                                                                                                                                                                                                                                                                                                                        
    namespace: vault                                                                                                                                                                                                                                                                                                                                   
    spec:
      size: 3
      image: vault:1.6.0
      bankVaultsImage: banzaicloud/bank-vaults:latest
      vaultPodSpec:
          priorityClassName: system-node-critical
      serviceAccount: vault
      serviceType: ClusterIP
      volumeClaimTemplates:
      -   metadata:
              name: vault-raft
          spec:
              storageClassName: persistent
              accessModes:
              - ReadWriteOnce
              volumeMode: Filesystem
              resources:
                  requests:
                      storage: 1Gi
      volumeMounts:
      -   name: vault-raft
          mountPath: /vault/file
      veleroEnabled: true
      caNamespaces:
      - '*'
      unsealConfig:
          options:
              preFlightChecks: true
          kubernetes:
              secretnamespace: vault
      config:
          storage:
              raft:
                  path: /vault/file
          listener:
              tcp:
                  address: 0.0.0.0:8200
                  tls_cert_file: /vault/tls/server.crt
                  tls_key_file: /vault/tls/server.key
          api_addr: https://vault.vault.svc.cluster.local:8200
          cluster_addr: https://vault:8201
          ui: true
      statsdDisabled: true
      resources:
          vault:
              limits:
                  cpu: 2
                  memory: 1Gi
              requests:
                  cpu: 1
                  memory: 512Mi
      externalConfig:
          policies:
          -   name: allow_secrets
              rules: 'path "secret/*" { capabilities = ["create", "read", "update", "delete", "list"] }'
          auth:
          -   type: kubernetes
              roles:
              -   name: default
                  bound_service_account_names:
          secrets:
          -   path: secret
              type: kv
              description: General secrets.
              options:
                  version: 2
      vaultEnvsConfig:
      -   name: VAULT_LOG_LEVEL
          value: debug
      labels:
          app: vault

```

I've fixed several yaml errors in the yaml embedded `vaultconfig` in the yaml data you've shared, assuming it's a helmfile values file.

`helmfile template` runs successfully now. Is this what you tried/wanted?
