### ISSUE TITLE
Specific version

### ISSUE THREAD

**Issue by omri-shaiko** [roboll/helmfile#18]
Is it possible to install a specific version of a chart?

**Comment by omri-shaiko** [comment]
Found it
```
charts:
  - name: mysql
    namespace: dev
    chart: stable/mysql
    version: 0.2.9
```
