### ISSUE TITLE
postinstall hook

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#1805]
Just wanted to have a dedicated issue for this.

Would anyone use it if Helmfile added a new `postinstall` hook?

It has been originally proposed by @cdunford in #1291. Althought I thought it was great, I had overwhelmed by all the works I had in Helmfile and forgot to discuss/implementing it.

**Comment by sandep121** [comment]
It will be nice to have postinstall in helmfile. I have a use case where I have to add a label to the namespace after the helm chart is installed, postinstall will come in handy in this case.

**Comment by anovikov-el** [comment]
I would be good for Helmfile to support both preinstall and postinstall. Our use case is when we need to copy a K8S secret from one namespace/release to another namespace/release (in k8s you can share secrets across the namespaces), so it should be executed before installation of the second one.

**Comment by anovikov-el** [comment]
any update here?

**Comment by mitom** [comment]
Another use-case for pre-install is that some managed k8s providers (e.g. EKS) provision clusters with some things pre-configured, like the default storage class. When we want to deploy a chart that provides other options and want to configure the default, we have to somehow unset the original default first (or in some cases, to just delete the existing one so we can move it into helm).

**Comment by philicious** [comment]
I'd like to also express interested in `preinstall` hook in particular and also all helm hooks in general.

Use-Case: Similar to deleting default storage-class, I want/need to delete the default AWS-CNI before I can sync the custom configured one

**Comment by rabbagliettiandrea** [comment]
+1, it would be super useful!

**Comment by tomislater** [comment]
Yeah; in our case it also would be great. For example we install `karpenter` via helm chart, but for `NodePool` objects we have just yamls:

```
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - apply
          - --namespace
          - '{{`{{ .Release.Namespace }}`}}'
          - -f
          - values/{{ .Environment.Name }}/karpenter-nodes/*.yaml
```

Now we need to use `postsync` to install them and `helmfile sync`, because `helmfile apply` does not trigger this for some reason 🤔
