### ISSUE TITLE
how to use environments values  in helm chart templates？

### ISSUE THREAD

**Issue by qianzhang613** [roboll/helmfile#1807]
the environments: env/acp.yaml
```
clb: 1.1.1.1
```
the helmfile:

```
environments:
  default:
    values:
      - ../env/acp.yaml
releases:
  ...
```
the sercet file in helm templates:
```
apiVersion: v1
kind: Secret
metadata:
  name: clb-secret
  namespace: default
type: Opaque
data:
  #CLB
  CLB: {{ $.Values.clb |quote  }}
```
now the  template output is :
```
apiVersion: v1
kind: Secret
metadata:
  name: ti-secret
  namespace: default
type: Opaque
data:
  #CLB
  CLB:
```
so how can i use clb values which define at `env/acp.yaml` in helm templates? 

many thanks!

**Comment by mumoshu** [comment]
Helmfile values and helm chart values are totally unrelated concepts :) You can only access Helm charts that are passed to `releases[].values` in your helm chart template.

**Comment by qianzhang613** [comment]
@mumoshu  eh.  how can i foward all values define at environments by  helm chart value.yaml to make valid in helm charts templates? i need define some public vaules that used by all the helm charts.

thank you

**Comment by mumoshu** [comment]
@qianzhang613 Hey! I would do that like this:

```
environments:
  default:
    values:
      - ../env/acp.yaml

---

releases:
- name: myapp
  chart: some/chart
  values:
  - {{ .Values | toYaml | nindent 4 }}
```

I'd also recommend reading #1808 by @vavdoshka, and appreciate it very much if you could submit some pull request to add this information in a similar place and manner!

I'm too used to using and writing helmfile and in most cases I have no idea why everything isn't obvious. So, contributions to the documentation are always welcomed ☺️
