### ISSUE TITLE
Remplate is not read in correctly unless there's a comment at the top

### ISSUE THREAD

**Issue by Temikus** [roboll/helmfile#1811]
I'm not entirely sure why this occurs but I do want to understand what's happening here. It seems that the `readFile` macro is not working the same way depending on file content.

Observe the following release:

```
releases:
  - name: falcosidekick
    namespace: falco
    chart: falcosecurity/falcosidekick
    version: 0.3.3
    values:
      - podAnnotations:
        {{ readFile "templates/datadog_annotations.yaml" | indent 10 }}
      - replicaCount: 3
      - webui:
          enabled: true
```

With this template, everything works fine:

```
```
