### ISSUE TITLE
evalsymlink failure chartify temp file reported as "no such file or directory" despite existing when using jsonPatches for adhoc

### ISSUE THREAD

**Issue by slalom25** [roboll/helmfile#1820]
` helm version > Version:"v3.4.2"`
`kustomize version > Version:kustomize/v4.0.5`
`helmfile version >  v0.138.7`

helmfile_deployment.yaml:

```
                 ***

releases:
  - name: "coredns"            
    version: {{.Environment.Values | default (env "COREDNS_VERSION") | default ""}}   
    <<: *chartmuseum                                                                   
    jsonPatches:                                                                   
    - target:                                                                              
         group: apps                                                                         
         version: v1                                                                        
         kind: Deployment                                                                    
         name: coredns-coredns                                                           
      patch:                                                                               
        - op: add                                                                            
           path: /metadata/labels/hello                                                     
           value: "world"
        
                 ***      
```     

Error:

```
generated and using kustomization.yaml:                                             
kind: ""                                                                           
apiversion: ""                                                                      
resources:                                                                          
- templates/service-metrics.yaml                                                   
- templates/service.yaml                                                            
- templates/deployment.yaml                                                         
- templates/configmap.yaml                                                          
- templates/clusterrole.yaml                                                        
- templates/clusterrolebinding.yaml                                                 
patchesJson6902:                                                                    
- target:                                                                               
     group: apps                                                                         
     kind: Deployment                                                              
     name: coredns-coredns                                                          
     version: v1                                                                                                                                    
   path: jsonpatches/patch.0.yaml     

Generating /tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns/all.patched.yaml                                                                                   running kustomize build /tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns --output /tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns/all.patched.yaml   

Error: evalsymlink failure on '/tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns' : lstat /tmp/chartify251993839: no such file or directory                                                                                                         
Removed /tmp/helmfile653553803/coredns-coredns-values-5b9b657487                    
Removed /tmp/helmfile110841454/coredns-coredns-values-5b769778b7                    
Removed /tmp/helmfile474989301/coredns-coredns-values-8474674f96                    
Removed /tmp/helmfile115401680/coredns-coredns-values-58cc6c684                     
err: [exit status 1                                                                                                                                                     

COMMAND:                                                                              
kustomize build /tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns --output /tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns/all.patched.yaml                                                                                             

OUTPUT:                                                                               
Error: evalsymlink failure on '/tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns' : lstat /tmp/chartify251993839: no such file or directory]                  
in ./helmfile_deployment.yaml: [exit status 1                                                                                                                           

COMMAND:                                                                              
kustomize build /tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns --output /tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns/all.patched.yaml                                                                                             

OUTPUT:                                                                               
Error: evalsymlink failure on '/tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns' : lstat /tmp/chartify251993839: no such file or directory]  

```     

But

```
ls /tmp/chartify251993839

coredns-coredns-6c6cdfbdd5   
```     

Indicating that the missing file / directory is in-fact present...
