### ISSUE TITLE
Unable to install rabbitmq release from the first attempt

### ISSUE THREAD

**Issue by acidos** [roboll/helmfile#1837]
My helmfile looks like this.

```
releases:
- name: prometheus-stack
  namespace: monitoring
  disableValidation: true
  chart: prometheus-community/kube-prometheus-stack
  values:
    - values/kube-prometheus-stack-values.yaml
  secrets:
    - secrets/promstack-secrets.yaml
  set:
    - name: grafana.dashboards.default.blackbox-dashboard.json
      file: dashboards/blackbox.json
- name: promtail
  namespace: monitoring
  chart: grafana/promtail
  version: 3.5.0
  values:
    - values/promtail-values.yaml
- name: loki
  namespace: monitoring
  chart: grafana/loki
  version: 2.5.0
  values:
    - values/loki-values.yaml
- name: blackbox
  namespace: monitoring
  chart: prometheus-community/prometheus-blackbox-exporter
  version: 4.11.0
  values:
    - values/blackbox-values.yaml
- name: rabbitmq
  namespace: rabbitmq
  chart: bitnami/rabbitmq
  disableValidation: true
  version: 8.11.9
  values:
    - values/rabbitmq-values.yaml
  secrets:
    - secrets/rabbitmq-secrets.yaml
```

When I run it first time, I always get an error:

```
Release "rabbitmq" does not exist. Installing it now.
  Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```

On the second run, it works fine. 

helmfile: v0.139.0
diff:   	3.1.3  	

I specifically added `disableValidation`, but it seems doesn't work for rabbitmq chart for some reason.
