### ISSUE TITLE
Pass remote values.yaml to release

### ISSUE THREAD

**Issue by alvgarvilla** [roboll/helmfile#1838]
Currently is possible to pass environment values as remote files:

```
environments:
  default:
    values:
    - git::<values_file_location>.yaml
```
But I cannot do the same for the release values:

```
releases:
  - name: my-release
    chart: repo/my-chart
    namespace: my-namespace
    missingFileHandler: Error
    values:
     - git::<values_file_location>.yaml
```
It fails because it cannot find the file:
` failed processing release my-release: values file matching "git::<values_file_location>.yaml" does not exist in "."`

Is there any way of passing remote files in the release values?
