### ISSUE TITLE
How to deal with helm errors due to invalid/missing provenance

### ISSUE THREAD

**Issue by apurvdeodhar** [roboll/helmfile#1850]
# Tool set versions
- kubectl
```bash
Client Version: v1.19.3
Server Version: v1.19.2
```

- helm
```bash
v3.5.3+g041ce5a
```

- helmfile
```bash
helmfile version v0.138.7
```

- minikube
```bash
minikube version: v1.14.2
```

# Configuration files
- helmfile.yaml
```yaml
---
repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: elastic
    url: https://helm.elastic.co
  - name: incubator
    url: https://charts.helm.sh/incubator

helmDefaults:
  kubeContext: 'minikube'
  cleanupOnFail: true
  verify: true
  timeout: 600
  createNamespace: true

commonLabels:
  name: elk-stack-test

releases:
  - name: logs-elasticsearch
    namespace: logs
    chart: elastic/elasticsearch
    version: 7.12.1
    missingFileHandler: Warn
#    values:
#      - elasticsearch/values.yaml
#    secrets:
#      - elasticsearch/secrets.yaml
    verify: true
    timeout: 600
    atomic: true
    cleanupOnFail: true
    disableValidation: true
    disableValidationOnInstall: true

  - name: logs-logstash
    namespace: logs
    chart: elastic/logstash
    version: 7.12.1
    missingFileHandler: Warn
#    values:
#      - logstash/values.yaml
#    secrets:
#      - logstash/secrets.yaml
    verify: true
    timeout: 600
    atomic: true
    cleanupOnFail: true
    disableValidation: true
    disableValidationOnInstall: true

  - name: logs-kibana
    namespace: logs
    chart: elastic/kibana
    version: 7.12.1
    missingFileHandler: Warn
#    values:
#      - kibana/values.yaml
#    secrets:
#      - kibana/secrets.yaml
    verify: true
    timeout: 600
    atomic: true
    cleanupOnFail: true
    disableValidation: true
    disableValidationOnInstall: true

  - name: logs-filebeat
    namespace: logs
    chart: elastic/filebeat
    version: 7.12.1
    missingFileHandler: Warn
#    values:
#      - filebeat/values.yaml
#    secrets:
#      - filebeat/secrets.yaml
    verify: true
    timeout: 600
    atomic: true
    cleanupOnFail: true
    disableValidation: true
    disableValidationOnInstall: true

```

# How to reproduce 
```bash
helmfile apply
```
# Expected behaviour 
```bash
Release "logs-filebeat" has been installed.

Release "logs-logstash" has been installed.

Release "logs-kibana" has been installed.

Release "logs-elasticsearch" has been installed.
```

# Actual behaviour 
```bash
COMBINED OUPUT:
  Release "logs-kibana" does not exist. Installing it now.
  Error: failed to download "elastic/kibana" at version "7.12.1" (hint: running `helm repo update` may help)
err 3: failed processing release logs-elasticsearch: command "/usr/local/bin/helm" exited with non-zero status:
.
.
.
.
.
COMBINED OUPUT:
  Release "logs-filebeat" does not exist. Installing it now.
  Error: failed to download "elastic/filebeat" at version "7.12.1" (hint: running `helm repo update` may help)
err 3: failed processing release logs-elasticsearch: command "/usr/local/bin/helm" exited with non-zero status:

```

# Directory structure
```
ELK
├── environments
│   └── dev
│       ├── secrets.yaml
│       └── values.yaml
└── helmfile.yaml
```
# My thoughts
Since I am using charts like filebeat, kibana, logstash from same repository elastic I think only because of this reason I need to `helm repo update`. Obviously this will work if I separate my mono `helmfile.yaml` and break it into chunks like mentioned [here](https://github.com/roboll/helmfile#glob-patterns) but IMO helmfile should have an option to update repo perhaps it could be a part of `helmDefaults` or `releases`  
```yaml
helmDefaults:
  kubeContext: 'minikube'
  cleanupOnFail: true
  updateRepo: true
```

```yaml
releases:
  - name: logs-elasticsearch
    namespace: logs
    updateRepo: true
```

# What I tried
- I followed the open issue [here](https://github.com/roboll/helmfile/issues/1059) and used `--force-update`, `--skip-deps` but it gives me same error as mentioned above.

Looking forward for your reply @mumoshu !!!
