### ISSUE TITLE
Unable to set `name` label on release

### ISSUE THREAD

**Issue by caleb15** [roboll/helmfile#1851]
k8-autoscaler was initially installed with the label type=autoscaler. I uninstalled it and tried re-installing with label name=autoscaler, but helmfile was no longer able to find the release.

```
caleb@local:~/work/fifteen5-helmfiles$ helmfile --version
helmfile version v0.138.4
caleb@local:~/work/fifteen5-helmfiles$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
caleb@local:~/work/fifteen5-helmfiles$ helmfile -e cloud30 list
NAME                            NAMESPACE       ENABLED LABELS
k8s-autoscaler                  kube-system     true    name:autoscaler
[other releases not shown]
caleb@local:~/work/fifteen5-helmfiles$ helmfile -e cloud30 -l name=autoscaler sync
[... irrelevant "Adding repo" logs truncated ... ]
Adding repo autoscaler https://kubernetes.github.io/autoscaler
"autoscaler" has been added to your repositories

err: no releases found that matches specified selector(name=autoscaler) and environment(cloud30), in any helmfile
```

As you can see in the list command, the label and environment does exist, so the sync should work.

releases/k8s-autoscaler.yaml:
```yml
repositories:
- name: autoscaler
  url: https://kubernetes.github.io/autoscaler

releases:
  - name: k8s-autoscaler
    labels: 
      name: autoscaler # this used to be type: autoscaler
    namespace: kube-system
    chart: autoscaler/cluster-autoscaler
    version: 9.9.2
    installed: {{ .Environment.Values.installed }}
    values:
      - autoDiscovery:
          clusterName: {{ .Environment.Name }}
        rbac:
          serviceAccount:
            name: autoscaler
            annotations:
               eks.amazonaws.com/role-arn: {{ .Environment.Values.role_name }}
        serviceMonitor:
          enabled: {{ .Environment.Values.prometheus_installed }}
          namespace: logging
        prometheusRule:
          enabled: {{ .Environment.Values.prometheus_installed }}
          namespace: logging
          interval: 1m
          rules:
          - alert: Autoscaling stopped
            expr: cluster_autoscaler_cluster_safe_to_autoscale < 1
            annotations:
              message: |
                Autoscaler has stopped because the cluster is unhealthy (33% of nodes or more are unready)
              summary: autoscaling stopped
            for: 5m
            labels:
              severity: critical

environments:
  cloud30:
    values:
      - installed: true
      - role_name: arn:aws:iam::<REDACTED>:role/FF{{ .Environment.Name }}EKSSTSAWS
      - prometheus_installed: false
```

helmfile:
```yml
helmfiles:
  - path: "releases/k8s-autoscaler.yaml"

environments:
  cloud30:
```
