### ISSUE TITLE
conditional requiredEnv

### ISSUE THREAD

**Issue by tomassatka** [roboll/helmfile#1854]
Hi 

Is it possible to conditionally use requiredEnv? 

I can provide the usecase.

C:.
├───.idea
└───releases
    ├───grafana
    │   ├───transformers
    │   └───values
    ├───influxdb
    │   ├───1.1.9
    │   │   ├───transformers
    │   │   └───values
    │   └───2.2.0
    │       ├───transformers
    │       └───values
    └───telegraf
        └───values

helmfile.yaml:
```yaml
helmfiles:
  - path: releases/grafana/helmfile.yaml
    values:
      - grafana:
          enabled: {{ env "GRAFANA_ENABLED" }}
  - path: releases/influxdb/1.1.9/helmfile.yaml
    values:
      - influxdb:
          enabled: {{ env "INFLUXDB_ENABLED" }}
  - path: releases/influxdb/2.2.0/helmfile.yaml
    values:
      - influxdb2:
          enabled: {{ env "INFLUXDB2_ENABLED" }}
  - path: releases/telegraf/helmfile.yaml
    values:
      - telegraf:
          enabled: {{ env "TELEGRAF_ENABLED" }}
```

now helmfile.yaml of grafana:
```yaml
{{$condition := "grafana.enabled"}}

releases:
  - name: grafana
    chart: helm-virtual/grafana
    condition: {{$condition}}
    namespace: {{ requiredEnv "GRAFANA_NAMESPACE"}}
    values:
      - values/values.yaml.gotmpl
      - env:
          LDAP_PASSWORD: {{ requiredEnv "GRAFANA_LDAP_PASSWORD" }}
    transformers:
      - transformers/route-op.yaml
      - transformers/route-content.yaml
```
and one helmfile of influxdb:
```yaml
{{$condition := "influxdb.enabled"}}

releases:
  - name: influxdb
    chart: helm-virtual/influxdb
    version: 2.2.0
    condition: {{$condition}}
    namespace: {{ requiredEnv "INFLUXDB_NAMESPACE" }}
    values:
      - values/values.yaml.gotmpl
    transformers:
      - transformers/route-op.yaml
      - transformers/route-content.yaml
```

the point is that if i run the installation over main helmfile i have to provide all requiredEnvs in subhelmfiles even that the condition for those subhelmfiles are set to false hence not required. Is there a way how to correlate on conditions for enabled releases to provide required envs? Or the only way is to use env and make it just optional?

thx
