### ISSUE TITLE
Potentially nondeterministic rendering of state secrets

### ISSUE THREAD

**Issue by yurrriq** [roboll/helmfile#1855]
Providing a MFE here would be difficult, but we seem to be encountering nondeterministic rendering of state secrets (:rofl:).

With a setup like the following, where `defaults.yaml` and `overrides.yaml` have some of the same keys, we seem to sometimes end up with the value from `defaults.yaml` and other times from `overrides.yaml`.

```yaml
environments:
  example:
    secrets:
    - secrets/defaults.yaml
    - secrets/example/overrides.yaml
```

The same pattern with `values` works fine, so perhaps this has something to do with `secrets`. It also seems to work ok with AWS KMS as the key store, but not always with our self-hosted Hashicorp Vault as the key store. The sops/vault `--debug` logs (with `HELM_SECRETS_DRIVER_ARGS=--verbose` too) seem to imply everything worked fine, and I do see the decrypted values from both `defaults.yaml` and `overrides.yaml`.

Does that make sense? Any idea what's going on here and how we might prevent the nondeterminism?
