### ISSUE TITLE
Handling dependencies in Chart.yaml

### ISSUE THREAD

**Issue by alexgaganov** [roboll/helmfile#1857]
Hey guys,

I'm facing the following issue while trying to deploy `prometheus-community/kube-prometheus-stack` using Helmfile. Their Chart.yaml has some conditional dependencies, such as:
```yaml
dependencies:
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.8.*
```
However, I don't really want to install Grafana, so I'm setting `grafana.enabled: false` in my Values.yaml file.
When I run `helmfile template`, the templates rendered still contain Grafana related resources.
But when I run `helm template` with the same Values.yaml file, everything is rendered correctly. 

Here's the relevant part from the debug output from `helmfile template` execution:
```
running helm fetch prometheus-community/kube-prometheus-stack --untar -d /var/folders/km/x2g0dhc17mn7sb5czxsmz3gw0000gp/T/chartify049605693/arn:aws:eks:eu-west-1:xxx:cluster/xxx/monitoring/prometheus-operator-k8s-test --version 15.4.6
Removing the dependencies field from the original Chart.yaml.
using requirements.yaml:
{}

options: {false [/var/folders/km/x2g0dhc17mn7sb5czxsmz3gw0000gp/T/helmfile964232339/monitoring-prometheus-operator-k8s-test-values-cc9744b76 /var/folders/km/x2g0dhc17mn7sb5czxsmz3gw0000gp/T/helmfile893169878/monitoring-prometheus-operator-k8s-test-values-79d85dbddc] [] [] monitoring 15.4.6 false true}
running helm template --debug=false --output-dir=/var/folders/km/x2g0dhc17mn7sb5czxsmz3gw0000gp/T/chartify049605693/arn:aws:eks:eu-west-1:xxx:cluster/xxx/monitoring/prometheus-operator-k8s-test/kube-prometheus-stack/helmx.1.rendered prometheus-operator-k8s-test /var/folders/km/x2g0dhc17mn7sb5czxsmz3gw0000gp/T/chartify049605693/arn:aws:eks:eu-west-1:xxx:cluster/xxx/monitoring/prometheus-operator-k8s-test/kube-prometheus-stack -f /var/folders/km/x2g0dhc17mn7sb5czxsmz3gw0000gp/T/chartify049605693/arn:aws:eks:eu-west-1:xxx:cluster/xxx/monitoring/prometheus-operator-k8s-test/kube-prometheus-stack/values.yaml -f /var/folders/km/x2g0dhc17mn7sb5czxsmz3gw0000gp/T/helmfile964232339/monitoring-prometheus-operator-k8s-test-values-cc9744b76 -f /var/folders/km/x2g0dhc17mn7sb5czxsmz3gw0000gp/T/helmfile893169878/monitoring-prometheus-operator-k8s-test-values-79d85dbddc --namespace monitoring
```
So after fetching the chart, Helmfile seems to be performing some manipulation on files in the chart's folder. When diffing two folders(fetched manually vs fetched by Helmfile) I see tons of differences in their structure.
![image](https://user-images.githubusercontent.com/9268222/119003852-bce09580-b996-11eb-9595-f9d71e178ac5.png)

Not sure it's a bug, most likely I'm missing some configuration. I'd appreciate it if you could assist me with making this work.
Please let me know if you need any additional info.

Helm version: v3.5.4
Helmfile version: v0.139.6

Thanks a lot,
Alex.

**Comment by mumoshu** [comment]
@alexgaganov Hey! Thanks for reporting.

Helmfile usually runs `helm template `directly on the release on `helmfile template`. But sometimes it does more.

When you use any of `forceNamespace`, `dependencies`, `jsonPatches`, `strategicMergePatches`, and `transformers` under each entries inside the `releases` of your `helmfile.yaml`, it calls [chartify](https://github.com/variantdev/chartify) under the hood to generate a "temporary" chart and run `kustomize` on it, to apply various customizations. What's why your seeing the differences.

That said, perhaps there is a bug in `chartify` that doesn't handle `grafana.enabled` correctly?

Could you provide me your `helmfile.yaml` for reproduction? That would help me investigate this issue faster.

**Comment by alexgaganov** [comment]
Thank you @mumoshu! You're absolutely right, seems that the issue happens because of the `forceNamespace` key I have in our `helmfile.yaml`. Once I remove it, all the templates are rendered correctly. 
Here're my configs:

### helmfile.yaml

```yaml
bases:
  - {{ requiredEnv "PWD" }}/config/repositories.yaml
  - {{ requiredEnv "PWD" }}/config/environments.yaml

---
bases:
  - {{ requiredEnv "PWD" }}/config/defaults.yaml

---
releases:
  - name: prometheus-operator-k8s-test
    chart: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    forceNamespace: monitoring
    version: 15.4.6
    labels:
      component: test-upg
    values:
      - values/prometheus-operator-k8s.yaml.gotmpl
 ```

### repositories.yaml

```yaml
repositories:
    - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
```

### environments.yaml

```yaml
environments:
  dev-mgmt:
    values:
      - clusterName: eks-dev-mgmt-1
      - accountId: XXXX
      - region: eu-west-1
      - internalDNSZone: eu-west-1.compute.internal
      - {{ requiredEnv "PWD" }}/config/environments/dev-mgmt.yaml
```

### defaults.yaml

```yaml
helmDefaults:
  kubeContext: arn:aws:eks:{{ .Values.region }}:{{ .Values.accountId }}:cluster/{{ .Values.clusterName }}
```

**Comment by mumoshu** [comment]
@alexgaganov Hey! Thanks. Could you also share `values/prometheus-operator-k8s.yaml.gotmpl`?

**Comment by alexgaganov** [comment]
Hey. Sure, please find the files below:

### values/prometheus-operator-k8s.yaml.gotmpl

```yaml
nameOverride: k8s
fullnameOverride: prometheus-k8s

global:
  imagePullSecrets:
    - name: regsecret

alertmanager:
  enabled: false

grafana:
  enabled: false

kubeApiServer:
  enabled: true
 
kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    cAdvisorMetricRelabelings:
      - action: labelmap
        regex: '(pod|container)'
        replacement: '${1}_name'

kubeControllerManager:
  enabled: false

coreDns:
  enabled: true

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

kubeStateMetrics:
  enabled: false
 
kube-state-metrics:
  rbac:
    create: false
  podSecurityPolicy:
    enabled: false

nodeExporter:
  enabled: false

prometheusOperator:
  enabled: true
  
  {{- with .Values.prometheusK8s.prometheusOperator.resources }}
  resources:  {{ toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.prometheusK8s.prometheusOperator.affinity }}
  affinity: {{ toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.prometheusK8s.prometheusOperator.tolerations }}
  tolerations: {{ toYaml . | nindent 4 }}
  {{- end }}

prometheus:
  enabled: true

  serviceAccount:
    create: true
    annotations: 
      eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.accountId }}:role/prometheus_k8s
  
  podDisruptionBudget:
    enabled: true

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts: 
      - prometheus-k8s.fiverr

  additionalPodMonitors:
    - name: thanos-sidecar
      jobLabel: thanos-sidecar
      selector: 
        matchLabels:
          app: prometheus
      namespaceSelector:
        matchNames:
          - monitoring
      podMetricsEndpoints:
        - port: http
          interval: 15s
  
  additionalServiceMonitors:
    - name: raingutter
      jobLabel: raingutter
      selector: 
        matchLabels:
          raingutter: "true"
      namespaceSelector:
        matchNames:
          - default
      endpoints:
        - port: raingutter
          interval: 10s
      targetLabels:
      - app
    - name: kube-state-metrics
      jobLabel: kube-state-metrics
      selector:
        matchLabels:
          component: kube-state-metrics
      namespaceSelector:
        matchNames:
          - monitoring
      endpoints:
        - port: http
          honorLabels: true
          metricRelabelings:
            - action: labeldrop
              regex: '(label_node_kubernetes_io_exclude_from_external_load_balancers|label_alpha_service_controller_kubernetes_io_exclude_balancer|label_spotinst_io_node_lifecycle)'

  prometheusSpec:
    enableAdminAPI: true
    externalLabels:
      cluster: {{ .Values.clusterName }}
    externalUrl:  {{ .Values.prometheusK8s.prometheus.prometheusSpec.externalUrl }}
    serviceMonitorSelector:
      matchExpressions:
      - key: release
        operator: NotIn
        values:
        - prometheus-operator-ec2
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 3d

    replicas: 2
    podAntiAffinity: hard
    {{- with .Values.prometheusK8s.prometheus.prometheusSpec.affinity }}
    affinity: {{ toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.prometheusK8s.prometheus.prometheusSpec.tolerations }}
    tolerations: {{ toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.prometheusK8s.prometheus.prometheusSpec.resources }}
    resources: {{ toYaml . | nindent 6 }}
    {{- end }}

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: resizeable-gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 200Gi

    thanos:
      baseImage: quay.io/thanos/thanos
      version: v0.14.0-rc.1
      objectStorageConfig:
        name: general.secrets.monitoring.thanos
        key: object-store.yaml

    containers:
      - name: thanos-sidecar
        args:
          - sidecar
          - --prometheus.url=http://127.0.0.1:9090/
          - --tsdb.path=/prometheus
          - --grpc-address=[$(POD_IP)]:10901
          - --http-address=[$(POD_IP)]:10902
          - --objstore.config=$(OBJSTORE_CONFIG)
          - --log.level=info
          - --log.format=logfmt
          - --min-time=-1d
```

To render it though you will need the environment file as well:

### config/environments/dev-mgmt.yaml

```yaml
---
prometheusK8s:
  prometheusOperator:
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
    affinity: {}
    tolerations: {}
  prometheus:
    prometheusSpec:
      externalUrl: https://prometheus.fiverrdev.com
      resources:
        requests:
          memory: 4Gi
          cpu: 1000m
      affinity: {}
      tolerations: {}
```
