### ISSUE TITLE
Layering State Template Files doesn't work according to the documentation

### ISSUE THREAD

**Issue by andy-krivtsov** [roboll/helmfile#1865]
I have a problem with layering of the template state file. 
Relevant parts of files:
**Main helmfile.yaml**
```
bases:
  - base-service-list.yaml
---
bases:
  - base-env.yaml
---
releases:
....
```

First base file: **base-service-list.yaml**
```
environments:
  default:
    values:
      - services/service-list.test.yaml
```
Loaded  **services/service-list.test.yaml:**
```
modules:
  - name: testmodule
    version: 2.0.2
    description: Real-time Database 
```

Second base file: **base-env.yaml**
```
environments:
  default:
    values:
      - values/env-defaults/env-values.yaml.gotmpl
```
And loaded **values/env-defaults/env-values.yaml.gotmpl**
```
requiredModuleList:
{{- range .Values.modules }}
  - {{ . }}
{{- end }}

```
And in this case i getting error:
```
in ./helmfile.yaml: failed to read base-env.yaml: failed to load environment values file "values/env-defaults/env-values.yaml.gotmpl": failed to render [values/env-defaults/env-values.yaml.gotmpl], because of template: stringTemplate:2:17: executing "stringTemplate" at <.Values.modules>: map has no entry for key "modules"
```

As i can understand the rendering engine for env-values.yaml.gotmpl doesn't receive .Values.* environment variables, that should be already available at this stage in helmfile (they come from first base, separated by --- )
