### ISSUE TITLE
jsonPatches bug in helmfile v0.139.7

### ISSUE THREAD

**Issue by rembj** [roboll/helmfile#1867]
```
$helmfile template
Adding repo bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories

in ./helmfile.yaml: [exit status 1

COMMAND:
  helm template --debug=false --output-dir=/var/folders/yk/_5kp54hs4txcnd81vqdn0nyc0000gq/T/chartify921903343/elasticsearch/elasticsearch/helmx.1.rendered elasticsearch /var/folders/yk/_5kp54hs4txcnd81vqdn0nyc0000gq/T/chartify921903343/elasticsearch/elasticsearch -f /var/folders/yk/_5kp54hs4txcnd81vqdn0nyc0000gq/T/chartify921903343/elasticsearch/elasticsearch/values.yaml

OUTPUT:
  load.go:120: Warning: Dependencies are handled in Chart.yaml since apiVersion "v2". We recommend migrating dependencies to Chart.yaml.
  Error: template: elasticsearch/templates/master-svc.yaml:4:11: executing "elasticsearch/templates/master-svc.yaml" at <include "elasticsearch.master.fullname" .>: error calling include: template: elasticsearch/templates/_helpers.tpl:15:20: executing "elasticsearch.master.fullname" at <include "common.names.fullname" .>: error calling include: template: no template "common.names.fullname" associated with template "gotpl"
  Use --debug flag to render out invalid YAML]
```

I have this helmfile.yaml

```
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
  - name: elasticsearch
    chart: bitnami/elasticsearch
    version: 15.2.2
    jsonPatches:
    - target:
        version: v1
        kind: StatefulSet
        name: elasticsearch-master
      patch:
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/0/subPathExpr
        value: elasticsearch/$(MY_POD_NAME)
```
If i use helmfile v0.139.6, everything works ok.
