### ISSUE TITLE
Release status indication within postsync hooks

### ISSUE THREAD

**Issue by dudicoco** [roboll/helmfile#1868]
Is there anyway of passing the release status (success/failure) to the postsync hook?

That would be very beneficial for a lot of different scenarios.

For example, a postsync hook could be used to send slack notifications with the release status:
```
  hooks:
  - events:
    - postsync
    showlogs: true
    command: ./slack_notification.sh
    args:
    - '{{`{{ index .Release.Status }}`}}'
```

**Comment by dudicoco** [comment]
@mumoshu

**Comment by jwitko** [comment]
It would be nice to have this as a native feature if its possible.  For now a work-around you could implement would be to just execute a helm command to check the status inside your `slack_notification.sh` , getting things like namespace, release name, etc. from the post-sync hook args.

**Comment by dudicoco** [comment]
so turns out this exists, and I even commented on the PR in the past :)
https://github.com/roboll/helmfile/pull/882

Was able to make it work:
```
  hooks:
  - events:
    - postsync
    showlogs: true
    command: echo
    args:
    - '{{`{{.Environment.Name}} {{.Release.Name}} {{ if .Event.Error }}failure{{ else }}success{{ end }}`}}'
```

@mumoshu it seems that there are a lot of great features which are being added to helmfile without documentation.
It would be great if such PRs could add a line or two to the docs.

**Comment by mumoshu** [comment]
@dudicoco Thanks for sharing! Yep. Would you mind writing one for this?

**Comment by dudicoco** [comment]
@mumoshu, i've opened https://github.com/roboll/helmfile/pull/1870

**Comment by dudicoco** [comment]
@mumoshu i've tried using https://github.com/variantdev/vals to pass the slack webhook secret to the slack notification script, however it seems that helmfile does not fetch the value from AWS SSM:

```
  hooks:
  - events:
    - presync
    - postsync
    showlogs: true
    command: echo
    args:
    - 'ref+awsssm://path/to/slack-webhook'
```

Running helmfile sync results in:
```
hook[presync] logs | ref+awsssm://path/to/slack-webhook
```

Any ideas?
