### ISSUE TITLE
Container lifecycle is broken

### ISSUE THREAD

**Issue by yuchaoran2011** [roboll/helmfile#1873]
One of the charts I would like to use helmfile to manage contains the following snippet under `spec.template.spec.containers` in the Deployment:
```
lifecycle:
  postStart:
    exec:
       command: [...]
  preStop:
    exec:
       command: [...]
```
Using regular `helm install` (without helmfile), I get the expected results: the main deployment pod, in addition to another pod that is started by `postStart`. But if I use `helmfile apply` to install the chart, the postStart pod gets started and then immediately gets terminated. I'm on Helm 3.6.0

**Comment by mumoshu** [comment]
@yuchaoran2011 Hey! Could you share a reproducible example? Theoretically speaking this is impossible to happen at helmfile-level as it is just calling `helm upgrade --install` in the end.

**Comment by yuchaoran2011** [comment]
Sure. I was installing this [chart](https://github.com/apache/incubator-yunikorn-release/tree/master/helm-charts/yunikorn). My `helmfile.yaml` is very simple:
```
helmDefaults:
  tillerless: true
releases:
- name: yunikorn
  namespace: default
  chart: "./charts/yunikorn"
```
Note that I'm using a local copy of the chart, but it has the same contents as the one I provided the link for above
