### ISSUE TITLE
apply does not execute lookup in charts with a resource lookup

### ISSUE THREAD

**Issue by hypnopotamus** [roboll/helmfile#1879]
helmfile apply doesn't end up executing the helm lookup template function in charts.  my particular case:
```yaml
{{- if .Values.monitoring.enabled -}}
{{- $prometheus := (lookup "monitoring.coreos.com/v1" "Prometheus" "" "").items | mustFirst }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "webapplication2.fullname" . }}
  namespace: {{ $prometheus.metadata.namespace }}
  labels:
    app: {{ template "webapplication2.name" . }}
    chart: {{ template "webapplication2.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  endpoints:
  {{- range .Values.monitoring.sources}}
  - interval: {{ .interval | default "10s" }}
    port: {{ .port }}
  {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "webapplication2.name" . }}
      release: {{ .Release.Name }}
{{- end }}
```
my helmfile uses `helmfiles:` to ensure the kube-prometheus-stack is installed before installing the charts for webapplication2 (the name is fantastic) which include this service monitor.  My workaround, for now, is that I know what namespace I am deploying prometheus to so I am not _required_ to look it up or jump through any other hoops to share the namespace (or I could change the prometheus configuration to watch for service monitors in any namespace).

I _think_ the issue is actually in helm; I opened this PR: https://github.com/helm/helm/pull/9797

apply uses the helm-diff plugin, helm-diff runs `helm upgrade --dry-run` which should (I think) be expected to make cluster contact... there was talk of a security issue with letting cluster contact be made in ways that might produce output in the related issue but it sounded like maintainers were willing to accept PRs for install and upgrade --dry-run to make cluster contact. The linked issue is for debugging the output of lookup with --dry-run, the PR only tries to change upgrade since template and install were pretty closely coupled.
