### ISSUE TITLE
Helmfile attempts to decrypt secrets file even if secrets file is empty

### ISSUE THREAD

**Issue by kevin-lindsay-1** [roboll/helmfile#1884]
I know that this behavior is technically intended, however I use `secrets` with an approach similar to `common/environments`, so that I can have a set of secrets applied to my deployment with a particular deployment.

As a result, certain environments do not have any data to add to the secrets merging process.

For example:
```yaml
# ./common/environments.yaml.gotmpl
environments:
  develop:
    secrets:
      - ./secrets/default.yaml
      - ./secrets/develop.yaml
    values:
      - ./environments/default.yaml.gotmpl
      - ./environments/develop.yaml.gotmpl
```

If I have secrets on `develop`, but none actually applied on `default`, `helm-secrets` is called regardless and errors out.

I think it should be pretty simple to add a check for completely empty files (maybe with a whitespace trim just in case), and if the file's text is `""`, then to simply use the `secrets` value of `{}` as a fallback.
