### ISSUE TITLE
Support Helm repository auth

### ISSUE THREAD

**Issue by FalconerTC** [roboll/helmfile#1886]
Repository auth is supported for Helmfile by supplying credentials to the repository definition, such as

```
repositories:
  ...
  - name: roboll
    url: http://roboll.io/charts
    certFile: optional_client_cert
    keyFile: optional_client_key
    username: optional_username
    password: optional_password
```

It would be useful if Helmfile could support registry auth, using `helm/registry.json` or `.docker/config.json` or equivalent. I'm not sure what it would take to support that though
