### ISSUE TITLE
requiredEnv evaluated if commented out

### ISSUE THREAD

**Issue by pathob** [roboll/helmfile#1895]
```
repositories:
  - name: bitnami
    url: <URL_TO_REPOSITORY>
    # username: {{ requiredEnv "ARTIFACTORY_USR" }}
    # password: {{ requiredEnv "ARTIFACTORY_PSW" }}

releases:
# - name: ...
```

The above helmfile.yaml causes an error during execution of helmfile as the requiredEnv are evaluated even though these lines are commented out. I know, there is no real reason to have these lines commented out, still I consider this as a bug.

**Comment by mumoshu** [comment]
@pathob Hey! This is working as expected. Go template and YAML is two completely different things and a `helmfile.yaml` is basically a go template file that renders YAML. So, it evaluates go template expressions before parsing it as YAML as... a go template file isn't a YAML document. That's why it fails.

**Comment by pathob** [comment]
Thanks for the fast feedback, I got it. Just to add it for other people, the right approach would be to also comment out the Go Template:

```
repositories:
  - name: bitnami
    url: <URL_TO_REPOSITORY>
    # username: {{/* {{ requiredEnv "ARTIFACTORY_USR" }} */}}
    # password: {{/* {{ requiredEnv "ARTIFACTORY_PSW" }} */}}

releases:
# - name: ...
```
