### ISSUE TITLE
vals getting evaulated even though value is overriden

### ISSUE THREAD

**Issue by pathob** [roboll/helmfile#1896]
I designed our environments in a way, where pre-prod and prod environments are using secrets from a vault and dev environments are using generic secrets derived from the release name.

E.g. (simplified) pre-prod and prod values in values.yaml.gotmpl:

```
admin-username: {{ .Release.Name }}-admin
admin-password: ref+vault://secret/{{ .Release.Name }}/admin#/password
```

And: dev values in values-dev.yaml.gotmpl:

```
admin-password: {{ .Release.Name }}-password
```

In my helmfile.yaml I'm overriding the pre-prod / prod values with stage-specific values like this (simplified):

```
releases:
  - name: service
    chart: repo/service
    version: 1.2.3
    values:
      - "releases/{{ .Release.Name }}/values.yaml.gotmpl"
      {{ if not (eq .Environment.Name "prod") }}
      - "releases/{{ .Release.Name }}/values-{{ .Environment.Name }}.yaml.gotmpl"
      {{ end }}
```

So, the merged (but not rendered) values should look like this for a dev environment:

```
admin-username: {{ .Release.Name }}-admin
admin-password: {{ .Release.Name }}-password
```

Still, the vals from the overriden value get evaluated and helmfile fails, if the secret is not present.
