### ISSUE TITLE
Helmfile should pass --args to "helm repo add"

### ISSUE THREAD

**Issue by almed4** [roboll/helmfile#1898]
# Summary
When adding a repo, default args are not passed to the command `helm repo add`.

# Expected Behavior
With `helmfile.yaml` configured with the following:

```yaml
helmDefaults:
  args:
    - "--pass-credentials"
```

`helm repo add` should be called with `--pass-credentials`

### Expected

```bash
exec: helm repo add repo https://raw.githubusercontent.com/owner/repo/ref/dir --force-update --username *** --password *** --pass-credentials
```

# Actual Behavior

With `helmfile.yaml` configured with the following:

```yaml
helmDefaults:
  args:
    - "--pass-credentials"
```

`helm repo add` is called *without* `--pass-credentials`

### Actual

```bash
exec: helm repo add repo https://raw.githubusercontent.com/owner/repo/ref/dir --force-update --username *** --password ***
```

# Feature Request/Bug

helmfile should pass default helm arguments to `helm repo add` or allow arguments to be included in a `repositories` object.
