### ISSUE TITLE
[ Question ]  Iterate over release with different values

### ISSUE THREAD

**Issue by Amos-85** [roboll/helmfile#1906]
Hi!
I'm trying to loop over same release but every iteration needs a different set of values per release iteration.

The helmfile looks like this:
```
releases:
{{ range $i, $releases := until .Values.RELEASE_COUNTER }}
{{ $chartNumber := add1 $releases | toString }}
- name: release-number-{{ $chartNumber }}
  <<: *default
  labels:
    app: '{{`{{ .Release.Name }}`}}'
    chart: some-chart
    tier: core
{{- end }}
```
What is the best way to achieve that with helmfile ?

**Comment by Cleming** [comment]
Hi @Amos-85 !

Maybe you can do something like:

values:
```
gitlabrunner:
  - name: blah
    foo: bar
  - name: blah2
    foo: bar
```
helmfile:
```
releases:
{{- range .Values.gitlabrunner }}
  - name: {{ .name }}
    chart: my/chart
    namespace: {{ .name }}
    values:
      - values.yaml.gotmpl
      - foo: {{ .foo }}
{{- end }}
```
