### ISSUE TITLE
environments override not working

### ISSUE THREAD

**Issue by slimm609** [roboll/helmfile#1913]
I am running into an issue with the environments not getting merged in to override values of the release. 

```
helmDefaults:
  atomic: true

releases:
  - name: netdata
    namespace: netdata
    missingFileHandler: Warn
    labels:
      proj: test
    chart: ./helm
    values:
      - ./values.yaml
      - sd:
          tag: test
          pullPolicy: Always

environments:
  production:
    values:
    - sd:
        pullPolicy: IfNotPresent
  dev:
```

when I run with the environment of `production` it does not update the values but in debug I can see it getting the value.  It just never does anything with it.

```
first-pass produced: &{production map[sd:map[pullPolicy:IfNotPresent]] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {production map[sd:map[pullPolicy:IfNotPresent]] map[]}
vals:
map[sd:map[pullPolicy:IfNotPresent]]
defaultVals:[]
second-pass rendering result of "helmfile.yaml.part.0":
 0: helmDefaults:
 1:   atomic: true
 2:
 3: releases:
 4:   - name: netdata
 5:     namespace: netdata
 6:     missingFileHandler: Warn
 7:     labels:
 8:       proj: test
 9:     chart: ./helm
10:     values:
11:       - ./values.yaml
12:       - sd:
13:           tag: test
14:           pullPolicy: Always
15:
16: environments:
17:   production:
18:     values:
19:     - sd:
20:         pullPolicy: IfNotPresent
21:   dev:

merged environment: &{production map[sd:map[pullPolicy:IfNotPresent]] map[]}
```

the rendered output still shows the default output

```
        - name: sd
          image: "agent-sd:test"
          imagePullPolicy: Always
```

**Comment by rafilkmp3** [comment]
+1

**Comment by FWest98** [comment]
The values you set in the `environments` section are different from the values in the `release`! The ones in the environment section are variables to be used in the templating of the helmfile itself, while the values you set in a release are passed on to the helm chart.

So, a working sample would be:
```yaml
releases:
  - name: netdata
    values:
      - sd:
          tag: test
          pullPolicy: {{ .Values.pullPolicy }}

environments:
  default:
    values:
    - pullPolicy: Always
  production:
    values:
    - pullPolicy: IfNotPresent
```
