### ISSUE TITLE
Cannot render .Release.Name

### ISSUE THREAD

**Issue by darkn3rd** [roboll/helmfile#1914]
In following documentation regarding `.Release.Name` in the `helmfile.yaml`, I found that I could not get this to resolve correctly.  Based on the documentation, using either `{{ .Release.Name }}` or ``{{`{{ .Release.Name }}`}}``, I do not get desired result, I get an error instead.

I follow these doc code snippets:

*  https://github.com/roboll/helmfile/blob/master/docs/writing-helmfile.md#release-template--conventional-directory-structure
* https://github.com/roboll/helmfile#labels-overview

### Steps for ``{{`{{ .Release.Name }}`}}``

I am running: `helmfile --debug --file bug1.yaml apply`

```yaml
templates:
  default: &default
    chart: linkerd/{{`{{ .Release.Name }}`}}
    namespace: {{`{{ .Release.Name }}`}}
    version: 2.10.2
    values:
      - installNamespace: false
        namespace: {{`{{ .Release.Name }}`}}

releases:
  - name: linkerd
    <<: *default
  - name: linkerd-viz
    <<: *default
  - name: linkerd-jaeger
    <<: *default
```

### Actual Results for ``{{`{{ .Release.Name }}`}}``

```
processing file "bug1.yaml" in directory "."
first-pass rendering starting for "bug1.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
first-pass rendering output of "bug1.yaml.part.0":
 0: templates:
 1:   default: &default
 2:     chart: linkerd/{{ .Release.Name }}
 3:     namespace: {{ .Release.Name }}
 4:     version: 2.10.2
 5:     values:
 6:       - installNamespace: false
 7:         namespace: {{ .Release.Name }}
 8:
 9: releases:
10:   - name: linkerd
11:     <<: *default
12:   - name: linkerd-viz
13:     <<: *default
14:   - name: linkerd-jaeger
15:     <<: *default
16:

could not deduce `environment:` block, configuring only .Environment.Name. error: failed to read bug1.yaml.part.0: reading document at index 1: yaml: invalid map key: map[interface {}]interface {}{".Release.Name":interface {}(nil)}
error in first-pass rendering: result of "bug1.yaml.part.0":
 0: templates:
 1:   default: &default
 2:     chart: linkerd/{{ .Release.Name }}
 3:     namespace: {{ .Release.Name }}
 4:     version: 2.10.2
 5:     values:
 6:       - installNamespace: false
 7:         namespace: {{ .Release.Name }}
 8:
 9: releases:
10:   - name: linkerd
11:     <<: *default
12:   - name: linkerd-viz
13:     <<: *default
14:   - name: linkerd-jaeger
15:     <<: *default
16:

first-pass produced: &{default map[] map[]}
first-pass rendering result of "bug1.yaml.part.0": {default map[] map[]}
second-pass rendering result of "bug1.yaml.part.0":
 0: templates:
 1:   default: &default
 2:     chart: linkerd/{{ .Release.Name }}
 3:     namespace: {{ .Release.Name }}
 4:     version: 2.10.2
 5:     values:
 6:       - installNamespace: false
 7:         namespace: {{ .Release.Name }}
 8:
 9: releases:
10:   - name: linkerd
11:     <<: *default
12:   - name: linkerd-viz
13:     <<: *default
14:   - name: linkerd-jaeger
15:     <<: *default
16:
```

### Steps for `{{ .Release.Name }}`

I am running: `helmfile --debug --file bug2.yaml apply`

```yaml
templates:
  default: &default
    chart: linkerd/{{ .Release.Name }}
    namespace: {{ .Release.Name }}
    version: 2.10.2
    values:
      - installNamespace: false
        namespace: {{ .Release.Name }}

releases:
  - name: linkerd
    <<: *default
  - name: linkerd-viz
    <<: *default
  - name: linkerd-jaeger
    <<: *default
```

### ActualResults for `{{ .Release.Name }}`

```
processing file "bug2.yaml" in directory "."
first-pass rendering starting for "bug2.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
first-pass rendering input of "bug2.yaml.part.0":
 0: templates:
 1:   default: &default
 2:     chart: linkerd/{{ .Release.Name }}
 3:     namespace: {{ .Release.Name }}
 4:     version: 2.10.2
 5:     values:
 6:       - installNamespace: false
 7:         namespace: {{ .Release.Name }}
 8:
 9: releases:
10:   - name: linkerd
11:     <<: *default
12:   - name: linkerd-viz
13:     <<: *default
14:   - name: linkerd-jaeger
15:     <<: *default
16:

template syntax error: template: stringTemplate:3:30: executing "stringTemplate" at <.Release.Name>: can't evaluate field Release in type state.EnvironmentTemplateData
first-pass rendering output of "bug2.yaml.part.0":
 0: templates:
 1:   default: &default
 2:     chart: linkerd/

first-pass produced: &{default map[] map[]}
first-pass rendering result of "bug2.yaml.part.0": {default map[] map[]}
vals:
map[]
defaultVals:[]
second-pass rendering failed, input of "bug2.yaml.part.0":
 0: templates:
 1:   default: &default
 2:     chart: linkerd/{{ .Release.Name }}
 3:     namespace: {{ .Release.Name }}
 4:     version: 2.10.2
 5:     values:
 6:       - installNamespace: false
 7:         namespace: {{ .Release.Name }}
 8:
 9: releases:
10:   - name: linkerd
11:     <<: *default
12:   - name: linkerd-viz
13:     <<: *default
14:   - name: linkerd-jaeger
15:     <<: *default
16:

err: error during bug2.yaml.part.0 parsing: template: stringTemplate:3:30: executing "stringTemplate" at <.Release.Name>: can't evaluate field Release in type state.EnvironmentTemplateData
in ./bug2.yaml: error during bug2.yaml.part.0 parsing: template: stringTemplate:3:30: executing "stringTemplate" at <.Release.Name>: can't evaluate field Release in type state.EnvironmentTemplateData
```

### Expected Results

Per documentation examples, I hope at some pass, I would have this rendered as where `.Release.Name` gets replaced as `linkerd`, `linkerd-viz`, and `linkerd-jaeger`.

**Comment by mumoshu** [comment]
Hey!

```
templates:
  default: &default
    chart: linkerd/{{ .Release.Name }}
    namespace: {{ .Release.Name }}
    version: 2.10.2
    values:
      - installNamespace: false
        namespace: {{ .Release.Name }}
```

This one never works due to that there's a chicken-and-egg problem. Helmfile needs to render the go template (including `{{.Release.Name}}) in order to get the YAML doc to be parsed, but it also needs to parse the YAML doc to know what which release it is processing (which is required to evaluate `{{.Release.Name}}`)

```
templates:
  default: &default
    chart: linkerd/{{`{{ .Release.Name }}`}}
    namespace: {{`{{ .Release.Name }}`}}
    version: 2.10.2
    values:
      - installNamespace: false
        namespace: {{`{{ .Release.Name }}`}}
```

This also doesn't work, because `chart`, `namespace`, and embedded `values` does not support per-release templates.

Only the below fields support it, as documented in https://github.com/roboll/helmfile/blob/master/docs/writing-helmfile.md#release-template--conventional-directory-structure

- valuesTemplate
- setTemplate
- installedTemplate
- waitTemplate
- file names under `values`
