### ISSUE TITLE
Include Transitive dependencies

### ISSUE THREAD

**Issue by pjotre86** [roboll/helmfile#1915]
Hello!
Imagine you have three services:  
`serviceA` which depends on `serviceB` which depends on `serviceC`.  
So in helmfile you would declare those dependencies with the helm of the `needs` feature:
```
serviceA:
  ...
  needs:
    - needs: serviceB

serviceB:
  ...
  needs:
    - needs: serviceC

serviceC:
  ...
```
Now I'd like to start up serviceA with all its dependencies using:  
`helmfile --selector name=serviceA  template --include-needs`  
But what's happening then is that just the direct dependency of `serviceA` (which `serviceB`) is started. serviceC which you could call a transitive dependency of `serviceA` is **not started**. That would have been the expected behavior for me (being used to docker-compose, which does exaclty that).  
  
So my question:  
### Is there a way to tell helmfile to also include transitive dependencies?
