### ISSUE TITLE
Env values behaves differently depending on inline or file values

### ISSUE THREAD

**Issue by vsimon** [roboll/helmfile#1919]
(v0.139.9):

I am able to do this, the value with the “env” gets picked up with `FOO=bar helmfile -e myenv diff`

environments.yaml

```
environments:
  myenv:
    values:
      - foo: {{ env "FOO" }}
```

However, it seems referencing the same “env” in a values file does not work. Getting an error

```
in helmfile.d/environments.yaml: failed to read environments.yaml: failed to load environment values file "values/myenv.yaml": yaml: invalid map key: map[interface {}]interface {}{"env \"FOO\"":interface {}(nil)}
```

environments.yaml

```
environments:
  myenv:
    values:
      - values/myenv.yaml
```

values/myenv.yaml

```
foo: {{ env "FOO" }}
```

Not sure if this is also supposed to work or not. Was attempting to have a more manageable environments file with separate files for envs instead one long inline-file.
