### ISSUE TITLE
Warn upon duplicate selector labels

### ISSUE THREAD

**Issue by cmeury** [roboll/helmfile#193]
To avoid human error, we should warn on duplicate labels for identical releases. Give this helmfile:

```yaml
  - name: traefik-ingress
    namespace: platform
    labels:
      minikube: deploy
    chart: stable/traefik
    version: 1.24.1

  - name: traefik-ingress
    namespace: platform
    labels:
      minikube: deploy
    chart: stable/traefik
    version: 1.35.0
```

Executing `helmfile --selector minikube=deploy` will just silently pick the second release (1.35.0). Could we fail or warn?
