### ISSUE TITLE
.HelmfileCommand is not available as an argument in combination with exec function

### ISSUE THREAD

**Issue by korotovsky** [roboll/helmfile#1932]
Hello,

It seems that impossible to pass the helmfile command as an argument when we want to gather values as external shell script.

```
environments:
    env_name:
        values:
            - acme: "{{`{{ exec 'bin/script_name.sh' (list (requiredEnv 'ENV_NAME') .HelmfileCommand)) }}`}}"
```

Both approaches with template defer and without do not work. When I use with defer it return just empty, without defer it throws an runtime error.
