### ISSUE TITLE
Support namespace variable in values paths

### ISSUE THREAD

**Issue by eugene-chernyshenko** [roboll/helmfile#1942]
I store specific values for namespace in the separate folder
Now I have to copy paste namespace to values path 

```
releases:
- name: app-fea-1
  namespace: fea-1
  chart: myrepo/mychart
  version: 0.1.0
  values:
  - fea-1/app/values.yaml
- name: app-fea-2
  namespace: fea-2
  chart: myrepo/mychart
  version: 0.1.0
  values:
  - fea-2/app/values.yaml
 ```
 
 Is there any way to not copypaste?
 May be like this
 
 ```
releases:
- name: app-fea-1
  namespace: fea-1
  chart: myrepo/mychart
  version: 0.1.0
  values:
  - {{ .Namespace }}/app/values.yaml
- name: app-fea-2
  namespace: fea-2
  chart: myrepo/mychart
  version: 0.1.0
  values:
  - {{ .Namespace }}/app/values.yaml
 ```
 
 `{{ .Namespace }}` doesn't interpolate it this case
