### ISSUE TITLE
The quotes are of different types in requiredEnv

### ISSUE THREAD

**Issue by logabot** [roboll/helmfile#1944]
```yaml
releases:
  - name: test
    values:
      - image:
           tag: {{ requiredEnv 'IMAGE_TAG' | default '1.2.1' }}
```
and 
```yaml
releases:
  - name: test
    values:
      - image:
           tag: {{ requiredEnv "IMAGE_TAG" | default "1.2.1" }}
```
not identical

with double quotes return 
```yaml
....
containers:
        - name: test-qa
          image: "<redacted>:1.148.0.srv-14-g5dea416e5"
```

with single quotes return 
```
err: error during helmfile.yaml.part.0 parsing: template: stringTemplate:31: malformed character constant: 'IMAGE_TAG'
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:31: malformed character constant: 'IMAGE_TAG'
```

tested on 0.139.9 and 0.140.0
