### ISSUE TITLE
Question: Helmfile apply - deployed to node that has specific label

### ISSUE THREAD

**Issue by AnthonyWC** [roboll/helmfile#1949]
I did a `helmfile apply` after adding keel and to my surprise it got installed to a node that has specific label, my helmfile did not have any nodeselector as I just didn't want it to get applied to node with those specific label.  And I had other existing helm release installed before that didn't get installed to those specific node:

My helmfile:
```
repositories:
- name: eks
  # https://github.com/aws/eks-charts
  url: https://aws.github.io/eks-charts

- name: secrets-store-csi-driver
  url: https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts

- name: keel
  url: https://charts.keel.sh

# https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller
# https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller
releases:
- name: aws-load-balancer-controller
  namespace: kube-system
  chart: eks/aws-load-balancer-controller
  version: 1.2.6
  values:
   - clusterName: eks-test

- name: secrets-store-csi-driver
  namespace: kube-system
  chart: secrets-store-csi-driver/secrets-store-csi-driver
  version: 0.2.0

- name: keel
  namespace: kube-system
  chart: keel/keel
```

Is this by design or a bug?  And is that a way to mitigate?  I suppose I can also add label to the other group and then put nodeselector for those but wondering why it got installed to those node when they have specific label.
