### ISSUE TITLE
Does kustomize work?

### ISSUE THREAD

**Issue by dennybaa** [roboll/helmfile#1954]
I have been trying jsonPatches and strategicMergePatches. Neither seems to work. For example:

the template

```
repositories:
- name: incubator
  url: https://charts.helm.sh/incubator

releases:
- name: raw1
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: raw1
        namespace: default
      data:
        foo: FOO
  strategicMergePatches:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: raw1
        namespace: default
      data:
        bar: BAR
```

renders into nothing and no configmap is ever deployed.
Does anyone have clarification on this? Thanks.

**Comment by yurrriq** [comment]
At least `jsonPatches` works for me, with kustomize 3.8.1.

**Comment by eigood** [comment]
I'm having this same problem too; kustomize 4.3.0, helmfile 0.139.9(tried 0.140.0), helm 3.7.0-rc3.

I have a local chart, with kustomize.yaml, that contains a single resource, a VirtualService for istio.  If I use a jsonPatch or a smp in helmfile, then the entire resource is not in /tmp/chartifyXXXX, and all.patched.resources.yaml is blank.

**Comment by eigood** [comment]
The following 3 files showcase the bug.  There is no ConfigMap in the final output.  If you comment-out the SMP, then the ConfigMap will be applied.  Uncomment again, and the CM gets removed.

```yaml
# helmfile.yaml
releases:
  - name: helmfile-bug
    chart: ./bug-helmfile
    strategicMergePatches:
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: helmfile-bug
        data:
          key: value
```
```yaml
# bug-helmfile/kustomization.yaml
resources:
  - ./config-map.yaml
```
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helmfile-bug
data:
  key: value
---
```
