### ISSUE TITLE
Question: Helm Charts versioning via git

### ISSUE THREAD

**Issue by tomaszdudek7** [roboll/helmfile#1955]
Imagine a following setup
```
repositories:
  - name: app-config
    url: git+https://github.com/my_company/app-configuration-repository?ref=master
```
with
```
releases:
  - name: app-config
    chart: app-config/app-config
    version: 1.2.3
  - name: app-config
    chart: app-config/app-config
    version: 4.5.6
    // ...
```

Can I somehow use git tags (inside `my_company/app-configuration-repository`) to version the helm chart? That is, instead of building `tgz` files with `helm package` and then hosting them somewhere as artifactory, I would like to force `helmfile` to use git tags as chart versions.

I imagine updating version inside the `Chart.yaml` in `my_company/app-configuration-repository` to arbitrary value `X.Y.Z`, creating a tag with the same version `git tag X.Y.Z HEAD`, pushing it and then referencing it inside helmfile as follows:
```
releases:
  - name: app-config
    chart: app-config/app-config
    version: X.Y.Z
```

Is there any way to achieve such behavior?
