### ISSUE TITLE
Strange behavior of helmDefaults.args when using parent helmfile

### ISSUE THREAD

**Issue by steffakasid** [roboll/helmfile#1957]
Hi,

I've got a strange issue when using helmDefaults.args:

1. If I use my sub helmfile directly everything works fine
2. When I use the parent helmfile the sub helmfile fails with the error message `Error: unknown flag: --skip-crds`. It looks like in that case the `--skip-crds` flag is passed to `helm repo add` and when executing the sub helmfile directly that doesn't happen.

Here are both helmfiles:

Parent helmfile:
```
---
helmfiles:
  - path: "releases/calico-helmfile.yaml"
```

Sub helmfile:
```
---
repositories:
  - name: aws-eks
    url: https://aws.github.io/eks-charts

helmDefaults:
  args:
    - "--skip-crds"

releases:
  - name: calico-crds
    chart: ../charts/calico-crds
    namespace: helm-releases
    # Download the calico operator chart and copy the crds into crd chart and deploy it seperatly as own chart
    hooks:
    - events: ["prepare", "clean"]
      showlogs: true
      command: "rm"
      args: ["-rf", "../../build"]
    - events: ["prepare"]
      showlogs: true
      command: "helm"
      args: ["pull", "https://github.com/projectcalico/calico/releases/download/v3.19.0/tigera-operator-v3.19.0-1.tgz", "--untar", "--untardir", "../../build"]
    - events: ["prepare"]
      showlogs: true
      command: "cp"
      args: ["-r", "../../build/tigera-operator/crds", "../charts/calico-crds/templates"]
  - name: tigera-operator
    chart: ../../build/tigera-operator
    needs:
      - calico-crds
    namespace: helm-releases
    values:
      - installation:
          # full spec description: https://docs.projectcalico.org/reference/installation/api#operator.tigera.io/v1.CNISpec
          enabled: true
          kubernetesProvider: "EKS"
```

Any idea why this happens?

Regards
Steffen
