### ISSUE TITLE
"needs" has no effect

### ISSUE THREAD

**Issue by bplaye** [roboll/helmfile#1959]
Hello `helmfile` community! 
I have been trying to make use of the keyword `needs` (following the [doc](https://github.com/roboll/helmfile#dag-aware-installationdeletion-ordering)) to control the order of installation of the releases.

Here is my helmfile:
```
helmDefaults:
  createNamespace: false
  timeout: 600

helmBinary: /usr/local/bin/helm

releases:
- name: dev-sjs-pg
  chart: ../helm_charts/sjs-pg
- name: dev-sjs
  chart: ../helm_charts/sjs
  needs: ['dev-sjs-pgg']
```

Regarding versions: 
- `helmfile version v0.139.9`
- `helm version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}`

When I run `helmfile sync` , both releases are installed simultaneously. In particular, there is no error due to my spelling error (`dev-sjs-pgg` instead of `dev-sjs-pg`). It is like `needs` is just not read.

Could you help me understanding what I am doing wrong please ?

**Comment by yurrriq** [comment]
I believe you need to specify the namespace as well, as in `needs: ['<namespace>/<release name>']`.

**Comment by bplaye** [comment]
Hello yurrriq,
Thanks for your help !

I tried the following helmfile without success. Actually, I think `needs` is just not read by the command `helmfile sync` because I do not receive any error like `cohort360/dev-sjs-pgg not found`.
Did you manage to make the keyword `needs` work ? 

```
helmDefaults:
  createNamespace: false
  timeout: 600

helmBinary: /usr/local/bin/helm

releases:
- name: dev-sjs-pg
  chart: ../helm_charts/sjs-pg
  namespace: cohort360
- name: dev-sjs
  chart: ../helm_charts/sjs
  namespace: cohort360
  needs: ['cohort360/dev-sjs-pgg']
```
