### ISSUE TITLE
Proposal: aliases support

### ISSUE THREAD

**Issue by alebabai** [roboll/helmfile#196]
One more thing that would be nice to have is aliases support for each release.
The main use-case is to have single yaml-file with values that will be applied to each release with out conflicts.
Ref: https://github.com/helm/helm/blob/master/docs/charts.md#alias-field-in-requirementsyaml

**Comment by osterman** [comment]
Can't labels be used to achieve something pretty similar to aliases?

**Comment by mumoshu** [comment]
@alebabai Hey. Thanks a lot for the feature request!
I took sometime to think about it twice, but I'm still confused. What would be an example use-case of this feature?

I'm confused, maybe, because your reference is about aliasing dependent subcharts from the perspective of the parent chart. What would be the equivalents of aliases, subcharts, and the parent chart in helmfile's imaginary `aliases` feature?

**Comment by alebabai** [comment]
@mumoshu it's a little simpler.
For example you have a helmfile with two releases

_**helmfile.yaml**_
```yaml
repositories:
- name: "stable"
  url: "https://kubernetes-charts.storage.googleapis.com"

releases:
- name: "grafana"
  namespace: "default"
  labels:
    chart: "grafana"
    repo: "stable"
    namespace: "default"
    vendor: "kubernetes"
    default: "false"
  chart: "stable/grafana"
  version: "1.12.0"
  values:
    ## the same values-file
    - "common.yaml"
- name: "prometheus"
  namespace: "default"
  labels:
    chart: "prometheus"
    repo: "stable"
    namespace: "default"
    vendor: "kubernetes"
    default: "false"
  chart: "stable/prometheus"
  version: "7.0.2"
  values:
    ## the same values-file
    - "common.yaml"
```

_**common.yaml**_
```yaml
## there are values for two releases, separated by aliases (e.g. release name)
grafana:
  persistence:
    enabled: true

prometheus:
  persistence:
    enabled: false
```

**Comment by osterman** [comment]
What's the benefit of having a single `values.yaml` (`common.yaml`) shared between the releases?

**Comment by osterman** [comment]
To "hijack" your feature request, I could see something related to "alias" as beneficial.

```
releases:
- name: "grafana"
  alias: "grafana.persistance"
  namespace: "default"
  labels:
    chart: "grafana"
    repo: "stable"
    namespace: "default"
    vendor: "kubernetes"
    default: "false"
  chart: "stable/grafana"
  version: "1.12.0"
  values:
    - persistance: enabled

- name: "grafana"
   alias: "grafana.nonpersistent"
   include: "grafana.persistent"
   values:
     - persistence:
         enabled: false
```

Basically, the ability to create multiple falvors of a release by inheriting from a base release and then overriding the values as necessary.

**Comment by mumoshu** [comment]
@alebabai I have an idea.

The combination of https://github.com/roboll/helmfile/issues/59#issuecomment-415690069 and #227 would allow you to create, say `values-default.yaml` that is readable from within the whole helmfile.yaml and values.yaml templates.

`values-defaults.yaml` is loaded into helmfile perhaps by writing:

```yaml
environments:
  default:
    values:
    - ./values-default.yaml

releases:
- name: data-api
  chart: mycharts/data-api
  values:
  - ./data-api.values.yaml
````

In `data-api.values.yaml` for the `data-api` release in your example, you'd just write:

```
{{ .Values | mapToYaml }}
```

which is transformed to:

```yaml
image:
  tag: 2.0.0-golden-master
```

Would it help your use-case?
