### ISSUE TITLE
helmfile deps fails to create a lock file for a release with strategicMergePatches

### ISSUE THREAD

**Issue by elchenberg** [roboll/helmfile#1965]
### Example with strategicMergePatches (fails)

```yaml
# helmfile.yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: nginx
    chart: bitnami/nginx
    version: 9.5.4
    strategicMergePatches:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx
          labels:
            hello: world
```

`helmfile deps` fails to create a lock file:

```sh
helmfile --version && helmfile deps && ls
```

```txt
helmfile version v0.140.1
Adding repo bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories

Updating dependency /tmp/chartify058519592/nginx/nginx
There are no repositories defined in your helmfile.yaml.
This means helmfile cannot update your dependencies or create a lock file.
See https://github.com/roboll/helmfile/issues/878 for more information.
helmfile.yaml
```

### Example without strategicMergePatches (succeeds)

```yaml
# helmfile.yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: nginx
    chart: bitnami/nginx
    version: 9.5.4
```

`helmfile deps` creates a lock file:

```sh
helmfile --version && helmfile deps && ls
```

```txt
helmfile version v0.140.1
Adding repo bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories

Updating dependency /tmp/844136855
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading nginx from repo https://charts.bitnami.com/bitnami
Deleting outdated charts

helmfile.lock  helmfile.yaml
```

To me the problems seems to be that after chartification the chartPath is a local directory: https://github.com/roboll/helmfile/blob/787e6c80d1d16c48912c5280a6a84a01b1a702c3/pkg/state/state.go#L1157

### Workaround

I applied this patch as a workaround but I doubt that it would be a proper fix:

```patch
diff --git a/pkg/state/state.go b/pkg/state/state.go
index eb5291a..2455a84 100644
--- a/pkg/state/state.go
+++ b/pkg/state/state.go
@@ -1128,7 +1128,7 @@ func (st *HelmState) PrepareCharts(helm helmexec.Interface, dir string, concurre
 				skipDepsDefault := release.SkipDeps == nil && st.HelmDefaults.SkipDeps
 				skipDeps := (!isLocal && !chartFetchedByGoGetter) || skipDepsGlobal || skipDepsRelease || skipDepsDefault
 
-				if chartification != nil {
+				if chartification != nil && helmfileCommand != "deps" {
 					c := chartify.New(
 						chartify.HelmBin(st.DefaultHelmBinary),
 						chartify.UseHelm3(helm3),
```
