### ISSUE TITLE
Needs not working as expected

### ISSUE THREAD

**Issue by vbode** [roboll/helmfile#1967]
Hello there,
With the below helmfile, I expect the test-tenant release to be released after gatekeeper, reverseproxy and tos-database when executing:
`helmfile --environment local sync`
It is however released in the second batch of releases, before gatekeeper (or reverseproxy) have been released. In debug logging I see:

```
GROUP RELEASES
1     default/passlayer-proxy, default/tos-database
2     minikube/default/passlayer-session, minikube/default/reverseproxy, default/test-tenant
3     minikube/default/passlayer-pks
4     minikube/default/gatekeeper
```

When executing  `helmfile --environment local -l name=test-tenant sync --include-needs`, I get this error:
```
panic: bug: unexpectedly failed to get releases for id "default/gatekeeper": [default/test-tenant default/tos-database]

goroutine 1 [running]:
github.com/roboll/helmfile/pkg/state.GroupReleasesByDependency
....
```

Any ideas what could be the issue?

**helmfile.yaml**
```
environments:
  local:
    values:
    - kubeContextBase: minikube

helmDefaults:
  createNamespace: false
  timeout: 120
  wait: true
commonLabels:

releases:
  - name: gatekeeper
    chart: bitnami/nginx 
    atomic: true 
    kubeContext: minikube   
    namespace: default
    needs:
      - passlayer-pks
  - name: passlayer-pks
    chart: bitnami/nginx 
    atomic: true
    kubeContext: minikube
    namespace: default
    needs:
      - passlayer-session
  - name: passlayer-session
    chart: bitnami/nginx
    atomic: true
    kubeContext: minikube
    namespace: default
    set:
      - name: fullnameOverride
        value: passlayer-session
    needs:
      - passlayer-proxy
  - name: reverseproxy
    chart: bitnami/nginx 
    atomic: true
    kubeContext: minikube
    namespace: default
    needs:
      - passlayer-proxy
  - name: passlayer-proxy
    chart: stable/mssql-linux
    namespace: default
    set: 
      - name: image.repository
        value: mcr.microsoft.com/mssql/server
      - name: image.tag
        value: 2019-latest
      - name: acceptEula.value
        value: "Y"
  - name: tos-database
    chart: stable/mssql-linux
    namespace: default
    set: 
      - name: image.repository
        value: mcr.microsoft.com/mssql/server
      - name: image.tag
        value: 2019-latest
      - name: acceptEula.value
        value: "Y"
    needs:
  - name: test-tenant
    chart: stable/mssql-linux
    namespace: default
    set: 
      - name: image.repository
        value: mcr.microsoft.com/mssql/server
      - name: image.tag
        value: 2019-latest
      - name: acceptEula.value
        value: "Y"
    needs:
      - reverseproxy
      - gatekeeper
      - tos-database
```
