### ISSUE TITLE
Helmfile ignores values files when using kustomize

### ISSUE THREAD

**Issue by 4c74356b41** [roboll/helmfile#1969]
works fine:
```
- name: istio-discovery
  namespace: istio-system
  chart: istio/discovery
  labels:
    part: discovery
    app: istio
    ci: environment
  values:
  - xxx
  - yyy
  - zzz
```
ignores values completely:
```
- name: istio-discovery
  namespace: istio-system
  chart: istio/discovery
  labels:
    part: discovery
    app: istio
    ci: environment
  values:
  - xxx
  - yyy
  - zzz
    strategicMergePatches:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: istiod
      namespace: istio-system
    spec:
      template:
        spec:
          affinity:
            podAntiAffinity: xxx
```
using jsonPatches doesn't fix this as well. all the values passed in via `values:` are ignored.
