### ISSUE TITLE
Can't Access .Release.Name for Templating

### ISSUE THREAD

**Issue by mkuf** [roboll/helmfile#1971]
Hello there, 

I'm currently trying to template releases for our deployment but I'm somewhat out of ideas when is comes to getting the snippets for `version`, `devel` and` condition` to work and not repeat myself endlessly.
The Goal is to make releases configurable via environment values. 

My File basically looks like this, where the releases themselves are almost identical except for their respective value names.

```
environments:
  default:
    values:
    - namespace: dev-local
  dev:
    values:
    - namespace: development
  prod:
    values:
    - namespace: production
    - svc:
        version: ^1.0.0
        devel: false
    - svc-extra:
        devel: false
    - svc-db:
        enabled: false
---
values:
  - svc:
      enabled: true
  - svc-extra:
      namespace: monitoring
      enabled: true
  - svc-db:
      enabled: true
---
helmDefaults:
  createNamespace: false
releases:
  - name: svc
    namespace: {{ .Values | get "svc.namespace" .Values.namespace }}
    chart: scr/{{`{{.Release.Name}}`}}
    version: {{ .Values | get "svc.version" "*" | quote }}
    devel: {{ .Values | get "svc.devel" true }}
    condition: svc.enabled
    values:
      - ../../values/{{ .Environment.Name }}.yaml 
      - ../../values/common/{{`{{ .Release.Name }}`}}-values.yaml
      - ../../values/templates/release-values.gotmpl
  - name: svc-extra
    namespace: {{ .Values | get "svc-extra.namespace" .Values.namespace }}
    chart: ../../charts/{{`{{.Release.Name}}`}}
    version: {{ .Values | get "svc-extra.version" "*" | quote }}
    devel: {{ .Values | get "svc-extra.devel" true }}
    condition: svc-extra.enabled
    values:
      - ../../values/{{ .Environment.Name }}.yaml
      - ../../values/common/{{`{{ .Release.Name }}`}}-values.yaml
      - ../../values/templates/release-values.gotmpl
  - name: svc-db
    namespace: {{ .Values | get "svc-db.namespace" .Values.namespace }}
    chart: ../../charts/{{`{{.Release.Name}}`}}
    version: {{ .Values | get "svc-db.version" "*" | quote }}
    devel: {{ .Values | get "svc-db.devel" true }}
    condition: svc-db.enabled
    values:
      - ../../values/{{ .Environment.Name }}.yaml
      - ../../values/common/{{`{{ .Release.Name }}`}}-values.yaml
      - ../../values/templates/release-values.gotmpl
```

Trying to get templating to work I came up with this, which still needs multiple repetitions for releases
```
[-snip-]

templates:
  base-release: &base-release
    values:
      - ../../values/{{ .Environment.Name }}.yaml 
      - ../../values/common/{{`{{ .Release.Name }}`}}-values.yaml
      - ../../values/templates/release-values.gotmpl
  local-release: &local-release
    <<: *base-release
    chart: ../../charts/{{`{{.Release.Name}}`}}
  scr-release: &scr-release
    <<: *base-release
    chart: scr/{{`{{.Release.Name}}`}}

releases:
  - name: svc
    <<: *scr-release
    namespace: {{ .Values | get "svc.namespace" .Values.namespace }}
    version: {{ .Values | get "svc.version" "*" | quote }}
    devel: {{ .Values | get "svc.devel" true }}
    condition: svc.enabled

[-snip-]
```

Ideally I'd like to use something like this, but as soon as I try to use `.Release.Name` anywhere else than `values` or `chart`, I get errors.

```
[-snip-]

templates:
  base-release: &base-release
    namespace: {{ .Values | get .Release.Name | get "namespace" .Values.namespace }}
    version: {{ .Values  | get .Release.Name | get "version" "*" | quote }}
    devel: {{ .Values  | get .Release.Name | get "devel" true }}
    condition: svc.enabled
    values:
      - ../../values/{{ .Environment.Name }}.yaml 
      - ../../values/common/{{`{{ .Release.Name }}`}}-values.yaml
      - ../../values/templates/release-values.gotmpl

[-snip-]
```
```
err: error during issue.yaml.part.2 parsing: template: stringTemplate:20:40: executing "stringTemplate" at <.Release.Name>: can't evaluate field Release in type state.EnvironmentTemplateData
in ./issue.yaml: error during issue.yaml.part.2 parsing: template: stringTemplate:20:40: executing "stringTemplate" at <.Release.Name>: can't evaluate field Release in type state.EnvironmentTemplateData
```

I couldn't quite wrap my head around how to get this to work. Especially how to template the value for `condition`. 
Any Help would be greatly appreciated.

-Markus

**Comment by mkuf** [comment]
Small Succes, I got the template for `namespace` and `version` to work. 
```
templates:
  base-release: &base-release
    namespace: {{`{{ .Values | get .Release.Name | get "namespace" .Values.namespace }}` | quote }}
    version: {{`{{ .Values | get .Release.Name | get "version" "" }}` | quote }}
    values:
      - ../../values/{{ .Environment.Name }}.yaml 
      - ../../values/common/{{`{{ .Release.Name }}`}}-values.yaml
      - ../../values/templates/release-values.gotmpl
  local-release: &local-release
    <<: *base-release
    chart: ../../charts/{{`{{.Release.Name}}`}}
  scr-release: &scr-release
    <<: *base-release
    chart: scr/{{`{{.Release.Name}}`}}
```

Trying to apply this scheme to `devel` yields an error because it expects a bool.
```
devel: {{`{{ .Values | get .Release.Name | get "devel" true }}` | quote }}
```
```
in ./issue.yaml: failed to read issue.yaml: reading document at index 1: yaml: unmarshal errors:
  line 22: cannot unmarshal !!str `{{ .Val...` into bool
```
Removing the quote function at the end changes the unmarshal error to
```
in ./issue.yaml: failed to read issue.yaml: reading document at index 1: yaml: unmarshal errors:
  line 22: cannot unmarshal !!map into bool
```

I don't quite understand why the above template behaves like that, as the value should be set correctly by the final get function. 

A push into the right direction would be greatly appreciated.

-Markus
