### ISSUE TITLE
State values are empty during first pass rendering of nested helmfile (.Values vs .Environment.Values behavior)

### ISSUE THREAD

**Issue by Sn0wFox** [roboll/helmfile#1974]
Hello there :)

I recently updated my (old) helmfile version to v0.140.1 and noticed a major change between the old `.Enviroment.Values` and `.Values`, at least inside a sub-helmfile `environments`.  Here is a minimum reproducible example:

**helmfile.yaml**
```yaml
missingFileHandler: Error
helmfiles:
  - path: ./sub.helmfile.yaml
    values:
      - foo: bar
```

**sub.helmfile.yaml**
```yaml
environments:
  default:
    values:
      - ./{{ .Environment.Values.foo }}.yaml.gotmpl
    missingFileHandler: Warn
```

Then, running `helmfile build` would output

```
skipping missing environment values file matching "./bar.yaml.gotmpl"
skipping missing environment values file matching "./bar.yaml.gotmpl"
...
```
... and the correctly rendered yaml.

But replacing `.Environment.Values.foo` with `.Values.foo` yields:

```
skipping missing environment values file matching "./.yaml.gotmpl"
skipping missing environment values file matching "./bar.yaml.gotmpl"
...
```

... along with the **correct** yaml. So a warning is emitted during the first-pass rendering of the sub-helmfile because somehow `.Values` is null at the time, whereas `.Environment.Values` is not. The second pass is then fine.

From my testing the first missing file (`./.yaml.gotmpl` in this case) is not actually parsed when it exists. Using `missingFileHandler: Error` also doesn't generate an error. The warning itself is disappointing but fine regarding expected output yaml.

**However**, things get messy when you start using functions. For example this sub-helmfile:

```yaml
{{ $file := printf "./%s.yaml.gotmpl" .Values.foo }}

environments:
  default:
    values:
      - {{ $file }}
    missingFileHandler: Warn
```

will result in a nil pointer dereference. Once again, using the old `.Environment.Values.foo` works fine.

Since `.Environment.Values` is deprecated, is there an alternative syntax I missed so the last exemple doesn't result  in a crash?
