### ISSUE TITLE
cannot use values from bases

### ISSUE THREAD

**Issue by schollii** [roboll/helmfile#1975]
helmfile version: 
```
helmfile version v0.140.1
```

The following setup fails: 

- environments.yaml:
```
environments:
  default:
    values:
      - datadogApiKey: someKey
```
- helmfile-bad.yaml:
```
bases:
  - environments.yaml

repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator

releases:
  - name: datadog
    chart: incubator/raw
    values:
      - datadog:
          apiKey: {{ .Values.datadogApiKey }}
```
- run template, build or sync command; eg:
```
$ helmfile -f helmfile-bad.yaml template
in ./helmfile-bad.yaml: error during helmfile-bad.yaml.part.0 parsing: template: stringTemplate:14:28: executing "stringTemplate" at <.Values.datadogApiKey>: map has no entry for key "datadogApiKey"
$ _
```

The following setup works: move the contents of environments.yaml into the helmfile, ie
- helmfile-ok.yaml:
```
environments:
  default:
    values:
      - datadogApiKey: someKey

repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator

releases:
  - name: datadog
    chart: incubator/raw
    values:
      - datadog:
          apiKey: {{ .Values.datadogApiKey }}
```
- run template, build or sync command; eg:
```
$ helmfile -f helmfile-ok.yaml template
Adding repo incubator https://charts.helm.sh/incubator
"incubator" has been added to your repositories

Templating release=datadog, chart=incubator/raw
$ _
```

Is this a bug or I'm doing something wrong?

**Comment by kingli-crypto** [comment]
I have the same issue on `helmfile version v0.142.0`

**Comment by oliver-subskribe** [comment]
Wondering if #1090 is related

**Comment by antaloala** [comment]
This is really related to how helmfile "double rendering" works (see [#308](https://github.com/roboll/helmfile/pull/308))
Solution was previously commented by @mumoshu (see [this comment](https://github.com/roboll/helmfile/issues/388#issuecomment-826162985) from #388).

You can easily solve it using a ```---``` yaml separator inside ```helmfile-bad.yaml``` (see below, I tested it using the helmfile yaml files commented above):
```yaml
environments:
  default:
    values:
      - datadogApiKey: someKey
---
repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator

releases:
  - name: datadog
    chart: incubator/raw
    values:
      - datadog:
          apiKey: {{ .Values.datadogApiKey }}
```
