### ISSUE TITLE
Documentation issue about required sub-helmfile "values/environments" settings when ".helmfiles[*].values" set from top-level state values file

### ISSUE THREAD

**Issue by antaloala** [roboll/helmfile#1979]
From many Helmfile releases ago the following text appears in the Helmfile main README.md file (https://github.com/roboll/helmfile/#readme), inside the helmfile.yaml included at the top of this doc file:

```yaml
#
# Advanced Configuration: Nested States
#
helmfiles:
- # Path to the helmfile state file being processed BEFORE releases in this state file
  path: path/to/subhelmfile.yaml
  # Label selector used for filtering releases in the nested state.
  # For example, `name=prometheus` in this context is equivalent to processing the nested state like
  #   helmfile -f path/to/subhelmfile.yaml -l name=prometheus sync
  selectors:
  - name=prometheus
  # Override state values
  values:
  # Values files merged into the nested state's values
  - additional.values.yaml
  # One important aspect of using values here is that they first need to be defined in the values section
  # of the origin helmfile, so in this example key1 needs to be in the values or environments.NAME.values of path/to/subhelmfile.yaml
  # Inline state values merged into the nested state's values
  - key1: val1
```
Here I am referring to this exact comments (copied from above)

```yaml
  values:
  # Values files merged into the nested state's values
  - additional.values.yaml
  # One important aspect of using values here is that they first need to be defined in the values section
  # of the origin helmfile, so in this example key1 needs to be in the values or environments.NAME.values of path/to/subhelmfile.yaml
```

I have been testing it with a sub-Helmfile that does not define (in its "values" stanza nor in the "environments" one) the .Values passed to it from the parent state file (I used the example shown in https://github.com/roboll/helmfile/blob/master/docs/writing-helmfile.md#re-using-environment-state-in-sub-helmfiles) and I did not get any rendering error.

Am I misunderstanding this comment in README.md?
Or it it about some old limitation that has been solved in newer releases?
(I am using testing with latest 0.140.1 ... I tried to reproduce it with 0.138.6 but it also worked)
