### ISSUE TITLE
values files not merged

### ISSUE THREAD

**Issue by dkirrane** [roboll/helmfile#1986]
helmfile passes multiple `--values` arguments to `helm upgrade --install`, whereas what I was expecting is a single merged values file. 
Is it possible to get that behavior?

My `helmfile`:
```yaml
- name: istio
  version: 1.8
  chart: myrepo/istio
  namespace: istio-system
  values:
    - config/values1.yaml.gotmpl
    - config/values2.yaml.gotmpl
```

My problem is values2 is overriding values1. The priority will be given to config in the last values file specified:

```yaml
# values1.yaml.gotmpl settings never get applied
gateways:
  istio_ingressgateway:
    type: LoadBalancer
    serviceAnnotations:
      service.beta.kubernetes.io/azure-dns-label-name: foo
```

```yaml
# values2.yaml.gotmpl wins
gateways:
  istio_ingressgateway:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 1Gi
```
