### ISSUE TITLE
template issue - cannot unmarshal !!map into string

### ISSUE THREAD

**Issue by dkirrane** [roboll/helmfile#1988]
I have the following template.

When I add ```{{`{{ .Release.Name }}`}}``` then helmfile sync throws `cannot unmarshal !!map into string`.
What's the correct way to do this?

This is happening for both `commonLabels` & template `labels` below

```yaml
commonLabels:
  app.kubernetes.io/instance: {{`{{ .Release.Name }}`}}

templates:
  default: &default
    chart: repo/{{`{{ .Release.Name }}`}}
    namespace: default
    labels:
      name: {{`{{ .Release.Name }}`}}
```
