### ISSUE TITLE
set values in release section

### ISSUE THREAD

**Issue by schollii** [roboll/helmfile#1993]
I have a script that programmatically determines the build tag to deploy, and I need to use the value in a few places (such as in the values file, and in a prepare hook). I could set a value in the environments element but the value's code has to be replicated in every child of environments. I could call the script in several places but that feels wrong (but it will work). 

Is there another way that I'm missing? 

Like if releases had a pre-values element which would be computed prior to the releases.name.values, and merged with the pre-values of environments and overriddable in individual releases, that would solve the problem. IE in a perfect world there could be a structure like this: 
```
releases:
   rel1: 
      pre_values: 
        name1: {{ ... }} # overrides those of the active environment, for this specific release
      hooks: 
      - events: ["prepare"]
        command: "./set-helm-chart-appversion.sh"
        args: ["--arg1",  .Values.name1 ]
      values:
        - name: name1
          value: {{ .Values.name1 }}
```

You could have pre_values at a few levels (as child of the releases, and child of environments), but the above would be sufficient.
