### ISSUE TITLE
Global hooks not running with nested sub-helmfiles 

### ISSUE THREAD

**Issue by igorkatz** [roboll/helmfile#1997]
Hi,
My helmfile version:
`helmfile version v0.139.9`

snippet of my helmfile.yaml:
````
---
repositories:
  - ...

helmDefaults:
  timeout: 600
  atomic: true
  cleanupOnFail: true
  skipDeps: true

hooks:
- events: ["prepare"]
  showlogs: true
  command: "/bin/sh"
  args: ["-c", "kubectl apply -f predefined-env.yaml --namespace mi-paas"]

helmfiles:
  - groups/*.yaml
 ````

helmfile command is used:
`helmfile --debug --no-color apply --skip-diff-on-install --skip-deps`

**Problem:**
Global hooks do not work when nested asub-helmfiles are defined
If remove nested sub-helmfiles,  global hooks will run:
````
helmfiles:
#  - groups/*.yaml
````
