### ISSUE TITLE
Passing multiple environments to helmfile

### ISSUE THREAD

**Issue by dudicoco** [roboll/helmfile#1999]
Hi,

I'm trying to pass multiple environments to helmfile:
```sh
helmfile -e staging -e prod build
```

This doesn't work as helmfile only takes the last `-e` argument.

Is there a way around this?

Thanks

**Comment by yurrriq** [comment]
Environments in helmfile are mutually exclusive. What is your intention here? Perhaps something like this:
```yaml
environments:
  staging:
    values:
    - path/to/staging.yaml
  production:
    values:
    - path/to/staging.yaml
    - path/to/production.yaml
```

**Comment by dudicoco** [comment]
@yurrriq `helmfile.yaml` is unrelated to the helmfile cmd flags.

My intention is to be able to deploy to multiple environments with one command.

**Comment by dudicoco** [comment]
I've found a workaround use an environment label instead of the native environment feature:
```yaml
releases:
- name: amazing-app
  chart: my-repo/amazing-app
  version: 1.0.0
  installed: true
  namespace: devops
  labels:
    environment: staging
- name: amazing-app
  chart: my-repo/amazing-app
  version: 1.0.0
  installed: true
  namespace: devops
  labels:
    environment: prod
```

You can then deploy in parallel: `helmfile -l environment=staging,name=amazing-app -l environment=prod,name=amazing-app apply`.

My problem now is that I can't figure out which release belongs to which environment from the helmfile output, for example:
```sh
Upgrading release=amazing-app, chart=my-repo/amazing-app
Release "amazing-app" has been upgraded. Happy Helming!
NAME: amazing-app
LAST DEPLOYED: Tue Nov 30 15:31:16 2021
NAMESPACE: devops
STATUS: deployed
REVISION: 68
TEST SUITE: None

Listing releases matching ^amazing-app$
amazing-app	devops   	68      	2021-11-30 15:31:16.141045 +0200 IST	deployed	amazing-app-1.0.0 	1.0

Upgrading release=amazing-app, chart=my-repo/amazing-app
Release "amazing-app" has been upgraded. Happy Helming!
NAME: amazing-app
LAST DEPLOYED: Tue Nov 30 15:32:32 2021
NAMESPACE: devops
STATUS: deployed
REVISION: 2
TEST SUITE: None

Listing releases matching ^amazing-app$
amazing-app	devops   	2       	2021-11-30 15:32:32.92882 +0200 IST	deployed	amazing-app-1.0.0 	1.0


UPDATED RELEASES:
NAME          CHART                 VERSION
amazing-app   my-repo/amazing-app    1.0.0
amazing-app   my-repo/amazing-app    1.0.0
```

@mumoshu any suggestions?
