### ISSUE TITLE
Strategic Merge Patches not working with local path

### ISSUE THREAD

**Issue by Hounddog** [roboll/helmfile#2008]
We are using helmfile  as a wrapper around our helm charts to introduce Values and own Templates.
For this we have defined `chart: .` in our releases.

However trying to introduce Strategic Merge Patches with this structure results in an error:
```
$helmfile template > out.yaml
in ./helmfile.yaml: [exit status 1

COMMAND:
  kustomize build /tmp/chartify820206815/mergepatches/mergePatchesTest --output /tmp/chartify820206815/mergepatches/mergePatchesTest/all.patched.yaml

OUTPUT:
  Error: accumulating resources: accumulation err='accumulating resources from 'helmx.1.rendered/test-with-local-directory/templates/configmap.yaml': evalsymlink failure on '/tmp/chartify820206815/mergepatches/mergePatchesTest/helmx.1.rendered/test-with-local-directory/templates/configmap.yaml' : lstat /tmp/chartify820206815/mergepatches/mergePatchesTest/helmx.1.rendered: no such file or directory': evalsymlink failure on '/tmp/chartify820206815/mergepatches/mergePatchesTest/helmx.1.rendered/test-with-local-directory/templates/configmap.yaml' : lstat /tmp/chartify820206815/mergepatches/mergePatchesTest/helmx.1.rendered: no such file or directory]
```
Versions:
`helmfile version v0.142.0`
`{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:36:27Z GoOs:linux GoArch:amd64}`

When moving the files to a subdirectory and naming the chart everything works as expected.

I have written together a simple test case with a configmap to reproduce this issue.
tree
```
.
├── Chart.yaml
├── helmfile.yaml
└── templates
    └── test-cm.yaml
```
Chart.yaml
```
apiVersion: v2
name: test-with-local-directory
description: Test Configmap with Local Directory
version: 1.0.0
```
helmfile.yaml
```
---
releases:
  - chart: .
    name: mergePatchesTest
    namespace: mergepatches
    strategicMergePatches:
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: patch-demo
        data:
          some_label: "after_patch"
```
templates/configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: patch-demo
data:
  some_label: "before_patch"
  ```
