### ISSUE TITLE
How to concatenate two requiredenv and dot as domain name?

### ISSUE THREAD

**Issue by ziyi-bear** [roboll/helmfile#2011]
I tried to let url as {{ requiredEnv "INGRESS_DOMAIN" }}.{{ requiredEnv "KUBE_INGRESS_BASE_DOMAIN" }}, but it keep shows error while using CICD, how cant i fix it? thanks.

```yaml
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: wp-{{ requiredEnv "CI_PROJECT_NAME" }}
  # namespace: {{ requiredEnv "KUBE_NAMESPACE" | quote }}
  createNamespace: false
  chart: bitnami/wordpress
  labels:
    ## Is template or custom
    type: template
  version: 12.2.0
  installed: true
  timeout: 600
  set:
    - name: metrics.enabled
      value: true
    - name: mariadb.image.debug
      value: true
  values:
    ## @section WordPress Configuration parameters
    - ## @param wordpressUsername WordPress username
      wordpressUsername: {{ requiredEnv "WP_USERNAME" }}
      ## @param wordpressPassword WordPress user password
      ## Defaults to a random 10-character alphanumeric string if not set
      wordpressPassword: {{ requiredEnv "WP_PASSWORD" }}
      ## @param wordpressEmail WordPress user email
      wordpressEmail: {{ requiredEnv "WP_EMAIL" }}
      ## @param wordpressFirstName WordPress user first name
      wordpressFirstName: {{ requiredEnv "WP_FIRSTNAME" }}
      ## @param wordpressLastName WordPress user last name
      wordpressLastName: {{ requiredEnv "WP_LASTNAME" }}
      ## @param wordpressBlogName Blog name
      wordpressBlogName: {{ requiredEnv "WP_BLOGNAME" }}
      ## @param wordpressScheme Scheme to use to generate WordPress URLs
      wordpressScheme: https
    ## SMTP mail delivery configuration
    - ## @param smtpHost SMTP server host
      ## @param smtpPort SMTP server port
      ## @param smtpUser SMTP username
      ## @param smtpPassword SMTP user password
      ## @param smtpProtocol SMTP protocol
      smtpHost: {{ env "WP_SMTP_HOST" | default "smtp.gmail.com" }} 
      smtpPort: {{ env "WP_SMTP_PORT" | default "587" }}
      smtpUser: {{ requiredEnv "WP_SMTP_USER" }} 
      smtpPassword: {{ requiredEnv "WP_SMTP_PASSWORD" }} 
      smtpProtocol: {{ env "WP_SMTP_PROTOCAL" | default "tls" }} 
    ## @section WordPress deployment parameters
    - ## @param replicaCount Number of WordPress replicas to deploy
      ## NOTE: ReadWriteMany PVC(s) are required if replicaCount > 1
      replicaCount: 1
      ## @param podAnnotations Annotations for WordPress pods
      podAnnotations:
        app.gitlab.com/app: {{ requiredEnv "CI_PROJECT_PATH_SLUG" }}
        app.gitlab.com/env: {{ requiredEnv "CI_ENVIRONMENT_SLUG" }}
      ## WordPress containers' resource requests and limits
      resources:
        limits: {}
        requests:
          memory: 512Mi
          cpu: 300m
    ## @section Traffic Exposure Parameters
    - ## WordPress service parameters
      service:
        ## @param service.type WordPress service type
        type: ClusterIP
    - ## Configure the ingress resource that allows you to access the WordPress installation
      ingress:
        ## @param ingress.enabled Enable ingress record generation for WordPress
        enabled: true
        ## DEPRECATED: Use ingress.annotations instead of ingress.certManager
        certManager: true
        ## @param ingress.ingressClassName IngressClass that will be be used to implement the Ingress (Kubernetes 1.18+)
        ## This is supported in Kubernetes 1.18+ and required if you have more than one IngressClass marked as the default for your cluster .
        ingressClassName: {{ env "INGRESS_CLASS" | default "public" }}
        ## @param ingress.hostname Default host for the ingress record
        hostname: {{ printf "$s.%s" ( requiredEnv "INGRESS_DOMAIN" ) ( requiredEnv "KUBE_INGRESS_BASE_DOMAIN" ) }}
        # {{ requiredEnv "INGRESS_DOMAIN" }}.{{ requiredEnv "KUBE_INGRESS_BASE_DOMAIN" }}
        # 
        ## @param ingress.annotations Additional annotations for the Ingress resource. To enable certificate autogeneration, place here your cert-manager annotations.
        annotations:
          #acme.cert-manager.io/http01-edit-in-place: "true"
          cert-manager.io/cluster-issuer: "cloudflare-prod"
          ## 為了上傳備份檔案
          nginx.ingress.kubernetes.io/proxy-body-size:  "550m"
        ## @param ingress.tls Enable TLS configuration for the host defined at `ingress.hostname` parameter
        ## TLS certificates will be retrieved from a TLS secret with name: `{{- printf "%s-tls" .Values.ingress.hostname }}`
        tls: true
    ## @section Persistence Parameters
    - ## Persistence Parameters
      persistence:
        ## @param persistence.enabled Enable persistence using Persistent Volume Claims
        enabled: true
        ## @param persistence.storageClass Persistent Volume storage class
        storageClass: {{ requiredEnv "WP_STORAGECLASS" }}
        ## @param persistence.accessModes [array] Persistent Volume access modes
        accessModes:
          - ReadWriteMany
        ## @param persistence.size Persistent Volume size
        size: 10Gi
    - wp-common/mariadb.values.yaml 
    - wp-common/memcached.values.yaml 
    - wp-common/disable.values.yaml 
    - mariadb:
        auth:
          rootPassword: {{ requiredEnv "DB_INIT_PASSWORD" | quote }}
          password: {{ requiredEnv "DB_INIT_PASSWORD" | quote }}
          replicationPassword: {{ requiredEnv "DB_INIT_PASSWORD" | quote }}
        primary:
          persistence:
            storageClass: {{ requiredEnv "DB_STORAGECLASS" | quote }}
        secondary:
          persistence:
            storageClass: {{ requiredEnv "DB_STORAGECLASS" | quote }}
    - commonAnnotations:
        app.gitlab.com/app: {{ requiredEnv "CI_PROJECT_PATH_SLUG" }}
        app.gitlab.com/env: {{ requiredEnv "CI_ENVIRONMENT_SLUG" }}  
```
I have tried 
* `hostname: {{ printf "$s.%s" ( requiredEnv "INGRESS_DOMAIN" ) ( requiredEnv "KUBE_INGRESS_BASE_DOMAIN" ) }}`
* `hostname: {{ requiredEnv "INGRESS_DOMAIN" }}.{{ requiredEnv "KUBE_INGRESS_BASE_DOMAIN" }}`

but both show the error below
![image](https://user-images.githubusercontent.com/54978757/143974444-587ba862-05a6-4e1a-8c43-b3db456b7d72.png)
```
$ helmfile --file helmfile.yaml --namespace "$KUBE_NAMESPACE" --selector type=template apply
in ./helmfile.yaml: in .helmfiles[0]: in wordpress/helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:88:103: executing "stringTemplate" at <.Values.ingress.hostname>: map has no entry for key "ingress"
```
