### ISSUE TITLE
How to use single gotmpl but use single block from it for values

### ISSUE THREAD

**Issue by apurvdeodhar** [roboll/helmfile#2018]
I have following `helmfile.yaml`

```yaml

helmDefaults:
  createNamespace: true
  cleanupOnFail: true
  kubeContext: minikube

environments:
  default:
    values:
      - ./values.yaml

repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: traefik-demo
    chart: traefik/traefik
    version: 10.6.2
    namespace: helmfile-demo
    values:
      - ./values.yaml.gotmpl
  - name: redis-demo
    namespace: helmfile-demo
    chart: bitnami/redis
    version: 14.6.2
    values:
      - ./values.yaml.gotmpl
```

This is how `values.yaml` and `values.yaml.gotmpl` looks like

```yaml
traefik:
  deployment:
    intiContainers:
     - name: volume-permissions
       image: busybox:1.31.1
       command: ["sh", "-c", "chmod -Rv 600 /data/*"]
       volumeMounts:
         - name: data
           mountPath: /data

  logs:
    general:
      # By default, the level is set to ERROR. Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
      level: DEBUG
    access:
      enabled: false

  service:
    enabled: true
    type: ClusterIP

redis:
  auth:
    enabled: true
    sentinel: true
```

```gotmpl
{{- with .Environment.Values | getOrNil "traefik" }}
{{- toYaml . | nindent 1 }}
{{- end }}

{{- with .Environment.Values | getOrNil "redis" }}
{{- toYaml . | nindent 1 }}
{{- end }}
```

#### What I am trying to do?
I would like to use a same `values.yaml.gotmpl` for 2 different releases and some how tell helmfile to only consider `traefik` block for traefik release and `redis` block for redis release from `values.yaml`. So that when I try 
```bash
helmfile write-values
```
it should only write corresponding block of values in the output. 

How can I achieve this?
