### ISSUE TITLE
How to add dynamic hooks from file 

### ISSUE THREAD

**Issue by i053322** [roboll/helmfile#2019]
helmfile.yaml

```
bases:
  - common-helmfile.yaml

# defer the template rendering to happen only after the values are loaded.
---

releases:
  - name: controller
    values:
      - values/controller-yaml
    hooks:
{{ .Values.hooks }}`

common-helmfile.yaml

environments:
  default:
    values:
      - values/common-values.yaml
      
common-values.yaml
key:value
```

I want to add dynamic hooks from file and I don't want to add it in the common-values.yaml
I tried to add another base but I need that two bases will be installed the default and the new one 

```
bases:
  - common-helmfile.yaml
  - hooks-helmfile.yaml
# defer the template rendering to happen only after the values are loaded.
---

releases:
  - name: controller
    values:
      - values/controller-yaml
    hooks:
{{ .Values.hooks }}`

hooks-helmfile.yaml

environments:
  default: / i tried also to change the name and to inject it with the helmfile and it didn't work
    values:
      - values/hooks-values.yaml

hooks.-values.yaml
c:d
```

helmfile --file ./helmfile/helmfile.yaml  sync        
I got an error
template: stringTemplate:22:10: executing "stringTemplate" at <.Values.hooks>: map has no entry for key "hooks"

I tried also to change the hooks

hooks:
  - values/hooks-values.yaml

and I got an error
line 22: cannot unmarshal !!str `values/...` into event.Hook

I tried also to change the base
```
bases:
  - test-helmfile.yaml
  - common-helmfile.yaml
```
and to add new file

test-helmfile.yaml
```
environments:
  dev:
    values:
    - values/common-values.yaml
    - values/hooks-values.yaml
```   
it is only working when I remove the common-helmfile.yaml and it didn't find the env.
