### ISSUE TITLE
Multiple template file between helm chart and helmfile

### ISSUE THREAD

**Issue by AbbasHallal** [roboll/helmfile#2020]
I am using bitnami helm charts to deploy redis via helmfile in my kuberenets cluster. I have my own bases/values.yaml.gotmpl. Bitnami have their own dependency chart `common` where they are templating common helpers for all charts. My helmfile deployment was failing since it was not able to find the common `common.names.fullname` and after a lot of research I saw that in helmfile, t**he last template wins** which is `bases/values.yaml.gotmpl` in my case and which doesn't have the common templates provided by Bitnami. 
A workaround on my side was to append the `_names.tpl` to bases/values.yaml.gotmpl so that the deployment doesn't fail. 
Any idea about this? Is there a better way to overcome this? 
Is it limitation of helmfile to add multiple templating files? 
**### Steps to reproduce:** 
```
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: stable
  url: https://charts.helm.sh/stable
- name: incubator
  url: https://charts.helm.sh/incubator
- name: common
  url: https://charts.bitnami.com/bitnami
releases:
- chart: bitnami/redis
  version: 14.8.11
  name: redis
  namespace: my-ns
  labels:
    app: redis
    chart: redis
    name: redis
    namespace: my-ns
  values:
  - ../../bases/values.yaml.gotmpl

  chartVersion: 14.8.11
  environment: dev
  mastercpulim: 1
  mastercpureq: 200m
  mastermemlim: 2Gi
  mastermemreq: 512Mi
  namespace: my-ns
  p12password: XXXXXXXXXXXXXXXX
  password: XXXXXXXXXXXX
  redistag: 6.2.6-debian-10-r53
  releaseName: redis
  replicacpulim: 1
  replicacpureq: 200m
  replicamemlim: 2Gi
  replicamemreq: 512Mi
  sentcpulim: 1
  sentcpureq: 200m
  sentineltag: 6.2.6-debian-10-r54
  sentmemlim: 2Gi
  sentmemreq: 512Mi
  storageClass: ceph
  vaultEndpoint: https://vault-example.com
```
Try to deploy the helmchart with helmfile and you will see an error complaining on missing templates.

**Comment by mumoshu** [comment]
@AbbasHallal Hey! I think you're misunderstanding helmfile value templates. A helmfile value template has nothing to do with a chart template. So obviously you can't use any template helpers defined in a helm chart (like bitnami commons chart) from within a helmfile values template `values.yaml.gotmpl`.

I'm closing this as answered but please feel free to reopen if necessary. Thanks!

**Comment by AbbasHallal** [comment]
Hello @mumoshu again, Well maybe I am still misunderstanding it. I am using now another **base** chart `prometheus-community/prometheus-elasticsearch-exporter` and as mentioned before I am using values.yaml.gotmpl in order to achieve the templating over different environments. Still getting errors when deploying: 

> failed to render values files "../../bases/values.yaml.gotmpl": failed to render [../../bases/values.yaml.gotmpl], because of template: stringTemplate:224:79: executing "stringTemplate" at <{{template "elasticsearch-exporter.fullname" .}}>: template "elasticsearch-exporter.fullname" not defined

The _helpers.tpl is being ignored and the chart is failing to be deployed.

**Comment by mumoshu** [comment]
@AbbasHallal Helmfile's values template doesn't support user-defined helpers! Users-defined helpers(a.k.a template partials) are a feature of Helm, not Helmfile.

https://helm.sh/docs/chart_template_guide/named_templates/#partials-and-_-files

**Comment by AbbasHallal** [comment]
@mumoshu Thanks for being so responsive! The problem is solved now which was due to something silly and didn't know where it was exactly but wiping the values.yaml.gotmpl and just adding the values that needs to overridden solved the issue and now the chart is deployed via helmfile smoothly. 
```
securityContext:
  enabled: false
resources:
  requests:
     cpu: 100m
     memory: 128Mi
  limits:
     cpu: 100m
     memory: 128Mi
secretMounts:
  - name: elastic-certs
    secretName: elasticsearch-certificate
    path: /ssl
es:
  uri: https://{{ .Values.elasticusername }}:{{ .Values.elasticpassword }}@test-elastic-search-master.tst01.svc.cluster.local:9200
  cluster_settings: true
  timeout: 30s
  ssl:
    enabled: true
    useExistingSecrets: true
    ca:
      pem: ca.pem
    client:
      enabled: true
      pem: client.pem
      key: client.key
  sslSkipVerify: false
serviceMonitor:
  enabled: true
  namespace: "{{ .Values.monitoringNamespace }}"
service:
  metricsPort:
    name: https
```
Default values were all removed to keep it as simple as this.
