### ISSUE TITLE
bug report: the install order alway releases  after helmfiles if  releases  and  helmfiles both in helmfile.yaml

### ISSUE THREAD

**Issue by tanguofu** [roboll/helmfile#2025]
when then helmfile.yaml :
```
releases:
  - name: crd
     ...

#
helmfiles:
  - path: ti-scheduler-module/helmfile.yaml
  -..
```
then the `crd` is lastest installed
