### ISSUE TITLE
--state-values-set / --state-values-file are not propagated to sub helmfiles

### ISSUE THREAD

**Issue by dany74q** [roboll/helmfile#2027]
Heya @mumoshu !

The --state-values-set and --state-values-file flags are not propagated to sub-helmfiles, I've wondered if this is intetional.
That is, the following doesn't work:

`helmfile --state-values-set=pasten=pasten template`

```yaml
# helmfile.yaml
helmfiles:
  - pasten.helmfile.yaml

# pasten.helmfile.yaml
bases:
  - pasten.base.yaml

# pasten.base.yaml
environments:
  dev:
    values:
    - {{ .Values.pasten }}.state-values.yaml.gotmpl

# pasten.state-values.yaml.gotmpl
pasten: 1337
```

It yields the following:
`in ./helmfile.yaml: in .helmfiles[0]: in ./pasten.helmfile.yaml: error during pasten.base.yaml.part.0 parsing: template: stringTemplate:4:16: executing "stringTemplate" at <.Values.pasten>: map has no entry for key "pasten"`

The templating works as expected if you're using it at the parent helmfile level, though.
Was that by design ? if not, would it make sense to propagate them (and / or introduce a flag that will propagate them if set) ?

Thanks !
