### ISSUE TITLE
Secrets file not decrypted when used in environment

### ISSUE THREAD

**Issue by djolez** [roboll/helmfile#2030]
Hi, first of all thanks a lot for great work, I use `helmfile` extensively. It seems that I've hit an issue with the order of templating secrets vs values files. In my use case I need to use environments, here is the relevant part of the release file:

```
environments:
  test:
    secrets:
      - ../values/test/secret.yaml
    values:
      - ../values/test/templated.yaml.gotmpl
```

`values/test/templated.yaml.gotmpl`
```
secret: {{ .Values.from_secret_file }}
```
When I run `helmfile` I get an error `map has no entry for key "from_secret_file"` and from the logs I can see that the file wasn't decrypted (it's usually the first log line). If I comment out `values` then decryption works, so to me it seems that values files are loaded before secrets, and in the case when there are templated secrets in values this won't work properly.

Thanks in advance for your help.

**Comment by mumoshu** [comment]
@djolez Hey! There's no defined dependency/ordering between environment secrets and values. That said, you can't write a dynamic env values template that depends on env secrets that way.

I'd try

```
environments:
  test:
    secrets:
      - ../values/test/secret.yaml
---
environments:
  test:
    values:
      - ../values/test/templated.yaml.gotmpl
```

So that the Helmfile is able to load the first YAML doc to populate the environment that is used when loading the second YAML doc. I don't recommend writing such a complex helmfile.yaml but if that's the only way for you, try it!
