### ISSUE TITLE
helmfile jsonPatches and strategicmergePatches fails to patch conditionally applied CRD resources and removes them

### ISSUE THREAD

**Issue by Arabus** [roboll/helmfile#2031]
When I attempt to patch additional labels before deploying a resource derived from a CRD e.g., a `ServiceMonitor` from `monitoring.coreos.com/v1` then `helmfile template` complains with

```
in ./helmfile.yaml: [exit status 1

COMMAND:
  kustomize build /var/folders/t8/6h6ygbwd3xsbyz9zfgjbmf200000gn/T/chartify2441895969/starboard-system/starboard-exporter/starboard-exporter --output /var/folders/t8/6h6ygbwd3xsbyz9zfgjbmf200000gn/T/chartify2441895969/starboard-system/starboard-exporter/starboard-exporter/all.patched.yaml

OUTPUT:
  Error: no matches for Id monitoring.coreos.com_v1_ServiceMonitor|~X|starboard-exporter; failed to find unique target for patch monitoring.coreos.com_v1_ServiceMonitor|starboard-exporter]
```

If I use a jsonPatch instead, it silently ignores the patch and removes the resource completely from the result!

This also happens with `helmfile apply` and `sync`.

### Code

Helmfile with patch

```
repositories:
  - name: giantswarm
    url: https://giantswarm.github.io/giantswarm-catalog

  - name: starboard-exporter
    chart: ./starboard-exporter
    namespace: starboard-system
    strategicMergePatches:
      - apiVersion: monitoring.coreos.com/v1
        kind: ServiceMonitor
        metadata:
          name: starboard-exporter
          labels:
            release: kube-prometheus-stack
```

Helm template file to be patched after templating (from <https://github.com/giantswarm/starboard-exporter/blob/main/helm/starboard-exporter/templates/servicemonitor.yaml>)

```
{{ if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.monitoring.serviceMonitor.enabled }}
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
  {{- include "labels.common" . | nindent 4 }}
  {{- with .Values.monitoring.serviceMonitor.labels }}
      {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
  {{- include "labels.selector" . | nindent 6 }}
{{- end }}
```

### Relevant Metadata

```
❯ helmfile version
helmfile version v0.142.0


❯ helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}

❯ helm plugin list
NAME    VERSION DESCRIPTION
diff    3.1.3   Preview helm upgrade changes as a diff


❯ kustomize version
{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:27:14Z GoOs:darwin GoArch:arm64}

❯ go version
go version go1.17.5 darwin/arm64


❯ sw_vers
ProductName:    macOS
ProductVersion: 11.6.2
BuildVersion:   20G314
```

### Additional Info

I assume this happens, because chartify does not know about the capabilities of the target cluster which results in helm excluding the resource from the release. Unfortunately I cannot employ the workaround (see below) inside a templating pipeline without a connection a running cluster that has this CRD deployed.

There is the `--args` parameter that should in theory allow me to pass `--api-versions monitoring.coreos.com/v1` to `helm template`. Unfortunately I does not seem to work in this case, the output of `helmfile --debug template` show no such argument in the list:

```
running helm fetch giantswarm/starboard-exporter --untar -d /var/folders/t8/6h6ygbwd3xsbyz9zfgjbmf200000gn/T/chartify2669589207/starboard-system/starboard-exporter
options: {false [] [] [] starboard-system  false false true}
running helm template --debug=false --output-dir=/var/folders/t8/6h6ygbwd3xsbyz9zfgjbmf200000gn/T/chartify2669589207/starboard-system/starboard-exporter/starboard-exporter/helmx.1.rendered starboard-exporter /var/folders/t8/6h6ygbwd3xsbyz9zfgjb
mf200000gn/T/chartify2669589207/starboard-system/starboard-exporter/starboard-exporter -f /var/folders/t8/6h6ygbwd3xsbyz9zfgjbmf200000gn/T/chartify2669589207/starboard-system/starboard-exporter/starboard-exporter/values.yaml --namespace starboard-system
```

I further assume this is because `--args` is not passed to chartifys version of `helm template`.

While the behaviour of strategicMergePatch is annoying and blocking jsonPatches is even worse because it not only omits the patch from the helm template output but also all capabilities based conditional templates and does so silently. During initial installation this might just result in a release that is missing resources or is not configured right,. During apply on an existing release this would outright delete existing resources, which could lead to dataloss or worse.

#### Workaround

I can run `helmfile template` and `helmfile apply` with the `--validate` flag, which makes the capabilities of the server side available to helm templates.

### Desired Behaviour

Allow me to provide a cli and/or configurable way to provide cluster resource capabilities to allow for proper patching and templating.

**Comment by Arabus** [comment]
Note; there is already an option for this `apiVersions`, but it appears it is not passed to the template call when using chartify

**Comment by mumoshu** [comment]
@Arabus Thanks for reporting! Would you mind confirming that it works with `helmfile apply --validate`?

```
$ helmfile apply -h | grep validate
   --validate                  validate your manifests against the Kubernetes cluster you are currently pointing at. Note that this requiers access to a Kubernetes cluster to obtain information necessary for validating, like the list of available API versions
```

**Comment by mumoshu** [comment]
@Arabus For cases where you don't want to rely on `--validate`(like you don't like cluster access just for rendering templates` I believe it should be great to have support for api-versions in chartify.
I've created an issue for that at https://github.com/variantdev/chartify/issues/15. Please feel free to leave comment/feedback/etc.
I'd also appreciate it if you could contribute it! Thanks.

**Comment by Arabus** [comment]
I can confirm that `helmfile apply --validate` contains the `ServiceMonitor` resource in question in the diff output against a running cluster with the `monitoring.coreos.com/v1` CRD deployed.

In addition I can confirm that if using a strategicMergePatch the resource is properly patched and according to debug output the `--validate` flag is passed to chartifys `helm template` command.

The flag is also passed when using a jsonPatch though the jsonPatch is not applied.

The unpatched resource looks like this:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: starboard-exporter
    app.giantswarm.io/branch: HEAD
    app.giantswarm.io/commit: 207abb88a43d59d828369c6c02df9b094b3971d8
    app.kubernetes.io/instance: starboard-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: starboard-exporter
    app.kubernetes.io/version: 0.2.0
    helm.sh/chart: starboard-exporter-0.2.0
  name: starboard-exporter
  namespace: starboard
spec:
  endpoints:
  - path: /metrics
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: starboard-exporter
      app.kubernetes.io/name: starboard-exporter
```

And the jsonPatch like this:
```
- op: add
  path: /metadata/labels/release
  value: kube-prometheus-stack
```

I am also still wary about the issue of jsonPatch silently passing if it doesn't match anything. I'd propose at least throwing a warning that the patch could not be applied.
