### ISSUE TITLE
[QUESTION] How to access values from 'releases:' on 'prepare' hook?

### ISSUE THREAD

**Issue by sergiomacedo** [roboll/helmfile#2033]
I'd like to access version and commit tag values from a values file presented configured in the 'releases:' block on the 'prepare' hook.

These are minimal yaml files for the desired setup. Company-app is a private chart for all company's apps to use. version.yaml contains ```version:``` and ```commit:```.

```
releases:
  - chart: company-app/company-app
    name: myapp
    namespace: myapp
    values:
      - ./values/version.yaml
      - ./values/base.yaml.gotmpl
    hooks:
        - events: ['prepare']
         command: "echo"
          args: [ "{{ env "TAG" | default "undefined" }}" , "{{`{{ .Values }}`}}", "charts/{{`{{ .Release.Name }}`}}/company-app/Chart.yaml"]
          showlogs: true
environments:
  homolog:
    values:
      - values/HOMOLOG.yaml
  production:
    values:
      - values/PRODUCTION.yaml
```

My base.yaml.gotmpl handle the environments this way:
```
# Load environment variables before merging
{{ toYaml .Environment.Values }}

# Default values for all environments
# Merge with environment objects, when needed
serviceAccount:
  create: true
  {{ toYaml .Environment.Values.serviceAccount | nindent 2 }}

useNewrelic: true

configMapEnvData:
  SKIP_UPLOAD: "false"
  PORT: "3000"
  {{ toYaml .Environment.Values.configMapEnvData | nindent 2 }}
```

When I run ```helmfile -e homolog template``` the log from the prepare hook only shows the values from the environment file. I expected to see all values at this point.

Is it possible to access the values from the ```releases:``` statement? What am I doing wrong here?

**Comment by mumoshu** [comment]
@sergiomacedo I thought it was possible with
```
args: [ "{{`{{ .Release.Values | get "whatever.key.you.want" "here's the default value" }}`}}"]
```

Could you confirm?

**Comment by sergiomacedo** [comment]
@mumoshu your line returns an error:

```
$ helmfile -e homolog template
in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: line 37: did not find expected ',' or ']'
$ helmfile --version
helmfile version v0.139.9
```

Removing the "get" function returns only the list of files on the releases.values block.
```
          args: ["{{`{{ .Release.Values }}`}}"]

$ helmfile -e homolog template
[...]
hook[prepare] logs | [values/version.yaml values/base.yaml.gotmpl]
```

**Comment by GMartinez-Sisti** [comment]
I'm having the same error when using values from environment: `did not find expected ',' or ']'`.

Using the value directly with helmfile templating works, but sending it to helm will cause that error.

**Comment by mumoshu** [comment]
@sergiomacedo @GMartinez-Sisti Well I made a mistake in my example but anyway, you definitely need to add `,` between array items to make it a valid YAML expression.

**Comment by sergiomacedo** [comment]
@mumoshu ok, but I'm too dumb to infer the correct line. 😅 Would you mind to send the correct one?

**Comment by mumoshu** [comment]
>           args: ["{{`{{ .Release.Values }}`}}"]

@sergiomacedo Here it is.

**Comment by sergiomacedo** [comment]
@mumoshu I'm a bit lost now. The line above was the one I used to see the map and file list. I tought you had a correct version for your line:

args: [ "{{`{{ .Release.Values | get "whatever.key.you.want" "here's the default value" }}`}}"]


As I said, the line just with .Release.Values shows the map for values defined directly in the releases.values AND a list of files that seems to be processed later:
```
[...]
    hooks:
        - events: ['prepare']
          command: "echo"
          args: ["{{`{{ .Release.Values }}`}}"]
          showlogs: true
    values:
      - foo: "bar"
      - values/version.yaml
      - values/base.yaml.gotmpl
[...]
```
```
$ helmfile -e homolog template
[...]
hook[prepare] logs | [map[foo:bar] values/version.yaml values/base.yaml.gotmpl]
```
