### ISSUE TITLE
helmfile transformers fix

### ISSUE THREAD

**Issue by tomassatka** [roboll/helmfile#2035]
Hi team

I made a fix for non working transformers:

Before the change when applying transformers user got following error from kustomize binary that kustomize failed and the reason was that in kustomization.yaml file were referred files inside helmx.1 directory however the directory was not existing at that point of time

```bash
tomas@tomas-ThinkPad-W550s:~/Develop/test$ helmfile template 
in ./helmfile.yaml: [exit status 1

COMMAND:
  kustomize build /tmp/chartify043502074/test --output /tmp/chartify043502074/test/all.patched.yaml

OUTPUT:
  Error: accumulating resources: accumulation err='accumulating resources from 'helmx.1.rendered/test/templates/serviceaccount.yaml': evalsymlink failure on '/tmp/chartify043502074/test/helmx.1.rendered/test/templates/serviceaccount.yaml' : lstat /tmp/chartify043502074/test/helmx.1.rendered: no such file or directory': evalsymlink failure on '/tmp/chartify043502074/test/helmx.1.rendered/test/templates/serviceaccount.yaml' : lstat /tmp/chartify043502074/test/helmx.1.rendered: no such file or directory]
```

solution was to remove the os.RemoveAll(helmOutputDir) poiting to helmx.1 dir

After removing and local testing the transformers works again.

Link to PR: https://github.com/variantdev/chartify/pull/13
fixes: https://github.com/roboll/helmfile/issues/1991

Kind regards
Tomas

**Comment by mumoshu** [comment]
@tomassatka This seems to happen only when you created helmfile.yaml within the local chart directory, and I have never expected any of you would do so!

Could you read my comments in the issue and the PR, and help me make a (seemingly) correct fix?

**Comment by armenr** [comment]
@mumoshu - I don't think your last comment is true...or maybe I'm misunderstanding. 

This is what my helmfile.yaml looks like, and I'm getting bitten by the same bug

```
helmDefaults:
  atomic: true
  cleanupOnFail: true
  force: false
  recreatePods: false
  skipDeps: true
  timeout: 600
  verify: false
  wait: true

commonLabels:
  system: argocd

releases:
  - name: argocd
    installed: true
    chart: "../../vendor-dependencies/argo-cd/synced/helm-chart/"
    version: ~4.2.1
    createNamespace: true
    namespace: argocd
    missingFileHandler: Warn
    values:
      - values.yaml
    strategicMergePatches:
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: argocd-cm
          namespace: argocd
        data:
          configManagementPlugins: |
            - name: helmfile
              init:
                command: ["sh", "-c"]
                args: ["helmfile repos"]
              generate:
                command: ["sh", "-c"]
                args: ["helmfile template --skip-deps"]


```
