### ISSUE TITLE
Layering Release Values

### ISSUE THREAD

**Issue by gakesson** [roboll/helmfile#2037]
Hello,

In the [The Helmfile Best Practices Guide](https://github.com/roboll/helmfile/blob/master/docs/writing-helmfile.md) below is documented:

_**Layering Release Values**
Please note, that it is not possible to layer values sections. If values is defined in the release and in the release template, only the values defined in the release will be considered. [...]_

However even though this is true for values, helmfile allows layering when valuesTemplate is defined in the release template and values is defined in the release.

So either this shouldn't be supported either, or documentation needs update.
Thoughts?

**Comment by mumoshu** [comment]
> However even though this is true for values, helmfile allows layering when valuesTemplate is defined in the release template and values is defined in the release.

Good catch! Yeah it should be technically possible today but I'd say it's unintended behavior. Perhaps it's better kept undocumented anyway so that we can safely "fix" it by dropping the support for layering release values?

**Comment by gakesson** [comment]
Thanks for getting back on this.

We actually utilize this loophole to our benefit, and I think values layering has its use-cases.
We have a helmfile structure/hierarchy in which a particular helmfile's releases gets its values from .Values, which contain both global values (applicable for every release) as well as release-specific values:

```
templates:

  commonReleaseConfig: &commonReleaseConfig
    namespace: {{ .Namespace }}
    labels:
      app: services-app
    valuesTemplate:
    {{- if ($config := (.Values | get "global" nil)) }}
      {{- $config | toYaml | indent 6 | printf "\n    -\n%s" }}
    {{- end }}

releases:

- name: service-a
  <<: *commonReleaseConfig
  chart: service-repo/service-a
  version: 2.1.0+11
  values:
  {{- if ($config := (.Values | get "service-a" nil)) }}
    {{- $config | toYaml | indent 4 | printf "\n  -\n%s" }}
  {{- end }}

- name: service-b
  <<: *commonReleaseConfig
  chart: service-repo/service-b
  version: 1.4.0+29
  values:
  {{- if ($config := (.Values | get "service-b" nil)) }}
    {{- $config | toYaml | indent 4 | printf "\n  -\n%s" }}
  {{- end }}
```

Ideally I would like to use the release templating to also handle the release-specific values, i.e. described in this question:
https://stackoverflow.com/questions/70501652/helmfile-release-templating (not sure if you know the answer to this question?)

But even with that I see other use-cases for us to use this type of values layering in order to DRY.

**Comment by mumoshu** [comment]
@gakesson I think you should write it like the below:

```
releases:

- name: service-a
  <<: *commonReleaseConfig
  chart: service-repo/service-a
  version: 2.1.0+11
  values:
  - {{ merge (.Values | get "global" dict()) (.Values | get "service-a" nil) | nindent 4 }}

- name: service-b
  <<: *commonReleaseConfig
  chart: service-repo/service-b
  version: 1.4.0+29
  values:
  - {{ merge (.Values | get "global" dict()) (.Values | get "service-b" nil) | nindent 4 }}
```

**Comment by mumoshu** [comment]
Here's more complete example:

```
values:
- service-a:
    a: A
  service-b:
    b: B
  global:
    global: GLOBAL

---

templates:

  commonReleaseConfig: &commonReleaseConfig
    namespace: {{ .Namespace }}
    labels:
      app: services-app

releases:

- name: service-a
  <<: *commonReleaseConfig
  chart: service-repo/service-a
  version: 2.1.0+11
  values:
  - {{ merge ((.Values | get "global" (dict)) | merge (dict)) (.Values | get "service-a" nil) | toYaml | nindent 4 }}

- name: service-b
  <<: *commonReleaseConfig
  chart: service-repo/service-b
  version: 1.4.0+29
  values:
  - {{ merge ((.Values | get "global" (dict)) | merge (dict)) (.Values | get "service-b" nil) | toYaml | nindent 4 }}
```

`helmfile build` is your friend for debugging 😄 

```
$ ./helmfile -f helmfile.2037.yaml build
DEBUG /home/mumoshu/bin/helm [helm version --client --short]
---
#  Source: helmfile.2037.yaml

filepath: helmfile.2037.yaml
helmBinary: helm
values:
- global:
    global: GLOBAL
  service-a:
    a: A
  service-b:
    b: B
releases:
- chart: service-repo/service-a
  version: 2.1.0+11
  name: service-a
  labels:
    app: services-app
  values:
  - a: A
    global: GLOBAL
- chart: service-repo/service-b
  version: 1.4.0+29
  name: service-b
  labels:
    app: services-app
  values:
  - b: B
    global: GLOBAL
templates:
  commonReleaseConfig:
    labels:
      app: services-app
renderedvalues:
  global:
    global: GLOBAL
  service-a:
    a: A
  service-b:
    b: B
```

**Comment by gakesson** [comment]
@mumoshu
Thanks!
The cumbersome aspect I see it is that that value section has to be repeated for every release (we have one helmfile with 60 releases). It would have been neat if there is any current way of expressing this in the release template.

**Comment by mumoshu** [comment]
@gakesson Hey! What you want seems like a more like programmatic approach to making it DRY.

Try defining data of your choice under `values` and use that to dynamically generate releases, like:

```
values:
- releases:
    service-a:
      version: 2.1.0+11
       ....
    service-b:
      version: 1.4.0+29
      ...

---

releases:
{{ range $name, $r := .Values.releases }}
- name: {{ $name }}
  chart: service-repo/{{ $name }}
  version: {{ $r.version }}
  values:
  - {{ merge ((.Values | get "global" (dict)) | merge (dict)) (.Values | get $name nil) | toYaml | nindent 4 }}
{{ end }}
```
