### ISSUE TITLE
helmfile apply: increasing revision without any change in manifest

### ISSUE THREAD

**Issue by leo191** [roboll/helmfile#2046]
helmfile.yaml
```
  repositories:
  - name: stable
    url: s3://awesomecharts/charts
  templates:
    default: &default
      chart: {{ requiredEnv "repo" }}/{{`{{ .Release.Name }}`}}
      missingFileHandler: Warn
      setTemplate:
      - name: ingress.hosts[0].paths[0]
        value: '/api/{{`{{ .Release.Name }}`}}(/|$)(.*)'
      values:
        - replicaCount: 1
          service:
            type: ClusterIP
          ingress:
            enabled: true
            hosts:
              - host:  {{ requiredEnv "HOST" }}
            tls: []
            annotations:
              kubernetes.io/ingress.class: "nginx"
          resources:
            limits:
              cpu: 200m
              memory: 0.5Gi
            requests:
              cpu: 200m
              memory: 0.5Gi
  helmDefaults:
    atomic: true 
    createNamespace: true        
    cleanupOnFail: true  
    timeout: 300
    wait: true
  releases:
  - name: mychart
    namespace: somename
    version: 4.0.0
    <<: *default
```

command: `helmfile -i --file helmfile.yaml apply`
output:

```
Comparing release=mychart, chart=stable/mychart
somename, mychart, Deployment (apps) has changed:
...
    template:
      metadata:
        annotations:
-         rollme: "kOIEh"
+         rollme: "cdR18"
...
```

each time this rollme annotation is changing not sure why.
