### ISSUE TITLE
repositories sync should be first when used in `helmfiles`

### ISSUE THREAD

**Issue by codering** [roboll/helmfile#2047]
My helmfile :

```yml

repositories:
  - name: test
    url: git+ssh://git@codehub.devcloud.cn-east-3.mygitlab.com/jcss00001/helm-charts@charts?ref=v0.2.0&sparse=0

helmfiles:
  - app/*/helmfile.yaml

```

when run `helmfile sync `,  the output is :
```sh
❯ helmfile sync
Affected releases are:
  asset-service-1 (test/springboot) UPDATED
  asset-web-1 (test/frontend) UPDATED

Upgrading release=asset-service-1, chart=test/springboot
Upgrading release=asset-web-1, chart=test/frontend
...
...
UPDATED RELEASES:
NAME              CHART              VERSION
asset-service-1   test/springboot     0.2.0
asset-web-1       test/frontend       0.2.0

Adding repo test git+ssh://git@codehub.devcloud.cn-east-3.mygitlab.com/jcss00001/helm-charts@charts?ref=v0.2.0&sparse=0
"test" has been added to your repositories

```

if I change versions of repo and chart, then `helmfile sync` run failed,  because the repo hasn't been updated yet.

```
❯ helmfile sync
Affected releases are:
  asset-service-1 (test/springboot) UPDATED
  asset-web-1 (test/frontend) UPDATED

Upgrading release=asset-service-1, chart=test/springboot
Upgrading release=asset-web-1, chart=test/frontend

FAILED RELEASES:
NAME
asset-web-1
asset-service-1
in ./helmfile.yaml: in .helmfiles[0]: in app/asset/helmfile.yaml: 2 errors:
err 0: failed processing release asset-web-1: command "/Users/xxx/.asdf/shims/helm" exited with non-zero status:
...
...
COMBINED OUTPUT:
  Error: failed to download "test/frontend" at version "0.1.0"
...
...
COMBINED OUTPUT:
  Error: failed to download "test/springboot" at version "0.1.0"

```
