### ISSUE TITLE
Cannot use dict as variable in env?

### ISSUE THREAD

**Issue by rlex** [roboll/helmfile#2050]
Trying to install metallb with envs enabled using helmfile
Both installations have this block:
```
  address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 1.1.1.1/32
```

With different IPs, obviously.

I specify it in env as follows:
```
global_metallb_configinline:
  address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 1.1.1.1/32
````

And then use in actual release as 
```
repositories:
  - name: metallb
    url: https://metallb.github.io/metallb
bases:
  - ../../environments/environments.yaml
---
releases:
  - name: metallb
    namespace: metallb-system
    kubeContext: {{ .Values.global_kubecontext }}
    createNamespace: true
    chart: metallb/metallb
    values:
    - controller:
        nodeSelector:
          node-role.kubernetes.io/master: "true"
    - speaker:
        nodeSelector:
          node-role.kubernetes.io/worker: "true"
    - configInline: {{ .Values.global_metallb_configinline }}
    - prometheus:
        podMonitor:
          enabled: true
        prometheusRule:
          enabled: false
          addressPoolExhausted:
            enabled: false
          addressPoolUsage:
            enabled: false
    - tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: kubernetes.io/role
          operator: master
          effect: NoSchedule
    - psp:
        create: false
```

However, actual config being generated ends up as 
```
map[address-pools:[map[addresses:[1.1.1.1] name:default protocol:layer2]]]
```

Seems like arrays and strings works nice, but something a bit more complex breaks it?

I tried with toYaml and stuff, hasn't worked for me.
