### ISSUE TITLE
regression in 0.143.0: flag --allow-no-matching-release does not work as in version 0.142.0

### ISSUE THREAD

**Issue by damoon** [roboll/helmfile#2062]
example helmfile:
```
repositories:
  - name: mittwald
    url: https://helm.mittwald.de
releases:
  - name: secret-generator
    namespace: kube-system
    chart: mittwald/kubernetes-secret-generator
    installed: false
    labels:
      phase: delete
  - name: secret-generator
    namespace: kube-system
    chart: mittwald/kubernetes-secret-generator
    version: 3.3.4
    values:
      - resources:
          limits:
            cpu: 100m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 400Mi
    strategicMergePatches:
      - fix-locked-leader.yaml

```

used command:
```
helmfile --state-values-file=/path/config.yaml --file=/path/helmfile.yaml --allow-no-matching-release --selector phase=setup  sync --skip-crds
```

thrown exception:
```
panic: assertion error: release "kube-system/secret-generator" has never been selected. This shouldn't happen!

goroutine 1 [running]:
github.com/roboll/helmfile/pkg/app.(*App).getSelectedReleases(0xc0001990e0, 0xc00031e000, 0x37)
	/home/circleci/workspace/helmfile/pkg/app/app.go:1207 +0xebe
github.com/roboll/helmfile/pkg/app.(*App).sync(0xc0001990e0, 0xc00031e000, {0x1ae5e88, 0xc0002a9700})
	/home/circleci/workspace/helmfile/pkg/app/app.go:1645 +0x95
github.com/roboll/helmfile/pkg/app.(*App).Sync.func1.1()
	/home/circleci/workspace/helmfile/pkg/app/app.go:368 +0x3b
github.com/roboll/helmfile/pkg/app.(*Run).withPreparedCharts(0xc00031e000, {0x15c4d61, 0x4}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000b54050, ...}, ...)
	/home/circleci/workspace/helmfile/pkg/app/run.go:91 +0x5ca
github.com/roboll/helmfile/pkg/app.(*App).Sync.func1(0xc00031e000)
	/home/circleci/workspace/helmfile/pkg/app/app.go:360 +0x234
github.com/roboll/helmfile/pkg/app.(*App).ForEachState.func1(0xc0005b4000)
	/home/circleci/workspace/helmfile/pkg/app/app.go:899 +0xef
github.com/roboll/helmfile/pkg/app.(*App).visitStates.func1({0x7ffc95adedb1, 0xd}, {0x7ffc95aded71, 0x3f})
	/home/circleci/workspace/helmfile/pkg/app/app.go:847 +0x722
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles.func1()
	/home/circleci/workspace/helmfile/pkg/app/app.go:679 +0x76
github.com/roboll/helmfile/pkg/app.(*App).within(0xc0001990e0, {0x7ffc95aded71, 0x3f}, 0xc00089d4a0)
	/home/circleci/workspace/helmfile/pkg/app/app.go:640 +0x267
github.com/roboll/helmfile/pkg/app.(*App).visitStateFiles(0xc0001990e0, {0x7ffc95aded71, 0xc00026fa38}, {{0xc0002a9290, 0x1, 0x1}, {{0xc0002a9720, 0x1, 0x1}}, 0x0, ...}, ...)
	/home/circleci/workspace/helmfile/pkg/app/app.go:673 +0x373
github.com/roboll/helmfile/pkg/app.(*App).visitStates(0xc0001990e0, {0x7ffc95aded71, 0x40cc94}, {{0xc0002a9290, 0x1, 0x1}, {{0xc0002a9720, 0x1, 0x1}}, 0x0, ...}, ...)
	/home/circleci/workspace/helmfile/pkg/app/app.go:759 +0xdd
github.com/roboll/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport(0xc0001990e0, {0x7ffc95aded71, 0x4d}, 0xc00089d760, 0x0, {0x0, 0x0, 0x15e1af9})
	/home/circleci/workspace/helmfile/pkg/app/app.go:1019 +0x4b2
github.com/roboll/helmfile/pkg/app.(*App).ForEachState(0xc0001990e0, 0xc00089d7c8, 0xe8, {0x0, 0x0, 0x0})
	/home/circleci/workspace/helmfile/pkg/app/app.go:895 +0xe5
github.com/roboll/helmfile/pkg/app.(*App).Sync(0xc0001990e0, {0x1ae5e88, 0xc0002a9700})
	/home/circleci/workspace/helmfile/pkg/app/app.go:357 +0x8a
main.main.func9(0x1ae5c98, {0xc00003cc60, 0x0})
	/home/circleci/workspace/helmfile/main.go:441 +0x4e
main.action.func1(0xc00003cc60)
	/home/circleci/workspace/helmfile/main.go:961 +0x86
github.com/urfave/cli.HandleAction({0x132e040, 0xc0002a8c60}, 0x4)
	/home/circleci/workspace/helmfile/vendor/github.com/urfave/cli/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0x15c4d61, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x16175c1, 0x43}, {0x0, ...}, ...}, ...)
	/home/circleci/workspace/helmfile/vendor/github.com/urfave/cli/command.go:173 +0x652
github.com/urfave/cli.(*App).Run(0xc0003836c0, {0xc00013a000, 0x8, 0x8})
	/home/circleci/workspace/helmfile/vendor/github.com/urfave/cli/app.go:277 +0x705
main.main()
	/home/circleci/workspace/helmfile/main.go:692 +0x5005
```
