### ISSUE TITLE
[QUESTION] How to pass credentials without declaring in plain text in the repo?

### ISSUE THREAD

**Issue by tomjohnburton** [roboll/helmfile#2069]
I'm running deployments of our app in our CI and obviously don't want to store a file with plain text passwords in it. 

Am I missing something?

**Comment by mugioka** [comment]
Using [helm-secrets](https://github.com/jkroepke/helm-secrets) seems to be the way to go.
refs: https://github.com/roboll/helmfile#secrets

**Comment by andrewnazarov** [comment]
Something like
```
repositories:
  - name: chainflip
    url: https://charts.chainflip.xyz
    username: xxx
    password: {{ env "MY_SECRET_PASSWORD" }}
```
can be considered as a workaround. Especially if your CI/CD system can treat env vars as secrets not showing them in outputs. Don't know if [vals functionally](https://github.com/roboll/helmfile/blob/master/docs/remote-secrets.md) works in `repositories:`. Presumably, it doesn't. Haven't tried this out.
