### ISSUE TITLE
Support helm --set-file

### ISSUE THREAD

**Issue by clkao** [roboll/helmfile#207]
With @mumoshu's [--set-file](https://github.com/helm/helm/pull/3758) merged and helm v2.10.0-rc.2 released, helmfile should support this if possible.

**Comment by mumoshu** [comment]
@clkao Thanks for the notice! I'd definitely like add --set-file support.

Any preference on the config syntax for that?

I was considering:

```yaml
values:
- ...
files:
  foo: foofile
```

and for consistency with the `values`, which is a yaml array:

```yaml
values:
- ...
files:
- foo: foofile
```

Now, I started to prefer this:

```yaml
values:
- ...
valueGenerators:
  # "file" generator generates a single chart value from a local file
  file:
    foo: foofile
```

Or

```yaml
values:
- ...
# "fileValueGenerator" generates a single chart value from a local file
fileValueGenerator:
  foo: foofile
```

**Comment by clkao** [comment]
Since `values` are currently for loading and merging a full object, would it make sense to provide set-file as --set with alternative key for consistency?  for example:

```
set:
  - name: project.regularKey
     value: regularValue
  - name: project.fileContentKey
     valueFromPath: /path/to/file
```

**Comment by mumoshu** [comment]
@clkao Thanks for the suggestion!

According to discussions made in another gh issues, I was considering to deprecate `set:` in favor of inline `values:` because the former may suffer from type confusion. See #119 for more context

Sorry for missing the context here. But I'd really appreciate it if I could hear from you about possible alternatives without leveraging `set:`. Thanks for again for the suggestion!

**Comment by mumoshu** [comment]
I'm a bit afraid being ambiguous between values files(values.yaml's) vs --set-file's.

How about this?

```yaml
values:
- ./myvalues.yaml
singleValueFromFile:
  foo.bar: path/to/file
```

to be translated to:

```
helm upgrade --install -f ./myvalues.yaml --set-file foo.bar=path/to/file
```

**Comment by sstarcher** [comment]
With the existence of `set-file` it likely makes sense to fully deprecate `set` and have this feature supplant it.

**Comment by mumoshu** [comment]
Thanks! Yes, that's my idea.

One more alternative that may not suffer from the merge ordering issue is to rely on a special yaml hash in an inlile values to trigger file-set:

```yaml
values:
- ./myvalues.yaml
- foo:
    bar:
      valueFromFile: path/to/file
    baz: inlineval1
- another:
     setting: inlineval2
```

This looks cleaner at glance. And it would work as long as no one use the special key in actual values.yaml.

**Comment by clkao** [comment]
`valueFromFile` sounds dangerously prone to collision. how about with a prefix like:

```yaml
values:
- ./myvalues.yaml
- foo:
    bar:
      -valueFromFile: path/to/file
    baz: inlineval1
- another:
     setting: inlineval2
```

**Comment by sstarcher** [comment]
I would support inlining it under `values` and detecting if it's a map or a string.

**Comment by mumoshu** [comment]
@clkao @sstarcher Sounds nice! Thanks for all the feedbacks.

One thing is that I'm too nervous that using `-` for the special suffix worries me about that some implementations may misinterpret it as a list...
I'll try to use `_` hence `_valueFromFile: path/to/file` in my first POC. Please feel free to provide any feedback on that too.

**Comment by mumoshu** [comment]
After thinking about this for a while, the implementation for my suggested solution is unnecessarily hard.
Do you need to parse the example below, to produce `--set-file foo.bar=path/to/file --values /tmp/xxxxinlineval1.yaml`?

```
- foo:
    bar:
      valueFromFile: path/to/file
    baz: inlineval1
```

Also, I now remember the support for set and set-string is still useful for setting a single array item as discussed in https://github.com/roboll/helmfile/issues/148#issuecomment-394941544

**Comment by mumoshu** [comment]
I'm discarding this alternative idea because it is too verbose 😆 

```yaml
values:
- ./myvalues.yaml
- setFile:
   - key: fooArray[0]
     value: path/to/file
- setString:
  - key: barArray[1]
    value: bar
- set:
  - key: bazArray[0]
    value: inlineval1
- another:
    setting: inlineval2
```

**Comment by mumoshu** [comment]
I bascially came back to @clkao's [original suggestion](https://github.com/roboll/helmfile/issues/207#issuecomment-410952564). Thanks again for the idea @clkao!

So, what we will have looks like:

```yaml
set:
# this is ok as of today, but should emit a validation error in near future - you can safely use inline values instead
- name: project.regularKey
  value: regularValue
# to be implemented. should emit a validation error. use inline values instead
- name: project.regularKey
  string: regularValue
# ok. helm is unable to deep merge arrays so this is the only way to set single item in an array
# ref https://github.com/helm/helm/issues/3486
- name: someArray[0]
  value: regularValue
# ok. translated to --set someArray[0]={1,2,3}
- name: someArray[0]
  - 1
  - 2
  - 3
# ok. translated to --set someArray[0]=1\,2\,3
- name: someArray[0]
  value: 1,2,3
# ok. notice there is `string: ` instead of `value: `
- name: someArray[0]
  string: regularValue
# ok. set-file should be used regardless of the target is an array item or a value.
- name: project.fileContentKey
  valueFromPath: /path/to/file
```

As you've seen in the middle of the example above, I'll also revert #136 to address #148, and make values escape free according to https://github.com/roboll/helmfile/issues/148#issuecomment-394941544

You should use inline values whereas possible to avoid complexity, anyway 😉

**Comment by sstarcher** [comment]
Honestly the entire set setup would be good if it went away.  Putting values directly into helmfile bloats up the definition and understanding is better if everything is in separate files.  I would not be sad if this entire capability was removed.

**Comment by mumoshu** [comment]
@sstarcher Thx for the feedback again! Entirely removing the `set` capability, including the support for `--set-file`, right?

Personally saying, I had wanted `--set-file` to avoid embedding huge conf files(like nginx.conf for example) into values.yaml's.

Would it be an acceptable solution, if we add a special format of `values.yaml` to be automatically translated to `--set` variants?

```yaml
values:
- values.yaml
- sets.yaml
```

sets.yaml:

```yaml
helmfile:
  set:
  - name: project.fileContentKey
    valueFromPath: /path/to/file
```
