### ISSUE TITLE
Values from secrets added in release object are not available in gotmpl file

### ISSUE THREAD

**Issue by MurzNN** [roboll/helmfile#2070]
I have some secrets for specific chart, that not depend on environment, so I fill them into `variables/my-chart/secrets.yaml` file, and add link to this file into release configuration:
```yaml
releases:
  - name: my-chart
    chart: my-chart
    namespace: my-chart
    secrets:
      - ./variables/my-chart/secrets.yaml
    values:
      - ./variables/my-chart/values.yaml.gotmpl
```
But they become not available in `values.yaml.gotmpl` file. If I move them back to `environments.default.secrets` section - they become available.
Is there any ways to make those secrets from releases available in go templating?
