### ISSUE TITLE
Add environments structure to Conventional Directory Structure

### ISSUE THREAD

**Issue by MurzNN** [roboll/helmfile#2073]
In the `writing-helmfile.md` file [here](https://github.com/roboll/helmfile/blob/061644c5d07c119527f19372d5e7b32cb350bfc7/docs/writing-helmfile.md?plain=1#L50) we already have a Conventional Directory Structure for per-release files like this:
```yaml
  values:
  - "./config/heapster/values.yaml"
  - "./config/heapster/{{ .Environment.Name }}.yaml"
  secrets:
  - "./config/heapster/secrets.yaml"
  - "./config/heapster/{{ .Environment.Name }}-secrets.yaml"
```
But there is missing information about directory structure for environments files (per-environment values and secrets files). Will be good to add them too. 
We already have below some examples like this:
```yaml
environments:
  stage:
    values:
    - env/stage.yaml
  prod:
    values:
    - env/prod.yaml
```

But in main readme file we have another structure example:
```yaml
environments:
  default:
    values:
    - environments/default/values.yaml
  production:
    values:
    - environments/production/values.yaml
    secrets:
    - environments/production/secrets.yaml
```

So maybe let's select one most common option as convention and describe it?
