### ISSUE TITLE
Helmfile error "There are no repositories defined in your helmfile.yaml" even when repositories exist

### ISSUE THREAD

**Issue by vitorfhc** [roboll/helmfile#2074]
This was mentioned on #1052 but looks like the error is back.

I created [this repo](https://github.com/vitorfhc/helmfile-bug-reproduce) for reproducing the bug.

Helm: `version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}`

When I run `helmfile deps` I get the error:

```
Adding repo jetstack https://charts.jetstack.io
"jetstack" has been added to your repositories

Updating dependency /var/folders/wn/41tq8rb916xfp0tl5l_492kw0000gp/T/chartify3832583743/dep/dep-01
There are no repositories defined in your helmfile.yaml.
This means helmfile cannot update your dependencies or create a lock file.
See https://github.com/roboll/helmfile/issues/878 for more information.
```

But, as you can see [here](https://github.com/vitorfhc/helmfile-bug-reproduce/blob/main/helmfile.yaml#L1-L3), `repositories` is declared.

**Comment by denist-huma** [comment]
Have you tried to remove all related to jetstack?

```yaml
releases:
- name: dep-01
  namespace: dep
  createNamespace: true
  version: 0.1.0
  chart: ./dep-01
  values:
  - ./values.yaml
```

There is a usual way to write dependencies in the Helm chart's Chart.yaml
Helmfile will not work the way you wrote it anyway. It needs dependencies to be in the same list of releases, to control the sync actions sequence.

**Comment by vitorfhc** [comment]
@denist-huma One thing that is getting me confused is that I thought the need for it to be in the same releases list was only when using `needs`.

When you define a `dependency` using `Chart.yaml` it creates the release anyway, but it provides a syntax to show it's not just another release but a dependency.

It would be nice to `helmfile.yaml` to approach itself as much as possible to the original Helm's syntax.

**Comment by itscaro** [comment]
@vitorfhc I confirmed that there is a bug with `deps`


Test fixture:
```
repositories:
- name: jetstack
  url: https://charts.jetstack.io
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: dep-01
  namespace: dep
  createNamespace: true
  version: 9.0.1
  chart: bitnami/apache
  dependencies:
  - alias: certManager
    version: ~v1.7.0
    chart: jetstack/cert-manager
```

Note the `# Source` line show that `cert-manager` is handled as dep of `apache`
```
$ helmfile template

Adding repo jetstack https://charts.jetstack.io
"jetstack" has been added to your repositories

Adding repo bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories

Templating release=dep-01, chart=/tmp/chartify3308889910/dep/dep-01/apache
---
# Source: apache/templates/charts/certManager/templates/cainjector-serviceaccount.yaml
```

```
$ helmfile deps

Adding repo jetstack https://charts.jetstack.io
"jetstack" has been added to your repositories

Adding repo bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories

Updating dependency /tmp/chartify3254475594/dep/dep-01/apache
There are no repositories defined in your helmfile.yaml.
This means helmfile cannot update your dependencies or create a lock file.
See https://github.com/roboll/helmfile/issues/878 for more information.
```

Cf. https://github.com/roboll/helmfile/blob/fcf9a7273f9391627118eced20707a35170f33ee/pkg/state/chart_dependency.go#L196-L204

@mumoshu, do you have any hint? I'm not familiar with `chartify` part.
