### ISSUE TITLE
helmfile deps cannot create a lock file for an OCI repo

### ISSUE THREAD

**Issue by denist-huma** [roboll/helmfile#2076]
IMO it is related to https://github.com/roboll/helmfile/issues/2075 but have different way to discover.

## reproduce

helmfile:

```yaml
repositories:
  - name: huma
    url: ghcr.io/huma-engineering/helm-charts
    oci: true

releases:
  - name: compose-operator
    namespace: compose-operator
    # chart: ../charts/compose-operator
    chart: huma/compose-operator
    version: 0.39.0
```

Run helmfile deps
 
```sh
$ helmfile deps
Pulling ghcr.io/huma-engineering/helm-charts/compose-operator:0.39.0
Exporting ghcr.io/huma-engineering/helm-charts/compose-operator:0.39.0
Pulled: ghcr.io/huma-engineering/helm-charts/compose-operator:0.39.0
Digest: sha256:59632103db46727136a1cd08388cced3ee802e596f1d119a2b2bd6318b93fa06

Exporting ghcr.io/huma-engineering/helm-charts/compose-operator:0.39.0
Pulled: ghcr.io/huma-engineering/helm-charts/compose-operator:0.39.0
Digest: sha256:59632103db46727136a1cd08388cced3ee802e596f1d119a2b2bd6318b93fa06

Updating dependency /tmp/helmfile4265576871/compose-operator/compose-operator/compose-operator/0.39.0/compose-operator
There are no repositories defined in your helmfile.yaml.
This means helmfile cannot update your dependencies or create a lock file.
See https://github.com/roboll/helmfile/issues/878 for more information
```
