### ISSUE TITLE
Support user and group impersonation

### ISSUE THREAD

**Issue by ktarplee** [roboll/helmfile#2088]
For example the following are possible in other tools
- `kubectl --as=cluster-admin ...`
- `helm --kube-as-user cluster-admin ...`
- `k9s --as=cluster-admin ...`

The benefits are outlined nicely [here](https://johnharris.io/2019/08/least-privilege-in-kubernetes-using-impersonation/) and the k8s docs are [here]9https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation).

This does not work because when helmfile calls `helm diff` and it does not pass these arguments
```yaml
helmDefaults:
   args:
   - "--kube-as-user cluster-admin"
```
