### ISSUE TITLE
"env" Multi-line environment variables only gets the first line in the chart

### ISSUE THREAD

**Issue by alvgarvilla** [roboll/helmfile#2090]
We have a secret object for generating a TLS certificate:

```
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  labels:
    {{- include "certsecret.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.ingress.tls.signedCert.cert | b64enc }}
  tls.key: {{ .Values.ingress.tls.signedCert.key | b64enc }}
type: kubernetes.io/tls
```

both the "cert" and the "key" are injected through environment variables:

```
ingress:
  tls:
    signedCert:
      key: |
	{{ env "TLS_KEY" }}
      cert: | 
        {{ env "TLS_CERT" }}
```
But the secret generated only contains the first characters of the environment variable:

```
apiVersion: v1
kind: Secret
metadata:
  name: mapview-global-signed-tls
data:
  tls.crt: LS0tLS1CRUdJTgo=
  tls.key: LS0tLS1CRUdJTgo=
type: kubernetes.io/tls  
```
