### ISSUE TITLE
Using "helmfile template --output-dir-template" on a chart with subcharts/dependencies overwrites resources.

### ISSUE THREAD

**Issue by sanyu** [roboll/helmfile#2095]
Hi, I'm using version 0.143.0:
```sh
❯ helmfile version
helmfile version v0.143.0
```

We have encountered an issue that affects charts with dependencies/subcharts. When trying to patch a chart that includes multiple dependencies, the patch is applied successfully (running "_**helmfile template**_" will show the resource patched correctly), but if we add the _"**--output-dir-template $(pwd)/tmp/{{.Release.Name}}**"_ parameter to write the files to a directory, the resulting files get overwritten because each chart is writing to the same "**_patched_resources.yaml_**" file and we end up with the resources of the last chart rendered.This can be reproduced using the following helmfile.yaml file:

```yaml
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    version: 15.1.3
    values:
      - alertmanager:
          ingress:
            enabled: true
    jsonPatches:
      - target:
          kind: Ingress
          group: networking.k8s.io
          version: v1
          name: kube-prometheus-stack-alertmanager
        patch:
          - op: replace
            path: /spec/rules/0/http/paths/0/backend/service/name
            value: blah
```
Currently every resource is written to _$(pwd)/tmp/{{.Release.Name}}/{{CHART}}_, is there a way we can get these files written to _$(pwd)/tmp/{{.Release.Name}}/{{CHART}}/{{Subchart}}_ so that we don't end up overwriting "**patched_resources.yaml**" ?

**Comment by chrigl** [comment]
If this is the same as I am seeing, the problem might come from `helm template`. This is how to reproduce:

```
helm create helmfile-2095
cd helmfile-2095
rm -r templates/*
cat > templates/all.yaml <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: 01-before
  namespace: default
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
     helm.sh/hook: post-install
  name: 02-breaker
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  # annotations:
  #    helm.sh/hook: post-install
  name: 03-after
  namespace: default
EOF

helm template foo . --output-dir build
```

The result in `build/helmfile-2095/templates/all.yaml` only contains `02-breaker`.
If you comment out the `helm.sh/hook` annotation, all secrets will result in build. Removing the comment on the annotation in `03-after`, results in `02-breaker` and `03-after` in build.

**Comment by JuroOravec** [comment]
I'm seeing similar problem when I use multipart helmfile.yaml, only the templates from the last part are written to the output dir, possibly because the previous parts are overwritten.

To reproduce, first define a multipart helmfile.yaml, e.g.
```yaml
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    version: 15.1.3

---
releases:
  - chart: oci://registry-1.docker.io/bitnamicharts/redis
    name: redis
    version: 18.18.0
```

Then run `helmfile template --output-dir testdir`
