### ISSUE TITLE
.Release.Name resolution for templating 

### ISSUE THREAD

**Issue by jycamier** [roboll/helmfile#2100]
Sometimes, `.Release.Name` (or `.Release.Namespace`) is resolved and sometimes not.

```yaml
### helmfile.yaml
templates:
  action-runner-controller: &action-runner-controller
    namespace: myworkspace
    chart: ./action-runner-controller
    labels:
      app: controller
    values:
      - ./action-runner-controller/services/values-{{`{{ .Release.Name }}`}}.yaml
      - foo:
          bar: "{{`{{ .Release.Name }}`}}"
    set:
      - name: foo
        value: "{{`{{ .Release.Name }}`}}"

releases:
  - name: release-foo
    <<: *action-runner-controller
  - name: release-bar
    <<: *action-runner-controller
```

Then , I run `helmfile build`

```yaml
releases:
- chart: action-runner-controller
  name: release-foo
  namespace: myworkspace
  labels:
    app: controller
  values:
  - ./action-runner-controller/services/values-myworkspace.yaml
  - foo:
      bar: '{{ .Release.Name }}'
  set:
  - name: foo
    value: '{{ .Release.Name }}'
- chart: action-runner-controller
  name: release-bar
  namespace: myworkspace
  labels:
    app: controller
  values:
  - ./action-runner-controller/services/values-myworkspace.yaml
  - foo:
      bar: '{{ .Release.Name }}'
  set:
  - name: foo
    value: '{{ .Release.Name }}'
templates:
  action-runner-controller:
    chart: ./action-runner-controller
    namespace: myworkspace
    labels:
      app: controller
    values:
    - ./action-runner-controller/services/values-{{ .Release.Namespace }}.yaml
    - foo:
        bar: '{{ .Release.Name }}'
    set:
    - name: foo
      value: '{{ .Release.Name }}'
renderedvalues: {}
```

**Comment by mumoshu** [comment]
@jycamier Hey! It's working as expected.

```
    values:
      - ./action-runner-controller/services/values-{{`{{ .Release.Name }}`}}.yaml
      - foo:
          bar: "{{`{{ .Release.Name }}`}}"
```

The value for `bar` won't be rendered as a template. If it did, how can we distinguish between a value that literally contains some go template expressions, and a value that should be rendered as template by helmfile? (An example of the former is prometheus config

If you do need to recursively render every key and value in a embedded yaml dict object, you must use `valuesTemplate` instead. There's also `setValuesTemplate`, which is a variant for `set`.
