### ISSUE TITLE
helmfiles section not working as intended

### ISSUE THREAD

**Issue by kokolight** [roboll/helmfile#2101]
I am trying to import multiple helmfiles into 1 helmfile as in the example like this:

root/helmfile.yaml
```
---
environments: 
  master: {}
  qa: {}

helmfiles:
  - path: charts/redis/helmfile.yaml
```
root/redis/helmfile.yaml
```
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: redis
    namespace: "default"
    chart: bitnami/redis
    missingFileHandler: Warn
```
I run this command from the root folder: 
`helmfile -e qa template`

but I get this error:
`err: no releases found that matches specified selector() and environment(qa), in any helmfile`

Anyone encountered this?
