### ISSUE TITLE
Can't access repository credentials when refactoring Helmfile into multiple bases

### ISSUE THREAD

**Issue by philomory** [roboll/helmfile#2123]
We have a private repository which requires credentials to access. The credentials are stored in a sops-encrypted file, so, we've been able to use it like this:

```yaml
environments:
  foo:
    secrets:
      - repo_credentials.yaml
  bar:
    secrets:
      - repo_credentials.yaml
...
repositories:
  - name: example
    url: https://repo.example.com/
    username: example
    password: {{ .Values.repo_password }}
```

This works (although it's annoying to have to list `repo_credentials.yaml` individually for all 11 of our clusters... but I have [a separate issue open about that](https://github.com/roboll/helmfile/issues/1505)), as long as you're only using a single `helmfile.yaml`.

Our `helmfile.yaml` grew to the point that it was really _way_ too long, and I decided to try splitting it up along functional lines. I moved all of the defaults (`values` and `helmDefaults` keys) to `defaults.yaml`, all of the environments to `environments.yaml`, all of the repositories to `repositories.yaml`, and all of the releases to `releases.yaml` (the plan was to factor that last one down even farther, but I never got that far). Then, `helmfile.yaml` itself was reduced simply to

```yaml
bases:
  - defaults.yaml
  - environments.yaml
  - repositories.yaml
  - releases.yaml
```

Unfortunately, this doesn't work; when `helmfile` tries to render `repositories.yaml`, it fails with the error `executing "stringTemplate" at <.Values.repo_password>: map has no entry for "repo_password"`.

At present, it doesn't seem like there's any reasonable way around this. If global secrets were available, I could just add `secrets: [repo_credentials.yaml]` to the top of `repositories.yaml`, but as it stands I'd instead of have to list all 11 of my clusters individually in `repositories.yaml` (after already listing them in `environments.yaml`), which sort of defeats the purpose of the refactoring I'm attempting. I could define the credentials in an environment variable, but for me a huge part of the appeal of helmfile in the first place is how self-contained everything is.

**Comment by philomory** [comment]
Actually, I seem to have found a way to make it work:
```yaml
bases:
  - defaults.yaml
  - environments.yaml
---
bases:
  - repositories.yaml
  - releases.yaml
```

For some reason it _doesn't_ work when I do it like this, though:
```yaml
bases:
  - defaults.yaml
---
bases:
  - environments.yaml
---
bases:
  - repositories.yaml
---
bases:
  - releases.yaml
```
