### ISSUE TITLE
Official example in official doc throws error for "Layering State Template Files"

### ISSUE THREAD

**Issue by fzyzcjy** [roboll/helmfile#2128]
Hi thanks for the wonderful lib! I need to use the "Layering State Template Files" feature but it does not seem to work.

I followed step-by-step for https://github.com/roboll/helmfile/blob/master/docs/writing-helmfile.md#layering-state-template-files . Then it has the following error:

```
helmfile sync             
in ./helmfile.yaml: error during mydefaults.yaml.gotmpl.part.0 parsing: template: stringTemplate:3:25: executing "stringTemplate" at <.Values.kubeContext>: map has no entry for key "kubeContext"
```

Full things:

```
(base) ➜  simple_example git:(master) ✗ ls
helmfile.yaml          mydefaults.yaml.gotmpl myenv.yaml             test.env.yaml
(base) ➜  simple_example git:(master) ✗ cat helmfile.yaml
# Part 1: Reused Environment Values
bases:
  - myenv.yaml
---
# Part 2: Reused Defaults
bases:
  - mydefaults.yaml.gotmpl
---
# Part 3: Dynamic Releases
releases:
  - name: test1
    chart: mychart-{{ .Values.myname }}
    values:
      replicaCount: 1
      image:
        repository: "nginx"
        tag: "latest"
(base) ➜  simple_example git:(master) ✗ cat myenv.yaml 
environments:
  test:
    values:
      - test.env.yaml%                                                                                                                                          
(base) ➜  simple_example git:(master) ✗ cat test.env.yaml  
kubeContext: test
wait: false
cvOnly: false
myname: "dog"%                                                                                                                                                  
(base) ➜  simple_example git:(master) ✗ cat mydefaults.yaml.gotmpl 
helmDefaults:
  tillerNamespace: kube-system
  kubeContext: {{ .Values.kubeContext }}
  verify: false
  {{ if .Values.wait }}
  wait: true
  {{ else }}
  wait: false
  {{ end }}
  timeout: 600
  recreatePods: false
  force: true%                                                                                                                                                  
(base) ➜  simple_example git:(master) ✗ helmfile sync             
in ./helmfile.yaml: error during mydefaults.yaml.gotmpl.part.0 parsing: template: stringTemplate:3:25: executing "stringTemplate" at <.Values.kubeContext>: map has no entry for key "kubeContext"
```
