### ISSUE TITLE
Support nested variable

### ISSUE THREAD

**Issue by monlor** [roboll/helmfile#2130]
```yaml
templates:
  default: &default
  installed: {{ .Values | get {{ .Release.Name }}.installed }}

releases:
- name: test
    <<: * default
```

installed can parse to `.Values.test.installed`
