### ISSUE TITLE
Values from environments are not merged into chart's Values

### ISSUE THREAD

**Issue by daper** [roboll/helmfile#2134]
Helmfile version: `v0.144.0`

With the following example:

_chart1/templates/file.yaml_
```
# --> {{ .Values.test }}
```

_helmfile.yaml_
```
environments:
  default:
    values:
      - test: true

releases:
  - name: one
    chart: chart1
```

`helmfile template` renders the following:
```
Building dependency release=one, chart=chart1
Templating release=one, chart=chart1
---
# Source: chart1/templates/file.yaml
# -->

```

Shouldn't it take the values from the default environment?
