### ISSUE TITLE
Q: Download multiple .yaml manifests

### ISSUE THREAD

**Issue by locomoco28** [roboll/helmfile#2136]
I've seen that you can specify remote URLs for Helm charts, but I couldn't find a way to download .yaml files directly which would be useful to install CRDs. Did I miss something in the documentation about it, or is there currently no way of doing this without creating a chart custom chart using Helm hooks to `wget` the files like in Gitlab's [cluster management template](https://gitlab.com/gitlab-org/project-templates/cluster-management/-/tree/master/applications/cert-manager)?

**Comment by mumoshu** [comment]
@locomoco28 Hey. You should be able to use go-getter URL in the `chart field like https://github.com/roboll/helmfile/issues/2106

**Comment by locomoco28** [comment]
@mumoshu Thanks for your quick response. How would that look like e.g. for the `kube-prometheus-stack` I have to install [multiple YAML files](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-33x-to-34x)

**Comment by mumoshu** [comment]
You'd need to repeat `release` within helmfile.yaml for each remote YAML file.

**Comment by locomoco28** [comment]
So a little bit like this?

<details>
  <summary>Prometheus CRDs <code>helmfile.yaml</code></summary>

```yaml
releases:
  - name: prometheus-crds-alertmanagerconfigs
    namespace: monitoring
    chart: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.55.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
    version: v1.0.0
    installed: true

  - name: prometheus-crds-alertmanagers
    namespace: monitoring
    chart: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.55.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
    version: v1.0.0
    installed: true

  - name: prometheus-crds-podmonitors
    namespace: monitoring
    chart: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.55.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
    version: v1.0.0
    installed: true

  - name: prometheus-crds-probes
    namespace: monitoring
    chart: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.55.0/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
    version: v1.0.0
    installed: true

  - name: prometheus-crds-prometheuses
    namespace: monitoring
    chart: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.55.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
    version: v1.0.0
    installed: true

  - name: prometheus-crds-prometheusrules
    namespace: monitoring
    chart: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.55.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
    version: v1.0.0
    installed: true

  - name: prometheus-crds-servicemonitors
    namespace: monitoring
    chart: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.55.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
    version: v1.0.0
    installed: true

  - name: prometheus-crds-thanosrulers
    namespace: monitoring
    chart: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.55.0/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
    version: v1.0.0
    installed: true
```
</details>

I wish there was an option to specify an array of charts. Maybe something similar to this would be feasible to implement?

```yaml
releases:
  - name: prometheus-crds
    namespace: monitoring
    charts:
      # Release names like <releases[i].name>-<releases[i].chart[j].name or filename>

      # examples:

        # prometheus-crds-alertmanagerconfigs
      - name: alertmanagerconfigs
        chart: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.55.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
      
        # prometheus-crds-monitoring-coreos-com-alertmanagers-yaml
      - chart: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.55.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
      # ...
    version: v1.0.0
    installed: true
```

**Comment by mumoshu** [comment]
Yeah it should work.
If you really need to make it DRY, use go templates within the helmfile.yaml.

**Comment by locomoco28** [comment]
Ooh that's a good idea, I didn't think of using go templates for the helmfiles. Thank you :)

**Comment by locomoco28** [comment]
hmm entering urls to yaml files doesn't seem to work for me tho. It expects a gzipped archive :/

**Comment by toVersus** [comment]
@locomoco28 
JFYI, I had similar use case and ended up adopting the following way referring to [this example](https://github.com/helmfile/helmfile/pull/22/files#diff-1c4ac4d3a00c7c0a2b95776f7e18e10795831a46f1be1976a99a4fbde39dec17):

```yaml
releases:
- name: prometheus-operator-crds
  chart: git::https://github.com/prometheus-operator/prometheus-operator.git@example/prometheus-operator-crd?ref=v0.55.0
```
