### ISSUE TITLE
Environment values are not injected to the chart

### ISSUE THREAD

**Issue by scrhicks** [roboll/helmfile#2137]
Hello

I created simple helmfile to deploy vault with `production` environment. But after apply the values from production config was not apply to the resources. What I'm doing wrong?

`helmfile.yaml`
```yaml
repositories:
- name: hashicorp
  url: https://helm.releases.hashicorp.com

environments:
  production:
    values:
      - environments/production/vault.yaml

releases:
  - name: vault
    namespace: vault
    createNamespace: true
    labels:
      app: vault
    chart: hashicorp/vault
    version: 0.19.0
```

`Sync command`:
```bash
helmfile --selector app=vault --environment=production sync
```

Best regards,
Przemyslaw

**Comment by baryal2022** [comment]
Same here

**Comment by morozovcookie** [comment]
Hello, 

I'm tried same stuff with Helmfile version v0.145.4, but instead of values.yaml in environment configuration I specify concrete variables.

**Comment by yxxhero** [comment]
```yaml
repositories:
- name: hashicorp
  url: https://helm.releases.hashicorp.com

environments:
  production:
    values:
      - environments/production/vault.yaml

releases:
  - name: vault
    namespace: vault
    createNamespace: true
    labels:
      app: vault
    chart: hashicorp/vault
    version: 0.19.0
    # pass values
    values:
      - vaulues.yaml.gotmpl  # use go template in this file. and config from environments/production/vault.yaml
```
