### ISSUE TITLE
Helmfile + git-helm, path mismatch

### ISSUE THREAD

**Issue by Vetal-ca** [roboll/helmfile#2158]
git-helm plugin, causing a path mismatch:

- helmfile.yaml
```yaml
repositories:
  - name:  guerzon
    url: git+https://github.com/guerzon/vaultwarden@?ref=main

helmDefaults:
  verify: true
  waitForJobs: true
  timeout: 600
  createNamespace: true

releases:
  - name: vault-warden
    namespace: vaultwarden
    chart:  guerzon/vaultwarden
```

`helmfile apply` show difference to apply while failing in the very end:

```
STDERR:
  /home/vetal/.local/share/helm/plugins/helm-git/helm-git: 302: cannot open /tmp/helm-git.mDulxt/vaultwarden-0.3.0.tgz: No such file
  cat: /tmp/helm-git.mDulxt/vaultwarden-0.3.0.tgz: No such file or directory
  Error: failed to fetch provenance "git+https://github.com/guerzon/vaultwarden@/vaultwarden-0.3.0.tgz?ref=main&sparse=1&depupdate=1&package=1.prov"

COMBINED OUTPUT:
  Release "vault-warden" does not exist. Installing it now.
  /home/vetal/.local/share/helm/plugins/helm-git/helm-git: 302: cannot open /tmp/helm-git.mDulxt/vaultwarden-0.3.0.tgz: No such file
  cat: /tmp/helm-git.mDulxt/vaultwarden-0.3.0.tgz: No such file or directory
  Error: failed to fetch provenance "git+https://github.com/guerzon/vaultwarden@/vaultwarden-0.3.0.tgz?ref=main&sparse=1&depupdate=1&package=1.prov"
```

`/tmp/helm-git.mDulxt/` does not exist. While repo file is fetched to `/home/vetal/.cache/helm/repository/vaultwarden-0.3.0.tgz`

Exporting `HELM_CACHE_HOME` to some explicit location won't help

All the latest, while `helm v3.9.2` is the same problem:

```bash
helm plugin list | grep git
helm-git        0.11.4          Get non-packaged Charts directly from Git.
helm version
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}
helmfile version
Helmfile version 0.146.0
```

Manual way, works for the path prospective:

```
helm repo add guerzon git+https://github.com/guerzon/vaultwarden@?ref=main
helm install vaultwarden guerzon/vaultwarden
```

It looks like helmfile, git-helm and helm combo does not
