### ISSUE TITLE
Stay DRY with the environment variables

### ISSUE THREAD

**Issue by PatrykKlimowicz** [roboll/helmfile#2175]
We would like to stay DRY in our helmfile but we are missing something there... It is more like a question than issue type.

Let's assume we have many releases and these scenarios:

- by default we do not want to deploy anything
- we'd like to deploy all releases for `all` env
- we'd like to have env per release to allow single release deployment at time

Our `releases` section is valid (we can deploy w/o any issues w/o the conditioning part), and to make the above scenarios possible we've added to each release section line like:

```yaml
releases:
  - name: foo
  # ...
  condition: foo.enabled
  # ...
```

Again, there are plenty of releases. We created the following `environments` section:

```yaml
environments:
  # by default there are no deployments enabled
  default:
    values:
      - foo:
           enabled: false
       - boo:
            enabled: false
       - bar:
           enabled: false
  # one env to rule them all
  default:
    values:
      - foo:
           enabled: true
       - boo:
            enabled: true
       - bar:
           enabled: true
  # One release at time starts here
  foo:
    values:
      - foo:
           enabled: true
       - boo:
            enabled: false
       - bar:
           enabled: false
  boo:
    values:
      - foo:
           enabled: false
       - boo:
            enabled: true
       - bar:
           enabled: false
  bar:
    values:
      - foo:
           enabled: false
       - boo:
            enabled: false
       - bar:
           enabled: true
```

What we are looking for is the possibility to do the following:

```yaml
environments:
  # by default there are no deployments enabled
  default:
    values:
      - foo:
           enabled: false
       - boo:
            enabled: false
       - bar:
           enabled: false
  # one env to rule them all
  default:
    values:
      - foo:
           enabled: true
       - boo:
            enabled: true
       - bar:
           enabled: true
  # One release at time starts here
  foo:
    values:
      - foo:
           enabled: true
  boo:
    values:
       - boo:
            enabled: true
  bar:
    values:
       - bar:
           enabled: true
```

Is there a way to achieve the above? So the possible scenarios:
1. `helmfile diff` -- does nothing for default env
2. `helmfile -e all diff` -- deploy everything
3. `helmfile -e foo diff` -- deploy foo only (no errors for other releases like `panic: environment values does not contain field 'boo'`)

We are using helmfile in version `v0.144.0`. All suggestions appreciated 😄
