### ISSUE TITLE
new Helmfile(v1.0.0) failed to run sync with templating error

### ISSUE THREAD

**Issue by 99887710** [roboll/helmfile#2189]
when trying to run `helmfile sync` with v1.0.0, it showed error 

in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:14:21: executing "stringTemplate" at <.Release.Name>: can't evaluate field Release in type *state.EnvironmentTemplateData

```
releases:
  - name: xxx
    chart: xxx
    version: xxx
    namespace: xxx
    kubeContext: xxx
    values:
      - ./{{`{{ .Release.Name }}`}}/values.yaml
    secrets:
      - ./{{`{{ .Release.Name }}`}}/secrets.yaml
```

But when I tried to use older version like v0.163.0, it worked, not sure if it is a breaking change related to template rendering. Does anyone have thoughts? thanks

Update: v1.0.0 works with the following one without `{{``

```
releases:
  - name: xxx
    chart: xxx
    version: xxx
    namespace: xxx
    kubeContext: xxx
    values:
      - ./{{ .Release.Name }}/values.yaml
    secrets:
      - ./{{ .Release.Name }}/secrets.yaml
```
