### ISSUE TITLE
Namespace value from default context not being propagated

### ISSUE THREAD

**Issue by dfilipov-glitnor** [roboll/helmfile#2192]
When running `helmfile apply -e dev` and trying to reference `{{ .Release.Namespace }}` in my `mongo/{{ .Environment.Name }}.yaml.gotmpl` like so:

`MONGO_HOST: "{{.Release.Namespace }}.svc.cluster.local/admin"` I get a null value, this is also show when I tried to template with passing `{{ .Release }}` to see what is being propagated and I get `namespace: `

**This however works when I explicitly pass the `--namespace` flag to helmfile like so `helmfile apply -e dev --namespace test-namespace`**

Here is my `releases` block for reference

```
releases:
  - name: mongodb-cluster
    chart: .
    atomic: true
    missingFileHandler: Warn
    values:
      - mongo/common.yaml.gotmpl
      - mongo/{{ .Environment.Name }}.yaml.gotmpl
```

I also tried working around this by passing `set` to my releases, but still no luck
```
set:
  namespace: {{ .Namespace }}
```
