### ISSUE TITLE
repos using token auth cannot finding the chart

### ISSUE THREAD

**Issue by jeff-knurek** [roboll/helmfile#22]
we're using a private chart repo with token auth in github: see https://medium.com/@kavehmz/using-a-private-github-repo-as-helm-chart-repo-https-access-95629b2af27c

and when trying to switch from a large umbrellla chart to use `helmfile`, running into an issue that the chart can't be found

here's a sample of the `helmfile`:
```
repositories:
  - name: authtest
    url: https://TOKEN@raw.githubusercontent.com/org/helmrepo/master/stable

charts:
  - name: dev-service
    namespace: dev
    chart: authtest/service
    # version: 1.1.1
    values:
    - service-values.yaml # (relative path to manifest)
```

and the output of `helmfile -f charts.yaml sync`:
```
exec: helm repo add authtest https://TOKEN@raw.githubusercontent.com/org/helmrepo/master/stable
"authtest" has been added to your repositories
exec: helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "authtest" chart repository
...Successfully got an update from the "roboll" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
exec: helm upgrade --install dev-service authtest/service --namespace dev --values .../service-values.yaml
Error: file "authtest/service" not found
err: exit status 1```
