### ISSUE TITLE
feat: --force, --recreate-pods, --timeout as first-class citizens in helmfile.yaml

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#229]
Extracted from https://github.com/roboll/helmfile/issues/210#issuecomment-415272256

This provides us more control over the flags passed to helm, without helmfile maintaining lists of supported args per each helm command.

```yaml
releases:
- name: myapp
   chart: ...
   wait: true
   recreatePods: true
   timeout: 600
   force: true
```
