### ISSUE TITLE
feat: Configurable default values for --verify, --force, --recreate-pods, and --timeout

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#230]
We had a discussion in https://github.com/roboll/helmfile/issues/210#issuecomment-415297831 about that having several dozens of releases in a single helmfile.yaml makes it cumbersome to set, for example, `wait: true` for all the releases.

`helmDefaults` can be extended to accept default values for these three settings, so that there should be no repetition required at all.

```yaml
helmDefaults:
  wait: true
  force: true
  recreatePods: true
  timeout: 60
```
