### ISSUE TITLE
Deprecate `set` in helmfile.yaml

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#243]
Ref https://github.com/roboll/helmfile/issues/227#issuecomment-416465961

You should use values files templates not to bloat up your helmfile.yaml

**Comment by goruha** [comment]
`--set-file` in difference to `readFile`  allow to use urls 
like
```
  set:
  - name: "configMaps.dashboards.files.deployment\\.json"
    file: https://raw.githubusercontent.com/cloudposse/grafana-dashboards/feature-kube-prometheus-dashboards/kube-prometheus/deployment-dashboard.json
```

Very useful.

**Comment by mumoshu** [comment]
@goruha Thanks! I'm aware of the feature. Good to know about someone who actually use the feature! I'll add a dedicated template function to fetch a remote url, and will ask for your confirmation before I actually deprecate or even remove the `set:` thing.

**Comment by mumoshu** [comment]
@Stono Your use-case is completely valid!

Unfortunately, I have no idea how we could cleanly support it with the template values file feature.
Don't worry. I won't remove the `set:` feature without your confirmation.

**Comment by sstarcher** [comment]
@Stono any reason you don't put that ```  
set:
  - name: deployment.containers[0].image.tag
    value: {{ requiredEnv "GO_PIPELINE_COUNTER" }}
```

In your values.yaml?

**Comment by goruha** [comment]
@mumoshu thanks!

**Comment by mumoshu** [comment]
@Stono More concretely, you could add `values.yaml.gotmpl` like:

```
deployment:
  containers:
  - image:
      tag: {{ requiredEnv "GO_PIPELINE_COUNTER" }}
```

And add the filename to `values:` in helmfile.yaml:

```
releases:
- name: sauron-web
  namespace: sauron-web
  chart: aws/platform-helm-at-service
  version: 0.1.{{ requiredEnv "GO_DEPENDENCY_LABEL_PLATFORM" }}
  values:
  - environments/values.yaml
  - environments/{{ requiredEnv "HELMFILE_ENV" }}/values.yaml
  - values.yaml.gotmpl
  secrets:
  - environments/{{ requiredEnv "HELMFILE_ENV" }}/secrets.yaml
```

Note that the gotcha here is that the values.yaml generated from `values.yaml.gotmpl` would replace the entire `deployment.containers[]` yaml array. So in case you have a secondary container defined by default in preceding values.yaml files, modify your chart to change `deployment.containers` from an array to a hash.

After that your `values.yaml.gotmpl` becomes:

```
deployment:
  containers:
    primary:
      tag: {{ requiredEnv "GO_PIPELINE_COUNTER" }}
```

**Comment by blissd** [comment]
I find `set` to be very convenient when using helmfiles for testing. I'd hate to see it go.

**Comment by mumoshu** [comment]
@blissd You seem to be talking about the --set flag, right? That's another story than this. I'm not going to remove the flag at all.

**Comment by blissd** [comment]
No, I mean `set` in the `helmfile.yaml` itself. We've been using v0.19, which I think predates the `gotmpl` files, but I'd like to upgrade to a newer version.

However, I'd be hesitant to use the `gotmpl` files because I like my values files to be the same as what would be passed to `helm` without using `helmfile`.

**Comment by mumoshu** [comment]
@blissd Thanks for clarifying! Makes sense, but do you know inline values in helmfile.yaml? That's basically better alternative to set:

**Comment by blissd** [comment]
Thanks, the inline values work fine for my use case. I'll have the team here migrate to that.

**Comment by philomory** [comment]
If we do end up deprecating `set` in favor of inline values, could we also merge the `values` and `secrets` sections in some way? Right now, it's impossible to specify a values file that will have higher priority than a secrets file, e.g., this command line cannot be replicated: `helm upgrade --install -f values.yaml -f secrets.yaml -f values.prod.yaml -f secrets.prod.yaml`.

If you write it like this:
```
values:
  - values.yaml
  - values.{{ .Environment.Name }}.yaml
secrets:
  - secrets.yaml
  - secrets.{{ .Environment.Name }}.yaml
```
... you'll end up with the following command: `helm upgrade --install -f values.yaml -f values.prod.yaml -f secrets.yaml -f secrets.prod.yaml`; that gives items from `secrets.yaml` higher priority than those in `values.prod.yaml` during the recursive merge.

**Comment by mumoshu** [comment]
@philomory Thanks! Yeah that's a valid point. I was thinking if we could use [remote secrets](https://github.com/roboll/helmfile/blob/b1190508b2fbbb56b80de916aa7e66dd9f07db2f/docs/remote-secrets.md#remote-secrets) though. WDYT?

**Comment by philomory** [comment]
That's great if you've got your secrets in Vault, it's a bit more awkward when each chart your deploying has a chart-specific `helm-secrets` YAML file, and some of those files for specific microservices might have the same key with different values.

**Comment by philomory** [comment]
Actually, I suppose `ref+sops://` would solve that case? It'd be nice if `vals` and `go-getter` could join forces to read a sops-encrypted file from a remote git repo, but maybe that's asking too much (and obviously that's unrelated to whether the `set` section is deprecated or not).

**Comment by mumoshu** [comment]
@philomory Yeah I thought `ref+sops://` in `values` could replace `secrets`.

Re: reading a sops encrypted file from a remote git repo, that sounds like an interesting use-case indeed :) Created https://github.com/variantdev/vals/issues/35 to track it.

**Comment by philomory** [comment]
@mumoshu So... does `ref+sops://` actually work? I tried the following:

```yaml
# helmfile.yaml
values:
  - ref+sops://secrets.yaml?&format=yaml

releases:
  - name: dummy
    chart: incubator/raw
    values:
      - {{ .Values | toYaml | nindent 8 | trimPrefix " " }}
```
```yaml
# secrets.yaml (before encrypting with sops)
foo: bar
```

Results:
```
$ helmfile template
in ./helmfile.yaml: environment values file matching "ref+sops://secrets.yaml?&format=yaml" does not exist in "."
```

There's not actually any examples of how to use `ref+sops://` anywhere in the Helmfile documentation (not even the PRs linked from the documentation), they only show `ref+vault://`; but using the `ref+sops://` syntax from the `vals` documentation doesn't seem to work for me.
