### ISSUE TITLE
Paths should be relative to that of helmfile.yaml

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#246]
In the example below:

```yaml
releases:
- name: myapp
  chart: ./myapp/charts/myapp
  values:
  - ./myapp/values.yaml
  secrets:
  - ./myapp/secrets.yaml
```

I would expect `helmfile -f path/to/helmfile.yaml` to resolve all the paths included in the file to be under the directory `path/to`. As of today helmfile resolves it relative to CWD.
