### ISSUE TITLE
feat: Environment, as a more maintainable alternative to a bunch of envvars

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#253]
Extracted from https://github.com/roboll/helmfile/issues/59#issuecomment-415690069

Let's add `environments` to helmfile.yaml:

```yaml
environments:
  default:
    values:
    - ./default.0.yaml
    - ./default.1.yaml.gotmpl
  # note: values from the default env. aren't inherited to production. Use yaml anchors for inheritance.
  production:
    values:
    - ./production.yaml

releases:
- name: myapp
   chart: mychart
   values:
  - values.yaml.gotmpl
```

In the above example, `default.0.yaml` and `default.1.yaml.gotmpl` is merged into a golang map, that can be referenced by `{{ .Environment.Values.foo.bar }}` from within the values.yaml template(#216) `values.yaml.gotmpl`.

`helmfile sync` against a missing environment should [SUCCEED with a big warning message](https://github.com/roboll/helmfile/issues/59#issuecomment-416500471).
