### ISSUE TITLE
feat: Merge multiple docs inside a single helmfile.yaml

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#254]
Extracted from https://github.com/roboll/helmfile/issues/59#issuecomment-416608106

This feature would allow us to template your `helmfile.yaml` according to environment values #253.

An example helmfile.yaml would look like this. Notice the document separator `---` in the middle of the yaml file:

```yaml
environments:
  default:
    values:
    - environments/default.yaml
---
respositories:
- name: your-private-git-repo-hosted-charts
  url: https://{{ .Environment.Values.githubToken }}@raw.githubusercontent.com/kmzfs/helm-repo-in-github/master/

releases:
- name: myapp
  # snip
```

#253 alone doesn't allow you to template your `helmfile.yaml` according to the environment values due to the chicken-and-egg problem. That is, helmfile.yaml needs to be templated before parsed as yaml. But templating the helmfile.yaml referencing `{{ .Environment.Values }}` requires you to load `environments:` form yaml.

This also helps the use-case of implementing ["base" and "layer" helmfiles](https://github.com/roboll/helmfile/issues/240#issuecomment-416886474).
