### ISSUE TITLE
feat: Secrets under environments

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#255]
Extracted from https://github.com/roboll/helmfile/issues/59#issuecomment-416270943

Enhance #253 to accept `secrets:` under each environment:

```yaml
environments:
  production:
  values:
  - environments/production/values.yaml
  secrets:
  - environments/production/secrets.yaml

releases:
- name: myapp
  values:
  - values.yaml.gotmpl
```

So that contents of `values.yaml` and decrypted `secrets.yaml` are merged and then can be referenced from within `values.yaml.gotmpl`.
