### ISSUE TITLE
"no such file or directory" error while renaming secrets.yaml.dec

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#258]
```yaml
releases:
- name: foo
  chart: stable/grafana
  secrets:
  - secrets.yaml
- name: bar
  chart: stable/grafana
  secrets:
  - secrets.yaml
```

`helmfile sync` and `helmfile diff` fails with an error like:

```
err: release "bar" in "helmfile.1.yaml" failed: rename /Users/mumoshu/go/src/github.com/roboll/helmfile/secrets.yaml.dec /var/folders/3z/43zzxy1x2w51l9z1_2b130vrgwhgzz/T/secret986719516: no such file or directory
```

Seems like there's a race-condition among concurrent `DecryptSecret` calls.
