### ISSUE TITLE
[Question] using environments feature

### ISSUE THREAD

**Issue by davidovich** [roboll/helmfile#273]
#253 brings environments control to helmfile. Nice. #266 allows inclusions of many helmfiles controlled by one master helmfile. Excellent.

I had just finished an implementation (with helmfile 0.25.3) which does something similar, but I am not sure how to use the new feature to implement my use-case. Below explains the current situation, if anyone can comment on an alternative, it would be very valuable.

```
.
├── helmfile.d
│   ├── 00_serviceA.yaml
│   ├── 01-serviceB.yaml
│   ├── 02-serviceC.yaml
├── local-charts
│   ├── serviceA
└── values
    ├── serviceA.yaml  # default values for the serviceA
    ├── serviceB.yaml  # default values for the serviceB
    ├── production
    │   ├── serviceA.yaml  # production values
    │   ├── serviceB.yaml
    │   ├── serviceC.yaml
    └── staging
        ├── serviceA.yaml  # staging values
        ├── serviceB.yaml
        └── serviceC.yaml
```

Below are the contents of the serviceA.yaml. 

```
releases:
- name: serviceA
  namespace: myTeam
  chart: ../local-charts/serviceA
  values:
    - ../values/serviceA.yaml  # load default values
    - ../values/{{ requiredEnv "DEPLOYMENT_ENV" }}/serviceA.yaml
```

DEPLOYMENT_ENV is injected by the ci-system, but it would be nice that helmfile would work without it. 

I am wondering if you have any input on how I should refactor or structure this to use the environments and/or helmfile inclusion features.

Note that each release can have or leave out defaults, and can have or leave out configuration for an environment. Right now, this structure forces me to have a duplicated file in the environment directory even if it is not required. I'd like to tend towards a more generalized structure if at all possible.

Thanks for all the work!

**Comment by mumoshu** [comment]
You should specify the environment name by a flag `helmfile --environment production sync`. `--environment` defaults to `default`.

If you have specific use-case that requires helmfile to set the env according to an environment variable, please file an another feature request!

**Comment by davidovich** [comment]
@mumoshu thank you very much for this response, it gives me many options, and a better understanding of the new features. 

I don't know what you think, but it would maybe be beneficial to be able to reference releases in the `environments:` section. This would allow flexibility on each release in a declarative manner. Then, we could do: 

```
environments:
  staging:
  production:
    serviceA:
      values:
      - env/production/serviceA/values.yaml

releases:
- name: serviceA
   ...
```

**Comment by davidovich** [comment]
@mumoshu The proposed solution does not seem to work, 

```
releases:
- name: serviceA
  namespace: myTeam
  chart: ./charts/serviceA
  values:
    - ./default/values.yaml  # load default values
    - ./environments/{{ .Environment.Name }}/serviceA.yaml
```
When I issue a `helmfile -e staging diff`, I get 

```
err: release "serviceA" in "app/serviceA/helmfile.yaml" failed: stat [app_path]/serviceA/environments/serviceA.yaml: no such file or directory
```

As you see, {{ .Environment.Name }} seems empty
