### ISSUE TITLE
feat: Hooks

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#295]
I imagine that you use helmfile in combination with various tools 😃
 
I'd like to investigate the possibility to enhance `helmfile.yaml`, so that you can also declaratively manage which tools are executed how, on which timing, and so on. And I'd like to achieve it without implementing so many features into the helmfile core.

#214 is one of feature requests relevant to this feature. #214 overrides specific helmfile internal task to use the specified command. So that helmfile could run any interchangeable command instead of e.g. `helm upgrade --install` to install/upgrade a helm release.

Hooks, on the other hand, would allow you to prepend or append arbitrary logics or commands to be executed along with a specific helmfile task.

For example:

- `preHelmUpgrade` hook would allow you to add commands to be executed before `helm upgrade --install` while in `helmfile sync`
- `preChartLoad` would allow you to run arbitrary commands in order to auto-fix or auto-generate the chart that is used for installation
- `preApplyRun` would allow you to run arbitrary command before `helmfile apply`. Use it to e.g. automatically retrieve a token to authenticate against the kubernetes cluster that corresponds to the helmfile environment (#267).

Consider it as something like [draft tasks](https://github.com/Azure/draft/blob/e657813f23d23b967ec99a6363533fc3f1253312/docs/reference/dep-008.md#motivation) or [helm2 plugin hooks](https://github.com/helm/helm/blob/master/pkg/plugin/hooks.go), or [helm3 lifecycle event handlers](https://github.com/helm/community/blob/master/helm-v3/002-events.md#scripting-event-handlers).

Please share your use-cases! Thanks.

**Comment by elemental-lf** [comment]
As mentioned in https://github.com/roboll/helmfile/issues/214 I'd like some kind of hooks. I'd probably align them more to the helm side of things (that is ``preHelmUpgrade``, ``postHelmUpgrade``, ``preChartLoad``) instead of the command line actions as a command line action might be a composite of actions (like ``sync`` and ``apply`` for example) and they are more likely to change yet, so there'd be no ``preApplyRun``.
Some thoughts: A failed pre-hook or post-hook should terminate helmfile. A post-hook should be called with status information about the preceding action to be able to react on it. Other information (like chart, release, revision) also needs to be passed along of course. To be able to use the same script to implement multiple hooks the name of the hook should also be passed along.
Environment variables are one option to pass the information to the external program but templating is the more natural one in our case and more versatile. The template would need to be escaped so that the rendering is deferred which is a bit of a hassle.

**Comment by mumoshu** [comment]
@elemental-lf Hey, thanks a lot for awesome feedbacks!

> align them more to the helm side of things (that is ``preHelmUpgrade``, ``postHelmUpgrade``, ``preChartLoad``) instead of the command line actions as a command line action might be a composite of actions (like ``sync`` and ``apply`` for example) and they are more likely to change

Makes a lot of senses.

> A failed pre-hook or post-hook should terminate helmfile

Agreed

> A post-hook should be called with status information about the preceding action to be able to react on it

What kind of status information would you like?
I guess, perhaps the oneline error message, and the whole stdout/stderr logs, so that we can create e.g. a slack notification post hook?

> Other information (like chart, release, revision) also needs to be passed along of course. To be able to use the same script to implement multiple hooks the name of the hook should also be passed along.

Agreed.

I imagine we would start with:

- `{{.Release.Name}}`
- `{{.Release.Chart}}`
- `{{.Release.Version}}`
- `{{.Release.Revision}}` (Current revision fetched from the last line of `helm history --output json`?)
- `{{.Hook.Phase}}` like `"preChartLoad"`
- `{{.Hook.Name}}` like `"chartifyMyFiles"`

> same script to implement multiple hooks

Sounds great!

I was firstly considering a configuration syntax like:

```yaml
releases:
- name: myapp
  chart: mychart
  hooks:
    preChartLoad:
     - command: {{` ./chartify -e {{ .Environment.Name }} {{ .Chart }} `}}
```

But to naturally support multiple hooks with a single script, I'd change it to:

```yaml
releases:
- name: myapp
  chart: mychart
  hooks:
    chartify:
      phases: ["preChartLoad"] # add as many phases here
      command: {{` ./chartify -e {{ .Environment.Name }} {{ .Chart }} `}}
```

> Environment variables are one option to pass the information to the external program but templating is the more natural one in our case and more versatile. 

Agreed.

> The template would need to be escaped so that the rendering is deferred which is a bit of a hassle.

Yeah. I'm still struggling to keep it simple as possible overall, but my best one so far is https://github.com/roboll/helmfile/issues/297#issuecomment-419611007. WDYT?

**Comment by elemental-lf** [comment]
@mumoshu, hope, you're well!

> What kind of status information would you like?
> I guess, perhaps the oneline error message, and the whole stdout/stderr logs, so that we can create e.g. a slack notification post hook?

I just thought about signalling success or failure. But your Slack use-case would indeed profit from some more information especially when using helmfile in an automated setting.

> But to naturally support multiple hooks with a single script, I'd change it to:
> 
> releases:
> - name: myapp
>   chart: mychart
>   hooks:
>     chartify:
>       phases: ["preChartLoad"] # add as many phases here
>       command: {{` ./chartify -e {{ .Environment.Name }} {{ .Chart }} `}}

Looks good. Why the extra level (``chartify``), why not directly below ``hooks``? 
I think ``phases`` would be somewhat of a misnomer as a phase describes a time interval and hooks are more like a specific point in time, that is _at_ the start of phase chartLoad or _at_ the end of phase chartLoad. But I didn't come up with a better word just yet.

Should there be global hooks that are always executed regardless of the release? Maybe even with some extra hooks like ``helmfileStart`` or ``helmfileEnd``? But maybe I'm starting to overthink this ;)

**Comment by mumoshu** [comment]
@elemental-lf Thanks as always for your feedback!

> Why the extra level (chartify), why not directly below hooks?

I wanted to name each hook command, so that the user can make sense of which hook is running. But that's not a strong opinion.

> I think phases would be somewhat of a misnomer as a phase describes a time interval and hooks are more like a specific point in time, that is at the start of phase chartLoad or at the end of phase chartLoad

Aha! Your explanation makes a lot of sense.

> Should there be global hooks that are always executed regardless of the release? Maybe even with some extra hooks like helmfileStart or helmfileEnd?

Sounds very useful!

> But maybe I'm starting to overthink this ;)

Probably :) But I tend to overthink things, too!

Anyway, I believe it's still valuable to "overthink" at first, so that we have more options to choose the minimum viable feature to start from it!

Now, I came up with 3 alternatives. My favorite is the third one below.

```yaml
releases:
- ...
  hooks:
    chartify:
      points: ["preChartLoad"] # add as many points in the release lifecycle here
      command: {{` ./chartify -e {{ .Environment.Name }} {{ .Chart }} `}}
```

```yaml
releases:
- ...
  plugins:
    chartify:
      hooks: ["preChartLoad"] # register this plugin to as many hooks as you want
      command: {{` ./chartify -e {{ .Environment.Name }} {{ .Chart }} `}}
```

```yaml
releases:
- ...
  hooks:
    preChartLoad: # register as many commands as you want to this hook
    - command: {{` ./chartify -e {{ .Environment.Name }} {{ .Chart }} `}}
```
