### ISSUE TITLE
Referencing environment values from within helmfile.yaml

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#297]
#267 supports referencing `.Environment.Name` from within helmfile.yaml, but `.Environment.Values`. The latter can be referenced from within values file templates only as of today.

Looking into use-cases like @Stono's https://github.com/roboll/helmfile/issues/243#issuecomment-418386220, I can't stop imagining how helmfile could reduce envvar references, replacing with  helmfile's env values.

For example, how about exploiting [```{{` STR `}}``` expressions](https://golang.org/pkg/text/template/#hdr-Examples) to nest templates?

The below example adds `template:` under each item in `releases`, so that the yaml string value for `template` is considered gotmpl that is rendered after `.Environment.Values` are loaded.

```yaml
releases:
- template: |{{`
    name: sauron-web
    namespace: sauron-web
    chart: aws/platform-helm-at-service
    version: 0.1.{{ .Environment.Values.goDependencyLabelPlatform" }}
    values:
    - environments/values.yaml
    - environments/{{ .Environment.Name }}/values.yaml
    secrets:
    - environments/{{ .Environment.Name }}/secrets.yaml
    set:
    - name: deployment.containers[0].image.tag
      value: {{ requiredEnv "GO_PIPELINE_COUNTER" }}
`}}
```

You many prefer accepting the release template without introducing the new key `template:`:

```yaml
releases:
- |{{`
  name: sauron-web
  namespace: sauron-web
  chart: aws/platform-helm-at-service
  version: 0.1.{{ .Environment.Values.goDependencyLabelPlatform" }}
  values:
  - environments/values.yaml
  - environments/{{ .Environment.Name }}/values.yaml
  secrets:
  - environments/{{ .Environment.Name }}/secrets.yaml
  set:
  - name: deployment.containers[0].image.tag
    value: {{ requiredEnv "GO_PIPELINE_COUNTER" }}
`}}
```

Or maybe just allow templating per value?
In the below example, only the value for `version` is templated.

```yaml
releases:
- name: sauron-web
  namespace: sauron-web
  chart: aws/platform-helm-at-service
  version: 0.1.{{` {{.Environment.Values.goDependencyLabelPlatform}} `}}
  values:
  - environments/values.yaml
  - environments/{{ .Environment.Name }}/values.yaml
  secrets:
  - environments/{{ .Environment.Name }}/secrets.yaml
  set:
  - name: deployment.containers[0].image.tag
    value: {{ requiredEnv "GO_PIPELINE_COUNTER" }}
```

**Comment by sstarcher** [comment]
One option would be to have 2 different `{{ }}` template enclosures.  `{{ }}` for the first pass that must make it a valid YAML and `[[ ]]` for templating after loading the environment.

Overall, I don't see a strong need for this feature and people would be better off putting the values/sets in a separate yaml file instead of inline.

**Comment by mumoshu** [comment]
@sstarcher Thanks for the comments!

We'd probably need to tackle slightly similar problem in #295 cc/ @elemental-lf
In #295, we'd need to defer templating, but with different parameters like release, chart, revision, and other contextual information.

The important difference here is that `[[ ]]` is templated after `{{ }}`, but before hook commands. We can't use same symbols to start a template expression in hooks. So a helmfile.yaml would look like something like this:

```yaml
environments:
  prod:
    values:
     - prodvalues.yaml

{{ if eq .Environment.Name "prod" }}
releases:
- name: myapp
   chart: mychart
   version: 0.1.0-[[ .Environment.Values.platform ]]
   hooks:
     preChartLoad:
      - command: {{` ./chartify -e {{ .Environment.Name }} {{ .Chart }} `}}
{{ end }}
```

Wow, we now have three variants of templates... 😭

**Comment by sstarcher** [comment]
sounds painful

**Comment by mumoshu** [comment]
yeah..

**Comment by mumoshu** [comment]
A little, possible simplification would be to use `{{` `}}` instead of `[[ ]]`.

Then, it becomes a vanilla golang template without need of double-rendering:

```yaml
environments:
  prod:
    values:
     - prodvalues.yaml

{{ if eq .Environment.Name "prod" }}
releases:
- name: myapp
   chart: mychart
   version: 0.1.0-{{` {{ .Environment.Values.platform }} `}}
   hooks:
     preChartLoad:
      - command: {{` ./chartify -e {{ .Environment.Name }} {{ .Chart }} `}}
{{ end }}
```

**Comment by sstarcher** [comment]
ya, having users double escape like that would function.

**Comment by mumoshu** [comment]
I'm even wondering if we can make templating of helmfile.yaml optional e.g. only helmfile.yaml.gotmpl whose file ext is `.gotmpl` is templated before parsed as yaml.

So that a vanilla helmfile.yaml without templating would look like the below, that has no need of double-escaping, while it is still possible to use templating per value basis:

```yaml
environments:
  prod:
    values:
     - prodvalues.yaml

releases:
- name: myapp
  installed: "{{ .Environment.Values.myapp.installed }}"
  chart: mychart
  version: "0.1.0-{{ .Environment.Values.platform }}"
  hooks:
    chartify:
      on: ["preChartLoad"]
      command: "./chartify -e {{ .Environment.Name }} {{ .Chart }}"
```

I guess we had discussed about that before #98?

**Comment by davidovich** [comment]
I’m a bit confused. How can
```
releases:
- name: myapp
  installed: "{{ .Environment.Values.myapp.installed }}"
```
Work if you haven’t settled a way to reference an environment? This issue (special template syntax to postpone rendering) or #308. ?

Why would you need to postpone the hook? If the env is available, should it just be used directly so that the rendered result contains the hook instruction?

**Comment by mumoshu** [comment]
> Work if you haven’t settled a way to reference an environment?

Similarly to https://github.com/roboll/helmfile/issues/273#issuecomment-419786262, `installed: "{{ .Environment.Values.myapp.installed }}"` in a vanilla helmfile.yaml is executed AFTER helmfile.yaml is loaded, but before any helmfile command is ecxecuted.

Moreover, in a helmfile.yaml.gotmpl, `installed: {{ .Environment.Values.myapp.installed }}` would do the job.

> Why would you need to postpone the hook? If the env is available, should it just be used directly so that the rendered result contains the hook instruction?

That's because the hook command requires the release name, chart, version, and other information that differs per release. Probably https://github.com/roboll/helmfile/issues/295#issuecomment-419618342 provides you some context about it!

**Comment by davidovich** [comment]
I haven't seen so much use cases yet, so I am still blind to what the new direction would allow. When I set out to do double render, I had only the `environments:` section in mind, which allows natural usage lower in the helmfile. Now what I understand is that there would be special keys (`installed:`) that helmfile would treat specially ?

Because when I read this:

`installed: "{{ .Environment.Values.myapp.installed }}"`, I feel (from what I gather to this date) is that there should be a corresponding
```
myapp:
   installed: true
```
in the `prodvalues.yaml` file.

But what about this (as mentioned by @elemental-lf):

```
{{ if (eq .Environment.myapp.shouldBeInstalled true) }}
...
{{ end }}
```

Of course all this works if you have a self-referential system as I said before (double-render or special template syntax). I prefer the double render solution at the moment, but only for populating the `environments:` dictionary. I don't know if people agree, but I like the generalization of allowing free-form access to the things I declare in `prodvalues.yaml` file. I am not sure this should propagate to the non-header parts of the file, if you know what I mean by header part (right now this would be the `environments:`) section.

I am not sure why you would want to segregate the helmfile.yaml and helmfile.yaml.gotmpl.

More reading on the issues, I get the why the deferred execution of the hooks is needed. I don't see that double rendering is in opposition to that, on the contrary, but I feel (repeat myself :-)) that it should only be applied to the environments: section. 

Taking from https://github.com/roboll/helmfile/issues/295#issuecomment-419870215:

```
releases:
- ...
  hooks:
    preChartLoad: # register as many commands as you want to this hook
    - command: {{` ./chartify -e {{ .Environment.Name }} {{ .Chart }} `}}
```
I also prefer this form.

**Comment by davidovich** [comment]
> Probably I'd just proceed with double-rendering enabled by default and no way to disable it.

Note that the prerender is supposed to be failsafe. In any error condition it will return at least the environment Name (as that is known in advance), as the current implementation does. If there was an error, it writes it as logger.Info().

If you still think it is a good idea, I will implement the final suggestions you added at #308.

**Comment by mumoshu** [comment]
@davidovich Thanks a lot for awesome work. Let's try!

Again, I understand the usefulness of the feature. So I'm fine as long as it won't break things that worked before, except the improvement to use missingkey=error more 😉

Regarding my suggestion, yeah, I appreciate it if you could address that.

**Comment by sstarcher** [comment]
@elemental-lf It seems to me that you are missing the power of the `environments` section.  Your examples show just using the environment name to pass in a static values file.

What the environments allow you to do is collect a common set of values that can be reused and templated in more complex ways.

Say I had a environment dev and I had a AWS certificate I wanted to pass to different services.
```
cert: blah
```

* Services 1
```
service:
  annotations:
    cert-annotation: "{{ .Environment.Values.cert}}"
```

* Service 2
```
a:
  service:
    annotations:
      cert-annotation: "{{ .Environment.Values.cert}}"

b:
  service:
    annotations:
      cert-annotation: "{{ .Environment.Values.cert}}"
```

Prior to environments existing I would of had to hard code that value into 3 different places.
