### ISSUE TITLE
helmfile lint does not add configured repositories

### ISSUE THREAD

**Issue by mhulscher** [roboll/helmfile#303]
Unlike `helmfile sync`, `helmfile lint` does not add missing repositories to local Helm. This will cause linting to fail unless the repository was previously configured.

```
$ helmfile --file helmfile.yaml lint
Error: repo incubator not found

err: exit status 1
```

`helmfile.yaml`
```
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com

releases:
- name: vault
  namespace: vault
  chart: incubator/vault
  version: 0.12.0
```
