### ISSUE TITLE
using helmfiles: key with relative paths is broken

### ISSUE THREAD

**Issue by davidovich** [roboll/helmfile#306]
When you run helmfile on a content like below from a foreign working directory, helmfile fails to find the globbed files.

helmfile.yaml
```
environments:
  staging:
  production:


helmfiles:
    - services/*/helmfile.yaml
```
