### ISSUE TITLE
Use values/secrets from within a remote chart

### ISSUE THREAD

**Issue by witten** [roboll/helmfile#324]
My use case: I'm using Helm charts hosted on a private package server not only as a means of packaging up and distributing Kubernetes templates, but also for distributing associated per-environment values and secrets. This means that our helm-secrets files are included in the charts themselves. The main benefit of an approach like this versus keeping the secrets separately is that we don't need a source code checkout (or more realistically, n source code checkouts, one per chart) to deploy. Instead, we can just use the remote chart on the chart server (effectively a build artifact) and deploy it directly.

Where Helmfile comes in is that I'd like to declare several Helm charts to deploy in a `helmfile.yaml`'s `releases:`, and have Helmfile able to pull the relevant values and secrets out of *remote* charts during deployment (`helmfile sync`). Under the hood, this might work by first `helm fetch`ing each remote chart so that the values and secrets files can be accessed.

Also, there's the question of how to refer to those values/secrets. As far as I know, `values:` and `secrets:` currently are interpreted as ~absolute paths or~ paths relative to the current directory. What we'd need for this feature request to work is a path relative to the root of the remote chart.

First, is something like this possible today? Perhaps with [`exec`](https://github.com/roboll/helmfile/#importing-values-from-any-source) or some other mechanism? If not, does this make sense as a feature request?

**Comment by witten** [comment]
Well, here's a total hack that appears to work for this use case:

```yaml
releases:
  - name: my-chart
    namespace: my-namespace
    chart: my-charts/my-chart
    set:
      - name: throwaway
        value: {{ exec "helm" (list "fetch" "my-charts/my-chart" "--untar") }}
    values:
      - my-chart/helm_vars/values.yaml
      - my-chart/helm_vars/beta/values.yaml
    secrets:
      - my-chart/helm_vars/secrets.yaml
      - my-chart/helm_vars/beta/secrets.yaml
```

Values and secrets from the downloaded chart appear to get consumed properly. It'd be nice if there was a better way to accomplish this. Even if it's just a better place to run `exec`.

**Comment by mumoshu** [comment]
@witten Hey! Thanks for the feature request. Looks like you have a very interesting use-case 👍 

We're planning to implement hooks #295. With that perhaps you could write helmfile.yaml like:

```yaml
releases:
- name: my-chart
  namespace: my-namespace
  chart: my-charts/my-chart
  # ...
  hooks:
    preChartLoad: # register as many commands as you want to this hook
    - command: {{` helm fetch {{ .Chart }} --untar`}}
```

Would it work for you?
