### ISSUE TITLE
feat: preChartLoad hooks

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#330]
A `preChartLoad` hook allows you to run an arbitrary command before helmfile runs a helm command that requires the existence of the chart.

```yaml
releases:
- ...
  hooks:
    preChartLoad: # register as many commands as you want to this hook
    - command: {{` ./chartify -e {{ .Environment.Name }} {{ .Chart }} `}}
```

Use-cases:

- https://github.com/roboll/helmfile/issues/295#issuecomment-419870215
- https://github.com/roboll/helmfile/issues/324#issuecomment-420108479

This depends on the per-value templating feature in helmfile.yaml as described in #329.
If we are to implement this at the first time, probably we should enable per-value templating only on chart hook commands. It will be enough for preChartLoad hooks, YAGNI, and could become a base of further discussions about how we'd evolve the per-value templating feature.
