### ISSUE TITLE
when no charts are selected repos don't get synced

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#338]
With the below helmfile a `helmfile repos` will result in 
`err: no releases found that matches specified selector() and environment(default), in any helmfile`

```
repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
```

On a similar vein the following will result in the stable repo never being added as this helmfile itself has no matching charts in it.
```
repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

environments:
  prod:
  dev:

helmfiles:
- helm/account/helmfile.yaml
{{ if (eq .Environment.Name "prod") }}
- helm/account/prod/helmfile.yaml
{{- end }}
{{ if (eq .Environment.Name "dev") }}
- helm/account/dev/helmfile.yaml
{{- end }}

```
