### ISSUE TITLE
Go templates `default` functionality is broken after version 0.33.0

### ISSUE THREAD

**Issue by apetheriotis** [roboll/helmfile#357]
The following example (it's provided in the helmfile readme) works on version 0.33 but on version 0.34 and onwards:

`helmfile.yaml`
```
environments:
  production:
    values:
    - production.yaml

releases:
- name: myapp
  values:
  - values.yaml.gotmpl
```

`production.yaml`
```
domain: prod.example.com
releaseName: prod
values.yaml.gotmpl

domain: {{ .Environment.Values.domain | default "dev.example.com" }}
```

The above setup fails on version 0.34 and onwards with:
```
 map has no entry for key "domain"
```

when the `domain` value is missing from the environment file `production.yaml`

Probably the functionality of go templates is not the expected one when the key is missing from the values file.

**Comment by davidovich** [comment]
Yes, I have reproduced this, and it is related to template parsing defaults that have changed from `missingkey=zero` to `missingkey=error`. See #317 for discussion.

The change appeared while implementing #308.

But I would like @mumoshu and @sstarcher to chime in on this because they reflected on the problem, and concluded that failing on a missing key was a better outcome. If the new behavior is wanted, we would need to update this example in the README to correctly reflect this fact.

Meanwhile, as a workaround, you can add a `default:` key in the `environments:` dictionary referencing a default.yaml which defines domain:

```yaml
environments:
  default:
     values:
        - default.yaml
```

**Comment by mumoshu** [comment]
Apologies I should have updated the doc about this. As @davidovich has kindly summarized, this is now a desired behavior.

The defaulting with the `default` func has possibility to hide the bug due to that you actually wanted to set an env value, but missed to do so. That's why I thought this should be a desired behavior. You should explicitly set the default value, in this case `"dev.example.com"`, explicitly in your `production.yaml`.

Does this make sense? I'm happy to hear your opinions.

**Comment by apetheriotis** [comment]
Thank you both for the clarification and no worries about the docs. 

> You should explicitly set the default value, in this case "dev.example.com", explicitly in your production.yaml.

I think following the above approach results in having a lot of duplicated values . For example in our case with 30 apps and 6 environments we would need to copy the value `replicas: 1`  in 5 different files and only change it in one file (prod.yaml) `replicas:2`. Instead if we could default it, we would have to declare the value `replicas:` just once (only in prod.yaml).

**Comment by sstarcher** [comment]
@apetheriotis could you give an example of how you used it before so we can see what the best path forward will be?

**Comment by apetheriotis** [comment]
Sure. So:


### Helmfiles structures 
```
apps/
  notify-api/
     helmfile.yaml    
  ...           
```

helmfile of notify api looks similar this:

```
helmDefaults:
  tillerNamespace: dev

environments:
  dev:
    values:
    - ../../../values/environments/dev.yaml

releases:
- chart: foobar/ap-notify-api
  name: ap-notify-api
  namespace: dev
  values:
  - ../../../values/apps/notify-api/notify-api.yaml.gotmpl
  version: 1.2.3
```

(Notice here, that in version 0.37 I could template the version, namespace etc so I could have only one file for each app and not one file per app per environment ) 

### Template structures 

```
apps\
 notify-api\
   notify-api.yaml.gotmpl
 .... 
```
where `notify-api.yaml.gotmpl` is:

```
replicas: {{ .Environment.Values.eventApi.replicas | default 1 }}

dashboards:
  enabled: {{ .Environment.Values.notifyApi.dashboards.enabled | default false }}
```

### Environment  structures 
```
dev.yaml

eventApi:
  dashboards:
    enabled: true
```
```
prod.yaml

eventApi:
  replicas: 10
```

^^ this is the point where the functionality of `default` is useful.

**Comment by sstarcher** [comment]
I was going to recommend something along the lines of, but realized with the new error setup that is likely not possible.

```
{{ if .Environment.Values.eventApi.replicas }}
replicas: {{ .Environment.Values.eventApi.replicas }}
{{ endif }}
```

**Comment by sstarcher** [comment]
@mumoshu do we have any way to check if a key exists without trying to access it.

**Comment by mumoshu** [comment]
@sstarcher AFAIK, theres no way to do so.

We could probably add a template func that works like `{{ exists ".Environment.Values.eventApi.replicas" }}` but in my op it isn't very intuitive.

> I think following the above approach results in having a lot of duplicated values

@apetheriotis This is definitely an issue that should be fixed somehow. I was thinking to allow "overlaying" environment values tmpl files like:

dev.yaml.gotmpl

```yaml
{{ readFile "defaults.yaml "}}
---
notifyApi:
  dashboards:
    enabled: true
```

prod.yaml.gotmpl

```yaml
{{ readFile "defaults.yaml "}}
---
notifyApi:
  replicas: 10
```

defaults.yaml

```yaml
notifyApi:
  replicas: 1
```

But I'm not very sure if everyone thinks this intuitive. I personally prefer this way, as you can make each env values files self-contained - no need to consult each chart values template files to see what's the default value.

WDYT?
