### ISSUE TITLE
feat: Support inline environment values for `.Environment.values.`

### ISSUE THREAD

**Issue by dtshepherd** [roboll/helmfile#359]
Support inline values for the `environments:` similar to `releases:`:
```
environments:
  default:
    values:
    - releaseName: "myrelease"
```
Which would allow you to access `{{ .Environment.Values.releaseName }}` without needing a separate file created.

**Comment by dtshepherd** [comment]
Split the CLI issue to #361

**Comment by mumoshu** [comment]
Thanks for the request! Yeah, I think this is useful.

**Comment by davidovich** [comment]
There is some opportunity to reuse existing code as this is exactly what is done in the releases section.

We would need to extract into a function the *values byte extracting logic* in [state.go](https://github.com/roboll/helmfile/blob/master/state/state.go#L1054-L1098), and reuse that. Note that this function does too many things right now, it extracts the values from files and creates temporary value files to be passed to helm. 

In essence, we would write a reusable ValuesExtractor, which could feed its bytes to a temporary helm values file writer, and then reuse this ValuesExtractor for implementing this issue.

**Comment by mumoshu** [comment]
Yeah. That sounds like a good way to implement this!

**Comment by asychev** [comment]
@mumoshu @roboll @sstarcher @cmeury 5 cents: it can be very useful to expose environment values to helmfile.yaml itself. In my case, I want to adjust db deployment per environment: in some environments I want to just spin up stable/postgres, but in another - inject cloudsql_proxy to backend deployment for use of Google Clouse SQL. Now it only possible by evaluating `.Environment.Name`, which is not intuitive. Any toughts? Maybe it already discussed somewhere?

**Comment by mumoshu** [comment]
@asychev I think env values are already available for use within helmfile.yawl in recent versions of helmfile. Do you have any specific example it doesn't work as expected?

**Comment by nikolajbrinch** [comment]
But if you use 
``` 
{{ readFile "environments.yaml" }}
---
```
The .Environment.Values read from here are not available in the helmfile.yaml

environments.yaml:
```
environments:
  dev:
    values:
    - ../../../values/dev/common.yaml
  test:
    values:
    - ../../../values/test/common.yaml
  preprod:
    values:
    - ../../../values/preprod/common.yaml
  prod:
    values:
    - ../../../values/prod/common.yaml
```
