### ISSUE TITLE
Env var interpolation in `repositories`

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#36]
Would it be possible to enhance the env var interpolation feature, so that we could safely git-commit a helmfile referencing private chart repositories which requires authn?

For example, we can use **private** git repos as helm chart repos like described in https://github.com/kmzfs/helm-repo-in-github#how-to-use-it-as-a-helm-repo.
However, it requires you to include a sensitive information(=auth credential) in repository urls.

Simply doing it results in a charts.yaml like:

```yaml
respositories:
- name: your-private-git-repo-hosted-charts
  url: https://YOUR_GITHUB_TOKEN@raw.githubusercontent.com/kmzfs/helm-repo-in-github/master/
```

which ins't very good to be committed into your git repo.

If the `repositories` section had a support for env var interpolation, it would look like:

```yaml
respositories:
- name: your-private-git-repo-hosted-charts
  url: "https://{{ env \"GITHUB_TOKEN\"}}@raw.githubusercontent.com/kmzfs/helm-repo-in-github/master/"
```

This makes helmfile safe enough to be committed into a git repo.

Note that running `helm sync` would result in printing the repository url containing the token like:

```
exec: helm repo add your-private-git-repo-hosted-charts https://YOUR_GITHUB_TOKEN@raw.githubusercontent.com/kmzfs/helm-repo-in-github/master/
```

I'd like to fix it, too. However, it could be done in an another github issue.
