### ISSUE TITLE
Implement absent for deletion of charts

### ISSUE THREAD

**Issue by estahn** [roboll/helmfile#362]
I would like to be able to define `absent` as part of a release in the helmfile. Upon `helmfile sync` all releases with `absent: true` will be deleted.

```
releases:
  - name: super-magician
    namespace: default
    chart: stable/prometheus-cloudwatch-exporter
    version: 0.2.0
    values:
      - prometheus-cloudwatch-exporter/values.yaml
    absent: true
```
