### ISSUE TITLE
Bug with environment values merge

### ISSUE THREAD

**Issue by asychev** [roboll/helmfile#377]
Hi! I think this is a bug or, maybe, I have missing something.

Imagine the following structure:

```
├── charts
│   └── environment
│       ├── Chart.yaml
│       ├── templates
│       │   └── configmap.yaml
│       └── values.yaml
├── environments
│   ├── dev
│   │   └── values.yaml
│   └── default.yaml.gotmpl
├── helmfile.yaml
└── values.yaml.gotmpl
```
```helmfile.yaml:```
```
environments:
  default:
    values:
    - environments/default.yaml.gotmpl
  dev:
    values:
    - environments/dev/values.yaml
    - environments/default.yaml.gotmpl

releases:
  - name: environment
    chart: ./charts/environment
    labels:
      tier: infrastructure
    values:
    - values.yaml.gotmpl
```
```values.yaml.gotmpl:```
```
baseUrl: {{ .Environment.Values | get "baseUrl" }}
backend:
  debug: {{ .Environment.Values | get "backend.debug" }}
```
```environments/default.yaml.gotmpl```
```
baseUrl: {{ .Environment.Values | getOrNil "baseUrl" | default "DEFAULT_ENV_BASEURL" }}
backend:
  debug: {{ .Environment.Values | getOrNil "backend.debug" | default "DEFAULT_ENV_DEBUG" }}
```
```environments/dev/values.yaml```
```
baseUrl: DEV_ENV_BASEURL
backend:
  debug: DEV_ENV_DEBUG
```
```charts/environment/values.yaml```
```
baseUrl: CHART_BASEURL
backend:
  debug: CHART_FALSE
```
```charts/environment/templates/configmap.yaml```
```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: configuration
data:
  BASE_URL: {{ .Values.baseUrl }}
  BACKEND_DEBUG: {{ .Values.backend.debug }}
```
```helmfile -l tier=infrastructure -e default template```
```
---
# Source: environment/templates/configmap.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: configuration
data:
  BASE_URL: DEFAULT_ENV_BASEURL
  BACKEND_DEBUG: DEFAULT_ENV_DEBUG
```
```helmfile -l tier=infrastructure -e dev template```
```
---
# Source: environment/templates/configmap.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: configuration
data:
  BASE_URL: DEFAULT_ENV_BASEURL <-- WHY? Needs to be DEV_ENV_BASEURL
  BACKEND_DEBUG: DEV_ENV_DEBUG
```
If I change order in helmfile.yaml from this
``` 
dev:
    values:
    - environments/dev/values.yaml
    - environments/default.yaml.gotmpl
```
to this:
``` 
dev:
    values:
    - environments/default.yaml.gotmpl
    - environments/dev/values.yaml
```
new result:
```
---
# Source: environment/templates/configmap.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: configuration
data:
  BASE_URL: DEV_ENV_BASEURL
  BACKEND_DEBUG: DEFAULT_ENV_DEBUG <--- WHY? Needs to be DEV_ENV_DEBUG
```

What am I doing wrong?

**Comment by asychev** [comment]
@mumoshu Thank you for the clarification, but it is still unclear for me.

About (1) - as I show before - only part of values wins.

In provided example seems that environments/default.yaml.gotmpl not needed anymore, because now I need to put the full set of variables into default environment values and to each other environment values files. I tried to avoid code duplication, when all values located in environments/default.yaml but in dev - only overrides of part of them, specific to dev environment.

If so, is it better to put default  values logic to values.yaml.gotmpl in `values` of `releases` and get rid of default environment files?

**Comment by mumoshu** [comment]
Hey! Thanks for the response.

> environments/default.yaml.gotmpl not needed anymore, because now I need to put the full set of variables into default environment values

Yes.

> but in dev - only overrides of part of them, specific to dev environment.

Yes. This is possible. Sorry If I'm not following you correctly, but you can of course write your `environments/dev/values.yaml` like this:

```
baseUrl: DEV_ENV_BASEURL
#Omit `backend` from your yaml, and then only `baseUrl` is overrode
#backend:
#  debug: DEV_ENV_DEBUG
```

You now have no need to complicate things with `getOrNil ... | default ...`.
And there seems like no code duplication in my example.

Is there anything else you wanted to do on top of this? Any input is welcomed. Thanks.

**Comment by asychev** [comment]
@mumoshu it is still not working for me:

```
.
├── charts
│   └── environment
│       ├── Chart.yaml
│       ├── templates
│       │   └── configmap.yaml
│       └── values.yaml
├── environments
│   ├── default.yaml
│   └── dev
│       └── values.yaml
├── helmfile.yaml
└── values.yaml.gotmpl
```
```helmfile.yaml```
```
environments:
  default:
    values:
    - environments/default.yaml
  dev:
    values:
    - environments/default.yaml
    - environments/dev/values.yaml

releases:
  - name: environment
    chart: ./charts/environment
    labels:
      tier: infrastructure
    values:
    - values.yaml.gotmpl
```
``` environments/default.yaml```
```
baseUrl: DEFAULT_ENV_BASEURL
backend:
  debug: DEFAULT_ENV_DEBUG
```
```environments/dev/values.yaml```
```
baseUrl: DEV_ENV_BASEURL
backend:
  debug: DEV_ENV_DEBUG
```
```values.yaml.gotmpl```
```
baseUrl: {{ .Environment.Values | get "baseUrl" }}
backend:
  debug: {{ .Environment.Values | get "backend.debug" }}
```

``` $ helmfile -l tier=infrastructure -e default template```
```
---
# Source: environment/templates/configmap.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: configuration
data:
  BASE_URL: DEFAULT_ENV_BASEURL
  BACKEND_DEBUG: DEFAULT_ENV_DEBUG
```
```$ helmfile -l tier=infrastructure -e dev template```
```
---
# Source: environment/templates/configmap.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: configuration
data:
  BASE_URL: DEV_ENV_BASEURL
  BACKEND_DEBUG: DEFAULT_ENV_DEBUG <---
