### ISSUE TITLE
No dependencies possible

### ISSUE THREAD

**Issue by hans-d** [roboll/helmfile#382]
```
repositories:
  - name: coreos
    url: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

releases:
- name: prometheus-operator
  namespace: monitoring
  chart: coreos/prometheus-operator
  values:
    - prometheus-operator-values.yml

- name: prometheus-server
  namespace: monitoring
  chart: coreos/kube-prometheus
  values:
    - prometheus-values.yml
```
The second sometimes gets executed first, causing it to fail as the first entry is needed first.

Would be nice to be able to specify that `prometheus-server` depends on `prometheus-operator`
