### ISSUE TITLE
Not able to use environment values in templates

### ISSUE THREAD

**Issue by jasonmorganson** [roboll/helmfile#384]
When using this `helmfile.yaml`, the environment values are not available in my helm template files.

```yaml
environments:
  sandbox:
    values:
    - sandbox/values.yaml
    secrets:
    - sandbox/secrets.yaml
  production:
    values:
    - production/values.yaml
    secrets:
    - production/secrets.yaml

releases:
- name: prom-norbac-ubuntu
  namespace: prometheus
  chart: stable/prometheus
```
I expected that to work. Am I missing something?

**Comment by asychev** [comment]
@jasonmorganson 

> Environment Values allows you to inject a set of values specific to the selected environment, into **_values.yaml templates_**. 

So, you need to write values.yaml.gotmpl and add it to `release` - in `values: `section

**Comment by call** [comment]
I had this same question and would have benefitted from a more explicit answer w/ samples. Here are some samples for anyone else who come across this issue needing help:

**helmfile.yaml**
```
environments:
  prod:
    secrets:
    - environments/prod/secrets.yaml
  dev:
    secrets:
    - environments/dev/secrets.yaml

{{ if eq .Environment.Name "prod" }}
context: some-prod-context
{{ end }}
{{ if eq .Environment.Name "dev" }}
context: some-dev-context
{{ end }}

releases:
- name: myrelease
  namespace: myreleasens
  chart: stable/myrelease
  version: 1.2.3
  values:
  - values.yaml.gotmpl
```

**values.yaml.gotmpl**
```
foo_secret:
  enabled: {{ .Environment.Values.foo_secret.enabled }}
  foo: {{ .Environment.Values.foo_secret.foo }}
  bar: {{ .Environment.Valuesfoo_secret.bar | quote }}
baz_secret:
  fizz: {{ .Environment.Values.baz_secret.fizz }}
  buzz: {{ .Environment.Values.baz_secret.buzz | quote }}
# ^^ '| quote' is necessary for things like ssh & jwt keys
```
**environments/prod/secrets.yaml**
```
foo_secret:
  enabled: true
  foo: myfoosecret
  bar: mybarciphertext
baz_secret:
  fizz: myfizzsecret
  buzz: mybuzzciphertext
