### ISSUE TITLE
Feat: Allow simple Vault integration

### ISSUE THREAD

**Issue by AndresPineros** [roboll/helmfile#392]
Currently there are many users that want to integrate Vault with Kubernetes, but there are no high level tools for this. The current Kubernetes AuthMethod for Vault is too complex and coupled to the definition of the charts. This proposal could allow for a Vault integration with Kubernetes that is simple and decoupled.

This could be the structure of a helmfile integrated with Vault:
```
releases:
  - chart: .
    name: release-test
    version: 0.1.0
    values:
      - application:
           mysql_url: jdbc.....
           mysql_user: localtest
           mysql_password: localtest
    vault:
      active: true
      secrets:
        - vaultPath: secret-engine/my-application
          key: mysql.username
          targetVar: application.mysql_user
        - vaultPath: secret-engine/my-application
          key: mysql.password
          targetVar: application.mysql_password
```

Basically the project could use the VAULT_ADDR and VAULT_TOKEN environment variables to query all the secrets from Vault using the `vaultPath` and the `key` to inject them to the helm release using `--set`.

So, for that example the `--set` flags of the `helm upgrade -i ...` command would look like:
```
--set application.mysql_user=<queried-secret> --set application.mysql_password=<queried-secret>
```

If the `vault.active` field is set to false, or the `vault` field is not used, the release will just use the "localtest" values.

The main advantage I see for this proposal is that it allows centralization of secrets. Usually storing encrypted secrets in repositories result in secret-management-madness as there is no unique source of truth in case multiple repositories require the same secret. Vault solves this. Of course, this approach only addresses static Vault secrets (secrets in git repos are static too). For dynamic Vault secrets, I think there's no other alternative than the Kubernetes Auth Method.

There is one security issue with this proposal: Tiller has to use the --storage (Secret) backend instead of the ConfigMap backend to avoid fetching injected secrets with `helm get values <release-name>`. Although, I think this is also a problem for the `helm-secrets` pluign.

**Comment by AndresPineros** [comment]
I would really like to PR this, but I don't know Golang. I just started learning it to be able to contribute, but I don't know how long it can take for me to learn and do a decent PR.

**Comment by mumoshu** [comment]
@AndresPineros Hey!

> there is no unique source of truth in case multiple repositories require the same secret

Yeah, I believe this is definitely the thing we should consider.

A possible work-around as of today would be to use templating. That is, include something like `{{ exec "./your/cmd/to/fetch/vault/secret/to/dump/yaml/or/json" (list "path.to.key") }}` within a `values.yaml.gotmpl` under `secrets:` field of your `helmfile.yaml`.

Would it work?

**Comment by sstarcher** [comment]
I think this would be a great feature to directly support and essentially change the secrets handling into a plug-able system.

**Comment by mumoshu** [comment]
And please let me plug-in that my own use-case requires an integration with AWS Secrets Manager :)

**Comment by mumoshu** [comment]
So I was wondering if it is possible to integrate a tool like gomplate to helmfile.

Relying on [gomplate datasources](https://gomplate.hairyhenderson.ca/datasources/), we can reliably add support for many backends including vault.

An example helmfile.yaml featuring the feature would look like:

```yaml
releases:
  - chart: .
    name: release-test
    version: 0.1.0
    datasources:
      myvault: vault://vault.example.com:8200///secret-engine/my-application
    values:
      - application:
           mysql_url: jdbc.....
           # Note that {{` and `}} must be required to defer template execution. Otherwise it is executed on loading helmfile.yaml, which doesnt work due to that no datasources are loaded yet
           mysql_url: {{` (datasource "myvault" "mysql.username" `}}
           mysql_password: {{` (datasource "myvault" "mysql.password" `}}
```

**Comment by osterman** [comment]
Data sources like `gomplate` would be great. Before I saw this issue, *today* I was thinking how it would be nice to access SSM Parameter store directly.

**Comment by osterman** [comment]
An extreme mock example of chaining commands:
```
exec dumb-init gosu ${ATLANTIS_USER} env BASH_ENV=/etc/direnv/bash direnv exec . chamber exec atlantis -- atlantis server
```

**Comment by mumoshu** [comment]
An alternative idea would be to focus on making secrets consumption from any backend declarative, while making the changes required to helmfile minimum.

That is, allow defining any secrets backend within a helmfile.yaml:

```yaml
secretsProvider:
- name: vault
  command: "bin/helmfile-secrets-provider-vault"
  protocols:
  - "vault"

releases:
-  chart: .
    name: release-test
    version: 0.1.0
    secrets:
      - vault://vault.example.com:8200////secret-engine/my-application/?application.mysql_user=mysql.user,application.mysql_password=mysql.password
```

In the above example, `bin/helmfile-vault-provider` is executed like `bin/helmfile-vault-provider 'vault://vault.example.com:8200////secret-engine/my-application/?...' > $temp_file_created_by_helmfile` to produce a values.yaml-like file containing the secret .

The produced secrets file should be subject to caching proposed in #444
