### ISSUE TITLE
helm default values are not used when layering values

### ISSUE THREAD

**Issue by apetheriotis** [roboll/helmfile#397]
Hi again :) 
I think helm defaults values are not used with the following structure (unless I a missing something)

```
----------- helmfile.yaml---------------
environments:
  production:
    values:
    - production.yaml

releases:
- name: myapp
  values:
  - values.yaml.gotmpl
-----------------------------------------------
```

```
----------- production.yaml---------------
 production.yaml                                         
    helmDefaults:                                          
       namespace: foo-namespace              
       tillerNamespace: foo-namespace      
-----------------------------------------------
```
if I put the `helmDefaults` inside the helmfile then everything seems to work.

**Comment by apetheriotis** [comment]
I just realised I can use the following:

```
----------- helmfile.yaml---------------
helmDefaults:                                        
  tillerNamespace: {{ .Environment.Values.tillerNamespace }}   

environments:
  production:
    values:
    - production.yaml

...
```

Apologies for the spamming :)
