### ISSUE TITLE
--set-file path semantics inconsistent with values:

### ISSUE THREAD

**Issue by clkao** [roboll/helmfile#399]
The path used in `set.file` is relative to pwd, rather than relative to the path of the actual helmfile or helmfile fragments.  This makes it inconsistent with the value files listed under `values:`.

ie for `helmfile.d/foo.yaml`:

```
    values:
      - ../foo-values.yaml
    set:
      - name: config.large-chunk-json
        file: ../foo-config.json
```

will actually not work for foo-values and foo-config.json in the same directory.
