### ISSUE TITLE
Feature request: Inlined values

### ISSUE THREAD

**Issue by hlascelles** [roboll/helmfile#40]
Would there be any appetite to allow inlining values in their natural nested form (instead of name/value pair). I imagine it would require temporary file creation during execution, unless there are libs to convert nested yaml to json dot notation. Not sure if that is beyond helmfile's remit.

eg:

```
charts:
  - name: vault                      
    namespace: vault             
    chart: roboll/vault-secret-manager
    inlined_values: 
      some:
        quite:
        - name: deep
          value: 
            variable: {{ env "VAL" }}
```

**Comment by mumoshu** [comment]
@hlascelles Hi! Thanks for the request.

> I imagine it would require temporary file creation during execution, unless there are libs to convert nested yaml to json dot notation

Would it work for you if helmfile translated your example to:

```yaml
set:
- name: some.quite.deep
   value: "{{ env \"VAL\" }}"
```

Is this what you're looking for?

And also, I'm still unable see a concrete benefit from achieving what you suggest 🤔 

Just curious, but what's your goal of having the another way to specify deeply nested values?
