### ISSUE TITLE
Absolute paths to values files do not work

### ISSUE THREAD

**Issue by ariep** [roboll/helmfile#400]
The following part of a helmfile (which is contained inside `helmfile.d`)
```
environments:
  myenv:
    values:
      - "/absolute/path/to/values.yaml"
```
fails to load the values file, because apparently the absolute path is appended to the path to the `helmfile.d` directory, giving `/path/to/helmfile.d/absolute/path/to/values.yaml` which is obviously not what was intended.
