### ISSUE TITLE
False positives when running helm-diff

### ISSUE THREAD

**Issue by andytom** [roboll/helmfile#410]
This is a little bit strange and I've been unable to reliably reproduce this issue but have seen this multiple time when running in our CI system.  The problem is that sometimes running `helmfile diff` returning false positives (see example below). I have only ever seen this happen when running multiple helm diffs processes at a time (e.g with `--concurrency` not set to `1`).

Example:
```diff
$ helmfile diff --concurency 3  --suppress-secrets
...
Comparing example1 internal-stable/example1
Comparing example2 internal-stable/example2
default, example1, Secret (v1) has changed:
+ Changes suppressed on sensitive content of type Secret
default, example1, ConfigMap (v1) has changed:
  # Source: example1/templates/configMap.yaml
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: example1
    labels:
-     app: "example1"
+     app: "example2"
      chart: "example1-0.2.1"
      release: "example1"
      heritage: "Tiller"
      image_tag: "0.0.1"
    data:
# -- REDACTED --
default, example1, Deployment (extensions) has changed:
  # Source: example1/templates/deployment.yaml
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: example1
    labels:
-     app: "example1"
+     app: "example2"
      chart: "example1-0.2.1"
      release: "example1"
      heritage: "Tiller"
      image_tag: "0.0.1"
  spec:
# -- REDACTED --

Comparing example3 internal-stable/example3
...
```

The `app` label is hard coded in the chart so should always be the same so I'm a little bit puzzled why this would change.
```handlebars
{{- define "releaseLabels" }}
app: "example1"
chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
release: "{{ .Release.Name }}"
heritage: "{{ .Release.Service }}"
image_tag: "{{ .Values.image.tag }}"
{{- end }}
```

We are currently running the following versions
```
$ helmfile --version
helmfile version v0.40.1
```
```
$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"} 
```
```
$ helm diff version
2.11.0+2
```

**Comment by mumoshu** [comment]
@andytom Hey! Thanks for the report.

At glance it seemed like a race issue in helm-diff, but reading helm-diff [code](https://github.com/databus23/helm-diff/blob/master/cmd/upgrade.go#L96) doesn't give me any insight. helm-diff seems to have no chance of a race here.. The same applies to helmfile as far as I can [see from the code-base](https://github.com/roboll/helmfile/blob/master/state/state.go#L639).

Do you by any chance have a kind of "global state" - like shared file(s), storage(s) - that affects your chart rendering?

**Comment by andytom** [comment]
> Do you by any chance have a kind of "global state" - like shared file(s), storage(s) - that affects your chart rendering?

Not that I can see, we have separate values files for each release and we use [helm-s3](https://github.com/hypnoglow/helm-s3) as our chart repo.

Our helmfile is very simple and looks like this
```yaml
---

repositories:
  - name: internal-stable
    url: s3://redacted/stable

charts:
  - name: example1
    chart: internal-stable/example1
    version: 0.2.1
    values:
      - stg/example1.yaml

  - name: example2
    chart: internal-stable/example2
    version: 0.2.1
    values:
      - stg/example2.yaml

  - name: example3
    chart: internal-stable/example3
    version: 0.2.1
    values:
      - stg/example3.yaml
...
```
