### ISSUE TITLE
Equivalent of Files.AsConfig of Helm

### ISSUE THREAD

**Issue by victornoel** [roboll/helmfile#414]
I have a chart with the following template:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-chart.fullname" . }}-embedded-files
data:
{{ toYaml .Values.embeddedFiles | indent 2 }}
```

The objective being to get the content of a set of files (they are in a directory on the filesystem) in this `ConfigMap`.

With helm by itself, I would have used: `{{ (.Files.Glob "my-files/*").AsConfig | indent 2 }}` to generate this part. With helmfile, I used `toYaml` combined with a value as above.

In the helmfile, for now, as a workaround, I write:
```yaml
    set:
      - name: "embeddedFiles.file-one\\.txt"
        file: my-files/file-one.txt
      - name: "embeddedFiles.file-two\\.txt"
        file: my-files/file-two.txt
     - ... etc
```

It would be great to have a access to a template function similare to the ones available for `Files` in helm to be able to write something like this:
```yaml
    set:
      - name: embeddedFiles
        value: {{ (.Files.Glob "my-files/*").AsConfig }}
```
