### ISSUE TITLE
Prescriptive directory structure for "magic" values files

### ISSUE THREAD

**Issue by mattparkes** [roboll/helmfile#428]
I've written a helmfile containing abut 40 releases and I'm having to repeat myself _a lot_:

Example:
```
  - name: heapster
    namespace: kube-system
    chart: stable/heapster
    version: 0.3.2
    values:
      - "./values/logging/heapster/common.yaml"
      - "./values/logging/heapster/{{ .Environment.Name }}.yaml"
    secrets:
      - "./values/logging/heapster/common-secrets.yaml"
      - "./values/logging/heapster/{{ .Environment.Name }}-secrets.yaml"

  - name: kubernetes-dashboard
    namespace: kube-system
    chart: stable/kubernetes-dashboard
    version: 0.10.0
    values:
      - "./values/kube-system/kubernetes-dashboard/common.yaml"
      - "./values/kube-system/kubernetes-dashboard/{{ .Environment.Name }}.yaml"
    values:
      - "./values/kube-system/kubernetes-dashboard/common-secrets.yaml"
      - "./values/kube-system/kubernetes-dashboard/{{ .Environment.Name }}-secrets.yaml"
```

One feature I really like about Ansible is that it automatically looks for it's values files for each "playbook" in [a certain directory structure](https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#directory-layout), and looks in multiple locations in a known order, allowing easy environment specific overrides, etc.

I think it would be really nice if `helmfile` automatically looked for a `values/<namespace>/<release-name>` directory and then automatically loaded (in order):
 1. A common file regardless of environment _(maybe `values.yaml` or `common.yaml`)_.
 2. An environment specific file (e.g `production.yaml`).
 3. Any files explicitly listed in the `helmfile.yaml` _(in order)_.

And then a similar process for secrets (either in a `secrets/<namespace>/<release-name>` directory or in `values/<namespace>/<release-name>`, with files suffixed with `-secrets` treated as secrets e.g `production-secrets.yaml`.)

Another things is that if helmfile can't stat the file, it errors out (which is great in that it stops mistakes from missing files), but it would be nice if a a switch could be set so that a certain file and/or directory not existing is a warning, not an error.

**Example Directory Tree:**
```
values/
    kube-system/                      # 'kube-system' namespace
        dashboard/                    # 'dashboard' release
            production.yaml           #  production Environment specific values
            production-secrets.yaml   #  production Environment specific secrets
            staging.yaml              #  staging Environment specific values
            values.yaml               #  contains values common to all Environments
        heapster/
            values.yaml               #  only common values.yaml is provided, no environment specific values are needed.
    web/                              # 'web' namespace
        [..]                          # sub-directories similar to above
```

Then my `helmfile.yaml` could be simplified to:

```
  - name: heapster
    namespace: kube-system
    chart: stable/heapster
    version: 0.3.2

  - name: kubernetes-dashboard
    namespace: kube-system
    chart: stable/kubernetes-dashboard
    version: 0.10.0
```

**Comment by sstarcher** [comment]
I have similar boilerplate that I use over and over again
```
accounts/
  dev/
  stg
    prometheus/
       values.yaml
       secrets.yaml
releases/
  prometheus/
    values.yaml
```

**Comment by mattparkes** [comment]
#408 Reduces the length of the lines, but not the number of lines, which is my ultimate goal with this suggestion.

I'll definitely updated my helmfile to make use of that feature though

**Comment by mumoshu** [comment]
I had been considering this as an important problem that should be fixed. But I had no idea how we can universally fix it. It is possible if you use `{{define` in the template but I think that's not what you want.

What if we add helmfile "mixins"?

```yaml
mixins:
  foo:
    # New configuration keys. The current behavior is 'Error'
    onMIssingValuesFile: Warn
    onMIssingSecretsFile: Warn
    values:
     # IMPORTANT: {{` {{ .Release.Name }} `}} is surrounded by {{` and `}} not to be executed on the loading time of helmfile.yaml.
     # We need to defer it until each release is actually processed by sync|diff|apply|etc.
      - "./values/logging/{{` {{ .Release.Name }} `}}/common.yaml"
      - "./values/logging/{{` {{ .Release.Name }} `}}/{{ .Environment.Name }}.yaml"
    secrets:
      - "./values/logging/{{` {{ .Release.Name }} `}}/common-secrets.yaml"
      - "./values/logging/{{` {{ .Release.Name }} `}}/{{ .Environment.Name }}-secrets.yaml"

releases:
- name: heapster
  namespace: kube-system
  chart: stable/heapster
  version: 0.3.2
  # Selectively include the mixin
  include:
  - foo
- name: kubernetes-dashboard
  namespace: kube-system
  chart: stable/kubernetes-dashboard
  version: 0.10.0
  include:
  - foo
```

Also extending and renaming `helmDefaults` to `defaults` for the sake of simpicity, you can write it even shorter:

```yaml
mixins:
  foo:
    # New configuration keys. The current behavior is 'Error'
    onMIssingValuesFile: Warn
    onMIssingSecretsFile: Warn
    values:
      - "./values/logging/{{` {{ .Release.Name }} `}}/common.yaml"
      - "./values/logging/{{` {{ .Release.Name }} `}}/{{ .Environment.Name }}.yaml"
    secrets:
      - "./values/logging/{{` {{ .Release.Name }} `}}/common-secrets.yaml"
      - "./values/logging/{{` {{ .Release.Name }} `}}/{{ .Environment.Name }}-secrets.yaml"

defaults:
  include:
  - foo

releases:
- name: heapster
  namespace: kube-system
  chart: stable/heapster
  version: 0.3.2
- name: kubernetes-dashboard
  namespace: kube-system
  chart: stable/kubernetes-dashboard
  version: 0.10.0
```

**Comment by sstarcher** [comment]
That seems reasonable and I like the addition of `onMissing`

**Comment by royjs** [comment]
yeah I also like the `onMissingValuesFile` addition. I think that it's really what is missing right now.
And the mixins idea would really help avoiding duplication

**Comment by mattparkes** [comment]
I _love_ the idea , but I'm not sure about about the terminology "`mixin`". (I see it's popular for Vue, so maybe other people are more familiar with the term.)

Maybe "`templates`" with a special entry called "default" which is applied to all releases (if it exists) and then we can move _all_ the stuff currently into helmDefaults into this and allow them to be specified per
```
templates:
  default:
    # New configuration keys. The current behavior is 'Error'
    missingValues: Warn
    missingSecrets: Warn
    values:
      - "./values/{{` {{ .Release.Name }} `}}/common.yaml"
      - "./values/{{` {{ .Release.Name }} `}}/{{ .Environment.Name }}.yaml"
    secrets:
      - "./values/{{` {{ .Release.Name }} `}}/common-secrets.yaml"
      - "./values/{{` {{ .Release.Name }} `}}/{{ .Environment.Name }}-secrets.yaml"
    tillerNamespace: default
    verify: false
    recreatePods: true

  mustfail:
    missingValues: Error
    missingSecrets: Error
    verify: true
    recreatePods: false
```

```
releases:
- name: heapster
  namespace: kube-system
  chart: stable/heapster
  version: 0.3.2
  template: default               # 'default' is implicit, but explicitly defined here as an example 

- name: kubernetes-dashboard
  namespace: kube-system
  chart: stable/kubernetes-dashboard
  version: 0.10.0
  template: mustfail             # mustfail is a combination of default with 'mustfail' (defined above) merged/replaced over the top
```

**Comment by mumoshu** [comment]
> Maybe "templates" with a special entry called "default" which is applied to all releases (if it exists) and then we can move all the stuff currently in helmDefaults into this.

Thanks for the feedback! I like the idea a lot 👍 

Are you ok with suffixing `missingValues` with `Policy` or `FilePolicy`? So that it looks `missingValuesFilePolicy: Warn` or `missingValuesPolicy: Warn`.

The intention here is to make it extra clear that it decides how(=policy) to handle missing values/secrets "file". It would be ok to omit the "file" part if it is already clear that it works against values files, not inline values.

**Comment by mumoshu** [comment]
Also, I think "template" is a good terminology that follows "pod templates" in k8s.

One reason I chosen "mixins" and "include" was to allow including multiple mixins for maximum reusability.

But YAGNI, right? Or do you think it's a good idea to start with `mixins` and `include` now?

Even in that case, I'd definitely borrow your idea of using `default` as the set of things included to releases by default, and rephrasing `helmDefaults` to `mixins.default` combied with implicit `include: [default]`

**Comment by mattparkes** [comment]
Yeah `missingValuesPolicy` or `missingValuesAction` looks good.

I'm personally happy with either terminology, especially since I'm only doing the easy part and writing the suggestion.

**Comment by mattparkes** [comment]
Your ``{{` {{ .Release.Name }} `}}`` syntax inspired me to try just use YAML `Anchors` and `Extends`.

Because Helmfile doesn't like invalid keys in the helmfile, I stuffed my values in a fake environment:

```
environments:
  staging_defaults: &defaults
    values:
      - "./values/{{` {{ .Release.Name }} `}}/common.yaml"
      - "./values/{{` {{ .Release.Name }} `}}/{{ .Environment.Name }}.yaml"
    secrets:
      - "./values/{{` {{ .Release.Name }} `}}/common-secrets.yaml"
      - "./values/{{` {{ .Release.Name }} `}}/{{ .Environment.Name }}-secrets.yaml"
```

```
releases:
- name: heapster
  namespace: kube-system
  chart: stable/heapster
  version: 0.3.2
  <<: *defaults
```

This _almost_ works, but complains that `values/{{.Release.Name}}/common.yaml cannot be found.

I wonder if a simpler way to achieve all this is to:
 1. Add an extra key to the helfile spec (`templates`)
 2. Make sure rendering of ``{{` {{ .Release.Name }} `}}`` is deferred until `sync|diff|apply|template`
 3. Add a complex example to the documentation using YAML Anchors and Extends
