### ISSUE TITLE
readFile fails for valid yaml lists

### ISSUE THREAD

**Issue by MichaelPanchenko** [roboll/helmfile#429]
### What
When reading a yaml file with a list using readFile,  unmarshalling can fail, dependent on the format of the list. So for example with a helmfile containing
```yaml
releases:
- name: my-release
  chart: stable/consul
  {{ readFile "values-list.yaml" }}
```

and 
_values-list.yaml_ as
```yaml
values:
  - key: value
  - key2: value2
```
the command ```helmfile template``` succeeds. However, with
_values-list.yaml_ as
```yaml
values:
- key: value
- key2: value2
```
(which is also a correct yaml list), ```helmfile template``` leads to:
```
failed to read helmfile.yaml: reading document at index 2: yaml: unmarshal errors:
  line 14: field key not found in type state.ReleaseSpec
  line 15: field key2 not found in type state.ReleaseSpec
```

### Why
I generate the values-list.yaml dynamically with ```yq```. However, ```yq``` generates yaml lists without indentation, so I cannot use the generated list with helmfile.

**Comment by mumoshu** [comment]
@MichaelPanchenko Hey! Thanks for using helmfile.

Due to how YAML works, you need to tell the template how much indentation you need, much like you do when writing helm chart templates:

```yaml
releases:
- name: my-release
  chart: stable/consul
{{ readFile "values-list.yaml" | indent 2}}
```

**Comment by MichaelPanchenko** [comment]
@mumoshu Thank you for your answer! Unfortunately, it does not quite work for me - helmfile template now fails with
```
helmfile template
failed to read helmfile.yaml: reading document at index 2: yaml: line 13: mapping values are not allowed in this context
```
I have tried several ways, including something like
```yaml
releases:
- : my-release
  chart: stable/consul
  values:
  {{ readFile "values-list.yaml" | indent 2}}
```
and values-list.yaml as
```yaml
- key: value
- key2: value2
```
but none seem to work

**Comment by mumoshu** [comment]
@MichaelPanchenko Could you try dumping your intermediate helmfile.yaml's that are rendered internally, by turning on debug logging?

```
helmfile --log-level=debug template 
```

**Comment by mumoshu** [comment]
```
releases:
- name: my-release
  chart: stable/consul
  values:
  {{ readFile "values-list.yaml" | indent 2}}
```

would result in:

```
second-pass rendering result of "/path/to/helmfile.yaml":
 0: releases:
 1: - name: my-release
 2:   chart: stable/consul
 3:   values:
 4:     - key: value
 5:   - key2: value2
```

With my proposed solution:

```
releases:
- name: my-release
  chart: stable/consul
  values:
# No indentation here!
{{ readFile "values-list.yaml" | indent 2}}
```

would result in:

```
 0: releases:
 1: - name: my-release
 2:   chart: stable/consul
 3:   values:
 4:   - key: value
 5:   - key2: value2
```
