### ISSUE TITLE
FR: Use non-packaged chart from Git repositories

### ISSUE THREAD

**Issue by aslafy-z** [roboll/helmfile#435]
I'd love to be able to release from non-packages helm repositories, directly from git, with a ref and path specification.

Example:  
```yaml
repositories:
  - name: cert-manager
    git: https://github.com/jetstack/cert-manager
    ref: release-0.5
    path: contrib/charts

releases:
  - name: cert-manager
    chart: cert-manager/cert-manager
    namespace: networking
  - name: vault
    chart: cert-manager/vault
    namespace: security
```

See `cert-manager` and `vault` charts from here: https://github.com/jetstack/cert-manager/tree/release-0.5/contrib/charts

Note:
- `cert-manager` has a requirements.yml which reference a local chart, so `helm dependency update` should be run for the chart before installing it, so the chart has to be considered as a local one.
- We can use git sparse checkout to limit the fetch size

Related: #214
