### ISSUE TITLE
Using semver at a docker image version level

### ISSUE THREAD

**Issue by michaelgeorgeattard** [roboll/helmfile#455]
I am not sure if this is out of scope for `helmfile`, but what if we could have something like the following:

```
repositories:
- name: repo
  url: xxx
context: xxx
releases:
- name: xxx
  namespace: demo
  chart: xxx
  version: 0.1.0
  values:
  - foo:
      image: bar/baz
      tag: {{ bar/baz:~1.*.*-dev  }}
```

Tag would then be interpolated to the latest version of `bar/baz` that satisfies the given constraint.

Our application image releases are decoupled from our chart releases, I was wondering if I could achieve a **static** chart version with a **dynamic** docker image version.

**Comment by michaelgeorgeattard** [comment]
To add weaveworks/flux achieves something similar as follows:

```
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  releaseName: mongodb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: mongodb
    version: 4.9.0
  values:
    image:
      repository: bitnami/mongodb
      tag: 4.0.3
    usePassword: false
    persistence:
      enabled: false
    securityContext:
      enabled: true
      fsGroup: 0
      runAsUser: 0
```
https://github.com/weaveworks/flux-get-started/blob/master/releases/mongodb.yaml
