### ISSUE TITLE
Chart version contraint with prefix issues

### ISSUE THREAD

**Issue by michaelgeorgeattard** [roboll/helmfile#456]
I have the following version defined in my yaml file, including a `-dev` suffix.

```
releases:
  - name: foo
    namespace: bar
    chart: repo/baz-dev
    version: ~0.1.0-dev
```

`helmfile apply` is picking up `repo/baz-dev` version `0.1.3` (no suffix). I think the fact the suffix was added should constrain the package range further.
