### ISSUE TITLE
Using values after template

### ISSUE THREAD

**Issue by caxalex** [roboll/helmfile#466]
I`m use template for many releases. 

```
templates:
  default: &default
    namespace: "default"
    chart: "stable/{{`{{ .Release.Name }}`}}"
    version: ""
    wait: true
    installed: true
    missingFileHandler: Warn
    values:
    - values/{{`{{ .Release.Name }}`}}/base.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml

```
 but one release needs in additions  custom values, I was tried to add after anchor:
```
- name: "traefik"
  <<: *default
  values:
  - values/traefik/custom.yaml
```
in this case   values in template were ignored.
how can I merge all values?

**Comment by mumoshu** [comment]
@caxalex Hey! Thanks for reporting.

Unfortunately it isn't possible as long as we rely on YAML anchors - YAML overrides the nested objects, rather than merging them.

I believe there's a work-around that exploits templating:

```yaml
{{ define "common" }}
    - values/{{`{{ .Release.Name }}`}}/base.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
{{ end }}

- name: "traefik"
  <<: *default
  values:
{{ template "common" . }}
  - values/traefik/custom.yaml
```

Does it work for you?

**Comment by mumoshu** [comment]
@caxalex Would you mind confirming my alternative idea, that enhances `helmfile` to "flatten" values?

The following state file:

```
templates:
    values: &commonValues
    - values/{{`{{ .Release.Name }}`}}/base.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml

- name: "traefik"
  <<: *default
  values:
  - *commonValues
  - specific.values.yaml
```

will internally and firstly parsed as:

```
- name: "traefik"
  values:
  -
    - values/{{`{{ .Release.Name }}`}}/base.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
  - specific.values.yaml
```

then flattened to:

```
- name: "traefik"
  values:
  - values/{{`{{ .Release.Name }}`}}/base.yaml
  - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
  - specific.values.yaml
```
