### ISSUE TITLE
helmfile + helm s3 issues (object not found by helmfile, but it is there for helm)

### ISSUE THREAD

**Issue by argais** [roboll/helmfile#480]
In https://github.com/roboll/helmfile/issues/220 I saw people using helmfile with helm s3 plugin apparently without issues.

I can use helm s3 just fine (init repo, push, update, install from repo), but once I do it from helmfile, no matter what I do it says it can't find the object.

```
repositories:
  - name: myrepo
    url: s3://myrepobucket

helmDefaults:
  tillerNamespace: kube-system
  kubeContext: sandbox.mydomain.com
  verify: true
  wait: true
  timeout: 600
  recreatePods: true

releases:
  - name: metrics-server
    namespace: kube-system
    chart: myrepo/metrics-server
    version: 2.2.0
```

```
➜ helmfile sync
Adding repo myrepo s3://myrepobucket
"myrepo" has been added to your repositories

Updating repo
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "myrepo" chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈

Upgrading myrepo/metrics-server
fetch from s3: object not found
Error: failed to download "opta/metrics-server" (hint: running `helm repo update` may help)

err: release "metrics-server" in "helmfile.yaml" failed: exit status 1
exit status 1
```

The object is there, I can copy it with aws cli, I can install the chart using `helm upgrade -i metrics-server myrepo/metrics-server` 

It doesn't look like its an issue with helm s3 plugin since it works by itself. Is there any other info I can provide to help figure out what is going on here?
