### ISSUE TITLE
helm 2.13 and atomic support

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#487]
Helm rolled out 2.13 and a new flag called --atomic it would be nice to support it in helmfile.

**Comment by Evesy** [comment]
I'm happy to try and tackle this one if no one minds?

**Comment by sstarcher** [comment]
@Evesy please do it would be very appreciated.

**Comment by Evesy** [comment]
I've only just thought, is this not covered under `--args`?

Unless it wants to be a first class option in helmfile like recreate pods etc.:

```
helmDefaults:
  tillerNamespace: tiller-namespace  #dedicated default key for tiller-namespace
  kubeContext: kube-context          #dedicated default key for kube-context (--kube-context)
  # additional and global args passed to helm
  args:
    - "--set k=v"
  # defaults for verify, wait, force, timeout and recreatePods under releases[]
  verify: true
  wait: true
  timeout: 600
  recreatePods: true
  force: true
  atomic: true
```
