### ISSUE TITLE
Multiple `Found duplicate keys` errors emitted by helm diff during `helmfile apply`

### ISSUE THREAD

**Issue by michaelgeorgeattard** [roboll/helmfile#510]
During `helmfile apply`, I am getting several instances of the error below:

`2019/03/28 10:40:34 Error: Found duplicate key "foo, ,  ()" in manifest`

`helmfile apply` appears to work correctly even after emitting the errors.

Reproduced by installing a cloned version of https://github.com/hashicorp/consul-helm.

```
releases:
  - name: consul
    chart: "../consul-helm"
    namespace: "foo"
```

* Using latest version of helm diff including https://github.com/databus23/helm-diff/commit/f0cbdb299a3b8c046879af8d30348d45ca5560eb

**Comment by mumoshu** [comment]
Thanks for reporting!
Does it reproduce when you used other charts, too?
2019年3月28日(木) 18:56 Michael George Attard <notifications@github.com>:

**Comment by michaelgeorgeattard** [comment]
@mumoshu No I did not reproduce this with any other charts. Thanks for following up.

**Comment by michaelgeorgeattard** [comment]
Issue looks like a resource file which, after being processed, only has comments left, such as below:

```
# ConfigMap with extra configuration specified directly to the chart
# for client agents only.
{{- if (or (and (ne (.Values.client.enabled | toString) "-") .Values.client.enabled) (and (eq (.Values.client.enabled | toString) "-") .Values.global.enabled)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "consul.fullname" . }}-client-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  extra-from-values.json: |-
{{ tpl .Values.client.extraConfig . | trimAll "\"" | indent 4 }}
{{- end }}
```

When processed by helm (diff), I am getting:

```
default, ,  () has been added:
- 
+ # Source: consul/templates/client-config-configmap.yaml
+ # ConfigMap with extra configuration specified directly to the chart
+ # for client agents only.
```
