### ISSUE TITLE
feat: Allow environment values to be overrode when referring sub-helmfile

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#523]
This is similar to #361, but for helmfile.yaml.

You can write `helmfile.yaml` containing one or more sub-helmfiles that is processed before `releases`, in `helmfiles`:

```yaml
environments:
  default:
   values:
  - environments/default/values.yaml

helmfiles:
- infra/helmfile.yaml

releases:
- name: myapp
  chart: charts/myapp
  values:
  - foo: {{ .Environment.Values.foo }}
```

#361 allows you to override any environment values of the "parent" helmfile.yaml, not sub-helmfiles.

So what if you wanted to propagate one or more environment values or their derivatives to sub-helmfiles?

You'd need something like this:

```yaml
helmfiles:
- path: infra/helmfile
  values:
    - foo: {{ .Environment.Values.foo }}
```

Or

```yaml
helmfiles:
- path: infra/helmfile
  environment:
    values:
    - foo: {{ .Environment.Values.foo }}    
```

Which one do you prefer? Or do you have another ideas? Any input is welcomed.

**Comment by mumoshu** [comment]
Alternative syntax:

```yaml
helmfiles:
- source: https://path/to/helmfile.yaml
   overrides:
      environments:
         customprod:
         - myownprod.yaml
```

In this case we introduce the key `overrides` so that it can be enhanced to support other fields in the future. YAGNI?

**Comment by sgandon** [comment]
nice idea with the `overrides`, I like iot when it is explicit.

**Comment by mumoshu** [comment]
Thoughts:

Specifying the name of the environment to be overrode like `environments.customprod` seems too verbose as you now need to write something like the below to override only the selected env:

```yaml
helmfiles:
- path: path/to/helmfile.yaml
  overrides:
    environments:
      {{ .Environment.Name}}:
        values:
        - myownprod.yaml
```

In addition to that, it isn't actually `overrides`, as it would just merge values from `myownprod.yaml` to the environment values defined in the `path/to/helmfile.yaml`.

Given above, I propose the following syntax to merge some env values provided by the parent state into the env values of the child:

```yaml
helmfiles:
- path: path/to/helmfile.yaml
  environment:
    additionalValues:
    - myownprod.yaml
```

Getting out-of-topic but we can enhance this syntax to allow selecting a specific env in the child state:

```yaml
helmfiles:
- path: path/to/helmfile.yaml
  environment:
    name: nonDefaultEnv
```

Or even inherit environment values:

```yaml
helmfiles:
- path: path/to/helmfile.yaml
  environment:
    # The config key is named after `selectorsInherited` 
    valuesInherited: true
```

But these are another stories. Please feel free to submit another feature requests if you need any of these. I'll focus on `additionalValues` in this issue.
