### ISSUE TITLE
Release key should be name+tillerNamespace

### ISSUE THREAD

**Issue by pvalsecc** [roboll/helmfile#528]
We tend to have ony tiller per namespace and I'd like to do something like that:
```yaml
releases:
  - name: monitoring
    namespace: gs-mutualized-print
    tillerNamespace: gs-mutualized-print
    chart: monitoring

  - name: monitoring
    namespace: gs-gmf-demo
    tillerNamespace: gs-gmf-demo
    chart: monitoring
```

But helmfile is not happy about that:
```
err: duplicate release "monitoring" found: there were 2 releases named "monitoring" matching specified selector
duplicate release "monitoring" found: there were 2 releases named "monitoring" matching specified selector
```

The primary key for releases should not be the name, but the name AND the tillerNamespace.
