### ISSUE TITLE
Looking for a good sample of using secrets per release

### ISSUE THREAD

**Issue by patrickmslatteryvt** [roboll/helmfile#535]
Hi, I'm having problems using secrets in a per release mode, such as the following simple test I used:

helmfile.yaml
```yaml
helmDefaults:
  tillerNamespace: kube-system
  kubeContext: MY_CLUSTER_NAME

context: MY_CLUSTER_NAME

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: bitnami
    url: https://charts.bitnami.com

releases:
- name: apache
  namespace: web-test
  chart: bitnami/apache
  version: 4.1.2
  values:
  - values.yaml.gotmpl
  secrets:
  - secrets.yaml
```

When I run:
```shell
helmfile --log-level=debug --file=./helmfile.yaml charts --args "--debug --dry-run"
```

I get:
```shell
err: release "apache" in "helmfile.yaml" failed: failed to render values files "/tmp/helmfile/values.yaml.gotmpl": failed to render [/tmp/helmfile/values.yaml.gotmpl], because of template: stringTemplate:3:26: executing "stringTemplate" at <.Values.metrics.imag...>: can't evaluate field Values in type state.EnvironmentTemplateData
failed to render values files "/tmp/helmfile/values.yaml.gotmpl": failed to render [/tmp/helmfile/values.yaml.gotmpl], because of template: stringTemplate:3:26: executing "stringTemplate" at <.Values.metrics.imag...>: can't evaluate field Values in type state.EnvironmentTemplateData
```

I'm obviously missing something in the setup here but I can't exactly determine what it is...
Can anyone point me towards a good complete example of using secrets in this way? (We don't use the Environment Secrets in our helmfiles)
The decryption of the secret is working as expected when I debugged that.
Thanks

Below are the rest of the test files I am using:

.sops.yaml
```yaml
creation_rules:
  - azure_keyvault: https://xxxxxxxxx.vault.azure.net/keys/sops-key/##################
```

secrets.dec.yaml
```yaml
metrics:
  image:
    pullPolicy: Always
```

secrets.yaml
```
metrics:
    image:
        pullPolicy: ENC[AES256_GCM,data:###############################,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://xxxxxxxxxxxxx.vault.azure.net
        name: sops-key
<snip>
```

values.yaml.gotmpl
```yaml
metrics:
  image:
    pullPolicy: {{ .Values.metrics.image.pullPolicy }}
```

**Comment by mumoshu** [comment]
@patrickmslatteryvt Hey!

Unfortunately you can't reference release values from within the release values.yaml, which defines the release values itself(Chicken-and-egg!).

Try moving any values used to generate per-release values to "environment values". Environment values can be defined under `environments` key in your helmfile.yaml like:

```yaml
environments:
  default:
    values:
    - environments/default.yaml
```

Your `default.yaml` could include:

```
metrics:
  image:
    pullPolicy: Always
```

Which is then used by your per-release values.yaml.gotmpl:

```
metrics:
  image:
    pullPolicy: {{ .Environment.Values.metrics.image.pullPolicy }}
```

Why do you need to define pullPolicy in secrets.yaml though?

**Comment by patrickmslatteryvt** [comment]
OK, thanks for making it clear. I have it working as expected now and have shown exactly what worked for me below:

helmfile
```yaml
helmDefaults:
  tillerNamespace: kube-system
  kubeContext: MY_CLUSTER_NAME

context: MY_CLUSTER_NAME

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: bitnami
    url: https://charts.bitnami.com

environments:
  default:
    secrets:
    - environments/secrets.yaml

releases:
- name: apache
  namespace: web-test
  chart: bitnami/apache
  version: 4.1.2
  values:
  - values.yaml.gotmpl
```

environments/secrets.dec.yaml
```yaml
metrics:
    image:
        pullPolicy: Unicorns
```

environments/secrets.yaml
```yaml
metrics:
    image:
        pullPolicy: ENC[AES256_GCM,data:CKGDaFGsjw0=,iv:vdyDoyKdmMBGcM30JsGMCQBBzGbCWWezZ9wBSGAeWVo=,tag:yIiHVroQzYWmExtiluT0bA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://##################.vault.azure.net
        name: sops-key
        version: ########################
        created_at: '2019-04-03T15:12:05Z'
<snip>
```

values.yaml.gotmpl
```yaml
metrics:
  enabled: true
  image:
    pullPolicy: {{ .Environment.Values.metrics.image.pullPolicy }}
```

```shell
helmfile --log-level=debug --file=./helmfile.yaml charts --args "--debug --dry-run"
processing file "helmfile.yaml" in directory "."
Decrypting secret /tmp/helmfile/environments/secrets.yaml
exec: helm secrets dec /tmp/helmfile/environments/secrets.yaml
Decrypting /tmp/helmfile/environments/secrets.yaml

second-pass rendering result of "helmfile.yaml":
 0: helmDefaults:
 1:   tillerNamespace: kube-system
 2:   kubeContext: v8d-dev-ze0-001-admin
 3: 
 4: context: v8d-dev-ze0-001-admin
 5: 
 6: repositories:
 7:   - name: stable
 8:     url: https://kubernetes-charts.storage.googleapis.com
 9:   - name: bitnami
10:     url: https://charts.bitnami.com
11: 
12: environments:
13:   default:
14:     secrets:
15:     - environments/secrets.yaml
16: 
17: releases:
18: - name: apache
19:   namespace: web-test
20:   chart: bitnami/apache
21:   version: 4.1.2
22:   values:
23:   - values.yaml.gotmpl
24: 

Decrypting secret /tmp/helmfile/environments/secrets.yaml
exec: helm secrets dec /tmp/helmfile/environments/secrets.yaml
Decrypting /tmp/helmfile/environments/secrets.yaml

worker 1/1 started
successfully generated the value file at /tmp/helmfile/values.yaml.gotmpl. produced:
metrics:
  enabled: true
  image:
    pullPolicy: Unicorns

worker 1/1 finished
worker 1/1 started
Upgrading bitnami/apache
exec: helm upgrade --install --reset-values apache bitnami/apache --version 4.1.2 --tiller-namespace kube-system --namespace web-test --values /tmp/values285679179 --debug --dry-run --kube-context=v8d-dev-ze0-001-admin
[debug] SERVER: "localhost:44134"

[debug] Fetched bitnami/apache to /home/pslattery/.helm/cache/archive/apache-4.1.2.tgz

Release "apache" does not exist. Installing it now.
[debug] CHART PATH: /home/pslattery/.helm/cache/archive/apache-4.1.2.tgz

NAME:   apache
REVISION: 1
RELEASED: Wed Apr  3 11:24:32 2019
CHART: apache-4.1.2
USER-SUPPLIED VALUES:
metrics:
  enabled: true
  image:
    pullPolicy: Unicorns

COMPUTED VALUES:
image:
  pullPolicy: Always
  registry: docker.io
  repository: bitnami/apache
  tag: 2.4.39
metrics:
  enabled: true
  image:
    pullPolicy: Unicorns
    registry: docker.io
    repository: lusotycoon/apache-exporter
    tag: v0.5.0
  podAnnotations:
    prometheus.io/port: "9117"
    prometheus.io/scrape: "true"
podAnnotations: {}
service:
  externalTrafficPolicy: Cluster
  httpsPort: 443
  nodePorts:
    http: ""
    https: ""
  port: 80
  type: LoadBalancer

HOOKS:
MANIFEST:

---
# Source: apache/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: apache-apache
  labels:
    app: apache-apache
    chart: "apache-4.1.2"
    release: "apache"
    heritage: "Tiller"
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Cluster"
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app: apache-apache
---
# Source: apache/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache-apache
  labels:
    app: apache-apache
    chart: "apache-4.1.2"
    release: "apache"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      app: apache-apache
      release: "apache"
  replicas: 1
  template:
    metadata:
      labels:
        app: apache-apache
        chart: "apache-4.1.2"
        release: "apache"
        heritage: "Tiller"
      annotations:
        prometheus.io/port: "9117"
        prometheus.io/scrape: "true"
        
    spec:      
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "status.localhost"
      containers:
      - name: apache-apache
        image: "docker.io/bitnami/apache:2.4.39"
        imagePullPolicy: "Always"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
        volumeMounts:
        - name: apache-data
          mountPath: /bitnami/apache
      - name: metrics
        image: docker.io/lusotycoon/apache-exporter:v0.5.0
        imagePullPolicy: "Unicorns"
        command: [ '/bin/apache_exporter', '-scrape_uri', 'http://status.localhost:8080/server-status/?auto']
        ports:
        - name: metrics
          containerPort: 9117
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
            null
          
      volumes:
      - name: apache-data
        emptyDir: {}

worker 1/1 finished
```


> Why do you need to define pullPolicy in secrets.yaml though?
That was just a super simple example that I put together to test with.
I reality I'm trying to use a DNS zone secret needed for the Jetstack cert-manager chart.

Thanks for the help!
