### ISSUE TITLE
Allow environment values files to be absolute

### ISSUE THREAD

**Issue by sgandon** [roboll/helmfile#549]
Here is the use case
We are storing chart version in a values file which is stored allong with the helmfile (relative) but those values could be automatically overridden by a local values file created from versions found in a given production cluster for instance.
But this local file is refered with an absolute path.
So this would be great that _environment_ values files uses the same resolution mechanism that release ones allowing for aboslute path to be also use. 
```
environments:
  default:
    values:
      - /Users/foo/.helmfile-local-cache/chart-versions.yaml
```
