### ISSUE TITLE
helmfile sync never process deployment CentOS 7.3, Ubuntu 16.04.4 LTS

### ISSUE THREAD

**Issue by xjantoth** [roboll/helmfile#55]
Hi there,

I just wanted to rewrite this piece of **working code**:

    helm install stable/prometheus --name prom --set rbac.create=false --namespace=prometheus

**my simple helmfile:**

    vim charts.yaml
     
    ...
    context:  <my_context>
    releases:
      # Published chart example
      - name: prometheusnorbac                            # name of this release
        namespace: prometheus                       # target namespace
        chart: stable/prometheus     # the chart being installed to create this release, referenced by `repository/chart` syntax
        set:                                   # values (--set)
          - name: rbac.create
            value: false
    ...
    wq!

**When I run:**

```
./helmfile -f charts.yaml sync
exec: helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
```

**Then chcek helm list**

```
 helm list
NAME            REVISION        UPDATED                         STATUS          CHART                   NAMESPACE
prom            1               Thu Mar 15 14:22:19 2018        DEPLOYED        prometheus-5.4.3        prometheus
promt           1               Fri Mar 16 11:50:31 2018        FAILED          prometheus-5.4.3        prometheus
promtemp        1               Fri Mar 16 10:58:31 2018        DEPLOYED        prometheus-5.4.3        prometheus

```

So from `helm list` output can be seen that deployment for `prometheusnorbac` was never finished.

**Tested OS's**
* Ubuntu 16.04.4 LTS
* Centos 7.3

**Comment by mumoshu** [comment]
Hi @xjantoth Sorry for the inconvenience. We've recently changed the key from `charts:` to `releases:`, and the binary had not been released since then.

But now, we have [v0.10](https://github.com/roboll/helmfile/releases/tag/v0.10) available for you! Would you mind trying once again with the new version? Thx.

**Comment by xjantoth** [comment]
Hi @mumoshu thanks for a new version **0.10**:


```

vim helmfile.yaml

...
context: <my_context>                   # kube-context (--kube-context)

releases:
  # Published chart example
  - name: prometheusnorbac                            # name of this release
    namespace: prometheus                       # target namespace
    releases: stable/prometheus     # the chart being installed to create this release, referenced by `repository/chart` syntax
    set:                                   # values (--set)
      - name: rbac.create
        value: false
...

```
Does this error message mean that I have to take my code  form **helmfile.yaml** and place  to
**/home/jantoth/.helm/repository/Charts.yaml**
 

```
 ./helmfile -f helmfile.yaml sync
exec: helm repo add roboll http://roboll.io/charts --kube-context <my_context>
"roboll" has been added to your repositories
exec: helm repo update --kube-context <my_context>
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "roboll" chart repository
Update Complete. ⎈ Happy Helming!⎈
exec: helm upgrade --install prometheusnorbac  --namespace prometheus --set rbac.create=false --kube-context sandbox.aws.zoomint.com
Release "prometheusnorbac" does not exist. Installing it now.
Error: no Chart.yaml exists in directory "/home/jantoth/.helm/repository"
err: exit status 1

```

**Comment by mumoshu** [comment]
@xjantoth Hi!

I've tried that myself and it turned out that you should change `releases: stable/prometheus` to `chart: stable/prometheus`.

**Comment by xjantoth** [comment]
@mumoshu Hi!

Thank you so much 👍 I have successfully deployed basic **prometheus** setup on k8s by using **helmfile**.

Much appreciate your instant help.

We will be testing it for a while from now.

Maybe you **would like to** post this update to your git **README** file:

-Jan

```
cat helmfile.yaml

 cat charts.yaml
context: <my_context>

releases:
  # Published chart example
  - name: promnorbacxubuntu         # name of this release
    namespace: prometheus              # target namespace
    chart: stable/prometheus             # the chart being installed to create this release, referenced by `repository/chart` syntax
    set:                                   # values (--set)
      - name: rbac.create
        value: false

```

**Usage**:

`./helmfile -f hemlfile.yaml sync`
