### ISSUE TITLE
Inconsistant config on missing file and no fail

### ISSUE THREAD

**Issue by johnmarcou** [roboll/helmfile#559]
Hi,

I just realised an ingress resources was not generated, since some values was not interpreted.
The reason was because a secret file did not exist. This happen only when using env secrets.

# How to reproduce
1. `helm create nginx`
2. create a Sops `env-secrets.yaml` file
3. Write this helmfile.yaml
```
environments:
  default:
    secrets:
      - env-secrets.yaml

releases:
  - name: myapp
    chart: nginx
    namespace: default
    secrets: [secrets.yaml]    # Notice this file does not exist
    values:
      - ingress:
          enabled: true
```
4. `helmfile diff`

# What is happening
Rendering provides one deployment and one service.

# What is expected
Helmfile should crash because the `secret.yaml` does not exist

# Workaround
Remove the `secrets: [secrets.yaml]` to fix the issue, of course :)
All deployment, service and ingress objects are rendered.

Context: helmfile version v0.54.2
