### ISSUE TITLE
Arrays appearing in multiple value/secret files are not merged together

### ISSUE THREAD

**Issue by michaelgeorgeattard** [roboll/helmfile#562]
Preferably array yaml values across multiple value/secret files should be merged together instead of overriding each other.

This is especially useful when part of the array is encrypted and stored in a secret file, and the other part can be clear-text.

```
releases:
  - name: baz
    chart: foo/bar
    version: 1.2.3
    namespace: foo
    values:
      - values.yaml
      - values2.yaml
```

values.yaml
```
deployments:
 - name: one
   value: one
```

values2.yaml
```
deployments:
 - name: two
   value: two
```

Output:

```
deployments:
 - name: two
   value: two
```

Expected output:

```
deployments:
 - name: one
   value: one
 - name: two
   value: two
```
