### ISSUE TITLE
lockfile causes issue with the same chart of different versions

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#598]
When running commands such as `template` on a helmfile that has the same chart, but at different versions.

```in ./helmfile.yaml: in .helmfiles[1]: in helm/account/dev/x/dev/helmfile.yaml: duplicate chart dependency "x". you can't have two or more charts with the same name but with different urls or versions: existing={x s3://charts/charts 1.4.3}, new={x s3://charts/charts 1.5.0}```

```
charts:
- name: x1
  <<: *default
  version: 1.4.3
- name: x2
  <<: *default
  version: 1.5.0
```

**Comment by mumoshu** [comment]
@sstarcher Hey! Good catch. This is unfortunately how helmfile works today.

I think I can safely loosen the restriction, that would exclude releases with correct semver(not version range) in `version` specified.

After that, in your case `x1` and `x2` will be exluced from the dependency locking process, as they are already "locked" anyway with the explicit semver specified in your `helmfile.yaml`.

Does that sound ok?

**Comment by mumoshu** [comment]
The gotcha is that this won't still succeed:

```
charts:
- name: x1
  <<: *default
  version: "> 1.4.3"
- name: x2
  <<: *default
  version: "> 1.4.4"
```

Do you need support for the above, that helmfile accepts different version constraints for the same chart? It is a bit harder to implement, but not impossible. Just wanted to confirm if you really need it.
