### ISSUE TITLE
0.63, layering/bases. Is this supposed to work?

### ISSUE THREAD

**Issue by bitsofinfo** [roboll/helmfile#604]
I read:
https://github.com/roboll/helmfile/blob/255d92064e232c40c10dddab72e19d66e9211cc5/docs/writing-helmfile.md

Tried this w/ 0.63

helmfile.yaml
```
bases:
  - myenv.yaml

helmDefaults:
  tillerNamespace: kube-system  
  kubeContext: {{ .Environment.Values.kubeContext }}
  verify: false
  {{ if .Environment.Values.wait }}
  wait: true
  {{ else }}
  wait: false
  {{ end }}
  timeout: 600
  recreatePods: false
  force: true

releases:
  - name: test1
    chart: mychart-{{ .Environment.Values.myname }}
    values:
      replicaCount: 1
      image:
        repository: "nginx"
        tag: "latest"
```

myenv.yaml
```
environments:
  test:
    values:
      - test.env.yaml
```

test.env.yaml
```
kubeContext: test
wait: false
cvOnly: false
myname: "dog"
```

Exec:
```
bash-4.4$ ./helmfile --log-level debug -f test.helmfile.yaml -e test apply
processing file "helmfile.yaml" in directory "."
first-pass rendering input of "helmfile.yaml.part.0": {test map[]}
could not deduce `environment:` block, configuring only .Environment.Name. error: failed to read helmfile.yaml.part.0: reading document at index 1: yaml: unmarshal errors:
  line 19: cannot unmarshal !!map into []interface {}
error in first-pass rendering: result of "helmfile.yaml.part.0":
 0: bases:
 1:   - myenv.yaml
 2:
 3: helmDefaults:
 4:   tillerNamespace: kube-system
 5:   kubeContext: <no value>
 6:   verify: false
 7:
 8:   wait: false
 9:
10:   timeout: 600
11:   recreatePods: false
12:   force: true
13:
14: releases:
15:   - name: test1
16:     chart: mychart-<no value>
17:     values:
18:       replicaCount: 1
19:       image:
20:         repository: "nginx"
21:         tag: "latest"
22:

first-pass rendering result of "helmfile.yaml.part.0": {test map[]}
second-pass rendering failed, input of "helmfile.yaml.part.0":
 0: bases:
 1:   - myenv.yaml
 2:
 3: helmDefaults:
 4:   tillerNamespace: kube-system
 5:   kubeContext: {{ .Environment.Values.kubeContext }}
 6:   verify: false
 7:   {{ if .Environment.Values.wait }}
 8:   wait: true
 9:   {{ else }}
10:   wait: false
11:   {{ end }}
12:   timeout: 600
13:   recreatePods: false
14:   force: true
15:
16: releases:
17:   - name: test1
18:     chart: mychart-{{ .Environment.Values.myname }}
19:     values:
20:       replicaCount: 1
21:       image:
22:         repository: "nginx"
23:         tag: "latest"
24:

err: error during helmfile.yaml.part.0 parsing: template: stringTemplate:6:30: executing "stringTemplate" at <.Environment.Values.kubeContext>: map has no entry for key "kubeContext"
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:6:30: executing "stringTemplate" at <.Environment.Values.kubeContext>: map has no entry for key "kubeContext"
```

**Comment by mumoshu** [comment]
@bitsofinfo Hey! Thanks for reporting.

Unfortunately, your example won't work due to how the double-rendering works #308. The gotcha here is your go template(=helmfile.yaml) is evaluated "to generate YAML". So `{{ .Environment.Values.myname }}` needs to know about `myname` BEFORE the template expression is evaluated.

Try separating your state file with `---`, so that `myname` is available in your last template:

```
bases:
  - myenv.yaml

---

helmDefaults:
  tillerNamespace: kube-system  
  kubeContext: {{ .Environment.Values.kubeContext }}
  verify: false
  {{ if .Environment.Values.wait }}
  wait: true
  {{ else }}
  wait: false
  {{ end }}
  timeout: 600
  recreatePods: false
  force: true

releases:
  - name: test1
    chart: mychart-{{ .Environment.Values.myname }}
    values:
      replicaCount: 1
      image:
        repository: "nginx"
        tag: "latest"
```
