### ISSUE TITLE
Add YAML string tag to requiredEnv calls

### ISSUE THREAD

**Issue by george-miller** [roboll/helmfile#608]
If you call requiredEnv in a helmfile and the environment variable is all numbers (i.e. `1234531231`), then helm will interpret that as a number and change it to scientific notation (`1234531231` -> `1.234531231e+09`).  Since we cannot surround `requiredEnv` calls with quotes, we had to add a YAML tag to our helmfile to make it work:
```
tag: !!string {{ requiredEnv "GIT_TAG" }}
```
This should be noted in the docs.

We were using requiredEnv for short git tags, and some short git tags can be all numbers (some regular git tags can be all numbers too, it's just really unlikely).  This resulted in our docker tags being exponents,  which isn't allowed.

**Comment by andrewnazarov** [comment]
@george-miller Does this happen in every block of helmfile.yaml? I faced the same inside the `set` block which is quite obvious since Helm itself has troubles with that.

**Comment by mumoshu** [comment]
Hey! Would this be duplicated of #476?

I've left `set` just for backward-compatibility, but it seems to be making more troubles than benefits these days.

**Comment by mumoshu** [comment]
Okay so in some cases the use of `set:` is inevitable. I'll add some guidance in the full config syntax section in README to rescue.

**Comment by mumoshu** [comment]
Ahh I got it! So this does affect `values`.

```
releases:
- name: foo
  chart: stable/envoy
  values:
  - image:
      tag: 1234531231 #=> image: "envoyproxy/envoy-alpine:1.234531231e+09"
```

```
- name: bar
  chart: stable/envoy
  values:
  - image:
      tag: !!string 123453123 #=> image: "envoyproxy/envoy-alpine:1234531231"
```

**Comment by mumoshu** [comment]
NG

```
releases:
- name: {{ .Environment.Values.foo }}
  chart: stable/envoy
  values:
  - image:
      tag: {{ .Environment.Values.tag }}
```

OK

```
- name: bar
  chart: stable/envoy
  values:
  - image:
      tag: !!string {{ .Environment.Values.tag }}
- name: baz
  chart: stable/envoy
  values:
  - image:
      tag: {{ .Environment.Values.tag | quote}}
- name: hoge
  chart: stable/envoy
  values:
  - image:
      tag: "{{ .Environment.Values.tag }}"
```
