### ISSUE TITLE
0.63.2 layering/bases env references across bases

### ISSUE THREAD

**Issue by bitsofinfo** [roboll/helmfile#611]
Tried this w/ 0.63.2

helmfile.yaml
```
bases:
  - myenv.yaml
  - mydefaults.yaml

---

releases:
  - name: test1
    chart: mychart-{{ .Environment.Values.myname }}
    values:
      replicaCount: 1
      image:
        repository: "nginx"
        tag: "latest"
```

mydefaults.yaml
```
helmDefaults:
  tillerNamespace: kube-system  
  kubeContext: {{ .Environment.Values.kubeContext }}
  verify: false
  {{ if .Environment.Values.wait }}
  wait: true
  {{ else }}
  wait: false
  {{ end }}
  timeout: 600
  recreatePods: false
  force: true
```

myenv.yaml
```
environments:
  test:
    values:
      - test.env.yaml
```

test.env.yaml
```
kubeContext: test
wait: false
cvOnly: false
myname: "dog"
```

I end up getting the following kind of error. I appears the `.Environment` (if loaded in a `bases`) is not available to subsequent bases?

```
...parsing: template: stringTemplate:6:30: executing "stringTemplate" at <.Environment.Values.kubeContext>: map has no entry for key "kubeContext"
```

I also tried a slight variation (with same result)

helmfile.yaml
```
bases:
  - myenv.yaml
---
bases:
  - mydefaults.yaml
---
releases:
  - name: test1
    chart: mychart-{{ .Environment.Values.myname }}
    values:
      replicaCount: 1
      image:
        repository: "nginx"
        tag: "latest"
```

related: https://github.com/roboll/helmfile/issues/604
