### ISSUE TITLE
0.64.1: multiple "bases" declarations yields duplicate releases

### ISSUE THREAD

**Issue by bitsofinfo** [roboll/helmfile#615]
see #611 

Using 0.64.1

This does not work (expected)
```
bases:
  - myenv.yaml
  - mydefaults.yaml
```

This does work (gets past the `.Environment` references in mydefaults.yaml), however it renders the `releases:` section twice (and then causes issues w. duplicate releases)

```
bases:
  - myenv.yaml
---
bases:
  - mydefaults.yaml
---
releases:
....
```

**Comment by mumoshu** [comment]
// Also see my comment at https://github.com/roboll/helmfile/issues/611#issuecomment-495027118

**Comment by mumoshu** [comment]
@bitsofinfo I couldn't reproduce the duplication issue.

Could you run `helmfile --log-level=debug` and see if it really duplicates releases?

For reference, here's what I've used:

The command:

```
helmfile -e=test --log-level=debug template
```

`helmfile.yaml`:
```
bases:
  - myenv.yaml
---
bases:
  - mydefaults.yaml
---
releases:
  - name: {{ .Environment.Values.myname }}
    chart: stable/envoy
    values:
    - replicaCount: 1

```
`mydefaults.yaml`:
```
helmDefaults:
  tillerNamespace: kube-system  
  kubeContext: {{ .Environment.Values.kubeContext }}
  verify: false
  {{ if .Environment.Values.wait }}
  wait: true
  {{ else }}
  wait: false
  {{ end }}
  timeout: 600
  recreatePods: false
  force: true

```
`myenv.yaml`:
```
environments:
  test:
    values:
      - test.env.yaml

```
`test.env.yaml`:
```
kubeContext: test
wait: false
cvOnly: false
myname: "dog"
```

**Comment by mumoshu** [comment]
@bitsofinfo Would you mind sharing your files so that I can try to reproduce or guess what's wrong?

**Comment by bitsofinfo** [comment]
I will tomorrow, but whats diff about mine is that within my `releases:` is a template using `range` (so its a loop, feeding of data coming from `.Environment.Values`

**Comment by mumoshu** [comment]
@bitsofinfo Hey! Did you have some time to work on it? I've tried myself but no luck.

**Comment by bitsofinfo** [comment]
I hope to get back to it sometime this week, I'll let you know

**Comment by bitsofinfo** [comment]
Here you go:

I run 
```
helmfile version v0.64.1

helmfile --log-level debug -f deployments.yaml -n default -e test1 apply
```

I get 
```
processing file "deployments.yaml" in directory "."
first-pass rendering input of "deployments.yaml.part.0": {test1 map[]}
error in first-pass rendering: result of "deployments.yaml.part.0":
 0: bases:
 1:   - envs.yaml
 2:

first-pass rendering result of "deployments.yaml.part.0": {test1 map[]}
second-pass rendering result of "deployments.yaml.part.0":
 0: bases:
 1:   - envs.yaml
 2:

first-pass rendering input of "envs.yaml.part.0": {test1 map[]}
first-pass rendering result of "envs.yaml.part.0": {test1 map[appname:test1 kubeContext:XXXX services:[map[name:x] map[name:y]] something:test1 wait:false]}
second-pass rendering result of "envs.yaml.part.0":
 0: environments:
 1:   test1:
 2:     values:
 3:       - test1.env.yaml
 4:   test2:
 5:     values:
 6:       - test2.env.yaml
 7:

merged environment: &{test1 map[appname:test1 kubeContext:XXXX services:[map[name:x] map[name:y]] something:test1 wait:false]}
merged environment: &{test1 map[appname:test1 kubeContext:XXXX services:[map[name:x] map[name:y]] something:test1 wait:false]}
first-pass rendering input of "deployments.yaml.part.1": {test1 map[appname:test1 kubeContext:XXXX services:[map[name:x] map[name:y]] something:test1 wait:false]}
error in first-pass rendering: result of "deployments.yaml.part.1":
 0:
 1: bases:
 2:   - defaults.yaml
 3:

first-pass rendering result of "deployments.yaml.part.1": {test1 map[appname:test1 kubeContext:XXXX services:[map[name:x] map[name:y]] something:test1 wait:false]}
second-pass rendering result of "deployments.yaml.part.1":
 0:
 1: bases:
 2:   - defaults.yaml
 3:

first-pass rendering input of "defaults.yaml.part.0": {test1 map[appname:test1 kubeContext:XXXX services:[map[name:x] map[name:y]] something:test1 wait:false]}
first-pass rendering result of "defaults.yaml.part.0": {test1 map[appname:test1 kubeContext:XXXX services:[map[name:x] map[name:y]] something:test1 wait:false]}
second-pass rendering result of "defaults.yaml.part.0":
 0: helmDefaults:
 1:   tillerNamespace: kube-system
 2:   kubeContext: XXXX
 3:   verify: false
 4:   wait: false
 5:   timeout: 600
 6:   recreatePods: false
 7:   force: true
 8:

merged environment: &{test1 map[appname:test1 kubeContext:XXXX services:[map[name:x] map[name:y]] something:test1 wait:false]}
merged environment: &{test1 map[appname:test1 kubeContext:XXXX services:[map[name:x] map[name:y] map[name:x] map[name:y]] something:test1 wait:false]}
first-pass rendering input of "deployments.yaml.part.2": {test1 map[appname:test1 kubeContext:XXXX services:[map[name:x] map[name:y] map[name:x] map[name:y]] something:test1 wait:false]}
first-pass rendering result of "deployments.yaml.part.2": {test1 map[appname:test1 kubeContext:XXXX services:[map[name:x] map[name:y] map[name:x] map[name:y]] something:test1 wait:false]}
second-pass rendering result of "deployments.yaml.part.2":
 0:
 1: releases:
 2:
 3:   - name: nginx-test1-x
 4:     namespace: default
 5:     chart: stable/nginx-ingress
 6:
 7:
 8:
 9:   - name: nginx-test1-y
10:     namespace: default
11:     chart: stable/nginx-ingress
12:
13:
14:
15:   - name: nginx-test1-x
16:     namespace: default
17:     chart: stable/nginx-ingress
18:
19:
20:
21:   - name: nginx-test1-y
22:     namespace: default
23:     chart: stable/nginx-ingress
24:
25:
26:

merged environment: &{test1 map[appname:test1 kubeContext:XXXX services:[map[name:x] map[name:y] map[name:x] map[name:y] map[name:x] map[name:y] map[name:x] map[name:y]] something:test1 wait:false]}
err: duplicate release "nginx-test1-x" found in "kube-system": there were 2 releases named "nginx-test1-x" matching specified selector
in ./deployments.yaml: duplicate release "nginx-test1-x" found in "kube-system": there were 2 releases named "nginx-test1-x" matching specified selector
```

**SOURCE FILES:**

defaults.yaml
```
helmDefaults:
  tillerNamespace: kube-system
  kubeContext: {{ .Environment.Values.kubeContext }}
  verify: false
  wait: false
  timeout: 600
  recreatePods: false
  force: true
```

deployments.yaml
```
bases:
  - envs.yaml

---

bases:
  - defaults.yaml

---

releases:

  {{- $appname := .Environment.Values.appname -}}
  {{- $namespace := .Namespace -}}

  {{- range $service := .Environment.Values.services }}

  - name: nginx-{{ $appname }}-{{ $service.name }}
    namespace: {{ $namespace }}
    chart: stable/nginx-ingress

  {{ end }}

```

envs.yaml
```
environments:
  test1:
    values:
      - test1.env.yaml
  test2:
    values:
      - test2.env.yaml
```

test1.env.yaml
```
appname: test1

kubeContext: XXXX
something: test1
wait: false

services:
  - name: "x"
  - name: "y"
```

test2.env.yaml
```
appname: test2

kubeContext: XXXX
something: test2
wait: false

services:
  - name: "x"
  - name: "y"

```
