### ISSUE TITLE
helmfile on windows

### ISSUE THREAD

**Issue by polganesh** [roboll/helmfile#638]
Hi,
I am trying to use helmfile on my windows machine.
**steps taken .**
- download windows latest exe version by visiting https://github.com/roboll/helmfile/releases/tag/v0.69.0
- added this file in path env variable
- ensure that helmfile -v gives correct result
- my helmfile specification for testing

```
context: eks-euc1-dev-infra-vpc001-poc-001   # kube-context (--kube-context)
releases:
  # Published chart example
  - name: grafana             # name of this release
    namespace: monitoring                   # target namespace
    chart: /external-apps/helm-charts/monitoring/grafana                   # repository/chart` syntax
    values:
      - /external-apps/helm-charts/monitoring/grafana/values.yaml                 # value files (--values)

```

when i executed helmfile -f specification.yaml sync it gives me error
Error: could not get Kubernetes config for context "eks-euc1-dev-infra-vpc001-poc-001": context "eks-euc1-dev-infra-vpc001-poc-001" does not exist
