### ISSUE TITLE
feat: adhoc chart dependencies

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#649]
Shameless plug: Adding `helm-x` integration to helmfile would allow you to add chart dependencies to your local or remote chart without modifying or forking it.

```yaml
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

releases:
- name: myapp
   chart: charts/mychart
   # version is required because it isn't provided by kustomization by its nature!
   version: 1.2.3
  dependencies:
  - name: envoy
     chart: stable/envoy
     version: 1.5
```

The `dependencies` setting results in running `helm x upgrade --adhoc-dependenci envoy=stable/envoy:1.5` ...` on `helmfile sync` for example, that has the same effect as adding the dependency to `requirements.yaml` of `charts/mychart`.

See https://github.com/mumoshu/helm-x for more information.
