### ISSUE TITLE
environment value not found using bases and templates

### ISSUE THREAD

**Issue by orbiran88** [roboll/helmfile#653]
Trying to use `bases:` with yaml containing `templates` will not evaluating environment values, followed by this comment: https://github.com/roboll/helmfile/issues/388#issuecomment-491712915

**Example:**

helmfile.yaml
```
bases:
- ../../../commons/environments.yaml
---

bases:
- ../../../commons/helmDefaults.yaml
---

bases:
- ../../../commons/repositories.yaml
---

{{ readFile "../../../commons/templates.yaml" }}
---

```

**Comment by mumoshu** [comment]
@orbiran88 Hey! Thanks for reporting.

This is unfortunately how `readFile` works.

Each part of your state file separated by `---` is a state template. And this:

```
---
{{ readFile "...." }}
```

basically means that import the content of "..." to this part as-is. Then parse the result as YAML.

There's a relevant feature request  #504 that allows you to include the file content after rendering the it as a template. I'd appreciate it if you could comment on it with your use-case if any.

**Comment by mumoshu** [comment]
For now you should use release templates. That is, rewrite your templates.yaml to NOT have:

```
{{ ... }}
```

but instead:

```
{{` ... `}}
```

Example:

```
templates:
  zookeeper: &zk
    chart: {{`{{ .Environment.Values | getOrNil "confluent.zookeeper.chart" }}`}}
    version: {{`{{ .Environment.Values | getOrNil "confluent.zookeeper.version" }}`}}
    namespace: {{`{{ .Environment.Values | getOrNil "namespace" }}`}}
    missingFileHandler: Warn
    values:
      - ../environments/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}.yaml
      - imageTag: {{`{{ .Environment.Values | getOrNil "confluent.imageTag" }}`}}
```

FYI: These nested `{{` are indeed inelegant. We have an on-going discussion to use other delimiters(`((`, `[[`, or whatever? And we should have distinct delimiter for state templates vs release templates) #658. I'd appreciate your comment on it as well!

**Comment by orbiran88** [comment]
Thanks @mumoshu for helping me out!

I tried your example but I'm getting:

```
second-pass rendering result of "01-infra.yaml.part.2":
 0:
 1: templates:
 2:   zookeeper: &zk
 3:     chart: {{`{{ .Environment.Values | getOrNil "confluent.zookeeper.chart" }}`}}
 4:     version: {{`{{ .Environment.Values | getOrNil "confluent.zookeeper.version" }}`}}
 5:     namespace: {{`{{ .Environment.Values | getOrNil "namespace" }}`}}
 6:     missingFileHandler: Warn
 7:     values:
 8:       - ../environments/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}.yaml
 9:       - imageTag: {{`{{ .Environment.Values | getOrNil "confluent.imageTag" }}`}}
10:

err: failed to read 01-infra.yaml: reading document at index 1: yaml: line 4: found character that cannot start any token
changing working directory back to "/opt/Gitlab/helmfile/helmfiles/namespace"
in helmfile.d/01-infra.yaml: failed to read 01-infra.yaml: reading document at index 1: yaml: line 4: found character that cannot start any token
```

**Comment by mumoshu** [comment]
@orbiran88 Ahh, sorry! As `readFile` reads the file as-is, even the golang template comments aren'y evaluated. So you have to write "release template" expressions that are also valid as YAML strings. Try:

```
templates:
  zookeeper: &zk
    chart: "{{ .Environment.Values | getOrNil "confluent.zookeeper.chart" }}"
    version: "{{ .Environment.Values | getOrNil "confluent.zookeeper.version" }}"
    namespace: "{{ .Environment.Values | getOrNil "namespace" }}"
    missingFileHandler: Warn
    values:
      - "../environments/{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}.yaml"
      - imageTag: "{{ .Environment.Values | getOrNil "confluent.imageTag" }}"
```

**Comment by chrisduong** [comment]
@mumoshu, so how can we include the separate Template file. I had tried with `readFile` and `helmfiles` statement. They all failed. It seems like we have to put `templates` statement and `releases` statement in the same Helmfile, then the rendering would work correctly. 

Is it possible that we can include the Template and Releases like this, so we don't have to write a very long Helmfile.

```yaml
bases:
  - environments.yaml
  # - defaults.yaml

---
helmfiles:
  - releases/nginx-ingress.yaml # Template 
```

```yaml
templates:
  nginx: &nginx
    chart: stable/nginx-ingress
    version: "{{ .Values.version }}"

releases:
  - name: nginx-controller
    <<: *nginx
```

**Comment by obeyda** [comment]
Hello, 
I followed along the comments of @mumoshu  here and on #388 and I got this finally working, 
here's my structure: 
helmfile:
```yaml
bases: 
  - environments.yaml
  - repositories.yaml
  - defaults.yaml
---
{{ readFile "./templates.yaml" }}

releases:
- name: my-release
  <<: *default

- name: ingress
  chart: ingress-nginx/ingress-nginx
  version: 3.19.0
  namespace: ingress
  values:
    - controller:
        service:
          loadBalancerIP: {{ .Values.ingressLoadBalancerIP }}  # from defaults.yaml
     <......>
```
environments.yaml:
```yaml
environments:
  dev:
    values:
    - kubeContext: test-dev
      ingressLoadBalancerIP: ip.ip.ip.ip
  test:
    values:
    - kubeContext: test-test
      ingressLoadBalancerIP: ip.ip.ip.ips
   <......>
```

repositories: _just plain old repositories, no templating there_

defaults.yaml
```yaml
helmDefaults:
  kubeContext: "{{`{{ .Values.kubeContext | quote }}`}}"  # from environments.yaml
  <.....>
```
templates.yaml
```yaml
templates:
  default: &default
    chart: './app-svc-{{ requiredEnv "SemVer" }}.tgz' 
    version: '{{ requiredEnv "SemVer" }}'
    namespace: "my-services"
    missingFileHandler: Error
    labels:
      tier: backend
    values:
      - values/default-values.yaml
      - values/{{ .Release.Name }}/{{ .Environment.Name }}.yaml.gotmpl
```

In templates.yaml, notice the order of`'` and `"`, no ``` {{` ```  or ``` `}}```
when using `readFile` the imported file must be a valid YAML, I just changed the language mode to YAML in my editor and fixed the errors :smile: 

Also, in `defaults.yaml`, this didn't work: 
```
    kubeContext: {{`{{ .Values.kubeContext | quote }}`}} # won't work 
```
I had this error: 
```
cannot unmarshal !!map into string
```
The fix was to simply make it a valid yaml: 
```
    kubeContext: "{{`{{ .Values.kubeContext | quote }}`}}" #works
```

So, in both `bases` and when using `readFile` the file must be a valid yaml, 

And when using `readFile` you don't need the deferring syntax (```{{` ``` and ``` `}```) , you can use templates just like `helmfile.yaml` as long as it stays a valid yaml syntax.

Please correct me if anything of the above is wrong.
Hope this helps.

**Comment by obeyda** [comment]
update:
in `defaults.yaml` above, when I used this "{{`{{ .Values.kubeContext | quote }}`}}", it didn't signal an error when using `helmfile template` but when I tried other commands like `diff` the template didn't render correctly, I got this:
```
context "{{ .Values.kubeContext | quote }}" does not exist
```

so, to work around this I updated my files:
helmfile.yaml:
```yaml
bases: 
  - ./base/environments.yaml
---
bases:
  - ./base/repositories.yaml
  - ./base/defaults.yaml
---
.... same as above
```

and defaults.yaml:
```yaml
helmDefaults:
  kubeContext: {{ .Values.kubeContext | quote }}
```
