### ISSUE TITLE
helmDefaults.kubeContext ignored

### ISSUE THREAD

**Issue by michaelgeorgeattard** [roboll/helmfile#674]
Seems that a regression in `v0.70.0` is causing `helmDefaults.kubeContext` to be ignored and is always using the current k8s cluster.

```
repositories:
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  - name: weaveworks
    url: https://weaveworks.github.io/flux
  - name: bitnami
    url: https://charts.bitnami.com

environments:  
  shared:
    values:
      - ../../env/cluster/shared.yaml

helmDefaults:
  kubeContext: arn:aws:eks:eu-west-1:1234:cluster/foo
  tls: true
  tillerNamespace: kube-system
```

An invalid `kubeContext` does not cause any issues. Switching context manually through `kubectl config use-context` hides the issue.
