### ISSUE TITLE
Reference Helm chart by URL

### ISSUE THREAD

**Issue by bastianeicher** [roboll/helmfile#675]
With Helm I can reference a chart via an absolute URL instead of using the `repository/chart` syntax. For example:

    helm install https://github.com/arangodb/kube-arangodb/releases/download/0.3.11/kube-arangodb-crd.tgz

However helmfile seems to interpret the URL as a local path if I write this in my `helmfile.yaml`:
```yaml
releases:
  - name: arangodb-crd
    chart: https://github.com/arangodb/kube-arangodb/releases/download/0.3.11/kube-arangodb-crd.tgz
```

Would it be possible to support this helmfile too?
