### ISSUE TITLE
feat: strategic-merge patch or alike for merging arrays in multi-part state file and bases

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#684]
Currently this:

```
releases:
- name: foo
---
releases:
- name: bar
```

results in:

```
releases:
- name: bar
```

That's because helmfile doesn't concat arrays.

The fix isn't that straightforward. Helmfile uses `mergo` under the hood. `mergo` has the option called `WithAppend` that merge arrays within a map or struct by concatenating. But just turning on doesn't work - resulting array items to be duplicated by double-rendering as reported in #615.

An alternative way would be to use strategic-merge patch to merge arrays according to the context. For example `releases` should be merged by `name`, or the combination of `name` and `selectors`.

**Comment by bradenwright** [comment]
I assume no update on this currently.  I was looking for a good way to keep helmfiles in subdirectories but then have a top-level helm which combined them all.  For test I was trying just some basic releases as you listed above, and then something like:

```
{{ $myfile1 := (readFile "myapp1/helmfile.yaml" | fromYaml) }}
{{ $myfile2 := (readFile "myapp2/helmfile.yaml"  | fromYaml ) }}
{{ deepCopy $myfile1 | merge $myfile2 | toYaml }}
```
But I get the same result as you mention above.

**Comment by mumoshu** [comment]
@bradenwright Hey! Thanks for reminding me about this one.

Would it be enough if Helmfile supports merging `releases` by `name`?

Do you need anything other than that in practice?

**Comment by bradenwright** [comment]
Essentially I'm trying to use `depends:` instead of `helmfiles:`, so I need 1 file that contains my dependencies.  But I have too many charts to keep them all in 1 top level file.

So I'd like to create a top-level helmfile by combining a bunch of helmfiles in app directories.  It would be a bonus if I could still run the helmfile in myapp1, myapp2, etc.  but really mainly I plan on running helmfile from the top level helmfile, that way I can deploy all the apps with 1 command or just install a single app (with its dependencies).

So I think merging releases would be the main thing I'm missing, merging repos would be nice as well but not as important.  I'd also be fine not merging so to speak but just appending, for releases b/c I won't name them the same, for repos merging would be nice so I don't have to create duplicates.

For other sections of the helmfile I could always just make common.yaml and render it or something along those lines.  Only places I intended to use merge are for repos and releases


*** Side note ***
I'm open to other approaches, and I'm trying something with merging values, and then leveraging those below (or trying to render a template).  But I'm not great at golang so struggling trying to get it working.

helmfile.yaml
```
{{ $myfile1 := readFile "myapp1/helmfile-release.yaml" | fromYaml }}
{{ $myfile2 := readFile "myapp2/helmfile-release.yaml" | fromYaml }}
{{ $myvals := merge $myfile1 $myfile2 -}}

{{ range $k, $v := $myvals.repositories -}}
repositories:
- name: {{ $k }}
  url: {{ $v.url }}
{{- end }}

{{ range $k, $v := $myvals.releases -}}
releases:
- name: {{ $k }}
  chart: {{ $v.chart }}
  namespace: {{ $v.namespace }}
  version:  {{ $v.version }}
{{- end }}
```

cat myapp1/helmfile-release.yaml
```
repositories:
  bitnami:
    url: https://charts.bitnami.com/bitnami

releases:
  myapp1:
    chart: bitnami/wordpress
    namespace: default
    version:  9.3.6
```

cat myapp2/helmfile-release.yaml
```
repositories:
  bitnami:
    url: https://charts.bitnami.com/bitnami

releases:
  myapp2:
    chart: bitnami/wordpress
    namespace: default
    version:  9.3.6
```

Thanks for replying so quick :)

**Comment by bradenwright** [comment]
I should mention that I have been able to get this working repositories render multiple times, so apply takes slightly longer, but it works.

cat helmfile.yaml:
```
{{- $filePaths := (exec "bash" (list "-c" "echo -n **/helmfile-release.yaml") | splitList " ") }}
 
helmDefaults:
  kubeContext: {{ .Environment.Name }}

environments:
  {{ .Environment.Name }}:
    values:
    - ../environments/default.yaml.gotmpl
    - ../environments/{{ .Environment.Name }}.yaml.gotmpl

repositories:
{{ range $filename := $filePaths }}
{{ $file := readFile $filename | fromYaml }}
{{ if (hasKey $file "repositories") }}
{{ range $k, $v := $file.repositories -}}
- name: {{ $k }}
  url: {{ $v.url }}
{{- end }}
{{- end }}
{{- end }}

releases:
{{ range $filename := $filePaths }}
{{ $file := readFile $filename | fromYaml }}
{{ range $k, $v := $file.releases -}}
- name: {{ $k }}
  chart: {{ $v.chart }}
  namespace: {{ $v.namespace }}
  version:  {{ $v.version }}
  condition: {{ $k }}.enabled
  labels:
    name: {{ $k }}
  values:
  - {{ $k }}/values.yaml.gotmpl
  needs:
  {{- range $v.needs }}
    - {{ . }}
  {{- end }}
  secrets:
  {{- range $v.secrets }}
    - {{ . }}
  {{- end }}
{{- end }}
{{- end }}
```

cat traefik/helmfile-release.yaml
```
repositories:
  traefik:
    url: https://containous.github.io/traefik-helm-chart

releases:
  traefik:
    chart: ../charts/traefik
    namespace: wi-system
    version:  8.1.4
    needs:
      - kube-system/namespaces
    secrets:
      - ../secrets/{{ .Environment.Name }}/traefik.yaml
      - ../secrets/{{ .Environment.Name }}/shared-api-wi-tronix-local.yaml
```

cat namespaces/helmfile-release.yaml
```
releases:
  namespaces:
    chart: ../charts/namespaces
    namespace: kube-system
    version:  0.1.0
    needs: []
    secrets: []
```
