### ISSUE TITLE
isLocalChart breaks helmfile with chart provided as URL to tar.gz

### ISSUE THREAD

**Issue by goruha** [roboll/helmfile#687]
The PR #593 added a bug when chart provided as URL to the tar.gz file.
Installing chart from tar.gz is acceptable for the helm 
```
$ helm install --name my-release -f my_values.yaml https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.1.0/splunk-connect-for-kubernetes-1.1.0.tgz
```
[Example](https://github.com/splunk/splunk-connect-for-kubernetes#deploy-with-helm)

We used the feature in the helmfile for splunk 
```
releases:
- name: "fluentd-splunk-logs"
  namespace: "kube-system"
  chart: "https://github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.1.0/splunk-kubernetes-logging-1.1.0.tgz"
  wait: true
  installed: {{ env "FLUENTD_SPLUNK_INSTALLED" | default "true" }}
```
[Example](https://github.com/cloudposse/helmfiles/blob/master/releases/fluentd-splunk-logs.yaml#L21)

Now run 'helmfile diff' fail with the error

```
merged environment: &{default map[]}
Building dependency https:/github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.1.0/splunk-kubernetes-logging-1.1.0.tgz
exec: helm dependency build https:/github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.1.0/splunk-kubernetes-logging-1.1.0.tgz
exec: helm dependency build https:/github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.1.0/splunk-kubernetes-logging-1.1.0.tgz: 
err: helm exited with status 1:
  Error: could not find https:/github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.1.0/splunk-kubernetes-logging-1.1.0.tgz: stat https:/github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.1.0/splunk-kubernetes-logging-1.1.0.tgz: no such file or directory
changing working directory back to "/localhost/projects/cloudposse/example/example.com/conf/helmfiles"
in ./helmfile.yaml: in .helmfiles[3]: in releases/fluentd-splunk-logs.yaml: helm exited with status 1:
  Error: could not find https:/github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.1.0/splunk-kubernetes-logging-1.1.0.tgz: stat https:/github.com/splunk/splunk-connect-for-kubernetes/releases/download/1.1.0/splunk-kubernetes-logging-1.1.0.tgz: no such file or directory

```
