### ISSUE TITLE
feat: version constraint.

### ISSUE THREAD

**Issue by nauxliu** [roboll/helmfile#698]
If I use the features introduced by the new version of helmfile, I can update the `required_version ` so my colleague knows that they need to upgrade the helmfile.

```yaml
required_version: ">= v0.78"

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: foo
    namespace: bar
```
