### ISSUE TITLE
Templating complex values.yaml files

### ISSUE THREAD

**Issue by ChrisCooney** [roboll/helmfile#700]
Consider the following `values.yaml` file. This is an excerpt from the default values file for the prometheus helm chart:

```
## ConfigMap override where fullname is {{.Release.Name}}-{{.Values.server.configMapOverrideName}}
## Defining configMapOverrideName will cause templates/server-configmap.yaml
## to NOT generate a ConfigMap resource
##
configMapOverrideName: ""
```

When we're attempting to use helmfile to template into this `values.yaml.gotpl` file, we are seeing errors. Obviously it is picking up on `{{` and seeing it as a template. We can accept this for comments since they can simply be deleted, however the same thing is happening for nested values that are not in comments.

```
## alertmanager ConfigMap entries
##
alertmanagerFiles:
  alertmanager.yml:
    global:
      slack_api_url: 'https://slack.com'

    receivers:
    - name: default-receiver
      pagerduty_configs:
        - service_key: key
      slack_configs:
      - channel: '{{ .CommonAnnotations.channel }}'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        title_link: '{{ template "slack.default.titlelink" . }}'
        pretext: '{{ .CommonAnnotations.summary }}'
        text: |-
          {{ range .Alerts }}
             *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            *Description:* {{ .Annotations.description }}
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
```

To be completely honest, I don't really know what the answer to this question is. It is understandable that `helmfile` is detecting these interpolation tokens - however it introduces a lot of escaping and complexity. Given that prometheus is such a widely used chart, I felt it was worth raising to start a discussion.
