### ISSUE TITLE
How to inherit values from the parent to the child helmfile?

### ISSUE THREAD

**Issue by RafalMaleska** [roboll/helmfile#725]
We are trying to use helmfile in our pipeline. For this we hoped to use a parent helmfile (with repository configuration and helm-defaults) and subhelmfiles that INHERIT from this master helmfile. 

Unfortunately this was not possible to achieve.

Are we missing out something?

**Comment by mumoshu** [comment]
@RafalMaleska What do you want to inherit?

One of the rules of helmfile is that each sub-helmfile should be usable independently. So let's assume that your sub-helmfile should be complete on its own i.e. should work without inheritance at all.

It does support inherting values expicitly from the parent to the sub-helmfiles by using this syntax:

```yaml
helmfiles:
- path: path/to/subhelmfile.yaml
   values:
   - foo: {{whatever available in the parent}}
```

Does it help?
