### ISSUE TITLE
How can i set release version to many releases with template?

### ISSUE THREAD

**Issue by caxalex** [roboll/helmfile#729]
I have the template for releases: 

```
  default: &default
    chart: "stable/{{ .Release.Name }}"
    version: ""
    wait: true
    installed: true
    missingFileHandler: Warn
    values:
    - values/{{ .Release.Name }}/base.yaml
    - values/{{ .Release.Name }}/{{ .Environment.Name }}.yaml
```
I have list of releases:
```
- name: "external-dns"
  <<: *default
- name: "metrics-server"
  <<: *default
- name: "prometheus-adapter"
  <<: *default
```
How can i create  list with name of release and version of helm chart and include in template?.
look like:

```
versions:
  external-dns: "1.3.0"
  metrics-server: "2.1.0"
  prometheus-adapter: ""
```

**Comment by mumoshu** [comment]
Hey!

First of all areate a versions.yaml containing:

```
versions:
  external-dns: "1.3.0"
  metrics-server: "2.1.0"
  prometheus-adapter: ""
```

In your helmfile.yaml you should remove `version: ""` from the `default` template and explicitly define version in each release like:

```
values:
- versions.yaml

#snip

- name: "external-dns"
  version: {{.Values.versions | get "external-dns"}}
  <<: *default
- name: "metrics-server"
  version: {{.Values.versions | get "metrics-server"}}
  <<: *default
- name: "prometheus-adapter"
  version: {{.Values.versions | get "prometheus-adapter" }}
  <<: *default
```

Hope this works for you.

**Comment by ag237** [comment]
I'm trying to achieve something similar, and the above doesn't seem to work for me.

versions.yaml

```
chartVersionMetricsServer: "2.3.0"
```

helmfile.yaml
```
bases:
- environments.yaml
---
bases:
- helmdefaults.yaml
---

helmfiles:
- path: releases/metrics-server/helmfile.yaml.gotmpl
  values:
  - versions.yaml
  - name: metrics-server
    base: true
- path: releases/external-dns/helmfile.yaml.gotmpl
  values:
  - name: external-dns
    base: true
- path: releases/cluster-autoscaler/helmfile.yaml.gotmpl
  values:
  - name: cluster-autoscaler
    base: true
```

releases/metrics-server/helmfile.yaml.gotmpl
```
releases:
  - name: metrics-server
    namespace: metrics-server
    chart: stable/metrics-server
    version: "{{ .Values | get "chartVersionMetricsServer" }}"
    missingFileHandler: Warn
    values:
    - "../../values/metrics-server/values.yaml.gotmpl"
    - "../../values/metrics-server/{{ .Environment.Name }}.values.yaml"
```

Error that I'm getting:

```
err: error during helmfile.yaml.gotmpl.part.0 parsing: template: stringTemplate:5:27: executing "stringTemplate" at <get "chartVersionMetricsServer">: error calling get: no value exist for key "chartVersionMetricsServer" in map[]
changing working directory back to "/Users/agardner/work/helmfile"
in ./helmfile.yaml: in .helmfiles[0]: in releases/metrics-server/helmfile.yaml.gotmpl: error during helmfile.yaml.gotmpl.part.0 parsing: template: stringTemplate:5:27: executing "stringTemplate" at <get "chartVersionMetricsServer">: error calling get: no value exist for key "chartVersionMetricsServer" in map[]```
