### ISSUE TITLE
readFile reads only first line

### ISSUE THREAD

**Issue by meiblorn** [roboll/helmfile#731]
Hi,

I have the following folder structure for openldap:
![image](https://user-images.githubusercontent.com/4069585/60388567-9e343580-9ac4-11e9-912b-75786ac8205b.png)

in `common.yaml.gotmpl` I have the following lines:
```
customLdifFiles:
    init.ldif: |
        {{ readFile "../files/ldif/init.ldif" }}
```

Content of `init.ldif` is:
```
dn: ou=groups,dc=example,dc=app
changetype: add
objectClass: top
objectClass: organizationalUnit
ou: groups

... and so on
```

Everything looks ok until I apply my helmfile:
(below is partial output of `helmfile apply`)
```  
apiVersion: v1
  kind: ConfigMap
  metadata:
    name: openldap-customldif
    labels:
      app: openldap
      chart: openldap-1.1.0
      release: openldap
      heritage: Tiller
  data:
    init.ldif: |-
+     dn: ou=groups,dc=example,dc=app
identified at least one change, exiting with non-zero exit code (detailed-exitcode parameter enabled)
```

As you can see, all the lines except first one of file are omitted and ignored.
Why it could happen? Is it bug? Is there any another way to read file and make it part of values?

**Comment by meiblorn** [comment]
Found workaround solution ... Looks ugly, but works

```
      set:
          - name: "customLdifFiles.init\\.ldif"
            file: files/ldif/init.ldif
```

**Comment by meiblorn** [comment]
Seems, it `readFile` reads file content as Go map structure ... In documentation said `readFile reads the specified local file and generate a golang string`. There is defect ...

**Comment by meiblorn** [comment]
`{{ exec "sh" (list "-c" "cat ../files/openid_provider.json") }}` also returns content as Go structure. What is wrong?

**Comment by mumoshu** [comment]
> Seems, that readFile reads file content as Go map structure ...

Nope. It actually reads the file as text!

```
customLdifFiles:
    init.ldif: |
        {{ readFile "../files/ldif/init.ldif" }}
```

this results in:

```
customLdifFiles:
    init.ldif: |
        dn: ou=groups,dc=example,dc=app
changetype: add
objectClass: top
objectClass: organizationalUnit
ou: groups

... and so on
```

Try

```
customLdifFiles:
  init.ldif: |
    {{ readFile "../files/ldif/init.ldif" | indent 4 }}
``

I prefer 2-spaces per indentation level so `init.ldif` has 2-spaces and `{{ readFile` must  have the 2 more spaces before it. That's why I added `indent 4`. Tweak it according to your preference tho.

**Comment by mumoshu** [comment]
Closing this as answered. But please feel free to reopen if necessary!

**Comment by meiblorn** [comment]
Thanks, correct indentation solved the problem

**Comment by mumoshu** [comment]
Glad it worked 👍

**Comment by darkn3rd** [comment]
@mumoshu This is not working as expected.

I find only the first line will be indented with this:
```yaml
    values:
      - identityTrustAnchorsPEM:  |
        {{ readFile "certs/ca.crt" | indent 2 }}
```

However, if I do this, every line is indented:

```yaml
    values:
      - identityTrustAnchorsPEM:  |
{{ readFile "certs/ca.crt" | indent 10 }}
```
I would prefer to have the first example, as the code is more easier to read.
