### ISSUE TITLE
Override values in sub-helmfile

### ISSUE THREAD

**Issue by mrsipan** [roboll/helmfile#748]
I have a basic question about overriding values in sub-helmfiles. Let's say I have this in my main _helmfile.yaml_:

```yaml
helmfiles:
  - path: nginx-controller/helmfile.yaml
    values:
      - controller:
          electionID: id2
```
Here I am trying to override the `controller.electionID` key.
My _nginx-controller/helmfile.yaml_ file looks like this:

```yaml
repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: sncr-ingress
    namespace: ingress-nginx
    chart: stable/nginx-ingress
    version: 1.6.18
    values:
      - controller:
          electionID: id1
```

After running `helmfile template`, `controller.electionID` is rendering the values set in the sub-helmfile (`id1`) instead of that of the main _helmfile.yaml_, that is, I was expecting `controller.electionID = id2`.

**Comment by mumoshu** [comment]
@mrsipan Hey! You need to rewrite your nginx-ontroller/helmfile.yaml like this:

```
values:
- controller:
    electionID: id1

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: sncr-ingress
    namespace: ingress-nginx
    chart: stable/nginx-ingress
    version: 1.6.18
    values:
      - controller:
          electionID: {{.Values.controller.electionID}}
```

The point is that we have two different `values` in helmfile. One is values for (1)helmfile itself, and (2)values for releases. 

This:

```
helmfiles:
  - path: nginx-controller/helmfile.yaml
    values:
      - controller:
          electionID: id2
```

overrides (1) only. You need explicit mappings from (1) to (2).

**Comment by mrsipan** [comment]
@mumoshu, this is what I was looking for, thank you for the clarification.

**Comment by MJBonifacio** [comment]
@mumoshu I'm seeing an issue in 0.85.2 where this doesn't work. I have the exact configuration above with a values, release, and helmfiles section in the "parent" helmfile.

A helmfile build gives something like this
```
***snip***
helmfiles:
- path: <path>
  environment:
    values:
    - top-level:
         key: override-val
***snip***
```

and my "sub"helmfile looks something like this 

```
releases:
- name: {{ requiredEnv ENV_VAR }}-name
  chart: <chart>
  version: <version>
  values:
  - top-level:
      key: {{ env "ENV_VAR" | default "default-val" }}
```

And yet when running `helmfile apply` on the "parent" helmfile, then doing a `helm get` on the sub-helmfile, I get something like this:

```
➜  helm get <sub-helmfile-release>
REVISION: 1
RELEASED: Wed Sep 25 18:31:33 2019
CHART: <sub-helmfile-chart>
USER-SUPPLIED VALUES:
top-level:
  key: default-val
```

However, I'm expecting the sub-release to receive `override-val` instead. Do you know what the issue might be?

**Comment by mumoshu** [comment]
@MJBonifacio Hey!

The issue is that you have `key: {{ env "ENV_VAR" | default "default-val" }}` and you are likely missing any `ENV_VAR` set.

Helmfile doesn't translate helmfile (state) values to envvars to relase/chart values or vice versa.

So I think what you want here is:

```
releases:
- name: {{ .Values | get "top-level" }}-name
  chart: <chart>
  version: <version>
  values:
  - top-level:
      key: {{ .Values | get "top-level" "default-val" }}
```
