### ISSUE TITLE
environments file not working when defined at the bottom of the helmfile

### ISSUE THREAD

**Issue by costimuraru** [roboll/helmfile#754]
Helmfile version: v0.80.1

I have the following environment file:

**DOESN'T WORK**

**my_envs.yaml**
```yaml
mysql:
  version: 1.3.0
```

This helmfile doesn't work:

**helmfile.yaml**
```yaml
releases:
- name: mysql1
  namespace: mysql
  version: {{.Environment.Values.mysql.version}}
  chart: stable/mysql

environments:
  default:
    values:
    - my_envs.yaml
```

Error:
```sh
$ helmfile sync
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: s
tringTemplate:4:25: executing "stringTemplate" at <.Environment.Values.mysql.version>: 
map has no entry for key "mysql"
```

---

**WORKS**
However, if we put environments first, it works:

**helmfile.yaml**
```yaml
environments:
  default:
    values:
    - my_envs.yaml

releases:
- name: mysql1
  namespace: mysql
  version: {{.Environment.Values.mysql.version}}
  chart: stable/mysql
```

```sh
$ helmfile sync
Upgrading stable/mysql
```

---

**WORKS**

What's even more interesting, if instead of `.Environment.Values.mysql.version`, we use just `.Environment.Values.version`, it works, even when the environments section is at the end of the file:

**helmfile.yaml**
```yaml

releases:
- name: mysql1
  namespace: mysql
  version: {{.Environment.Values.version}}
  chart: stable/mysql

environments:
  default:
    values:
    - my_envs.yaml
```

**my_envs.yaml**
```yaml
version: 1.3.0
```

```sh
$ helmfile sync
Upgrading stable/mysql
```

Any idea what's going on?

**Comment by mumoshu** [comment]
@costimuraru Hey! Good catch. TL;DR; this is due to that how "double-rendering" works. I'd like to deprecate it in a longer-term but I'll try my best to explain what's going-on.

---

This is due to how [double-rendering](#308) works and no straight-forward work-around exists.

The fundamental problem we have here is that your first example:

```
releases:
- name: mysql1
  namespace: mysql
  version: {{.Environment.Values.mysql.version}}
  chart: stable/mysql

environments:
  default:
    values:
    - my_envs.yaml
```

has "self-reference" to `.Environment.Values.mysql.version`.

Why I call it "self-reference" is that to resolve `.Environment.Values.mysql.version` you need to load `my_envs.yaml` first. But to load `my_envs.yaml` helmfile needs to render helmfile.yaml. This is a kind of chicken-and-egg problem :)

Helmfile has a feature called "double-rendering", that circumvents this problem by rendering `helmfile.yaml` as a go template "until it sees any error". The above `helmfile.yaml` fails while rendering at `{{.Environment.Values.mysql.version}}` so the first rendering result of it is:

```
releases:
- name: mysql1
  namespace: mysql
  version: 
```

Again this is because that it rendered the go template until it sees error while rendering a template expression at the value for the key "version".

Helmfile produces the final result by rendering `helmfile.yaml` as a go template again, with the environment values loaded by loading the YAML produced by the first render. The first render result doesn't contain "environments" cuz it failed before rendering "environments.

In contrast, your second example:

```
environments:
  default:
    values:
    - my_envs.yaml

releases:
- name: mysql1
  namespace: mysql
  version: {{.Environment.Values.mysql.version}}
  chart: stable/mysql
```

this works because the first pass is able to render:

```
environments:
  default:
    values:
    - my_envs.yaml

releases:
- name: mysql1
  namespace: mysql
  version: 
```

which contains `environments` that can be loaded and then fed into the second pass.

Lastly, your third example works because the first-pass doesn't fail. It produces:

```
releases:
- name: mysql1
  namespace: mysql
  version: <no value>
  chart: stable/mysql

environments:
  default:
    values:
    - my_envs.yaml
```

`<no value>` is the placeholder string that is generated when you've queried for an empty key in a  map. The difference between the second and the third example is that either the query is made against a map or `nil`.

To be extra clear, the second example fails because `{{.Environment.Values.mysql.version}}` results in querying `version` in `.Environment.Values.mysql.` which is `nil`.

**Comment by mumoshu** [comment]
The best way would be to avoid relying on double-rendering entirely.

Try separating your `helmfile.yaml` with `---` to turn it into two-parts go template.

```
environments:
  default:
    values:
    - my_envs.yaml
---
releases:
- name: mysql1
  namespace: mysql
  version: {{.Environment.Values.mysql.version}}
  chart: stable/mysql
```

The semantics is much simpler now. The first-part produces environment values that is fed to the second part. There's no chicken-and-egg problem anymore.

**Comment by costimuraru** [comment]
thanks @mumoshu 

using `---` did the trick.

We were actually having the same issue when trying to use `bases` in the sub helmfiles.

**common.yaml**
```yaml
environments:
  default:
    values:
    - environments_default_values.yaml
```

**did not work:**
subhelmfile.yaml:
```yaml
bases:
  - common.yaml

releases:
- name: mysql1
  namespace: mysql
  version: {{.Environment.Values.version}}
  chart: stable/mysql
```

**works now:**
subhelmfile.yaml:
```yaml
bases:
  - common.yaml
---
releases:
- name: mysql1
  namespace: mysql
  version: {{.Environment.Values.version}}
  chart: stable/mysql
```
