### ISSUE TITLE
doc: Templating tips and tricks

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#756]
Let's gather all the tips and tricks worth included in the documentation, by linking from various questions answered in this repo.

**Comment by mumoshu** [comment]
Use `index .Values (requiredEnv "FOO")` to get the environment value at the path determined from an envvar #755

**Comment by mumoshu** [comment]
Including an external file b64-encoded as a helm value #757

**Comment by mumoshu** [comment]
Selectively inheriting helmfile values to sub-helmfile: #725

**Comment by mumoshu** [comment]
Leveraging a sub-helmfile to differentiate template params across two or more releases https://github.com/roboll/helmfile/issues/387#issuecomment-513737164

**Comment by andrewnazarov** [comment]
The `|` trick taken from the [Slack discussion](https://sweetops.slack.com/archives/CE5NGCB9Q/p1560151215037500)

**Comment by andrewnazarov** [comment]
I've seen somewhere a dedicated block for global variables, cannot find it in the current docs.

**Comment by mumoshu** [comment]
Pinning sub-helmfile version by @osterman:

```
helmfiles:
  - path: "git::https://github.com/cloudposse/helmfiles.git@releases/reloader.yaml?ref=0.48.0"
```

Slack: https://sweetops.slack.com/archives/CE5NGCB9Q/p1563983556083300?thread_ts=1563939458.049400&cid=CE5NGCB9Q

**Comment by mumoshu** [comment]
Conditional Release enabled if and only if specific Helmfile value is set: https://github.com/roboll/helmfile/issues/784#issuecomment-517577134

**Comment by andrewnazarov** [comment]
How `helmfile destroy` deals with the releases order: #797

**Comment by mumoshu** [comment]
Installing Istio with Helmfile: #789

**Comment by mumoshu** [comment]
Installation ordering: #137

**Comment by mumoshu** [comment]
Inline and external template snippets for reducing code repetition #803

**Comment by mumoshu** [comment]
Erasing environment values with layering and overrides(Use sprig's `unset`) https://github.com/roboll/helmfile/issues/866#issuecomment-533748904

**Comment by mumoshu** [comment]
Reusing conventional release spec with `define` and `template`: https://github.com/roboll/helmfile/issues/860#issuecomment-532465422

**Comment by mumoshu** [comment]
Referencing the release name from other releases, without release templates:

```
{{ $db_release := "mydb" }}

releases:
- name: {{ $db_release}}
  chart: charts/db
- name: app
  chart: charts/app
  values:
  - db:
      host: {{ $db_release }}:3306
```

Ref: https://sweetops.slack.com/archives/CE5NGCB9Q/p1568910579018700

**Comment by mumoshu** [comment]
Reference the cluster name from kubeconfig and reuse it across releases: https://github.com/roboll/helmfile/issues/852#issuecomment-533782003

`clustername.sh`:

```
#!/bin/bash

set -e

KUBE_CONTEXT=${KUBE_CONTEXT:-$1}

kubectl config view > kubeconfig.tmp
KUBECONFIG=kubeconfig.tmp
if [ ! -z "$KUBE_CONTEXT" ]; then
  kubectl config use-context $KUBE_CONTEXT 1>&2
fi
kubectl config view --minify -o jsonpath='{.clusters[*].name}'
rm kubeconfig.tmp
```

`helmfile.yaml`

```
{{ $cluster := exec "bash" (list "clustername.sh") }}

releases:
- name: datadog
  chart: stable/datadog
  values:
  - datadog:
      tags:
      - cluster:{{$cluster}}
```

**Comment by mumoshu** [comment]
Helm v3: Creating and managing namespaces https://github.com/roboll/helmfile/issues/891

**Comment by jurgenweber** [comment]
how to loop releases dynamically and reference a secret:

https://github.com/roboll/helmfile/issues/986#issuecomment-555792108

**Comment by mumoshu** [comment]
Adding annotations with a post-sync hook:

```
    hooks:
      - events: ["postsync"]
        command: "/bin/sh"
        args: ["-c", "kubectl annotate --overwrite --namespace={{`{{ .Release.Namespace }}`}} DaemonSet/{{`{{ .Release.Name }}`}}-agent secret.reloader.stakater.com/reload=kiam-agent-certificate-secret,kiam-ca-cert"]
      - events: ["postsync"]
        command: "/bin/sh"
        args: ["-c", "kubectl annotate --overwrite --namespace={{`{{ .Release.Namespace }}`}} DaemonSet/{{`{{ .Release.Name }}`}}-server secret.reloader.stakater.com/reload=kiam-server-certificate-secret,kiam-ca-cert"]
```

ref: https://sweetops.slack.com/archives/CE5NGCB9Q/p1572946918049300?thread_ts=1572531812.021800&cid=CE5NGCB9Q
