### ISSUE TITLE
Unable to use .Release.Name in values.gotmpl

### ISSUE THREAD

**Issue by albertmichaelj** [roboll/helmfile#760]
I have a use case where I want the `.Release.Name` to be used as a variable in a `values.gotmpl` file. However, no matter what I do, the values.gotmpl file will not render `.Release.Name`. Is this expected behavior? Are there suggestions on how to work around this?

My use case is that I have multiple deployments of the same app on the same kubernetes cluster with non-namespaced objects (specifically PVs and filepaths on an NFS server) that need to be given unique names. I am using the release name as a unique identifier to add as a prefix to these non-namespaced objects. So, if you can't use `.Release.Name` in a gotmpl file, is there any other way to pass a unique value to the `gotmpl` file and still run a single `helmfile -f ... sync` command?

**Comment by mumoshu** [comment]
@albertmichaelj Hey!

`Release.Name` is available only while rendering helmfile.yaml, not values file templates.

As a work-around, can you extract the part of your `values.gotmpl` into `helmfile.yaml` like:

```yaml
releases:
- name: yourapp
   chart: yourchart
   values:
   - pathOnNfs: /path/to{{.Release.Name}}
```

If not, I think this is a valid feature request, as I see no downside of improving helmfile to allow `.Release.Name` within `values.gotmpl`.

**Comment by albertmichaelj** [comment]
@mumoshu Thanks for the response, and it's really helpful to know that I wasn't just doing something stupid. If it's not a major change, I think being able to specify some kind of unique value that can be propagated to the `values.gotmpl` file would be very, very helpful for my use case. The problem is that I (for various reasons) need to specify `pathOnNfs` multiple places in the `values.yaml` file, and while I could conceivably set the values a bunch of times in the helmfile, that would clutter things up quickly.

This doesn't necessarily need to be the `Release.Name`. It could be something in the release like 
```yaml
releases:
- name: yourapp
    chart: yourchart
    environment:
      - customValue: "whatever"
    values:
      - values.gotmpl
```
and then in `values.gotmpl` you could have something like:
```yaml
foo: {{ .Environment.Custom.Values.customValue }}
```
This would be more flexible in that you could always set `customValue` to `Release.Name` using double rendering in the helmfile. The big need for me, is that I need someway to specify per release values that need to be repeated several times in the `values.gotmpl` for a variety of reasons (generally because I'm using an existing chart and I am trying to avoid forking the chart).

There isn't any functionality currently like this in helmfile, right?

I know that I can call helmfile with something like `CUSTOM="whatever" helmfile -f helmfile.yaml sync` and then I can use the `CUSTOM` environmental variable, but it keeps me from using a single helmfile call to update all of my releases (and I can't easily version control that command).

Is this use case within scope for helmfile? If not, please don't make changes that aren't within the spirit of the tool.

Thanks!

**Comment by mumoshu** [comment]
@albertmichaelj Hey!

A short-term solution to your problem would be to leverage sub-helmfile, like @janekbaraniewski has shared in https://github.com/roboll/helmfile/issues/387#issuecomment-513737164.

In longer-term, the combination of double-rendering and per-release overrides as you've suggested seems like the best way forward!

Fortunately, we have a similar request that can accommodate your use-case as well. See the discussion starting from https://github.com/roboll/helmfile/issues/745#issuecomment-510737741 - I think we can extend it so that you can rewrite your example as:

```yaml
releases:
- name: yourapp
  chart: yourchart
  set:
  - valuesFrom:
      templateFile:
        path: values.gotmpl
        valuesFrom:
        # Instead of implicitly passing helmfile's values to the values.gotmpl
        # explicitly set this so that it inherits all the helmfile values into the template rendering context of `values.gotmpl`
        - valuesInherited: true
        # Overrides
        - inline:
            customValue: "whatever"
```

The syntax seems a bit verbose but the benefits are countless - I believe it does support your use-case, and also (1)it's completely backward-compatible, (2)has extensibility to support other value sources like AWS SSM, Vault, etc.

WDYT?
