### ISSUE TITLE
feat: Option to stop helmfile when postsync hook failed

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#764]
Helmfile as of today doesn't stop when one of releases failed while running `postsync`.

// The documentation for hooks is available in https://github.com/roboll/helmfile#hooks, and `postsync` was added in #601.

[I've received a feature request in our slack channel](https://sweetops.slack.com/archives/CE5NGCB9Q/p1563450746230800) that, to run `helm test` on `postsync` to verify the installation was successful and stop if failed we need a way to optionally instruct helmfile to stop on non-zero exit code from a command run via `postsync`.

How about adding `errorHandler: Stop` that should be set only when you want helmfile to stop when the hook fails?

```
releases:
- name: myapp
  chart: mychart
  # *snip*
  hooks:
  - events: ["postsync"]
    showlogs: true
    command: "my-nofity-to-slack-cmd"
    args: ["{{`{{.Environment.Name}}`}}", "{{`{{.Release.Name}}`}}", "{{`{{.HelmfileCommand}}`}}\
"]
  - events: ["postsync"]
    showlogs: true
    # NEW: Warn(default) keep helmfile running on error, Stop(new behavior) stops helmfile on error
    errorHandler: Stop
    command: "helm"
    args: ["test", "{{`{{.Release.Name}}`}}"]
```

**Comment by dudicoco** [comment]
@mumoshu that would be a great addition!

**Comment by iAnomaly** [comment]
Would love to see the inverse of this supported for `presync` as well @mumoshu. I.e. `errorHandle: Warn` for `presync`.

```
releases:
- name: myapp
  chart: mychart
  # *snip*
  hooks:
  - events: ["presync"]
    showlogs: true
    # NEW: Stop(default) stops helmfile on error, Warn(new behavior) keep helmfile running on error
    errorHandler: Warn
    command: "kubectl"
    args: ["-n", "kube-system", "delete", "my-resource", "my-name"]
```
