### ISSUE TITLE
Release template in nested string isn't rendered

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#769]
This is reported in our official Slack channel: https://sweetops.slack.com/archives/CE5NGCB9Q/p1563863513024900

This doesn't work, leaving `"{{.Release.Name}}"` not rendered:
```yaml
releases:
- name: myapp
  values:
  - app:
    name: {{`"{{.Release.Name}}"`}}
```

While this works:

```yaml
releases:
- name: myapp
  values:
  - appName: {{`"{{.Release.Name}}"`}}
```
