### ISSUE TITLE
release values don't honour order

### ISSUE THREAD

**Issue by Morriz** [roboll/helmfile#775]
Seen the following example:
```yaml
release:
  - name: bla
    values:
      - some: value
        another: overridingEnvVars
      - somefile.gotmpl
```
I would expect the first values to be merged with a clone of the environment variables, BEFORE the rendering of `somefile.gotmpl`. This is not the case. Each of the entries in the values array is rendered seperately before being merged successively.

I really think there is a BIG use case for this, and I would love to see this "fixed" as it would solve almost all of my composability problems.
