### ISSUE TITLE
feat: `helmfile build` to produce rendered and flattened state file for GitOps

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#780]
## Problem

Helmfile's advanced templating features consisting of "release templates", "sub-helmfiles", "state values", "environments" are all GREAT for making your desired states DRY by avoiding repeated configs across environments.

But advanced templating has downside - less predictable results. This makes it very hard to debug and audit deployments made by Helmfile.

### Helmfile Diff

`helmfile diff` helps by previewing changes to be made to the cluster before deploying. But you need real cluster connectivity from your CI to run diff, which is a security concern. And sometimes, you still need another level of visibility to "intermediate" result produced by Helmfile - rendered helmfile.yaml template.

### Debug logs, Dry-Run, Captured Releases, ...

People usually use `--helmfile --log-level=debug` for that purpose. `helmfile --dry-run` #118 is being discussed for additional visibility and better U/X.

@bitsofinfo has proposed ability to write rendered releases to the local disk in #752. This sounds like a good idea for visibility and auditability. But one gotcha is that it may lack correctness due to how Helmfile is implemented today. Helmfile as of today applies rendered releases in-place. So if Helmfile is enhanced to write a slightly different representation of releases to disk, it's theoretically possible that what Helmfile wrote and what Helmfile applied differs, which makes the whole purpose of the feature meaningless.

### GitOps

GitOps is recently emerging for better audited and reproducible deployments. But it doesn't really help Helmfile.

Highly templatized `helmfile.yaml` commited into Git for GitOps doesn't automatically provide useful git-diff - because the diff isn't based on rendered helmfile.yaml. You need either CI or your brain to render the helmfile.yaml template and take useful diff to give confidence that a new helmfile deployment doesn't break your system, which is hard.

## Solution

I'm proposing the combination of the followings:

- Embrace GitOps
- GitOps-friendly Helmfile "ReleaseSet" API
- `helmfile build` that writes a ReleaseSet
- Alternative and internal RelesetSet processor(In-place processor we have today remains for backward-compatibility

A ReleaseSet is produced from the ordinary helmfile.yaml template you all have today and looks like:

```yaml
apiVersion: helmfile.example.com/v1alpha1
kind: ReleaseSet
metadata:
  name: myapp
  annotations:
    approved: "false"
spec:
  releases:
  # or ns1/baz meaning both namespace and tillerNamespace set to ns1
  - name: bar
    chart: mychart
    namespace: ns1
    tillerNamespace: ns1
    dependencies:
    - somerandomlygeneratedgroupname:baz
    values:
    - inline:
        foo: bar
    secrets:
    - inline:
        # embedded secrets.yaml contents (=values encrypted by sops
    - # References to values in SSM
    - # References to values in Vault
  # or ns2/somerandomlygeneratedgroupname:baz meaning both namespace and tillerNamespace set to ns2
  - name: somerandomlygeneratedgroupname:baz
    chart: mychart2
    namespace: ns2
    tillerNamespace: ns2
```

All the releases, values and encrypted secrets and the selected environment included in your helmfileand its sub-helmfiles and will be rendered and flattened.

The environment will be erased hence there's no occurrence of "environment" in the build output.

We need a DAG of "dependencies"(#715 and #723) to flatten sub-helmfiles.

The typical usage of `helmfile build` would look as follows.

On your laptop(for testing) or CI(for production), `helmfile build` is run to produce a flattened ReleaseSet:

```console
$ cd helmfile-template-repo/
$ helmfile -e prod -f helmfile.yaml.gotmpl build > ../gitops-repo/helmfile.prod.yaml

$ cd ../gitops-repo
$ git commit -m 'New deployment'
$ git push origin master
```

On your laptop(for testing) or CD(for production), the CD pipeline recognizes `approved: "false"` in your releaset set and runs `helmfile diff` so that you can review changes at K8s manifests level for approval:

```console
$ helmfile -f helmfile.prod.yaml diff | some-cmd-to-send-github-comment
```

You approve it by commenting on the PR to the "helmfile-template-repo" with `/approve`.

On your laptop(for testing), or CI triggered via a GitHub pull request comment(for production), some command to modify the ReleasetSet to have a `approved: "true"` annotation:

```console
# `helmfile approve` is just a nice-to-have here. You can use yq or sed instead
$ helmfile -f helmfile.prod.yaml approve > helmfile.prod.approved.yaml
$ cp helmfile.prod.approved.yaml helmfile.prod.yaml
$ git commit -m 'Automated approval' && git push
```

On your laptop or CD, the CD pipeline recognizes `approved: "true"` and therefore runs `helmfile apply`:

```
$ git clone git@github.com:yourorg/yourgitopsrepo.git -b your-pr
$ helmfile -f helmfile.prod.yaml apply
```

This way, you have complete audit logs of what's being rendered and deployed by Helmfile in Git.

**Comment by mumoshu** [comment]
cc/ @sstarcher @osterman @bitsofinfo @Stono I'm considering to enhance Helmfile this way for better auditing of Helmfile deployments with GitOps, and better security by optionally limiting CI to have no access to production clusters and exposing no github webhook endpoint.

WDYT?

**Comment by bitsofinfo** [comment]
I dig it!!! Solid idea.

Some questions:

* The `ReleaseSet` example above; I assume this new format AND the existing format for a helmfile could *both* still be consumable by `helmfile -f <releaseset format | non-releaseset format>` Would absolutely have to have this compatibility or flexibility to use either. Just double checking your 4th bullet above :)

* What I like about this is that it does not impose/force any particular flow. In my use case I could still just use `build` to give me this auditable record, what I or anyone else does with it is up to the operator of helmfile. This is important.

* a `ReleaseSet's` `annotations` should be customizable. I.E. the name of the annotation keys and value(s). I don't see a need for complexity here, just some simple `k=v,k=v` kind of capability would be good here. Also perhaps consider adding `labels`, but this might not be needed as annotations are more appropriate, as my understanding of the k8s spec is `labels` is reserved maybe for actual objects created within k8s by a manifest, which we clearly are *not* doing here.
```
helmfile -e prod -f helmfile.yaml.gotmpl --set-annotations a1=y,a2=z build 
```

* Another thought, it would be nice to be able to add into an annotations a auto-generated string representation of the arguments passed to helmfile build that produced this result. This would be very helpful for my use case where the "generated" releases are very dynamic.
```
...
annotations:
  helmfilecmdargs: "-f helmfile.yaml -e env --state-values-set x=y ... etc build"
```

* Just a note, currently I have some hacky tooling that is manually parsing out the `debug` produced `releases:` block for my auditing purposes. This would most definitely replace that.  Secondly I am also heavily using the `--quiet & template` option to get my the k8s yaml to store as well. I would still have that need, but its pretty un-related to this.

* Overall, these are just my initial thoughts, but I'm excited about this, great idea!

**Comment by sstarcher** [comment]
I fully agree that if we can remove or make all templating of helmfiles first-class citizens it would be much better and easier to handle and debug.  Templating of a helmfile itself is essentially a crutch and a dirty work around.

Embedded secrets.yaml could result in a massive release set.  It would likely be better to create it as a separate object and to reference them as refs.

Everything in ReleaseSet should be cleanly diff-able.

**Comment by mumoshu** [comment]
> * The `ReleaseSet` example above; I assume this new format AND the existing format for a helmfile could *both* still be consumable by `helmfile -f <releaseset format | non-releaseset format>` Would absolutely have to have this compatibility or flexibility to use either. Just double checking your 4th bullet above :)

Your assumption is correct :) Btw, implementation-wise it should be a matter of Helmfile checking existence of `apiVersion` and `Kind`, which should be easy enough.

> * What I like about this is that it does not impose/force any particular flow. In my use case I could still just use `build` to give me this auditable record, what I or anyone else does with it is up to the operator of helmfile. This is important.

Exactly. I believe that's important.

> * Another thought, it would be nice to be able to add into an annotations a auto-generated string representation of the arguments passed to helmfile build that produced this result

Seems like a valid feature request! I like it as much as I like `run` annotation added to pods created by `kubectl run` :)

> * Just a note, currently I have some hacky tooling that is manually parsing out the `debug` produced `releases:` block for my auditing purposes. This would most definitely replace that. 

Yep, I believe so too.

> Secondly I am also heavily using the `--quiet & template` option to get my the k8s yaml to store as well. I would still have that need, but its pretty un-related to this.

Yep. You'll still need it.

FWIW, I'm currently forwarding `helmfile diff` outputs to the pull request triggered the helmfile deployment for the same purpose as you(I think)

**Comment by mumoshu** [comment]
> I fully agree that if we can remove or make all templating of helmfiles first-class citizens it would be much better and easier to handle and debug.  Templating of a helmfile itself is essentially a crutch and a dirty work around.

I do envision that, after this enhancement, helmfile can be used in combination with other templating tool based on jsonnet, Lua, ECMAScript or anything else.

The minimum feature of Helmfile will be a solid ReleaseSet reconciler that supports DAG, hooks, and many pluggable values/secrets backends.

> Embedded secrets.yaml could result in a massive release set.  It would likely be better to create it as a separate object and to reference them as refs.
> 
> Everything in ReleaseSet should be cleanly diff-able.

I agree, but I'm not yet sure how it should fully work.

Anything other than `secrets.yaml` collocated in the same repo as `helmfile.yaml` will remain references to actual secrets. Based on https://github.com/roboll/helmfile/issues/745#issuecomment-510889406 it may look like:

```
spec:
  releases:
  # or ns1/baz meaning both namespace and tillerNamespace set to ns1
  - name: bar
    chart: mychart
    set:
    - values:
        foo: bar
    - valuesFrom:
        sops:
          inline: |
            #embedded secrets.yaml #1
    - valuesFrom:
        sops:
          inline: |
            #embedded secrets.yaml #2
    - valuesFrom:
        sops:
          url: github.com/yourorg/yourrepo//yourenv@secrets.yaml?ref=<commit id>
    - valuesFrom:
         ssm: #ssm path and anything needed for importing kvs from ssm
    - valuesFrom:
         vault: #vault path and anything needed for importing kvs from vault
```

Perhaps small `secrets.yaml`s can be embedded with `set[].valuesFrom.sops.inline` as shown in the above, and bigger `secrets.yaml` should be referenced by urls.

Maybe it's fine to omit the ability to embed small `secrets.yaml` and make everything imported as references to secrets.yaml's.

Then the remaining problem is how Helmfile should get the URL of a secrets.yaml.

Let's say you have a "source" repo that contains `helmfile.yaml` and `secrets.yaml` where `helmfile.yaml` looks like:

```yaml
releases:
- name: myapp
  chart: mychart
  secrets:
  - secrets.yaml
```

`helmfile build --name myapp` would produce the below:

```
apiVersion: helmfile.example.com/v1alpha1
kind: ReleaseSet
metadata:
  name: myapp
spec:
  releases:
  - name: myapp
    chart: mychart
    set:
    - valuesFrom:
        sops:
           url: github.com/yourorg/yourrepo//yourenv@secrets.yaml?ref=<commit id>
```

Can we safely assume that `helmfile build` is always run within a Git repository with a `origin` correctly set so that Helmfile is able to run `git remote show origin` to get the `github.com/yourorg/yourrepo/` part of the url and `git rev-parse --short HEAD` to get the `<commit id>`?
