### ISSUE TITLE
feat: First-class Support for Conditional Release

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#781]
I'm seeing emerging use of `{{ if eq .Environment.Name "theenv" }}` in helmfile.yaml templates for making releases optional for a subset of environments.

To me, helmfile templates are necessarily evil for 

I'm considering to add Helmfile a first-class support for that use-case by adding `if` configuration key to `helmfile.yaml`:

```yaml
releases:
- name: istio
  chart: istio.io/istio
  if:
     environment:
     - dev
     - staging
```

Any thoughts?

**Comment by andrewnazarov** [comment]
It would be great. The syntax proposal is the following:

```
releases:
- name: istio
  chart: istio.io/istio
  environment:
    - dev
    - staging
```

or plural

```
releases:
- name: istio
  chart: istio.io/istio
  environments:
    - dev
    - staging
```

**Comment by mumoshu** [comment]
@andrewnazarov Thanks! `environments` seems cleaner.

What I was struggling though is that I was expecting to need some way to enable release according to state values. Towards that, it would be great if we can start with an extendable syntax.

Let's say we wanted to enable Istio in dev and staging OR `istio.enabled` is set to true, which of the below options do you like most?

Option 1:

```yaml
releases:
- name: istio
  chart: istio.io/istio
  enabledEnvironments:
  - dev
  - staging
  enabledValues:
  - istio.enabled
```

Option 2:

```yaml
releases:
- name: istio
  chart: istio.io/istio
  enabled:
    environments:
    - dev
    - staging
    value: istio.enabled
```

Option 3:

```yaml
releases:
- name: istio
  chart: istio.io/istio
  enabled:
    environments:
    - dev
    - staging
    if: istio.enabled
```

Option 4:

```yaml
releases:
- name: istio
  chart: istio.io/istio
  environments:
  - dev
  - staging
  enabledIf: istio.enabled
```

**Comment by andrewnazarov** [comment]
A bit confusing use case at first. Could you please elaborate? 

So, you are talking about setting the parameter somewhere else for some specific environments (different from dev and staging). And then to install a release based on the value of that parameter. Or if the environment is not set, to install a release for every environment, but only if the parameter equals a certain value. Am I getting you right?

Maybe we should introduce a block `conditions:` or something like that for all the cases when the release should be installed.

I'm wondering if this clashes somehow with `installed: true/false`.

**Comment by mumoshu** [comment]
> And then to install a release based on the value of that parameter. Or if the environment is not set, to install a release for every environment, but only if the parameter equals a certain value. Am I getting you right?

Yes. I'd say it's similar to how Helm umbrella chart toggles a subchart with `condition: subchart.enabled`.

> Maybe we should introduce a block conditions: or something like that for all the cases when the release should be installed.

Sounds good!

> I'm wondering if this clashes somehow with installed: true/false.

Probably not. `instal: true/false` processes a release to install or uninstall it onto/from the cluster, where `conditions` filters the release out of the process. So `installed` can be used to install/uninstall a conditional release.

It will be confusing to some people though.

**Comment by mumoshu** [comment]
With `conditions` I think we have 3 more options.

Option 5:

```yaml
releases:
- name: istio
  chart: istio.io/istio
  environments:
  - dev
  - staging
  condition: istio.enabled
```

Option 6:

```yaml
releases:
- name: istio
  chart: istio.io/istio
  condition:
    environments:
    - dev
    - staging
    value: istio.enabled
```

Option 7:

```yaml
releases:
- name: istio
  chart: istio.io/istio
  conditions:
  - environments:
     - dev
     - staging
  - value: istio.enabled
```

**Comment by zmiccar** [comment]
I like _option 5_ for the sole reason of it being more clean.

**Comment by zmiccar** [comment]
And in my opinion every list should have a plural named key.

**Comment by mumoshu** [comment]
Also note that these conditions are concatenated with logical AND op. In pseudo-code the above is

> `.Environment.Name in ["dev", "staging"] && .Values.istio.enabled`

**Comment by acaire** [comment]
@mumoshu I'm keen to give this a crack, as I really need this functionality - I thought about modelling it off Kubernetes:
```
releases:
- name: test
  chart: incubator/raw
  filters:
  - key: environment
    operator: In
    values:
    - test
  - key: environment
    operator: NotIn
    values:
    - prod
```

I've put a POC into #1190 - Thoughts?

**Comment by mumoshu** [comment]
@acaire Hey! Thanks for giving it a shot.

I thought about this for a while, and I concluded this should be the `condition: whatever.enabled` syntax, where `whatever.enabled` can be defined within environment values:

```
values:
# Istio is disabled by default
- istio:
    enabled: false

environments:
  dev:
  staging:
    values:
    - istio:
        enabled: true
  prod:
    values:
    - istio:
        enabled: true

releases:
- name: istio
  chart: istio/istio
  condition: istio.enabled
```

The good part of that is it's easy to write simple cases without go template, while also supporting complex usecases like yours with go template:

```
values:
# Istio is disabled by default
- istio:
    enabled: false

{{ define "istio-setting" }}
{{ $env := . -}}
{{ $val := or (list "test" | has $env) (not (list "prod" | has $env)) -}}

{"istio": {"enabled": {{ $val}} -}}
{{ end }}

environments:
  dev:
  staging:
    values:
    - {{ template "istio-setting" "staging" }}
  prod:
    values:
    - {{ template "istio-setting" "prod" }}

releases:
- name: istio
  chart: istio/istio
  condition: istio.enabled
```
