### ISSUE TITLE
How to run helmfile sequentially

### ISSUE THREAD

**Issue by shikhar7** [roboll/helmfile#784]
helmfile.yaml

```
releases:
  - name: dmp-prerequisites
    chart: ./helm-installer/dmp-prerequisites
    values:
    - values.yaml.tmpl
    wait: true
  - name: help
    chart: ./helm-installer/help
    values:
    - values.yaml.tmpl
```

i want to run these chart sequentially one after the other how to run this.Is it possible to run it sequentially.

**Comment by mumoshu** [comment]
@shikhar7 Hey! Try providing `--concurrency 1` to helmfile :)

**Comment by shikhar7** [comment]
Thanks Alot it worked!!...:)

**Comment by shikhar7** [comment]
Hi just one thing is there conditional statement support in hemfile like i want to execute the above help chart only if the variable 'isHelp' set to true...Is it possible to do that?

**Comment by mumoshu** [comment]
Yes, please try using a go template expression like `{{ if .Environment.Values.isHelp }}`

**Comment by shikhar7** [comment]
Hi Can you please be specific like i have to use hook for that or where should i set this condition.

```
releases:
  - name: dmp-prerequisites
    chart: ./helm-installer/dmp-prerequisites
    values:
    - values.yaml.tmpl
    wait: true
  - name: help
    chart: ./helm-installer/help
    values:
    - values.yaml.tmpl
    hooks:
  - events: ["prepare", "cleanup"]
    showlogs: true
    command: "echo"
    args: ["{{`{{if eq .Environment.Values.isHelp \"true\"}}"]
```
**Sorry i am new to helmfile and is trying to understand it.**
