### ISSUE TITLE
Wait for job to be successfully running

### ISSUE THREAD

**Issue by shikhar7** [roboll/helmfile#785]
Hi, I am trying to run the below helmfile.yaml and in case of mysql as shown below i have one job and i need to wait for the job to be successfully completed before going to another helm chart release.I am running helmfile sequentially by using --concurrency=1.

I have earlier used shell script and i used to do something like `kubectl wait --for=condition=complete --timeout=-1s job/mysql-load -n ${global_namespace}`.Is there any way to do so in helmfile.If yes can you please elaborate on that.
```
releases:
{{ if .Environment.Values.isDmpPrerequisites }}
  - name: dmp-prerequisites
    chart: ./helm-installer/dmp-prerequisites
    values:
    - values.yaml.tmpl
{{ end }}

{{ if .Environment.Values.isDynamicPv }}
  - name: dynamic-pv
    chart: ./helm-installer/dynamic-pv
    values:
    - values.yaml.tmpl
{{ end }}

{{ if .Environment.Values.isMysqlInternal }}
  - name: mysql
    chart: ./helm-installer/mysql
    values:
    - values.yaml.tmpl
    wait: true
{{ end }}

{{ if .Environment.Values.isHelp }}
  - name: help
    chart: ./helm-installer/help
    values:
    - values.yaml.tmpl
{{ end }}

environments:
  default:
    values:
    - environments/default/values.yaml
```

**Comment by mumoshu** [comment]
Yep. Try setting `wait: true` for each release under `releases`, or run `kubectl wait` in [hooks](https://github.com/roboll/helmfile#hooks)!

**Comment by shikhar7** [comment]
I have tried to set wait:true in all and in command how do i need to set this ...setting this way doesn't work.
```
releases:
{{ if .Environment.Values.isDmpPrerequisites }}
  - name: dmp-prerequisites
    chart: ./helm-installer/dmp-prerequisites
    values:
    - values.yaml.tmpl
{{ end }}

{{ if .Environment.Values.isDynamicPv }}
  - name: dynamic-pv
    chart: ./helm-installer/dynamic-pv
    values:
    - values.yaml.tmpl
{{ end }}

{{ if .Environment.Values.isMysqlInternal }}
  - name: mysql
    chart: ./helm-installer/mysql
    values:
    - values.yaml.tmpl
    wait: true
{{ end }}

{{ if .Environment.Values.isHelp }}
  - name: help
    chart: ./helm-installer/help
    values:
    - values.yaml.tmpl
    hooks:
    - events: ["prepare", "cleanup"]
      showlogs: true
      command: "kubectl"
      args: ["{{`get nodes`}}"]
{{ end }}

environments:
  default:
    values:
    - environments/default/values.yaml
```

**Comment by mumoshu** [comment]
@shikhar7 It should work for pods, pvcs, services, and deployments according to the helm usage(`wait: true` just adds `--wait` to helm commands called by helmfile):

```
      --wait                     if set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment are in a ready state before marking the release as successful. It will wait for as long as --timeout
```

Maybe helm's --wait doesn't work for jobs? Then we may need a feature request to helm.

Otherwise running `kubectl wait` in helmfile hooks should work

**Comment by shikhar7** [comment]
@mumoshu If we some how allow array in command like given below then this may work
   ```
 hooks:
    - events: ["prepare", "cleanup"]
      showlogs: true
      command: [ "/bin/bash", "-c", "--" ]
      args: ["{{`oc get nodes`}}"]
```

**Comment by mumoshu** [comment]
Great!

FYI, you can also use this as a shorter alt `args: ["-c", "--","oc get nodes"]`.

```
{{` ... `}}
```

Is needed only when you want to treat go-template expressions as plain yaml strings.

**Comment by shikhar7** [comment]
Yup Thanks....:)

**Comment by sebnyberg** [comment]
Here's an example that waits for the job to finish using `kubectl wait`

```
  hooks:
  - events: ["cleanup"]
    showlogs: true
    command: "kubectl"
    args: ["wait", "--for=condition=complete", "--timeout=3600s", "job/myjob"]
```
