### ISSUE TITLE
hooks not called with destroy

### ISSUE THREAD

**Issue by Morriz** [roboll/helmfile#802]
I don't see the hooks being called when I destroy a chart. I need it to call them though...can it be enabled?

**Comment by mumoshu** [comment]
Which types of hooks are you referring? (We have plenty of them like `presync`, `postsync`, `cleanup` etc

**Comment by vinayr** [comment]
+1
None of the currently supported hooks (`prepare`, `presync`, `postsync`, `cleanup`) work with destroy.

**Comment by Morriz** [comment]
exactly...no hooks at all work upon destroy

**Comment by mumoshu** [comment]
Ah that makes sense! And none of hooks doesn't fit with `destroy`.

So how about adding the `predelete` hook?

**Comment by vinayr** [comment]
Not sure about `predelete` since delete is deprecated. May be `predestroy`?

**Comment by syenduri** [comment]
May i know whether hooks while 'helmfile destroy' were available? like predestroy/postdestroy?

**Comment by mumoshu** [comment]
@vinayr FWIW, `delete` isn't deprecated. It is just a recommended alias for `delete --purge`!

**Comment by mumoshu** [comment]
@syenduri Not yet. But let's use this issue as a feature request to add `predelete`.

**Comment by mherwig** [comment]
Ah hook that will be called when running helmfile destroy would be very helpful
+1

**Comment by tstmrk** [comment]
`predestroy` and `postdestroy` hooks would be great!

**Comment by SCLogo** [comment]
will this be implemented in the near future ?

**Comment by ejianu** [comment]
I subscribe to adding `predestroy` and `postdestroy` pretty please :)

**Comment by lukasmrtvy** [comment]
@mumoshu  What about somthing like this:

```
hooks:
- events: ["presync"]
  command: "/bin/sh"
  args: ["-c", "kubectl get -R {{`{{ .Chart.Name }}`}}/crds/ >/dev/null 2>&1 || \
         { helm pull {{`{{ .Release.Chart }}`}} --version {{`{{ .Release.Version }}`}} && tar -Oxzf {{`{{ .Chart.Name }}`}}-{{`{{ .Release.Version }}`}}.tgz {{`{{ .Chart.Name }}`}}/crds/ | kubectl apply -R -f -; }"]

- events: ["postdestroy"]
  command: "/bin/sh"
  args: ["-c", "kubectl get -R {{`{{ .Chart.Name }}`}}/crds/ >/dev/null 2>&1 || \
         { helm pull {{`{{ .Release.Chart }}`}} --version {{`{{ .Release.Version }}`}} && tar -Oxzf {{`{{ .Chart.Name }}`}}-{{`{{ .Release.Version }}`}}.tgz {{`{{ .Chart.Name }}`}}/crds/ | kubectl delete -R --ignore-not-found -f -; }"]
```

Related: https://github.com/roboll/helmfile/issues/1124#issuecomment-626771771
