### ISSUE TITLE
.Values vs .Environment.Values

### ISSUE THREAD

**Issue by eddycharly** [roboll/helmfile#816]
Hi,
I'm new to helmfile and am playing with it.
I am not sure when i should use `.Environment.Values`, as using `.Values` seems to be working.

For example :
```
{{ if .Values.core.metricsServer.enabled }}
  - name: metrics-server
    namespace: core
    chart: stable/metrics-server
    values:
      - templates/core/metrics-server.yaml
{{ end }}
```

In the example above `.Values.core.metricsServer.enabled` is correctly set to `true/false`.

Should i use `.Environment.Values.core.metricsServer.enabled` instead ?
Or `.Values.core.metricsServer.enabled` is fine ?
