### ISSUE TITLE
Using `installed` inside templates

### ISSUE THREAD

**Issue by astorath** [roboll/helmfile#818]
Hi!

Just can't figure out how to use `installed` key inside `template` context:

1. This way I get invalid yaml:
```yaml
templates:
  service: &service
    installed: {{`{{ true | ternary "yes" "no" }}`}}

releases:
  - name: test
    chart: stable/nginx-ingress
    namespace: default
    <<: *service
```

output:
```
processing file "test.yaml" in directory "."
first-pass rendering starting for "test.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
could not deduce `environment:` block, configuring only .Environment.Name. error: failed to read test.yaml.part.0: reading document at index 1: yaml: unmarshal errors:
  line 3: cannot unmarshal !!map into bool
  line 3: cannot unmarshal !!map into bool
error in first-pass rendering: result of "test.yaml.part.0":
 0: templates:
 1:   service: &service
 2:     installed: {{ true | ternary "yes" "no" }}
 3:
 4: releases:
 5:   - name: test
 6:     chart: stable/nginx-ingress
 7:     namespace: default
 8:     <<: *service
 9:

first-pass produced: &{default map[] map[]}
first-pass rendering result of "test.yaml.part.0": {default map[] map[]}
second-pass rendering result of "test.yaml.part.0":
 0: templates:
 1:   service: &service
 2:     installed: {{ true | ternary "yes" "no" }}
 3:
 4: releases:
 5:   - name: test
 6:     chart: stable/nginx-ingress
 7:     namespace: default
 8:     <<: *service
 9:

err: failed to read test.yaml: reading document at index 1: yaml: unmarshal errors:
  line 3: cannot unmarshal !!map into bool
  line 3: cannot unmarshal !!map into bool
in ./test.yaml: failed to read test.yaml: reading document at index 1: yaml: unmarshal errors:
  line 3: cannot unmarshal !!map into bool
  line 3: cannot unmarshal !!map into bool
```

2. this way, something happens inside helmfile serialization:
```yaml
templates:
  service: &service
    installed: "{{`{{ true | ternary "yes" "no" }}`}}"

releases:
  - name: test
    chart: stable/nginx-ingress
    namespace: default
    <<: *service
```

output:
```
processing file "test.yaml" in directory "."
first-pass rendering starting for "test.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
could not deduce `environment:` block, configuring only .Environment.Name. error: failed to read test.yaml.part.0: reading document at index 1: yaml: line 2: did not find expected key
error in first-pass rendering: result of "test.yaml.part.0":
 0: templates:
 1:   service: &service
 2:     installed: "{{ true | ternary "yes" "no" }}"
 3:
 4: releases:
 5:   - name: test
 6:     chart: stable/nginx-ingress
 7:     namespace: default
 8:     <<: *service
 9:

first-pass produced: &{default map[] map[]}
first-pass rendering result of "test.yaml.part.0": {default map[] map[]}
second-pass rendering result of "test.yaml.part.0":
 0: templates:
 1:   service: &service
 2:     installed: "{{ true | ternary "yes" "no" }}"
 3:
 4: releases:
 5:   - name: test
 6:     chart: stable/nginx-ingress
 7:     namespace: default
 8:     <<: *service
 9:

err: failed to read test.yaml: reading document at index 1: yaml: line 2: did not find expected key
in ./test.yaml: failed to read test.yaml: reading document at index 1: yaml: line 2: did not find expected key
```
