### ISSUE TITLE
helm apply fails due to Error: unknown command "diff" for "helm"

### ISSUE THREAD

**Issue by hrb-tamura-yukichi** [roboll/helmfile#822]
Today I Installed helmfile through Homebrew.

```bash
brew install helmfile
```

Simple helmfile.yaml

```yaml
releases:
  - name: hoge-rel
    namespace: default
    chart: ./hoge
    set:
      - name: foo
        value: bar
 ```

Then execute:

```bash
helmfile apply
```

I see the output below:

```
Building dependency hoge
No requirements found in hoge/charts.

Comparing hoge-rel hoge
err 0: failed processing release hoge-rel: helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
```

Command Versions:

```bash
helmfile --version                                                                                                                                                                                           
```

>helmfile version v0.81.3

```bash
helm version
```

>Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
>Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
