### ISSUE TITLE
Layering "values" section in release templates

### ISSUE THREAD

**Issue by a-hat** [roboll/helmfile#836]
It seems that it is not possible to have multiple `values` sections defined. I would have expected helmfile to merge the values, but it takes only the last section defined.

For example, having this helmfile:

```
templates:
  default: &default
    values:
    - defaults.yaml    
  env1: &env1
    <<: *default
    values: 
    - env1.yaml

releases:
- name: demo
  <<: *env1
  values:
  - demo.yaml
```

This will only apply `demo.yaml`, but it would have been nice if also `defaults.yaml` and `env1.yaml` would be applied (in this order).

If I am not missing something, and this is a valid feature request, I would be willing to have a go at implementing the feature.

**Comment by mumoshu** [comment]
@a-hat Hey! Thanks for writing this up. I believe this is a valid feature request that should ideally be addressed asap.

What's blocking me from doing so is that I'm not yet sure how we can differentiate when to merge and not to merge `values` and how the merge to be done.

For example, in your use-case `values` should be merged, but some existing helmfile users won't like that behavior if forced. So we may need an option to toggle merging.

Regarding how the merge is done - some people want arrays nested within values to be appended some are not(=want them overrode). We may need an option for that as well.

The prior art in this area is [spruce](https://github.com/geofffranks/spruce). K8s "strategic-merge patch" can be leveraged if it's reusable as a go library.

Do you have any suggestion/idea on the two points?

**Comment by a-hat** [comment]
Thanks @mumoshu for your feedback.

That is indeed a good point, sometimes it might be necessary to overwrite the `values` instead of merging. I think the right place to decide whether to replace or overwrite the values from the previous layer is when defining a `values` block. Maybe with another keyword like `valuesMerge`, this would also ensure backwards compatibility. Defining both `values` and `valuesMerge` should result in an error.

```
templates:
  default: &default
    values:
    - defaults.yaml    
  env1: &env1
    <<: *default
    values: 
    - env1.yaml
  env2: &env2
    <<: *env2
    valuesMerge: 
    - env2.yaml

releases:
- name: demo
  <<: *env1
  valuesMerge:
  - demo.yaml
```

Which would result in 

```
- env1.yaml
- env2.yaml
- demo.yaml
```

I am not sure about array merging, maybe this could be a global flag? Alternatively, if it would be possible to use the values generated by the previous layers, the existing array values could be manually inserted when needed.
