### ISSUE TITLE
feat: `--set k=v` for helmfile apply, sync and diff

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#840]
Extracted from https://github.com/roboll/helmfile/issues/768#issuecomment-528432947

The existing `--state-values-set` sets state values used for templating helmfile.yaml itself. In contrast, this new `--set` sets release/chart values for all the helm releases defined in all the helmfile.yaml files involved.

The use of it isn't generally recommended. It is for adapting Helmfile to legacy charts that needs several `helm upgrade`s to complete a single logical upgrade.

**Comment by mumoshu** [comment]
cc/ @sstarcher

**Comment by sstarcher** [comment]
If you would like to stay away from adding limited use features such as this we could attempt to work around it in a different manner.  When we do this we specifically target a single release.  Another option would be for helmfile to split out a composite of all of the secrets/values to a file and we could use that to run `helm upgrade` targeting that file and the --set.

**Comment by mumoshu** [comment]
> Another option would be for helmfile to split out a composite of all of the secrets/values to a file and we could use that to run helm upgrade targeting that file and the --set.

@sstarcher That sounds feasible and seems useful also for debugging purpose.

Another workaround that you can possibly do today would be using `--state-values-set`:

```
helmfile -l name=myapp --state-values-set adhoc.foo=bar apply
```

```
values:
- adhoc: {}

releases:
- name: myapp
  chart: charts/myapp
  values:
  - values.yaml
  - adhoc:
{{ if .Values.adhoc }}{{ .Values.adhoc | toYaml | indent 6 }}{{ end }}
```
