### ISSUE TITLE
Helmfile does not interpolate lists correctly

### ISSUE THREAD

**Issue by skang0601** [roboll/helmfile#844]
It seems as though Helmfile does not interpolate lists correctly when passing the values down to the Helm chart.

Given an example as such:
```
bases:
  - environments.yaml

--
# Root helmfile
values:
  namespaces:
    names:
      - foo
      - bar

helmfiles:
  - path: releases/namespaces.yaml
    values:
    - namespace:
        names: {{ .Values.namespaces.names}}

# Release Helmfile
releases:
  - name: "namespaces"
    labels:
      chart: "namespaces"
    chart: "../charts/namespaces"
    version: "0.1.0"
    wait: false
    installed: true
    tillerNamespace: "kube-system"
    values:
      - namespaces:
          names: {{.Values.namespace.names }}


# Relevant template

{{- range .Values.namespaces.names}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    component: app
{{- end }}
```

I end up with the list just being passed in as a string 

```
+ # Source: namespaces/templates/namespace.yaml
+ apiVersion: v1
+ kind: Namespace
+ metadata:
+   name: foo bar
+   labels:
+     component: app
```

The ugly workaround I've found that seems to work was to explicitly templating in a range function in both my root and release helmfile which seems to render out the list correctly. I presume this is happening since `{{}}` is a string interpolation?

Any guidance on how to handle collections like this would be appreciated thanks!
