### ISSUE TITLE
how do I add multiple charts to the same release?

### ISSUE THREAD

**Issue by red8888** [roboll/helmfile#845]
im a little confused about how this is supposed to work. I want to use helmfile to manage my chart dependancies instead of helm requirements

Can I have helmfile deploy multiple charts to the same release? I get an error when trying to do this:

```
releases:
  - name: myrelease
    namespace: {{ requiredEnv "NAMESPACE" }}
    chart: ./someChart
  - name: myrelease
    namespace: {{ requiredEnv "NAMESPACE" }}
    chart: ./someOtherChart
```

> in ./helmfile.yaml: duplicate release ....
