### ISSUE TITLE
feature request: ability to access cluster name from within helmfile execution

### ISSUE THREAD

**Issue by stevenolen** [roboll/helmfile#852]
It would be very useful to inject the cluster name (or _active_ kube-context) into a helm variable in order for releases to have cluster-awareness. In our environment we are using a handful of clusters and it would be extremely helpful to be able to pass a cluster name to something like `datadog.tags` in the datadog chart to easily tag all metrics produced by that agent by cluster name.

There's workaround currently making use of the fact that `helmDefaults.kubeContext` can require an environment variable and our contexts have a 1-1 relationship with cluster name:

```
helmDefaults:
  kubeContext: {{ requiredEnv "KUBE_CONTEXT" | quote }}
```

allows any release to then use `{{ env "KUBE_CONTEXT"}}` to achieve a similar result, but requires setting this env var for `helmfile` execution, instead of being able to have it supplied via `kubectl config current-context` or passed to helmfile via `--kube-context`.

(per @mumoshu here: https://sweetops.slack.com/archives/CE5NGCB9Q/p1568264781019100?thread_ts=1568228278.017500&cid=CE5NGCB9Q)

**Comment by mumoshu** [comment]
@stevenolen Hey! So I'm still unsure how this can be cleanly implemented with/in helmfile.

But anyway, the `exec` template func can be used to call `kubectl config view` to extract the cluster name from the current context:

```
{{ $cluster := exec "kubectl" (list "config" "view" "--minify" "-o" "jsonpath='{.clusters[*].name}'") }}

releases:
- name: datadog
  chart: stable/datadog
  values:
  - datadog:
      tags:
      - cluster:{{$cluster}}
```

Does this work?

**Comment by mumoshu** [comment]
> that workaround is actually not so great. per https://github.com/roboll/helmfile/issues/443#issuecomment-478317647 `helmDefaults.kubeContext` isn't passed to sub-helmfiles 😞 

Yeah but I'm not sure there's a single answer whether --kube-context  should be inherited to subhelmfiles or not.

In the meantime, could you just use an envvar if you want it inherited to subhelmfiles implicitly?

```
KUBE_CONTEXT=myctx helmfile apply
```

In all your helmfiles:

```
helmDefaults:
  kubeContext: {{ requiredEnv "KUBE_CONTEXT" | quote }}
```

**Comment by mumoshu** [comment]
I wrote up an enhanced version of https://github.com/roboll/helmfile/issues/852#issuecomment-533781650 that supports KUBE_CONTEXT:

`clustername.sh`:

```
#!/bin/bash

set -e

KUBE_CONTEXT=${KUBE_CONTEXT:-$1}

kubectl config view > kubeconfig.tmp
KUBECONFIG=kubeconfig.tmp
if [ ! -z "$KUBE_CONTEXT" ]; then
  kubectl config use-context $KUBE_CONTEXT 1>&2
fi
kubectl config view --minify -o jsonpath='{.clusters[*].name}'
rm kubeconfig.tmp
```

```
{{ $cluster := exec "bash" (list "clustername.sh") }}

releases:
- name: datadog
  chart: stable/datadog
  values:
  - datadog:
      tags:
      - cluster:{{$cluster}}
```
