### ISSUE TITLE
feature request: support --ca-file flag to helm repo add

### ISSUE THREAD

**Issue by tmeneau** [roboll/helmfile#855]
The `helm repo add` command has a `--ca-file` that can be used to connect to `https` repositories with self-signed certificates, which [isn't currently supported in helmfile](https://github.com/tmeneau/helmfile/blob/9d851cda3be9ee077afa6859f58410c761babf2c/pkg/helmexec/exec.go#L71-L84) an option corresponding to [Helm's --ca-file](https://github.com/helm/helm/issues/3074).

While this is kind of an edge case it did come up for me.

#### Proposal:
The helmfile's `repositories` spec would be updated to support a new `caFile` option for each repository, which (exactly like the `certFile` and `keyFile` options) just be proxied to the `helm repo add` command:

```yaml
repositories:
- name: insecure
   url: https://charts.my-insecure-domain.com
   caFile: optional_ca_crt
```
