### ISSUE TITLE
Propagate helmDefaults to `helmfiles`

### ISSUE THREAD

**Issue by RobertoUa** [roboll/helmfile#867]
Suppose I have a `helmfile.yaml` with `helmDefaults` and `helmfiles` with a list of files. How do I propagate values from `helmDefaults` to these child helmfiles? 

I know if I'd used `releases` instead of `helmfiles` it would've worked. But I have some CRDs and putting everything in `releases` wouldn't work. Using `helmfiles` only for CRDs and `releases` for everything else also wouldn't work for me.

helmfile.yaml
```yaml
helmDefaults:
  tillerNamespace: kube-system
  tillerless: true
  kubeContext: context
  verify: true 
  wait: true
  timeout: 600

helmfiles: #helmDefaults are not propagated to these files
  - dashboard-values.yaml
  - metrics.yaml
  - prometheus.yaml
  - consul-values.yaml
  - redis-values.yaml
```

**Comment by mumoshu** [comment]
@RobertoUa Hey! Unfortunately it isn't impossible.

Alternatively, I'd suggest you to use values overrides when calling sub-helmfiles.

That is, in your parent helmfile.yaml you override helmfile state values like:

```
helmfiles:
- path: dashboard-values.yaml
  values:
  - helmDefaults:
      tillerless: true
      wait: true
      # snip
````

And then in your sub-helmfiles you render the helmDefaults from state values:

```
values:
- helmDefaults:
     tillerless: false
     # snip

helmDefaults:
{{ .Values.helmDefaults | toYaml }}

releases:
...
```

Helmfile state values (`values:`) is considered (almost) only the parameters passed to helmfile. So this method can be also good as it is clear to the user of subhelmfiles that those subhelmfiles supports overriding helmDefaults from the caller-side.
