### ISSUE TITLE
Using latest Linux binary LF line endings trigger error

### ISSUE THREAD

**Issue by michaelgeorgeattard** [roboll/helmfile#871]
Using latest Linux binary running:

```
helmfile -e utility --interactive apply --skip-deps
```

```
err: no releases found that matches specified selector() and environment(utility), in any helmfile
```

Switching line endings for file from LF to CRLF causes the command to work correctly.

```
{{ readFile "../../common.yaml" }}
--- <-- Error caused by this line, but works when file is CRLF
helmDefaults:
  tls: true
  tillerNamespace: kube-system

environments:
  utility:

releases:
  - name: kubernetes-dashboard-eks-admin
    namespace: kube-system
    chart: rig/kubernetes-dashboard-eks-admin
    version: 0.0.2
```
