### ISSUE TITLE
Unable to pass default environment values

### ISSUE THREAD

**Issue by zen4ever** [roboll/helmfile#872]
I'm having a hard time to pass values to helmfile template. I have following helmfile

```yaml
repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
environments:
  default:
    values:
    - defaults.yaml
releases:
  - name: "{{ .Values.nginxIngressRelease }}"
    chart: stable/nginx-ingress
    values:
      - ingx-values.yaml
    atomic: true
  - name: "{{ .Values.nginxIngressRelease }}"-to-sd
    chart: stable/prometheus-to-sd
    values:
      - metricsSources:
          nginx-ingress-metrics: http://{{ .Values.nginxIngressRelease }}-nginx-ingress-controller-metrics:9913
    atomic: true
```

with `defaults.yaml` looking like this

```yaml
nginxIngressIP: 35.238.253.164
nginxIngressRelease: ingx
```

but I'm getting an error while running `helmfile --log-level=debug template`

```
processing file "helmfile.yaml" in directory "."
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
replaced <no value>s to workaround https://github.com/golang/go/issues/24963 to address https://github.com/roboll/helmfile/issues/553:
  strings.Join({
      ... // 6 identical lines
      "    - defaults.yaml",
      "releases:",
-      `  - name: "<no value>"`,
+      `  - name: ""`,
      "    chart: stable/nginx-ingress",
      "    values:",
      "      - ingx-values.yaml",
      "    atomic: true",
-      `  - name: "<no value>"-to-sd`,
+      `  - name: ""-to-sd`,
      "    chart: stable/prometheus-to-sd",
      "    values:",
      "      - metricsSources:",
-      "          nginx-ingress-metrics: http://<no value>-nginx-ingress-controller-metrics:9913",
+      "          nginx-ingress-metrics: http://-nginx-ingress-controller-metrics:9913",
      "    atomic: true",
      "",
  }, "\n")

could not deduce `environment:` block, configuring only .Environment.Name. error: failed to read helmfile.yaml.part.0: reading document at index 1: yaml: line 13: did not find expected key
error in first-pass rendering: result of "helmfile.yaml.part.0":
 0: repositories:
 1:   - name: stable
 2:     url: https://kubernetes-charts.storage.googleapis.com
 3: environments:
 4:   default:
 5:     values:
 6:     - defaults.yaml
 7: releases:
 8:   - name: "<no value>"
 9:     chart: stable/nginx-ingress
10:     values:
11:       - ingx-values.yaml
12:     atomic: true
13:   - name: "<no value>"-to-sd
14:     chart: stable/prometheus-to-sd
15:     values:
16:       - metricsSources:
17:           nginx-ingress-metrics: http://<no value>-nginx-ingress-controller-metrics:9913
18:     atomic: true
19:

first-pass produced: &{default map[] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {default map[] map[]}
second-pass rendering failed, input of "helmfile.yaml.part.0":
 0: repositories:
 1:   - name: stable
 2:     url: https://kubernetes-charts.storage.googleapis.com
 3: environments:
 4:   default:
 5:     values:
 6:     - defaults.yaml
 7: releases:
 8:   - name: "{{ .Values.nginxIngressRelease }}"
 9:     chart: stable/nginx-ingress
10:     values:
11:       - ingx-values.yaml
12:     atomic: true
13:   - name: "{{ .Values.nginxIngressRelease }}"-to-sd
14:     chart: stable/prometheus-to-sd
15:     values:
16:       - metricsSources:
17:           nginx-ingress-metrics: http://{{ .Values.nginxIngressRelease }}-nginx-ingress-controller-metrics:9913
18:     atomic: true
19:

err: error during helmfile.yaml.part.0 parsing: template: stringTemplate:9:21: executing "stringTemplate" at <.Values.nginxIngressRelease>: map has no entry for key "nginxIngressRelease"
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:9:21: executing "stringTemplate" at <.Values.nginxIngressRelease>: map has no entry for key "nginxIngressRelease"
```

It looks like it doesn't load `defaults.yaml` even I'm following the documentation in README.md. I have a latest release of helmfile `helmfile version v0.85.2`
