### ISSUE TITLE
feat: Accept dictionaries/maps too in `releases:`

### ISSUE THREAD

**Issue by rustycl0ck** [roboll/helmfile#893]
It would become a lot easier to reuse the releases with minor changes if the `releases` could be a collection of maps/dictionaries instead of lists. For example, it would allow the use of yaml anchors or maybe other templating engines (go templates or jsonnet or anything) to reuse the contents of a previous release with minor changes.

Current:
```yaml
releases:
  - name: vault                            
    namespace: vault                       
    labels:                                  
      foo: bar
    chart: roboll/vault-secret-manager     
    version: ~1.24.1                       
    missingFileHandler: Warn 
    values:
      - vault.yaml
      - address: https://vault.example.com
      - image:
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        db:
          username: {{ requiredEnv "DB_USERNAME" }}
          password: {{ requiredEnv "DB_PASSWORD" }}
        proxy:
          domain: '{{ requiredEnv "PLATFORM_ID" }}.my-domain.com'
          scheme: '{{ env "SCHEME" | default "https" }}'
    set:
    - name: foo.config
      file: path/to/file
    - name: bar[0]
      values:
      - 1
      - 2
    - name: namespace
      value: {{ .Namespace }}
    secrets:
      - vault_secret.yaml
  - name: myvault
    namespace: myvault                       
    labels:                                  
      foo: bar
    chart: roboll/vault-secret-manager     
    version: ~1.24.1                       
    missingFileHandler: Warn 
    values:
      - vault.yaml
      - address: https://vault.example.com
      - image:
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        db:
          username: {{ requiredEnv "DB_USERNAME" }}
          password: {{ requiredEnv "DB_PASSWORD" }}
        proxy:
          domain: '{{ requiredEnv "PLATFORM_ID" }}.my-domain.com'
          scheme: '{{ env "SCHEME" | default "https" }}'
    set:
    - name: foo.config
      file: path/to/file
    - name: bar[0]
      values:
      - 1
      - 2
    - name: namespace
      value: {{ .Namespace }}
    secrets:
      - myvault_secret.yaml
```
Expected:
```diff
  releases:
-   - name: vault
+   vault: &vaultRelease
+     name: vault
      namespace: vault
      labels:
        foo: bar
      chart: roboll/vault-secret-manager
      version: ~1.24.1
      missingFileHandler: Warn
      values:
        - vault.yaml
        - address: https://vault.example.com
        - image:
            tag: {{ requiredEnv "IMAGE_TAG" | quote }}
          db:
            username: {{ requiredEnv "DB_USERNAME" }}
            password: {{ requiredEnv "DB_PASSWORD" }}
          proxy:
            domain: '{{ requiredEnv "PLATFORM_ID" }}.my-domain.com'
            scheme: '{{ env "SCHEME" | default "https" }}'
      set:
      - name: foo.config
        file: path/to/file
      - name: bar[0]
        values:
        - 1
        - 2
      - name: namespace
        value: {{ .Namespace }}
      secrets:
        - vault_secret.yaml
-   - name: myvault
-     namespace: myvault
-     labels:
-       foo: bar
-     chart: roboll/vault-secret-manager
-     version: ~1.24.1
-     missingFileHandler: Warn
-     values:
-       - vault.yaml
-       - address: https://vault.example.com
-       - image:
-           tag: {{ requiredEnv "IMAGE_TAG" | quote }}
-         db:
-           username: {{ requiredEnv "DB_USERNAME" }}
-           password: {{ requiredEnv "DB_PASSWORD" }}
-         proxy:
-           domain: '{{ requiredEnv "PLATFORM_ID" }}.my-domain.com'
-           scheme: '{{ env "SCHEME" | default "https" }}'
-     set:
-     - name: foo.config
-       file: path/to/file
-     - name: bar[0]
-       values:
-       - 1
-       - 2
-     - name: namespace
-       value: {{ .Namespace }}
-     secrets:
-       - myvault_secret.yaml
+   myvault:
+     <<: *vaultRelease
+     name: myvault
+     namespace: myvault
+     secrets:
+       - myvault_secret.yaml
```
Not the best example, but should be enough to get the idea.
