### ISSUE TITLE
Feature request - kubeContext support in environments

### ISSUE THREAD

**Issue by white-hat** [roboll/helmfile#898]
I got a k8s cluster for each environment (dev, stage, prod) and I'd like to be able to set     `kubeContext` for all my deployments in `environments` not in `releases`.
So when I want to deploy all releases to `stage` environment, for example, having
```
environments:
  stage:
    kubeContext: stage-k8s
```
I will just run `helmfile -e stage apply` and do not have to care of setting right kubectl context

**Comment by mumoshu** [comment]
@white-hat Hey! This sounds like a great feature request.

**Comment by voron** [comment]
As a work-around I use templates and k8s context naming in following way
```yaml
environments:
  dev:
  staging:
  prod:
templates:
  bitcoind: &bitcoind
    ...
    kubeContext: gke-{{ .Environment.Name }}-0
    ...
releases:
  - name: common-btc
    <<: *bitcoind
    # deploys with kubeContext depending on environment

  {{ if eq .Environment.Name "dev" }}
  - name: dev-btc0
    <<: *bitcoind
    # deploys with kubeContext: gke-dev-0
  {{ end }}

  {{ if eq .Environment.Name "staging" }}
  - name: staging-btc0
    <<: *bitcoind
    # deploys with kubeContext: gke-staging-0
  {{ end }}
```
