### ISSUE TITLE
failed processing release

### ISSUE THREAD

**Issue by cilerler** [roboll/helmfile#905]
I wonder what am I doing wrong, I appreciate any help.

### console
```
PS [20191022:192234] > helmfile apply                                                                                                                                                                                                                                                                                                 Adding repo stable https://kubernetes-charts.storage.googleapis.com
"stable" has been added to your repositories
Adding repo incubator https://kubernetes-charts-incubator.storage.googleapis.com
"incubator" has been added to your repositories

Updating repo                                                                                                                                                                                                                                                                                                                                                                                                Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
Comparing release=kubernetes-dashboard, chart=stable/kubernetes-dashboard
********************
Release was not present in Helm.  Diff will show entire contents as new.
********************
...
identified at least one change, exiting with non-zero exit code (detailed-exitcode parameter enabled)

Upgrading release=kubernetes-dashboard, chart=stable/kubernetes-dashboard                                                                                                                                                                                                                                                                                                                                    in ./helmfile.yaml: failed processing release kubernetes-dashboard: helm.exe exited with status 1:                                                                                                                                                                                                                                                                                                             Error: failed to download "stable/kubernetes-dashboard" (hint: running `helm repo update` may help)
```

### helmfile.yaml
```
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com

helmDefaults:
  kubeContext: docker-desktop
  verify: true
  wait: true
  timeout: 600
  recreatePods: true
  force: true

releases:
  - name: kubernetes-dashboard
    chart: stable/kubernetes-dashboard
    namespace: kube-system
    values:
    - enableSkipLogin: true

```

**Comment by mumoshu** [comment]
@cilerler Hey! I believe this is due to some issue in the chart/the upstream charts registry.

For me this, mostly your config but without `verify: true` omitted, worked:

```
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com

helmDefaults:
#  kubeContext: docker-desktop
#  verify: true
  wait: true
  timeout: 600
  recreatePods: true
  force: true

releases:
  - name: kubernetes-dashboard
    chart: stable/kubernetes-dashboard
    namespace: kube-system
    values:
    - enableSkipLogin: true
```

Could you omit `verify: true` for problematic regs/charts?

Also in general, running helmfile with debug logs enabled like `helmfile --log-level=debug apply` helps you to diagnose issue(by helping you to decide if it's helmfile or helm behaving in a unexpected way
