### ISSUE TITLE
in ./helmfile.yaml: no resolved dependency found for "..."

### ISSUE THREAD

**Issue by cilerler** [roboll/helmfile#908]
Getting error below upon running `helmfile --log-level=debug apply`

```
err: no resolved dependency found for "grafana"
in ./helmfile.yaml: no resolved dependency found for "grafana"
```

### helmfile.yaml

```
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com

helmDefaults:
  kubeContext: docker-desktop
  verify: true
  wait: true
  timeout: 600
  recreatePods: true
  force: true

releases:
  - name: kubernetes-dashboard
    chart: stable/kubernetes-dashboard
    namespace: kube-system
    values:
    - enableSkipLogin: true

  # [stable/seq](https://github.com/helm/charts/blob/master/stable/seq/)
  - name: seq
    verify: false
    chart: stable/seq
    namespace: default
    values:
    - image:
        tag: preview
      service:
        type: LoadBalancer
        port: 5341

  # [stable/grafana](https://github.com/helm/charts/blob/master/stable/grafana/)
  - name: grafana
    verify: false
    chart: stable/grafana
    namespace: default
    values:
    - image:
        tag: 6.3.5
      service:
        type: LoadBalancer
        port: 3000
      ingress:
        enabled: true
      persistence:
        enabled: true
```
