### ISSUE TITLE
Accessing nested maps in .Values from helmfile.yaml

### ISSUE THREAD

**Issue by a-hat** [roboll/helmfile#916]
Rendering the following template fails when trying to resolve `.Values.versions.traefik` with the error message `executing "stringTemplate" at <.Values.versions.traefik>: map has no entry for key "versions"`.

Why is it not possible to access the `traefik` key in the `.Values.versions` map? Without the nested map it works fine (e.g. `.Values.traefikVersion`)

```
releases:
- name: traefik
  namespace: kube-system
  chart: stable/traefik
  version: {{ .Values.versions.traefik }}

values:
  - versions:
      traefik: 1.7
```

**Comment by mumoshu** [comment]
@a-hat This seems like due to how double-rendering works. 

Maybe the first render that happens before YAML parsing is faling and stopping at `{{ .Values.versions.traefik }}` which may result in the first render to produce:

```
releases:
- name: traefik
  namespace: kube-system
  chart: stable/traefik
  version: ""
```

Helmfile reads the above to compute `.Values` and the second render fails...

The workaround would be to declare `values` in the beginning:

```
values:
  - versions:
      traefik: 1.7

releases:
- name: traefik
  namespace: kube-system
  chart: stable/traefik
  version: {{ .Values.versions.traefik }}
```
