### ISSUE TITLE
Helm hooks not applying

### ISSUE THREAD

**Issue by musabmasood** [roboll/helmfile#918]
## The problem

I have this strange issue where the jobs with helm hooks are not being rendered in `helmfile diff` nor is it applied in `helmfile apply`. In this example, the `hook-job.yaml` doesn't get rendered/applied.

## Versions

```
➜  helmfiletest helmfile --version
helmfile version v0.85.3
➜  helmfiletest kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.10", GitCommit:"8cea5f8ae165065f0d35e5de5dfa2f73617f02d1", GitTreeState:"clean", BuildDate:"2019-10-05T00:08:10Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}
➜  helmfiletest helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
helmServer: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
➜  helmfiletest helm diff version
2.11.0+5
```
## Setup

Directory structure:

![image](https://user-images.githubusercontent.com/8170066/67869803-52da7400-fb04-11e9-9974-33b816f07b61.png)

`helmsfile.yaml`:

```
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com

helmDefaults:

  tillerNamespace: kube-system
  tillerless: false
  kubeContext: gke_byond-infinity-platform_northamerica-northeast1-a_integrity-cicd
  verify: false
  atomic: true
  timeout: 1000
  wait: true
  recreatePods: false
  force: true

releases:

  - name: mychart
    installed: true
    namespace: mychart
    chart: mychart
   
```

`hook-job.yaml`:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: hook-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```

`no-hook-job.yaml` (annotations turned off)

```
apiVersion: batch/v1
kind: Job
metadata:
  name: no-hook-job
  # annotations:
  #   "helm.sh/hook": post-install
  #   "helm.sh/hook-weight": "-5"
  #   "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```

## Outputs:

Here is the output of `helmfile --log-level debug diff`:

```
➜  helmfiletest helmfile --log-level debug diff
processing file "helmfile.yaml" in directory "."
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
first-pass produced: &{default map[] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {default map[] map[]}
vals:
map[]
defaultVals:[]
second-pass rendering result of "helmfile.yaml.part.0":
 0: repositories:
 1: - name: stable
 2:   url: https://kubernetes-charts.storage.googleapis.com
 3: - name: incubator
 4:   url: https://kubernetes-charts-incubator.storage.googleapis.com
 5:
 6: helmDefaults:
 7:
 8:   tillerNamespace: kube-system
 9:   tillerless: false
10:   kubeContext: gke_byond-infinity-platform_northamerica-northeast1-a_integrity-cicd
11:   verify: false
12:   atomic: true
13:   timeout: 1000
14:   wait: true
15:   recreatePods: false
16:   force: true
17:
18: releases:
19:
20:   - name: mychart
21:     installed: true
22:     namespace: mychart
23:     chart: mychart
24:

merged environment: &{default map[] map[]}
Adding repo stable https://kubernetes-charts.storage.googleapis.com
exec: helm repo add stable https://kubernetes-charts.storage.googleapis.com
exec: helm repo add stable https://kubernetes-charts.storage.googleapis.com: "stable" has been added to your repositories

"stable" has been added to your repositories

Adding repo incubator https://kubernetes-charts-incubator.storage.googleapis.com
exec: helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com
exec: helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com: "incubator" has been added to your repositories

"incubator" has been added to your repositories

Updating repo
exec: helm repo update
exec: helm repo update: Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Unable to get an update from the "chartmuseum" chart repository (http://localhost:28081):
	Get http://localhost:28081/index.yaml: dial tcp [::1]:28081: connect: connection refused
...Unable to get an update from the "ccc" chart repository (http://localhost:28081):
	Get http://localhost:28081/index.yaml: dial tcp [::1]:28081: connect: connection refused
...Successfully got an update from the "harbor" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "rook-release" chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "rook-master" chart repository
Update Complete.

Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Unable to get an update from the "chartmuseum" chart repository (http://localhost:28081):
	Get http://localhost:28081/index.yaml: dial tcp [::1]:28081: connect: connection refused
...Unable to get an update from the "ccc" chart repository (http://localhost:28081):
	Get http://localhost:28081/index.yaml: dial tcp [::1]:28081: connect: connection refused
...Successfully got an update from the "harbor" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "rook-release" chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "rook-master" chart repository
Update Complete.

Building dependency release=mychart, chart=mychart
exec: helm dependency build mychart
exec: helm dependency build mychart: No requirements found in mychart/charts.

No requirements found in mychart/charts.

worker 1/1 started
worker 1/1 finished
worker 1/1 started
Comparing release=mychart, chart=mychart
exec: helm diff upgrade --reset-values --allow-unreleased mychart mychart --tiller-namespace kube-system --kube-context gke_byond-infinity-platform_northamerica-northeast1-a_integrity-cicd --namespace mychart
exec: helm diff upgrade --reset-values --allow-unreleased mychart mychart --tiller-namespace kube-system --kube-context gke_byond-infinity-platform_northamerica-northeast1-a_integrity-cicd --namespace mychart: ********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************
mychart, no-hook-job, Job (batch) has been added:
-
+ # Source: mychart/templates/no-hook-job.yaml
+ apiVersion: batch/v1
+ kind: Job
+ metadata:
+   name: no-hook-job
+   # annotations:
+   #   "helm.sh/hook": post-install
+   #   "helm.sh/hook-weight": "-5"
+   #   "helm.sh/hook-delete-policy": hook-succeeded
+ spec:
+   template:
+     spec:
+       containers:
+       - name: pi
+         image: perl
+         command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
+       restartPolicy: Never
+   backoffLimit: 4

********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************
mychart, no-hook-job, Job (batch) has been added:
-
+ # Source: mychart/templates/no-hook-job.yaml
+ apiVersion: batch/v1
+ kind: Job
+ metadata:
+   name: no-hook-job
+   # annotations:
+   #   "helm.sh/hook": post-install
+   #   "helm.sh/hook-weight": "-5"
+   #   "helm.sh/hook-delete-policy": hook-succeeded
+ spec:
+   template:
+     spec:
+       containers:
+       - name: pi
+         image: perl
+         command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
+       restartPolicy: Never
+   backoffLimit: 4

worker 1/1 finished
```

Here is the output of `helmfile apply`:

```
➜  helmfiletest helmfile apply
Adding repo stable https://kubernetes-charts.storage.googleapis.com
"stable" has been added to your repositories

Adding repo incubator https://kubernetes-charts-incubator.storage.googleapis.com
"incubator" has been added to your repositories

Updating repo
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Unable to get an update from the "chartmuseum" chart repository (http://localhost:28081):
	Get http://localhost:28081/index.yaml: dial tcp [::1]:28081: connect: connection refused
...Unable to get an update from the "ccc" chart repository (http://localhost:28081):
	Get http://localhost:28081/index.yaml: dial tcp [::1]:28081: connect: connection refused
...Successfully got an update from the "rook-release" chart repository
...Successfully got an update from the "rook-master" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "harbor" chart repository
...Successfully got an update from the "incubator" chart repository
Update Complete.

Building dependency release=mychart, chart=mychart
No requirements found in mychart/charts.

Comparing release=mychart, chart=mychart
********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************
mychart, no-hook-job, Job (batch) has been added:
-
+ # Source: mychart/templates/no-hook-job.yaml
+ apiVersion: batch/v1
+ kind: Job
+ metadata:
+   name: no-hook-job
+   # annotations:
+   #   "helm.sh/hook": post-install
+   #   "helm.sh/hook-weight": "-5"
+   #   "helm.sh/hook-delete-policy": hook-succeeded
+ spec:
+   template:
+     spec:
+       containers:
+       - name: pi
+         image: perl
+         command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
+       restartPolicy: Never
+   backoffLimit: 4
identified at least one change, exiting with non-zero exit code (detailed-exitcode parameter enabled)

Upgrading release=mychart, chart=mychart
Release "mychart" does not exist. Installing it now.
NAME:   mychart
LAST DEPLOYED: Wed Oct 30 10:59:18 2019
NAMESPACE: mychart
STATUS: DEPLOYED

RESOURCES:
==> v1/Job
NAME         COMPLETIONS  DURATION  AGE
no-hook-job  1/1          9s        10s

==> v1/Pod(related)
NAME               READY  STATUS     RESTARTS  AGE
no-hook-job-2vmxt  0/1    Completed  0         10s



Listing releases matching ^mychart$
NAME   	REVISION	UPDATED                 	STATUS  	CHART        	APP VERSION	NAMESPACE
mychart	1       	Wed Oct 30 10:59:18 2019	DEPLOYED	mychart-0.0.0	           	mychart
```
