### ISSUE TITLE
Atomic helmfile release

### ISSUE THREAD

**Issue by iAnomaly** [roboll/helmfile#925]
We have a need for treating all releases within a single helmfile as atomic.

Currently, we are using `atomic: true` such that EACH release is atomic: if a release fails, Helm rolls it back to the previous release (or purges the release if it was the first attempt).

We have a use case where we would like ANY failed release within the helmfile to result in the rollback of ALL successful releases.

@mumoshu and I discussed this at length on Slack here: https://sweetops.slack.com/archives/CE5NGCB9Q/p1572563989024200
with the tentative proposal of adding `helmfile apply --atomic` operation to enable this behavior while leaving `atomic: true` helmfile configuration unchanged.

**Comment by jkroepke** [comment]
Currently we are using an umbrella chart combined with helm --atomic.

I would like to replace the custom code around our umbrella chart generator with helmfile, but it seems not possible w/o this feature yet.

**Comment by mumoshu** [comment]
@jkroepke Hey! I'm very interested in how your custom code works. Are you deploying a single umbrella chart composed of multiple charts so that you can leverage `helm-rollback` to rollback all the subcharts in case of a helm-upgrade failure? If so, that sounds like a completely different strategy than what @iAnomaly has requested in this issue.

If all you want is to automatically generate an umbrella chart on demand, you can do that today by using `dependencies`:

```
releases:
- name: myapp
  chart: charts/main
  dependencies
  - chart: charts/sub1
  - chart: charts/sub2
```

**Comment by mumoshu** [comment]
@jkroepke OK. Could you try this:

```
releases:
- name: myapp
  chart: incubator/raw
  atomic: true
  dependencies
  - chart: charts/sub1
  - chart: charts/sub2
  values:
  - sub1:
      enabled: true
  - sub1: "ref+file://relative/path/to/sub1/values.yaml"
  - sub2:
      enabled: true
  - sub2:  "ref+file://relative/path/to/sub2/values.yaml"
```

**Comment by mumoshu** [comment]
@jkroepke I tried my own suggestion and it didn't work. The `ref+` URL is transformed into a scalar value by [vals](https://github.com/variantdev/vals) integrated into Helmfile. But transforming the URL into the whole yaml file content isn't supported yet.

I can see it's pretty easy to make the below possible:

```
  values:
  - sub1:
      enabled: true
      "ref+file://relative/path/to/sub1/values.yaml":
  - sub2:
      enabled: true
      "ref+file://relative/path/to/sub2/values.yaml":
```

Would it help you if that was possible?
