### ISSUE TITLE
feat: Support label lists

### ISSUE THREAD

**Issue by MLBMatt** [roboll/helmfile#943]
We have some situations where we want to run different Charts based on environment, but instead of using `.Environment.Name` and doing conditional Go templating to that end, we want the ability to leverage labels-as-lists and conditionally run them.

For instance, we have certain charts we want applied to non-prod, prod or both. Using labels like:

```yaml
releases:
  - name: some-chart
    labels:
      env: 
        - npd
  - name: other-chart
    labels:
      env: 
        - npd
        - prod
```

By running `helmfile -l env=npd sync` we get both charts to sync, running `helmfile -l env=prod` syncs just `other-chart`, etc.

Is this something that is inline with the vision of labels or can we accomplish this some other way?

**Comment by mumoshu** [comment]
@MLBMatt Hey! Would the `env/npd: y` style work?

```yaml
releases:
  - name: some-chart
    labels:
      env/npd: y
  - name: other-chart
    labels:
      env/npd: y
      env/prod: y
```

`helmfile -l env/npd sync`  would sync both charts and `helmfile -l env/prod sync` would sync the other chart only.

Probably this would work too:


```yaml
releases:
  - name: some-chart
    labels:
      env/npd:
  - name: other-chart
    labels:
      env/npd:
      env/prod:
```

With e.g. `helmflie -l env/npd= sync`.

**Comment by MLBMatt** [comment]
This would work but isn't necessarily as clean as I was thinking

**Comment by mumoshu** [comment]
@MLBMatt I hear you! We might need something other than that.

Extending labels to accept multiple values didn't seem very natural where we k8s users usually take it as just a list of kv pairs, where the proposal makes it key-values pairs.

Is the environment name only filter you want? Then how about this

```yaml
releases:
- name: some-chart
  environmentsInstalled:
  - npd
- name: other-chart
  environmentsInstalled: 
    - npd
    - prod
```

Or a more generic alternative could be:

```yaml
releases:
- name: some-chart
  installed: false
  environments:
    npd:
      installed: true
- name: other-chart
  installed: false
  environments: 
    npd:
      installed: true
    prod:
      installed: true
```

With YAML anchors we can make it a bit more DRY:

```yaml
templates:
  base: &base
    installed: false
  npd: &npd
    npd:
      installed: true
  prod: &prod
    prod:
      installed: true

releases:
- <<: *base
  name: some-chart
  environments:
    <<: *npd
- <<: *base
  name: other-chart
  environments: 
    <<: *npd
    <<: *prod
```

The latter alternative would open up possibilities to customize other release settings per environment, like `values` and `kubeContext`...

```yaml
releases:
- name: other-chart
  installed: false
  values:
  - default.values.yaml
  environments:
    npd:
      installed: true
      kubeContext: npdcluster
      values:
      - values.npd.yaml
    prod:
      installed: true
      kubeContext: prodcluster
      values:
      - values.prod.yaml
```
