### ISSUE TITLE
values from "environments" section are not reachable

### ISSUE THREAD

**Issue by dududko** [roboll/helmfile#957]
### Problem
When I pass the object to environment values the `helmfile.yaml` templating fails.

Here is the example.
```
releases:
  - name: a-release
    namespace: {{ .Values.namespace.name  }}

environments:
  default:
    values:
      - namespace:
          name: hello-world
```
helmfile build output: 
```
error during helmfile.yaml.part.0 parsing: template: stringTemplate:3:25: executing "stringTemplate" at <.Values.namespace.name>: map has no entry for key "namespace"
```

However it works if I pass the value with a flag `--state-values-set=namespace.name=test`, or when there is no nesting in values 
```
environments:
  default:
    values:
      - namespace: hello-world
```

### Observation
The content of `{{ .Values }}` is actually correct: `map[namespace:map[name:hello-world]]`, also I can access the `namespace` field with `{{ .Values.namespace }}`, but all dict operation on this object fail.

**Comment by mumoshu** [comment]
@dududko Hey! I believe this is due to how Double Rendering works.

I'm working hard to deprecate it and make a more intuitive alternative as the default in #932, but in the meantime, try moving `environments` to the beginning of your config, like:

```
environments:
  default:
    values:
      - namespace:
          name: hello-world

releases:
  - name: a-release
    namespace: {{ .Values.namespace.name  }}
```

**Comment by Aaron-ML** [comment]
This also appears to be an issue if you reference base: environments.yaml at the top, I have to manually merge them into the main helmfile to get the values to propagate correctly.

**Comment by mumoshu** [comment]
Note: I keep getting questions like this for 2 years.

The short answer is to use `---` so that the rendering order is more obvious:

```
environments:
  default:
    values:
      - namespace:
          name: hello-world

---

releases:
  - name: a-release
    namespace: {{ .Values.namespace.name  }}
```
