### ISSUE TITLE
Error in ./helmfile.yaml: release "redis" failed:

### ISSUE THREAD

**Issue by tomjohnburton** [roboll/helmfile#960]
```
repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
helmDefaults:
  tillerNamespace: default
  tillerless: true
releases:
  - name: kubernetes-dashboard-eks-admin
    namespace: kube-system
    chart: rig/kubernetes-dashboard-eks-admin
    version: 0.0.2

```
