### ISSUE TITLE
How to set value in hook

### ISSUE THREAD

**Issue by Vad1mo** [roboll/helmfile#978]
I would like to set `functionNamespace` into the hook args as seen in the example below. 
I tried ``` "{{`{{ .Release.Values.functionNamespace }}`}}" ``` but this doesn't work. 

On the other hand if I set ```"{{`{{ .Release.Values }}`}}"``` I see in the console logs the output `hook[prepare] logs | create namespace [map[functionNamespace:openfaas-fn]`

How can I get the map value for the key functionNamespace:openfaas?

```yml
releases:
  - name: openfaas
    namespace: openfaas
    chart: openfaas/openfaas
    version: ~5.2.2
    values:
      - functionNamespace: openfaas-fn
      - basicAuthPlugin:
          user: master
          password:
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "echo" # instead of kubectl
        args: ["create", "namespace", "{{`{{ .Release.Values.functionNamespace }}`}}"]
```
