### ISSUE TITLE
How to parse other  template file outside of helm

### ISSUE THREAD

**Issue by Vad1mo** [roboll/helmfile#979]
I created a presync hook to create a second namespace. I don't want to put the second namespace in the chart as it would be removed if the chart is deleted. I don't want the functions to disapear. 

This is why I am creating the namespace in the hook. But on the second run of the helmfile there is an error indicating that the namespace already exists. 

I would like to put the namespace creation in a kubernetes definition file, so it becomes idempotent. 

What Im trying to do is to read the k8s `yaml` or template file and set the namespace from `functionNamespace` then provide that output as an argument to kubctl in the hook.

Now I don't know how I would be able to take a yaml file and replace a value in it and provide it as an argument to kubectl. 

```yaml
     values:
      - functionNamespace: openfaas-fn
      - basicAuthPlugin:
          user: master
          password:
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          [
            "create",
            "namespace",
            '{{`{{ range .Release.Values }} {{ with (index . "functionNamespace") }} {{ . }} {{ end }}{{ end }}`}}',
          ]
```
#978

**Comment by mumoshu** [comment]
@Vad1mo Hey! Sorry if I'm not following you correctly but can you just do it idempotently like:

```
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "sh"
        args:
        - c
        - for ns in {{ .Values.some.namespaces | join " " }}; do kubectl create namespace $ns; done
```

Anyways, you can't refer to `.Release.Values` as of today - `releases[].values` are only for passing to the helm chart, not for templating inside helmfile.yaml. You can use `.Values` that is available within the scope of helmfile.yaml, though.
