### ISSUE TITLE
Recursive error on empty list item

### ISSUE THREAD

**Issue by ademspr** [roboll/helmfile#983]
Hi,
I am using helmfile on windows.

I was trying to run a lint in my prometheus-operator.yaml file with:

```sh
$ helmfile -f .\helmfile.d\monitoring.yaml -l chart=prometheus-operator lint
```

This is my \helmfile.d\monitoring.yaml file
```yaml
bases:
  - ../commons/environments.yaml
  - ../commons/defaults.yaml.gotmpl
  - ../commons/repositories.yaml
helmfiles:
  -  
  - ../releases/prometheus-operator/prometheus-operator.yaml
  - ../releases/elastic-stack/elasticsearch.yaml
  - ../releases/elastic-stack/kibana.yaml
```
By carelessness I left an empty item in helmfiles and found that helmfile looped through all the files in my directory. This has increased CPU and memory usage and made the helmfile process not exit.

![image](https://user-images.githubusercontent.com/9203767/69096728-bbe24700-0a33-11ea-9375-809e36d6ee23.png)
