### ISSUE TITLE
loop over release with secrets and values.

### ISSUE THREAD

**Issue by jurgenweber** [roboll/helmfile#986]
How can I do something like this?

```
{{ if .Environment.Values.container_registries }}
{{ range .Environment.Values.container_registries }}
  - name: {{ .name }}
    namespace: devops
    chart: gabibbo97/imagepullsecrets
    <<: *default
    installed: {{ $.Values | get "container_registry.installed" true }}
    set:
      - imagePullSecret.registryURL: {{ .url }}
      - imagePullSecret.secretName: {{ .name }}
      - imagePullSecret.username: {{ .user }}
      - imagePullSecret.password: {{ .pass }}
{{ end }}
{{ end }}
```

Ideally I would want the password in environments secrets.

**Comment by mumoshu** [comment]
Hey! I'd suggest trying something like this.

Firstly, choose one of supported vals providers listed in https://github.com/variantdev/vals#suported-backends and store the passwords in it.

Let's say you've chosen HashiCorp Vault and stored passwords like `vault kv put secrets/container_registry_passwords NAME=PASS`:

```
{{ if .Environment.Values.container_registries }}
{{ range .Environment.Values.container_registries }}
  - name: {{ .name }}
    namespace: devops
    chart: gabibbo97/imagepullsecrets
    <<: *default
    installed: {{ $.Values | get "container_registry.installed" true }}
    set:
      - imagePullSecret.registryURL: {{ .url }}
      - imagePullSecret.secretName: {{ .name }}
      - imagePullSecret.username: {{ .user }}
      - imagePullSecret.password: ref+vault://secrets#/container_registry_passwords/{{ .name }}
{{ end }}
{{ end }}
```

**Comment by jurgenweber** [comment]
ok, I am using helm secrets but I am getting this weird error now:
```
in ./helmfile.yaml: in .helmfiles[2]: in helmfile/bases.yaml: failed to read releases.yaml.gotmpl: reading document at index 1: yaml: unmarshal errors:
  line 234: field imagePullSecrets.registryURL not found in type state.SetValue
  line 235: field imagePullSecrets.secretName not found in type state.SetValue
  line 236: field imagePullSecrets.username not found in type state.SetValue
  line 237: field imagePullSecrets.password not found in type state.SetValue
```

**Comment by jurgenweber** [comment]
I just realised that one is a user issue. set is 
```
- name: asdf
   values: asdf
```

**Comment by mumoshu** [comment]
Also note that you have to use `values` rather than `set` to enable vals integration so it should be:

```
    values:
      - imagePullSecret:
          password: ref+vault://secrets#/container_registry_passwords/{{ .name }}
```

I've updated my example above

**Comment by jurgenweber** [comment]
ok, final setup:

```
{{ if .Values.container_registries }}
{{ range .Values.container_registries }}
  - name: {{ .name }}
    namespace: devops
    chart: gabibbo97/imagepullsecrets
    installed: true
    version: 1.0.2
    <<: *default
    set:
      - name: imagePullSecret.registryURL
        value: {{ .url }}
      - name: imagePullSecret.secretName
        value: {{ .name }}
      - name: imagePullSecret.username
        value: {{ .user }}
    values:
      - imagePullSecret:
          password: ref+sops://../secrets/secrets.yaml#/container_registry_passwords/{{ .name }}
{{ end }}
{{ end }}
```

the weird part is the release is not showing to be installed by `diff` or `apply`

**Comment by mumoshu** [comment]
Perhaps something is going wrong in helm-diff..?

Could you kindly verify that the vanilla `helm diff --reset-values --allow-unreleased name gabibbo97/imagepullsecrets --version 1.0.2 --namespace devops --values some.values.yaml`  does detect changes?

**Comment by mumoshu** [comment]
Maybe a bug in helm 3 + helm-diff?

**Comment by jurgenweber** [comment]
no, its a problem with the chart.

I downloaded it:

```
$ cat templates/imagepullsecrets.yaml
{{- if .Values.imagePullSecrets }}
{{- range $i, $pullSecret := .Values.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pullSecret.secretName }}
{{- if $pullSecret.annotations }}
  annotations:
{{ toYaml $pullSecret.annotations | indent 4 }}
{{- end }}
{{- if $pullSecret.labels }}
  labels:
{{ toYaml $pullSecret.labels | indent 4 }}
{{- end }}
data:
{{- if $.Values.addAuthField }}
  .dockerconfigjson: {{ include "imagepullsecrets.dockerconfigjson-with-auth" $pullSecret | nospace | b64enc | quote }}
{{- else }}
  .dockerconfigjson: {{ include "imagepullsecrets.dockerconfigjson" $pullSecret | nospace | b64enc | quote }}
{{- end }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
```

firstly, I have `imagePullSecrets` vs `imagePullSecret`

and now I have 

```
  Error: template: imagepullsecrets/templates/imagepullsecrets.yaml:7:22: executing "imagepullsecrets/templates/imagepullsecrets.yaml" at <$pullSecret.secretName>: can't evaluate field secretName in type interface {}
```

**Comment by mumoshu** [comment]
@jurgenweber Wow, isn't this a regression in Helm v3? I thought Helm v3 is intended to not break charts with only a few exceptions

**Comment by jurgenweber** [comment]
/me shrugs.

no idea, didn't use this in helm2. :)

**Comment by jurgenweber** [comment]
No, user issue again! :) lol. I got it working:

```
{{ if .Values.container_registries }}
{{ range .Values.container_registries }}
  - name: {{ .name }}
    namespace: devops
    chart: gabibbo97/imagepullsecrets
    installed: true
    version: 1.0.2
    <<: *default
    values:
      - imagePullSecrets:
          - password: ref+sops://../secrets/{{ env "HELMFILE_CLUSTER" | default "local" }}.yaml#/container_registry_passwords/{{ .name }}
            secretName: {{ .name }}
            username: {{ .user }}
            registryURL: {{ .url }}
{{ end }}
{{ end }}
```

**Comment by mumoshu** [comment]
Glad to see it worked 🎉 

> Error: Failed to render chart: exit status 1: coalesce.go:165: warning: skipped value for imagePullSecrets: Not a table.

Ah interesting. So this might be an issue in the chart, that `imagePullSecrets` isn't set to `{}` that makes `--set imagePullSecrets.whatever` failing like this...?

> I would like to add this loop to the tips and trickets ticket if you are keen? 

That would be great!

**Comment by jurgenweber** [comment]
I have a new variant I am trying tyo get working:
```
{{ if .Environment.Values.mysql }}
{{ range $i, $instance := .Values.mysql.instances }}
  - apiVersion: v1
    kind: Service
    metadata:
      name: database-{{ $i }}
      namespace: shared
    spec:
      type: ExternalName
      externalName: {{ $instance.externalName }}

  - apiVersion: v1
    kind: Secret
    metadata:
      name: database-{{ $i }}
      namespace: shared
      labels:
        app.kubernetes.io/name: database
        app.kubernetes.io/instance: database
    data:
      root_user: {{ $.Values.mysql.instance.(index $instance "externalName").root.user | b64enc }}
      root_pass: {{ $.Values.mysql.instance.(index $instance "externalName").root.pass | b64enc }}

  - apiVersion: v1
    kind: Secret
    metadata:
      name: database-{{ $i }}
      namespace: tenant
      labels:
        app.kubernetes.io/name: database
        app.kubernetes.io/instance: database
    data:
      tenant_user: {{ $.Values.mysql.instance.(index $instance "externalName").tenant.user | b64enc }}
      tenant_pass: {{ $.Values.mysql.instance.(index $instance "externalName").tenant.pass | b64enc }}
{{ end }}
{{ end }}
```
