### ISSUE TITLE
How to pass variables in the value.yaml ? 

### ISSUE THREAD

**Issue by vankhoa011** [roboll/helmfile#989]
First of all, thank you for creating this tool. However, after I read the document, I'm still got confused.
For example: we have the the redis stable helm chart, and we have the values.yaml .
In the values.yaml, we have the password file which I need to pass from other file such as secrets.yaml.

So my `helmfile.yaml` is 
```
environments:
  {{ .Environment.Name }}:

releases:
- name: "redis"
  chart: "stable/redis"
  version: ~9.5.0     
  values:
  - values.yaml.gotmpl
  - secrets.yaml
```
Content of `values.yaml.gotmpl`:

```
password: {{ .Values.secrets.redis.password }}
```

However, it shows error `map has no entry for key "secrets"`
If I change the helmfile 
```
environments:
  {{ .Environment.Name }}:
  values:
  - secrets.yaml
releases:
- name: "redis"
  chart: "stable/redis"
  version: ~9.5.0     
  values:
  - values.yaml.gotmpl
```
and the content of  `values.yaml.gotmpl`:
```
password: {{ .Values.secrets.redis.password }}
```
It's working correctly.  What's purpose of using template ?  Where can we pass the variables ? 
I understand that we can pass the value from environments field such as
```environments:
  {{ .Environment.Name }}:
  values:
  - secrets.yaml```

But we can still pass the variable from the release fields. For example: 
```
releases:
- name: "redis"
  chart: "stable/redis"
  version: ~9.5.0     
  values:
  - values.yaml.gotmpl
```
Thank you in advance.

**Comment by vankhoa011** [comment]
Another situation is that if we don't add values files and we add values in the environment. 
```
environments:
  {{ .Environment.Name }}:
  values:
  - values.yaml
releases:
- name: "redis"
  chart: "stable/redis"
  version: ~9.5.0     
``` 
Can the helmfile render the template ? I ran the test. It seems that the helmfile can't render the template.
